### ISSUE TITLE
Array#&, Array#|, Array#-, Array#uniq, and Array#uniq! are fast and... wrong

### ISSUE THREAD

**Issue by vais** [opal/opal#1001]
`Array#&`, `Array#|`, `Array#-`, `Array#uniq`, and `Array#uniq!` all use a JavaScript object as a poor man's hash, storing and looking up array items as **keys** in that "hash".

I've been reluctant to change this for performance reasons, but this reminds me of the saying that code can be made infinitely fast as long as you are willing to accept an incorrect result.

@elia, @meh, @adambeynon any ideas on what (if anything) should be done with these methods?

**Comment by elia** [comment]
We need to measure 🕙 
We might discover that it's not that bad to do the right thing

**Comment by vais** [comment]
@elia don't hold out on me, I can't take the suspense.... what **is** *the right thing* to do?!

Joking aside, do you think we should try to use Opal's `Hash` instead? What do you have in mind?

**Comment by elia** [comment]
😅

Yes, if a benchmark using Hash instead of the JS object gives acceptable perf difference we can _fix all the things_!

**Comment by vais** [comment]
:smile: Ok, @elia, I will give that a shot! I really can't live without my `Array#uniq` :stuck_out_tongue_winking_eye: In fact, I use all of the above methods in Ruby regularly, so the thought of them kinda-maybe-working in Opal makes me really uncomfortable.

**Comment by Ajedi32** [comment]
FYI, JavaScript does have a native implementation of Hash called [`Map`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map). Unfortunately, browser support for `Map` isn't very mature yet. All of the latest browsers support it, but only the very latest. (E.g. IE10 doesn't support it, but IE11 does.)
