### ISSUE TITLE
true.eql?(true) #=> false

### ISSUE THREAD

**Issue by vais** [opal/opal#1003]
```
$ bundle exec opal -v
Opal v0.8.0.rc1
$ bundle exec opal-repl
>> true.eql?(true)
=> false
>> false.eql?(false)
=> false
```
:stuck_out_tongue_winking_eye:

**Comment by vais** [comment]
@eregon could really use your advice on this one. I cannot find any spec in RubySpec that would catch this bug. Any ideas where/how to add a spec for the correct behavior of the `eql?` method on booleans?

**Comment by vais** [comment]
@elia I already have a fix for this issue, but I don't want to push it without a spec to lock it down. Let's see what @eregon tells us...

**Comment by eregon** [comment]
@vais Good catch!
```ruby
> TrueClass.method :eql?
=> #<Method: Class(Kernel)#eql?>
```
So this should be specified in `Kernel#eql?`.
`Kernel#eql?` is an alias of `BasicObject#equal?` (and  `BasicObject#==` is another alias).
All these specs should be shared therefore, and some cases with true/false are already specified in `core/kernel/equal_spec.rb`, which is the wrong location (there is no such method) and should move to `core/basicobject/equal_spec.rb`.

Short version: it is a mess and I'll clean it :smile:

**Comment by eregon** [comment]
@vais Should be fixed with https://github.com/ruby/rubyspec/commit/52d82de0eff77db811a6800145f6456c178e595a, please confirm :)

**Comment by vais** [comment]
Thank you, @eregon, the new specs do catch the bug in Opal, so now we can work on a fix! Thanks again for the quick turnaround!
