### ISSUE TITLE
Code not executed in v. 0.8.0

### ISSUE THREAD

**Issue by svoboda-jan** [opal/opal#1012]
Hi,

I tried Opal `0.8.0` in my Rails app and noticed that instead of executing transpiled code inside anonymous JS function it just adds it to `Opal.modules`, but doesn't seem to be actually calling it from anywhere.

In `0.8.0` I have to add a script with `Opal.modules["application"](Opal)` to make the same code from `0.7.1` work. Is that a known / intended behaviour ?

```javascript
/* Generated by Opal 0.7.1 */
(function(Opal) {
  Opal.dynamic_require_severity = "ignore";
  var self = Opal.top, $scope = Opal, nil = Opal.nil, $breaker = Opal.breaker, $slice = Opal.slice;

  Opal.add_stubs(['$require', '$puts']);
  self.$require("opal");
  return self.$puts("G'day world!");
})(Opal);
```

```javascript
/* Generated by Opal 0.8.0 */
Opal.modules["application"] = function(Opal) {
  Opal.dynamic_require_severity = "ignore";
  var self = Opal.top, $scope = Opal, nil = Opal.nil, $breaker = Opal.breaker, $slice = Opal.slice;

  Opal.add_stubs(['$require', '$puts']);
  self.$require("opal");
  return self.$puts("G'day world!");
};
```

**Comment by elia** [comment]
Basically for the loading to be handled by opal-rails you need to switch from application.js to application.js.rb and use ruby requires. 

Otherwise you need to handle the initial loading yourself with either 

      Opal.require("your-module");

or

      Opal.load("your-module");

_Ping me to reopen if needed_

**Comment by svoboda-jan** [comment]
Thanks,

I was using `.js.rb` and ruby requires, but not the `opal-rails` gem. (befause of version flexibility with the `opal` gem)

I found the reson it stopped working:
https://github.com/opal/opal-rails/commit/0251a8ea9c0273383720022c9227a25031021b1b

So the change is that using opal with rails now requires loading code.

**Comment by elia** [comment]
Exactly, and if you want you can use 
      Opal::Processor.load_asset_code(sprockets, source)

directly, which will take care of marking bon Opal files and stubbed files as already required.
