### ISSUE TITLE
JS Library Integration (Example?)

### ISSUE THREAD

**Issue by ashes999** [opal/opal#1019]
Hi,

Other than jQuery, which has its own `opal-jquery` gem, how do I go about integrating with other, pure Javascript libraries, with Opal?

For example, if I wanted to use CraftyJS, I want to call JS methods like `Crafty.c(...)` or `Crafty.e(...)`. It's not clear from the docs or the existing issues how I would go about doing that, or if I need to create wrappers or something else before this would work.

Is there an example I can look at where someone does this, even with just a simple JS function or class?

**Comment by gabrielrios** [comment]
You can call JS from Ruby using backticks(`) http://opalrb.org/docs/compiled_ruby/#javascript-from-ruby

Or you can use the native module for simple wrapping http://opalrb.org/docs/compiled_ruby/#native-module

**Comment by ashes999** [comment]
@gabrielrios since there are two options, can you suggest which to use, or what the differences are?

Is it sensible (or is it wasteful) to create Ruby objects with methods that just wrap backtick-calls?

**Comment by Ajedi32** [comment]
@ashes999 That's what Native does. The way I see it, there are three levels of integration possible here:

1. Backticks
  - Quick and dirty.
  - Necessary in some situations (especially situations sensitive to performance).
  - A bit like writing inline assembly code in C.
2. `Native`
  - A quick way to wrap a JavaScript object and use it in Ruby.
  - Good for typical usage, or when a Ruby wrapper library isn't available.
3. Full wrapper libraries
  - Provide a Ruby-style interface to a JavaScript library
  - Preferable when available
  - If you're using a specific library a lot, it might be worth it to write your own wrapper library

**Comment by gabrielrios** [comment]
I think using Native is better, as your code looks better that way.
This is exactly what libraries like opal-jquery does. 

So if you're using things on just one place you might want to just use Native module directly, but wrapping on ruby objects is a better long-term solution

**Comment by ashes999** [comment]
If this can be documented somewhere, that would be fantastic, as it clearly identifies the trade-offs.

@Ajedi32 can you explain how backticks is a better option for performance-sensitive code? Roughly what kind of performance hit are we taking when we use native or wrapper libraries? (Also, please clarify if wrapper libraries means something other than what I described -- Ruby classes with methods/properties that use backticks internally.)

**Comment by Ajedi32** [comment]
@ashes999 It's not a serious hit. Pretty much analogous to using inline assembly in C. You get better control over the code generated, so you can do a lot of manual optimisation to make things run faster. I think you also save one method dispatch per call (you call the method directly, instead of calling the wrapper object which then calls the method).

In that remark about performance I was speaking more in the general case (writing inline JS code) than just the specific case of wrapping libraries. The overhead of an extra method dispatch is unlikely to be significant in most situations.

And yes, wrapper libraries typically use either backticks or native internally. The point of such a library is mostly just to provide a nicer, more Ruby-like interface to an existing JS library. (Compared to `Native`).

**Comment by elia** [comment]
@Ajedi32 would you like to write a short guide for this putting together the comments above?
_(If you do ping me in the PR and I'll help reviewing :smile_cat:)_

All the guides now live in the docs folder and are formatted in markdown:

https://github.com/opal/opal/tree/master/docs

**Comment by Ajedi32** [comment]
Sure, I'll give it a shot. Might take me a bit since I've been pretty busy with classes at college starting up again, but I'll get to it.

**Comment by Ajedi32** [comment]
Anything specific you think I should include beyond what's already in the docs. It seems to me that http://opalrb.org/docs/compiled_ruby/#javascript-from-ruby is already pretty clear, but that might just be because I already understand how they work.

**Comment by elia** [comment]
Agree, @ashes999 should we add something to the guide?

Otherwise can we close this?

**Comment by ashes999** [comment]
I'll submit a PR @elia, you can decide if it adds enough clarity, or if things are okay as-is.

**Comment by elia** [comment]
Closed by #1098
