### ISSUE TITLE
Calling methods on JS objects prefixes "$", resulting in "not found" errors

### ISSUE THREAD

**Issue by ashes999** [opal/opal#1023]
I'm working on wrapping CraftyJS with Opal. I have some methods that return pure JS objects. One such example is `return Crafty.e('2D Canvas Fourway')`.  This object has a `.fourway` method I can invoke in Javascript.

Here's the code I want to write:

```
@e = Crafty.e('2D Canvas Fourway') # Crafty.e => `Crafty.e(...)`
@e.fourway(8)
```

I get an error that `self.e.$fourway is not a function`.

The solution is to write (terrible?) code like:

```
@e = Crafty.e('2D Canvas Fourway') # Crafty.e => `Crafty.e(...)`
`#{@e}.fourway(8)`
```

This is worse with objects, such as when I'm passing in a hash -- instead of using Ruby notation (`{ :x => 3, :y => 70 }`), I have to use JS notation (`{ x: 3, y: 7 }`).

Is there an easy solution to this?

**Comment by gabrielrios** [comment]
You probably want to make `Crafty.e` return a Native object. Something like this

```ruby
class Crafty
  def self.e(args)
     Native(`Crafty.e(args)`)
  end
end
```

**Comment by ashes999** [comment]
That's excellent, thanks. It works.
