### ISSUE TITLE
(for x in hash) adds 300+ OpalClass instances to hash

### ISSUE THREAD

**Issue by ashes999** [opal/opal#1024]
Continuing my ongoing saga of integrating Opal with CraftyJS, I've run into a problem I can't solve.

CraftyJS has a function which pre-loads images and audio files. Here's an example of what you can pass in:

```
Crafty.load({
  images: ['image1.png', 'image2.png'], audio: ['audio3.ogg']
}, function() { ... loading complete ... });
```

Let's call the hash `data`. As part of it's loading process, it uses code like:

```
for (type in data) { // images, audio
  for (asset in data[type]) { // image1.png, image2.png
    asset.search(...)
  }
}
```

With Opal, I tried first sending in a Ruby hash and letting Opal convert it; I was getting a `$Hash` instance without the `images` and `audio` properties. To get around that, I convert it to JSON (via `to_s`.gsub('=>', ':')`, because `to_json` tells me that `no method to_json on <json-looking-string>').

Anyway, I managed to get the hash structured I want. It has only two properties, `images` and `audio`, with the array of objects.

But the problem is, the for-loop iterates over around ~400 objects, most of them being instances of `OpalClass`. Obviously, calling `someOapClassInstance.search` fails.  If I just call `for (x in data) { console.log(x) }`, I can see all the Opal-added properties (prefixed with `$`).

Is there a way to create a clean hash somehow, and avoid this problem?

Is there a way to fix this on Opal, without asking the CraftyJS guys to change their code (eg. by checking if `search` is defined before calling it)

This happens even if I pass in a hard-coded Javascript string:

```
var hash = { images: [1, 2], audio: [3] }
for (x in hash) { console.log(x); } // 300+ things come out
```

Or am I just misunderstanding something?

If you want to see this for yourself, you can look at [my project repository](https://github.com/ashes999/terrace). Repro steps:

- Run `ruby build.rb web-craftyjs`
- Open `bin/web-craftyjs/index.html` in your browser

You'll see the `f.search` error. You can set a breakpoint at `crafty.js:8537`.

**Comment by Ajedi32** [comment]
My guess is you'd have to use `Hash#to_native` or something? That doesn't seem to be documented anywhere though either, is it?

**Comment by Ajedi32** [comment]
Maybe some RDoc comments could be added to <https://github.com/opal/opal/blob/master/stdlib/native.rb#L489-L520>? Then we'd just need to use them to generate HTML and host them them somewhere.

**Comment by ashes999** [comment]
@Ajedi32 that solves the "outer" problem (`data` has only two things). The problem is that `data[type]` (`Array` instance -- eg. `data[images]`) still has the additional 300 objects in it.  I need to create a recursive structure with `to_n` all the way through.

Is this possible?

**Comment by elia** [comment]
@ajedi32 yes, actually there's already a place for that kind of docs at http://opalrb.org/docs/ under "API documentation". It's unfortunate that for some reason Native isn't covered and we need to fix that. 

As of the array to_n should call to_n on all its elements, if it doesn't let me know and we'll ask @meh to fix it 😊

**Comment by ashes999** [comment]
@elia I confirmed this by testing. Here's a minimal example that should reproduce it:

Ruby:
```
hash = { :primes => [1, 2, 3, 5, 7, 11] }
native = hash.to_n
`js_iterate(native)`
```

JS:
```
function js_iterate(obj) {
  for (var collection in obj) {
    var count = 0;
    for (var item in collection) {
      count++;
    }
    console.log("Count: " + count);
  }
}
```

`count` is 300+.

**Comment by gabrielrios** [comment]
I have hit this issue in the past #680

I guess that's because how Array works in Opal, being a toll-free bridge to JS Array, it has all those properties so the same object can be used on both JS and Opal code.

I know that probably blaming Crafty on this isn't exactly the solution, but I think iterating on a array using `for .. in ..` isn't recommended, and one should use `for .. of` (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...in#Array_iteration_and_for...in)

**Comment by ashes999** [comment]
I've confirmed that they've fixed this on the CraftyJS side. For anyone reading this, you need Crafty 0.6.4 or greater for this to work. (That release doesn't exist yet, so I'm using a custom dev version.)

Thanks for educating me about `for .. in` and `to_n`. There's lots to learn :)

**Comment by Ajedi32** [comment]
Should Opal be defining enumerable properties on the arrays returned by `to_n`? Seems to me that might be the real issue here. On the other hand, I believe it's recommended to use `hasOwnProperty` when using `for ... in` anyway. I don't really know...

**Comment by ashes999** [comment]
@Ajedi32 Do you want me to open an issue for that? Or to re-open this issue and clarify that when I have a hash with arrays, `hash.to_n` doesn't recursively call `to_n` on the arrays?

**Comment by Ajedi32** [comment]
@ashes999 It's probably cleanest to open a new issue for that IMO. Or instead you could just edit this issue to more accurately reflect the problem. Either way is fine.

**Comment by ashes999** [comment]
@Ajedi32  I've up dated your issue to describe the issue in detail. Let me know if you want me to do anything else.

**Comment by Ajedi32** [comment]
Oops, sorry. Guess I wasn't clear enough. By "this issue" I meant the one we're posting comments on right now (which you actually have the ability to edit, not just comment on), not the one I just created and linked to this issue.
