### ISSUE TITLE
Update mspec runner to phantomjs 2

### ISSUE THREAD

**Issue by elia** [opal/opal#1026]
That given the number of random crashes we're getting lately on travis.

cc @vais

**Comment by vais** [comment]
:+1:

**Comment by elia** [comment]
Apparently the crashes were due to a bug CRuby 2.2.1 which is what travis means by `2.2`, bumping the version seem to have made them disappear.

Yet updating to phantojs2 seems waaay easier than I thought as this commit by @aost demonstrates:

https://github.com/aost/opal-minitest/commit/787ab61cd8610363095f3e8178dbb95b90998b90
