### ISSUE TITLE
Backticks don't allow string substitution

### ISSUE THREAD

**Issue by Quincunx271** [opal/opal#1033]
In Ruby, this is allowed:

    cmd = 'ruby -e "puts 1"'
    p `#{cmd}`

In Opal, however, this does not work (I'm working with jQuery):

    methodName = "innerWidth"
    p `$(window).#{methodName}()`

Instead of compiling it to what I'd expect:

    methodName = "innerWidth"
    return self.$p(eval("$(window)." + methodName + "()"))

This compiles to:

    methodName = "innerWidth";
    return self.$p($(window).methodName());

This is definitely not what it should be compiled to.

----

Note that I should also be able do something like this:

    myArray = "[1, 2, 3, 4]"
    p `$.extend(true, [], #{myArray})`

This means that we cannot simply compile every case like the previous to this:

    methodName = "innerWidth"
    return self.$p($(window)[methodName]())

**Comment by Ajedi32** [comment]
> Instead of compiling it to what I'd expect:
> 
> ```
> methodName = "innerWidth"
> return self.$p(eval("$(window)." + methodName + "()"))
> ```
> 
> This compiles to:
> 
> ```
> methodName = "innerWidth";
> return self.$p($(window).methodName());
> ```
> 
> This is definitely not what it should be compiled to.

Given that methodName can't necessarily be known at compile time, what *should* it compile to? Were you expecting a call to [`eval`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/eval)? I guess I can see how that would make sense, but that's not how Opal does things.

Interpolation in backticks in Opal doesn't just work by doing string interpolation. Instead, it compiles the interpolated Ruby code to its JavaScript equivalent, then inserts that into the JS code in the x string.

This actually works better than string interpolation IMO. Try these instead:

```ruby
methodName = "innerWidth"
p `$(window)[#{methodName}]()`
```

```ruby
myArray = [1, 2, 3, 4]
p `$.extend(true, [], #{myArray})`
```

That's far less brittle than relying on the interpolated string resulting in valid JavaScript code IMO.

Also, you might be interested in [opal-jquery](https://github.com/opal/opal-jquery), given the code snippets you used as examples.

**Comment by Ajedi32** [comment]
IMO, the documentation should be amended to make this difference more explicit. The current section on [inline JavaScript](http://opalrb.org/docs/compiled_ruby/#inline-javascript) does include an example of interpolation done this way, but it doesn't explicitly spell out this difference in how interpolation of x-strings are handled.

**Comment by elia** [comment]
@Quincunx271 the desired behaviour can still be obtained via JavaScript `eval`:

```rb
methodName = "innerWidth"
p `eval(#{ "$(window).#{methodName}()" })`
```

@Ajedi32 agree, any wording you can suggest to improve the docs? 
(of course feel free to send a PR! :stuck_out_tongue_winking_eye:)

**Comment by elia** [comment]
_@Quincunx271 I closed the issue, but let me know if you feel this needs further discussion and I'll reopen_
