### ISSUE TITLE
Enumerator with_index has problems with arrays

### ISSUE THREAD

**Issue by Quincunx271** [opal/opal#1034]
I've discovered that this results in an array of `undefined`s:

    a = [5, 4, 3, 2, 1]
    a.map!.with_index { |element, index| [element, index] }

`map` instead of `map!` is slightly different; it outputs `[5, 4, 3, 2, 1]`. I don't know why this is so, but when I monkey patched `Enumerator` like so, it worked:

    class Enumerator
       def with_index(offset=0)
          return enum_for(:with_index) unless block_given?
          index = offset
          self.each do |value|
             result = yield value, index
             index += 1
             result
          end
       end
    end

**Comment by vais** [comment]
Good catch, thanks!
