### ISSUE TITLE
Calling Time#usec via Opal returns 0 and throws "Microseconds are not supported" 

### ISSUE THREAD

**Issue by djboardman** [opal/opal#1041]
I get a message saying `Microseconds are not supported` when I call `Time#usec` either in Chrome or in the following example on the "Try" page on opalrb.org (both on 0.8.0.beta1): 

http://opalrb.org/try/?code:t%20%3D%20Time.now%0Aputs%20t.usec

The input on the try page is:

    t = Time.now
    puts t.usec

And the output is:

    Microseconds are not supported
    0

It looks like `Time#usec` is supported in Opal by a call to `.getMilliseconds()` on a `Date` object, and a direct Javascript call to this works fine in the Chrome Console.

`Time#to_f` works fine so it's not a big deal to get subseconds, but is `Time#usec` supported?

**Comment by vais** [comment]
```
$ bundle exec opal -ve "p Time.now.usec"
Opal v0.9.0.dev
391000
```
https://github.com/opal/opal/blob/master/opal/corelib/time.rb#L376
:beers:
