### ISSUE TITLE
Proposal: add an example .html file to test/ directory or somewhere else

### ISSUE THREAD

**Issue by shevegen** [opal/opal#1043]
The readme at the main page says:

"Just open this page in a browser and check the JavaScript console."

However, some users - like me - may be a bit naive and struggle to get this to work.

Would it be possible to put those few lines in the .html file, into a standalone .html file too?

It could link to the remote .js, in the event that you do not want to distribute the current opal.js code with the .gem

**Comment by elia** [comment]
@shevegen can you check if https://github.com/opal/opal/pull/1087/files?short_path=04c6e90#diff-04c6e90faac2675aa89e2176d2eec7d8 is any good?

I changed the wording expecting the reader to know how to insert a js file in a page, but keeping the more extended HTML example. 

Any suggestion on how to improve would be really appreciated.

**Comment by elia** [comment]
closed by #1087
