### ISSUE TITLE
Proposal: add an option in Native ##alias_native to handle arrays of given class

### ISSUE THREAD

**Issue by balmoral** [opal/opal#1044]
Suggest additional option for the alias_native helper which will convert a native array to a ruby Array of a given class, e.g.

```
    alias_native :points, :points, array: Point 
```

Something like this:
```
    def alias_native(new, old = new, options = {})
        ...
        if as = options[:as]
           ...
        elsif klass = options[:array]
          define_method new do |*args, &block|
            if value = Native.call(@native, old, *args, &block)
              value.map{ |e| klass.new(e) }
            end
          end
        else
          define_method new do |*args, &block|
            Native.call(@native, old, *args, &block)
          end
        end
      end
    end
```

**Comment by elia** [comment]
Personally I'm not sure alias_native is the right method for this feature, but can't think of anything else either. 

cc @meh

**Comment by balmoral** [comment]
I’ve patched it into my project and it works well and seems natural in the code:
```
    alias_native :renderer, :renderer, as: Renderer
    alias_native :set_title, :setTitle
    alias_native :series, :series, array: Series 
```
Could be a very common requirement. Maybe keyword `:as_array_of` would make it read better:
```
    alias_native :series, :series, as_array_of: Series 
```
BTW Opal and it's partner Volt are truly liberating. Wrapping the Highcharts js library (opal-highcharts) hardly took any time. Now working on fully reactive implementation in Volt (volt-highcharts). Fast and fun client-side coding :smile: You guys are doing awesome work.

**Comment by meh** [comment]
I don't think this should go into `Native`.

As reference of how my stance is, check [this](https://github.com/opal/opal-browser/blob/master/opal/browser/navigator.rb) from `opal-browser`.

**Comment by elia** [comment]
> BTW Opal and it's partner Volt are truly liberating. Wrapping the Highcharts js library (opal-highcharts) hardly took any time. Now working on fully reactive implementation in Volt (volt-highcharts). Fast and fun client-side coding  You guys are doing awesome work.

Always great to hear! :smile_cat: 

I'm going to close the issue as I feel the same, keeping `Native` a bit lower level.

That sai I think it's useful anyway and could be a great addition to opal-activesupport for example. The method could change to something like `expose_native` or just `expose`.

**Comment by meh** [comment]
I was considering this a little more, and it wouldn't be out of scope if it used `Native::Array`, but the end result doesn't look that good.

Current:
```ruby
def mime_types
  Native::Array.new `#@native.mimeTypes`, get: :item, named: :namedItem do |m|
    MimeType.new(m)
  end
end
```

Would be:
```ruby
alias_native :mime_types, :mimeTypes, get: :item, named: :namedItem do |m|
    MimeType.new(m)
end
```

Opinions?
