### ISSUE TITLE
Class#new cannot be optimized by v8

### ISSUE THREAD

**Issue by jgaskins** [opal/opal#1045]
I just noticed that, in Chrome/v8, instantiation of Ruby objects is unable to be optimized by the VM because it uses the `arguments` array (via `*args` in Opal): https://github.com/opal/opal/blob/247d921f43e2fcdec47405c1c2a38472fc89ca71/opal/corelib/class.rb#L42

Safari doesn't seem to have any trouble with it (it renders Clearwater apps 3x as fast as Chrome when I don't use render caching), but in rendering a pretty large virtual DOM several times in Clearwater just now, I spent 14.6% of my CPU time in `Class#new`.

I don't know if there's a way around it, but @vais asked me nicely to open an issue. :-) I've tried a few things, like explicitly setting positional arg names in `Class#new`, but that breaks when you _do_ want splatted args in class constructors.

**Comment by jgaskins** [comment]
I did some more profiling and benchmarking and it looks like it's the reassignment of the splat variable that's causing the problem.

```ruby
require 'opal'

class Foo
  def bar(*args, &block)
    %x{}
  end

  %x{
    def.$baz = TMP_2 = function() {
      var $iter = TMP_2.$$p;
      var block = $iter || nil;

      var args = $slice.call(arguments, 0);
      TMP_2.$$p = null;
    };
  }
end
```

The two methods in this class compile to nearly identical JS. The only real difference is that `args` in `bar` is reassigned from the method signature. You can see I removed `args` from `baz`'s method signature and declared it as a variable within the function. Using this code that looks like it was written by a high-school student and not a veteran software engineer, I had some interesting results in both Chrome and Safari:

```ruby
foo = Foo.new

start = Time.now
count = 0
while Time.now - start < 10
  foo.baz
  count += 1
end

`document.write("<p>" + count + "</p>")`

start = Time.now
count = 0
while Time.now - start < 10
  foo.bar
  count += 1
end
```

In Chrome, the performance increase was roughly 18%:

```
19766704

16446747
```

In Safari, the results were even better (+24%):

```
31287542

25341646
```

Now, this is a microbenchmark and the results jumped around a bit (likely due to insane amounts of GC for all the `Arguments` and `Date` objects being generated), but when I modified `Class#new` to use this pattern, the profiling I did in Chrome on my giant Clearwater app (just spamming Cmd-[ and Cmd-] to force rerendering as much as possible) showed a vast reduction in the amount of time spent in `Class#new`. It dropped from 14% down to around 3.5%.

It still can't be fully optimized because it does use the `arguments` object, but the "Not optimized" message in the Chrome profile changed from "Assignment to parameter in arguments object" to "Bad value context for arguments object". Not sure if that's a good thing, but it appears to be faster.

**Comment by meh** [comment]
Can you benchmark something like `def foo(a, b, *args)` with and without reassignment?

Maybe those can be optimized a little too.

**Comment by jgaskins** [comment]
I've put the benchmark code into a [gist](https://gist.github.com/jgaskins/42a7f95d2cab130ac0fc) and made a few tweaks to it. Feel free to provide feedback if my hand-compiled JS isn't right. The results are a lot closer now, which I think might be due to the fact that I'm yielding blocks containing the code to benchmark rather than just having it inline.

Here are the results in Safari (11.2% better for positional + splat without block, 8.5% better for positional + splat + block):

```
Opal Default, no args, capture block: 24285032

Optimized JS, no args, capture block: 28194365

Opal Default, two args, no block: 25618967

Optimized JS, two args, no block: 28496845

Opal Default, two args, capture block: 22497150

Optimized JS, two args, capture block: 24424636
```

**Comment by elia** [comment]
Here's some background about the V8 error message: https://code.google.com/p/v8/issues/detail?id=3037

**Comment by meh** [comment]
This should be fixed now.
