### ISSUE TITLE
Inline if/unless with function call breaks

### ISSUE THREAD

**Issue by Papierkorb** [opal/opal#1049]
Hello. Running the following snippet on opalrb.org/try throws a Javascript error (See below):

````ruby
Element.find('.container').each do |element|
  next unless element.prop 'data-bound'
  puts element.inspect
end
````

But when I move the unless condition into a variable and check just that variable, it works:

````ruby
Element.find('.container').each do |element|
  foo = element.prop 'data-bound'
  next unless foo
  puts element.inspect
end
````

The above snippet should output two lines like `<Element ..>`

---

JavaScript error when trying the first snippet looks like this:

````
TypeError: $a is undefined
TMP_2@http://opalrb.org/javascripts/try.js line 20 > eval:22:55
x.yield1@http://opalrb.org/javascripts/try.js:4:27752
Opal.modules["opal/jquery/element"]/</l@http://opalrb.org/javascripts/try.js:20:1567
@http://opalrb.org/javascripts/try.js line 20 > eval:20:1
@http://opalrb.org/javascripts/try.js line 20 > eval:2:1
Opal.modules.try_opal/</def.$eval_code@http://opalrb.org/javascripts/try.js:20:27285
Opal.modules.try_opal/</def.$run_code@http://opalrb.org/javascripts/try.js:20:27177
Opal.modules.try_opal/TMP_3@http://opalrb.org/javascripts/try.js:20:28023
K.Callbacks/f@http://opalrb.org/javascripts/application.js:2:16761
K.Callbacks/p.fireWith@http://opalrb.org/javascripts/application.js:2:17547
.ready@http://opalrb.org/javascripts/application.js:2:12306
pt@http://opalrb.org/javascripts/application.js:2:9734
````

The interesting pieces from the generated JavaScript code:

**Broken** snippet:
````js
if ((($a = element.$prop("data-bound")) !== nil && (!$a.$$is_boolean || $a == true))) {
} else {
  return nil;
};
````

**Working** snippet:
````js
foo = element.$prop("data-bound");
 (foo !== false && foo !== nil) {
} else {
  return nil;
};
````

I think that `(!$a.$$is_boolean || $a == true)` in the broken snippet is the culprit, as `$prop()` returns `undefined`. Verification by manually calling it in the JavaScript console of the developer tools:

````js
Opal.Element.$find(".container").$prop("data-bound");
// => undefined
````

**Comment by meh** [comment]
Ruby methods should never return non-Ruby values.

**Comment by meh** [comment]
For the sake of discussion #867 would *fix* this, but I'm strongly against it because things would break again as soon as you try to call a method on any bubbled up `undefined` or `null` instance and it would be even harder to debug.

**Comment by Papierkorb** [comment]
Isn't this a bug with opal-jquery then, in that a method it provides may yield weird results?

**Comment by meh** [comment]
@Papierkorb very likely, yes, open an issue on there :panda_face:
