### ISSUE TITLE
class varible named @constructor is not converted properly

### ISSUE THREAD

**Issue by bwl21** [opal/opal#1053]
```ruby
  def initialize(name)
    @name = name
    @constructor = "foo"
  end
```

compiles to in http://opalrb.org/try/#
```javascript
    def.$initialize = function(name) {
      var self = this;

      self.name = name;
      return self.constructor = "foo";
    };
```

but as `@constructor` is a variable already coming from javascript. As @elia told me, it should compile to `constructor$`

**Comment by vais** [comment]
Duplicate of https://github.com/opal/opal/issues/993
