### ISSUE TITLE
Inconsistent behavior with anonymous classes.

### ISSUE THREAD

**Issue by yxhuvud** [opal/opal#1054]
code:

```rb
x = Class.new
X = x
class X
  def initialize
    puts 'hi'
  end
end
x.new
```
opal output:

mri output:
`hi`

**Comment by vais** [comment]
@elia is this related to https://github.com/opal/opal/issues/1056 and maybe also fixed by https://github.com/kachick/opal/commit/e818cc8b3784621ae560c43f259a4e9f74ffa986?
