### ISSUE TITLE
opalrb alongside sprockets asset pipeline

### ISSUE THREAD

**Issue by Thermatix** [opal/opal#1055]
I can't find out how to integrate opalrb with a sprockets asset-pipeline, how do you do this? 

I don't want to have two separate sprockets processes, one for opalrb and one for assets, unless of course this is the only way you can have it?

**Comment by elia** [comment]
Here's a complete example from opal-rails which does just that reusing the sprockets environment of rails:

https://github.com/opal/opal-rails/blob/master/lib/opal/rails/engine.rb#L28-L67

**Comment by Thermatix** [comment]
Thank you!

**Comment by elia** [comment]
:+1:

**Comment by Thermatix** [comment]
umm right sorry to open it up again, but this is very, rails specific, I'm trying to do this for sinatra.

**Comment by elia** [comment]
no prob, if you're using sinatra then you probably want to check out the sinatra example in the repo and let me know if that works for you:

https://github.com/opal/opal/blob/master/examples/sinatra/config.ru

**Comment by Thermatix** [comment]
I've looked at that, but seeing that Opal uses sprockets, I decided to move from asset-pack to sprockets and integrate opal into it so only one sprockets instance is running.

Looking at that code example however, it looks like opal detects and integrates into sprockets automatically, so you only end up with one sprockets instance, is this correct?

**Comment by elia** [comment]
There's a prepackaged rack app (Opal::Server) that includes a sprockets environment but you can also do things manually (like in the rails example). 

Alas, mixing rack and sprockets and custom stuff is not straightforward. But the task is considerably easier if you don't care about sourcemaps. If that's the case you should be able to just add `Opal.paths.each {|p| sprockets.append_path p}` and sprockets will pick up opal files from your assets dir.

Anyway I guess you need to mix in all of the above examples to find your custom solution.

**Comment by Thermatix** [comment]
ok, thanks for clarity, I will probably add my solution this issue thread but thank you.

**Comment by elia** [comment]
Yes definitely share your solution and feel free to ask if you're stuck on something

**Comment by Thermatix** [comment]
Ok, how do I deal with setting up opals config? like it is here? https://github.com/opal/opal-rails/blob/master/lib/opal/rails/engine.rb#L47-L51 where do the settings come from and where are they normally set up from?

**Comment by elia** [comment]
they come from rails standard config, the current way to set global config for opal is through Opal::Config

https://github.com/opal/opal/blob/master/lib/opal/config.rb#L7-L13

eg:

```rb
Opal::Config.arity_check_enabled = true if ENV['RACK_ENV'] == 'development'
```

PS. you see `Processor` there because it is outdated, should be `Config`

**Comment by Thermatix** [comment]
How do I tell sprockets I'm using opal?

Ok, so now I'm doing config like this:

```ruby
Opal::Config.config.each do |c_option,default|
	unless default == assets.opal_config[c_option]
		c = "#{c_option}="
		Opal::Config.send(c,assets.opal_config[c_option])
	end 
end

so, unless you set something different, it won't change the defaults.

**Comment by elia** [comment]
@Thermatix requiring opal should be sufficient (it requires opal/processor internally: https://github.com/opal/opal/blob/d9dee023a057de5b4289825826dad8037ca08508/lib/opal/sprockets/processor.rb#L166-L167)

**Comment by Thermatix** [comment]
I see, Ok, well I think I got it working, sort of, the browser returns 200 for the resources. the mime types is set correctly... only nothing is returned and I don't know why and i'm still fairly new to sprockets so I was wondering if you could tell me what I'm doing wrong?

Here's a [gist](https://gist.github.com/Thermatix/6c7d579a4962cc905d72) with what I've got so far.
