### ISSUE TITLE
Assigning anonymous class to a constant doesn't name the class

### ISSUE THREAD

**Issue by jgaskins** [opal/opal#1056]
MRI:

```
2.2.1 :001 > Foo = Class.new
 => Foo
2.2.1 :002 > Foo.new
 => #<Foo:0x007fec0aaad4a0>
```

Opal ([try link](http://opalrb.org/try/?code:Foo%20%3D%20Class.new%0Ap%20Foo.new)): `#<#<Class:0x4c6>:0x4c8>`

I am reasonably sure MRI has a special parser rule for assigning constants. Because of that, I don't know how difficult this would be to implement. I'm sure it's possible to do in Opal, but I'm kind of afraid of how deep it would have to be.

I noticed this because `Foo = Struct.new(:bar)` gave me `AnonClass` when I pretty-printed it.

**Comment by elia** [comment]
@kachick I used a slightly different approach in d9dee02 (vs e818cc8), please let me know if you see any potential problem with it

**Comment by kachick** [comment]
@elia :beers:
