### ISSUE TITLE
code compiled from opal doesn't seem to do anything

### ISSUE THREAD

**Issue by Thermatix** [opal/opal#1058]
So, I have code and opal is compiling it, but it doesn't seem to be doing anything

For example I'd expect:
```ruby
puts 'Hello World!'
```
To compile to (or something close to):
```javascript
console.log('Hello World!')
```
and output into the console `Hello World!`, instead it compiles to:
```javascript
/* Generated by Opal 0.8.0 */
Opal.modules["javascripts/hello_world"] = function(Opal) {
  Opal.dynamic_require_severity = "error";
  var self = Opal.top, $scope = Opal, nil = Opal.nil, $breaker = Opal.breaker, $slice = Opal.slice;

  Opal.add_stubs(['$puts']);
  return self.$puts("Hello World!")
};
/* Generated by Opal 0.8.0 */
Opal.modules["application"] = function(Opal) {
  Opal.dynamic_require_severity = "error";
  var self = Opal.top, $scope = Opal, nil = Opal.nil, $breaker = Opal.breaker, $slice = Opal.slice;

  Opal.add_stubs(['$require']);
  return self.$require("javascripts/hello_world")
};

```

And doesn't do anything.

Whats going on?

**Comment by elia** [comment]
You need to bootstrap the app main module from JavaScript with `Opal.load('application')`.
Alternatively you can use `Opal::Processor.load_asset_code(sprockets_env, name)` from Ruby which will  return the proper JS bootstrap code and works nicely with non-opal libs files and stubs.

An example of the produced code would be:

```
      if (typeof(Opal) !== 'undefined') {
        Opal.mark_as_loaded("opal");
Opal.mark_as_loaded("corelib/runtime.self");
Opal.mark_as_loaded("jquery.self");
Opal.mark_as_loaded("jquery_ujs.self");
Opal.mark_as_loaded("rspec/matchers/built_in/have");
Opal.mark_as_loaded("diff/lcs");
Opal.mark_as_loaded("diff/lcs/hunk");
Opal.mark_as_loaded("fileutils");
Opal.mark_as_loaded("test/unit/assertions");
Opal.mark_as_loaded("coderay");
Opal.mark_as_loaded("optparse");
Opal.mark_as_loaded("shellwords");
Opal.mark_as_loaded("socket");
Opal.mark_as_loaded("uri");
Opal.mark_as_loaded("drb/drb");
        Opal.load("application");
      }
```

**Comment by elia** [comment]
link: http://www.rubydoc.info/gems/opal/Opal%2FProcessor.load_asset_code

_really need to add some comments :confounded:_

**Comment by Thermatix** [comment]
So including the opal library isn't enough? huh, ok, where would I put `Opal::Processor.load_asset_code(sprockets_env, name)`? is it something that I put in my opal ruby files or after I load and set up sprockets or in a route?

**Comment by Thermatix** [comment]
Hmmm Ok, but how do I get the sprockets environment into it? aren't the files compiled by opal in a different environment to the main app?
