### ISSUE TITLE
Can't define methods when a mandatory parameter is put just after an optional one

### ISSUE THREAD

**Issue by RoxasShadow** [opal/opal#1062]
`def sample(a = nil, b); end` is given to both the rubies.
- Opal 0.8.0.beta1

> SyntaxError: An error occurred while compiling: (file)
> 
> unexpected '"tRPAREN"'
> Source: (file):1:22
> def sample(a = nil, b); end
> ~~~~~~~~~~~~~~~~~~~~~^
- rbx-2.5.7 (but also mri-2.2.0)

> rbx-2.5.7 :006 > def sample(a = nil, b); end
> => :sample

**Comment by alexdowad** [comment]
It seems that the parser only expects to see arguments with default values at the end of the arglist.

**Comment by alexdowad** [comment]
Looking at debug parser output, I could see that the `a = nil` bit is reduced to `f_optarg`. Searching for `f_optarg` took me to the rule for an argument list: it's `f_args` at `grammar.y:1564`. Looking the rule over, it was definitely not designed to accept an argument with default value *before* an argument without. I can fix the grammar, but I wonder what the compiler will do after that...

**Comment by alexdowad** [comment]
Both `parser` and `opal` have the same `f_args`... but `parser` has 15 derivation rules for it, `opal` has 9. This is to cover cases like the one in this issue.

**Comment by alexdowad** [comment]
The compiler definitely needs an upgrade first. I just tried patching the grammar to accept a restarg before a normal arg. Result:

```
6:13 ~prog/Ruby/opal % bundle exec bin/opal -e "def sample(*a, b); end"        [master]
(:args, (:restarg, :a), (:arg, :b))

/tmp/opal-nodejs-runner-20151206-18143-11dtj1s:18989
  return (Opal.defn(Opal.Object, '$sample', function(, b) {
                                                     ^
SyntaxError: Unexpected token ,
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3
```

**Comment by vais** [comment]
@alexdowad btw, fixing this would make it possible to start running all of the RubySpecs in [rubyspec/core/method](https://github.com/ruby/rubyspec/tree/master/core/method) directory, which are currently not being run at all because of parser errors - https://github.com/opal/opal/blob/master/spec/rubyspecs#L63 :wink:

**Comment by elia** [comment]
@alexdowad please send a PR anyway as it would make the perfect starting point to fix the compiler.

**Comment by elia** [comment]
```rb
def sample(a = nil, b); p [a,b]; end
sample 2
sample 1, 2
```

result:

```
⤑ pbpaste | opal _0.10.3_
[nil, 2]
[1, 2]
```
