### ISSUE TITLE
wrapper function for templated backtick string fails fails to work

### ISSUE THREAD

**Issue by Thermatix** [opal/opal#1067]
simply put this works

```ruby
Document.ready? do
	render_component LoginForm, `document.getElementById('view_port')`
end
```

This doesn't

```ruby
def get_by_id id
	`document.getElementById('#{id}')`
end

Document.ready? do
	render_component LoginForm, get_by_id('view_port')
end
```
With or without a return in the `get_by_id ` function.

Either I'm missing something or this is a bug?

**Comment by meh** [comment]
`document.getElementById('#{id}')` is going to get compiled into `document.getElementById('id')`, you want to pass the id without the quotes.

**Comment by Ajedi32** [comment]
This is pretty much a duplicate of #1033. I guess this is a pretty common misunderstanding.
