### ISSUE TITLE
if to_s does not return a string, things blow up

### ISSUE THREAD

**Issue by catmando** [opal/opal#1068]
``` ruby

class Foo < String
end

class Bar 
  def to_s
    Foo.new
  end
end

puts "abc#{Bar.new}def"

```

dies with

`TypeError: Cannot convert object to primitive value`

**Comment by jgaskins** [comment]
I thought MRI would fall back to `inspect`, but it looks like it uses the default `to_s` implementation if `to_s` doesn't return a string:

```
2.2.3 :001 > Foo = Class.new { define_method(:to_s) { Object.new } }
 => Foo
2.2.3 :002 > Foo.send(:define_method, :inspect) { 'zomg' }
 => :inspect
2.2.3 :003 > "Hello #{Foo.new}"
 => "Hello #<Foo:0x007fc3a63d1870>"
```

**Comment by elia** [comment]
just for info here's the relevant code: https://github.com/opal/opal/blob/master/lib/opal/nodes/literal.rb#L121-L147

Apparently it doesn't call `.$to_s()` explicitly but rather relies of JS calling `.toString()` [wich in turn calls `.$to_s()`](https://github.com/opal/opal/blob/master/opal/corelib/runtime.js#L1828-L1830)

So, maybe we can just add a check about $to_s presence in the runtime and extract the [default implementation](https://github.com/opal/opal/blob/master/opal/corelib/kernel.rb#L1137-L1139) to something like `Opal.objectToString(obj)`.

**Comment by hmdne** [comment]
It works for subclasses of String in v1.1.

But this code still breaks:

```ruby
class Foo
  def to_s
    "test"
  end
  alias inspect to_s
end

class Bar 
  def to_s
    Foo.new
  end
end

puts "abc#{Bar.new}def"
```

**Comment by hmdne** [comment]
In short, to fix it, we may need to run toString in a loop...
