### ISSUE TITLE
Return value of implicit hash ||= assignment with missing parentheses discards code in JS

### ISSUE THREAD

**Issue by Papierkorb** [opal/opal#1069]
Hello,

Opal generates bad JavaScript code for the following snippet:

````ruby
class Cacher
  def cached(selector)
    @cache ||= {}
    @cache['a'] ||= expensive 'something'
  end
  
  def expensive(a)
    "foo"
  end
end

puts Cacher.new.cached('foo').inspect
````

The snippet implements a simple cache with a Hash as store. Line 4 returns the value for the key 'a' if one is set, else it sets the value to whatever the part after `||=` evaluates to. In all cases, the method is expected to return `"foo":String`

The issue is with line 4: `@cache['a'] ||= expensive 'something'`

Opal has an issue with this because the arguments to `expensive` are not in parentheses. If you change the line to this: `@cache['a'] ||= expensive('something')`, it works as expected. MRI returns the expected value with and without parentheses.

What's interesting is that when looking at the generated JavaScript code, you see that Opal completely omits the call on the right of `||=`:

````javascript
def.$cached = function(selector) {
  var $a, self = this;
  ((($a = self.cache) !== false && $a !== nil) ? $a : self.cache = $hash2([], {}));
  return self.cache;
};
````

Compared to the version **with** parentheses:
````javascript
def.$cached = function(selector) {
  var $a, $b, $c, self = this;

  ((($a = self.cache) !== false && $a !== nil) ? $a : self.cache = $hash2([], {}));
  return ($a = "a", $b = self.cache, ((($c = $b['$[]']($a)) !== false && $c !== nil) ? $c : $b['$[]=']($a, self.$expensive("something"))));
};
````

**Comment by Papierkorb** [comment]
Fixed in current `master`, closing. Thanks!

**Comment by elia** [comment]
👍🏼
