### ISSUE TITLE
Increasing default Opal runtime size

### ISSUE THREAD

**Issue by jgaskins** [opal/opal#1071]
I've noticed the JS payload for my Clearwater apps getting larger with each Opal upgrade, so I thought I'd have a look at the minified+gzipped size of each Opal release back to 0.7.2:

- 0.7.2: 37KB
- 0.8.0: 43KB
- 0.9.0.dev: 55KB

These only include the Opal runtime, compiled and minified via the Rails asset pipeline — the only line in my `app/assets/application.rb` file was `require 'opal'`. The over-the-wire footprint of the Opal runtime has increased by almost 50% since 0.7.2. I realize that this is because of the breakneck speed at which Rubyspecs are being implemented (which I really do applaud), but I wonder if maybe we should make some of those features opt-in to trim down the payload — I remember @adambeynon talking about this several months ago on the Gitter channel. For example, I don't think a lot of apps will need `Complex` and `Rational`, so it might be worth pruning those from the default payload.

It's not a huge deal; a difference of 18KB isn't serious. The only reason it caught my attention is that sometimes I brag that an entire Clearwater app (including all dependencies like the Opal runtime, `virtual-dom`, and `opal-browser`) is usually smaller than Ember.js and I can't do that now. :-)

For the sake of numeric exposition:
- Ember.js was 97KB at the time on its own — no Handlebars, Ember Data, or the Ember app itself
- a "Hello World" Clearwater app (including the Opal runtime, `virtual-dom`, and `opal-browser`) was somewhere in the ballpark of 87KB on Opal 0.7.2
- [Ember.js is now 107KB](http://emberjs.com/builds/#/release), but I don't know if that includes Handlebars/HTMLBars or Ember Data these days.
- the app I'm currently working on is about 115KB minified+gzipped on 0.9.0.dev. Opal + Clearwater clocks in at 107KB, so it's still on par at least. :-)

**Comment by jaredcwhite** [comment]
I appreciate you pointing this issue out -- I just gotta say WOW, that is truly crazy that Opal + Clearwater minified & gzipped is still mostly on par with Ember.js. Either that proves Opal is awesome, or rather it proves the top JS frameworks out there have to implement so much stuff on top of JS to make things usable, it might as well be its own programming language. :)

**Comment by elia** [comment]
💂🏾✋🏿 Imma let you finish, but this PR has the best timing ever https://github.com/opal/opal/pull/1066

**Comment by jgaskins** [comment]
@jaredcwhite Pretty much. Underscore.js is basically just Ruby's `Enumerable` for JS, which makes sense because Jeremy Ashkenas (author of Underscore as well as CoffeeScript and Backbone) was a Ruby developer before he got into JS.

@elia Nice! Something that makes the timing even more perfect is that I actually had the new issue page open since right about when that PR was opened, I just kept forgetting to finish it up and submit it. :-) :boom:

On that note, closing because [we can cherry-pick what we need now](https://github.com/opal/opal/tree/master/opal#cherry-picking).

**Comment by elia** [comment]
Ha! Remember to share the numbers if you check them. Also PRs adding docs for this would really be appreciated 😁

**Comment by jgaskins** [comment]
This is the minimum Opal runtime required to run the Clearwater app I'm experimenting with (a Twitter client):

```ruby
require 'opal/mini'
require 'corelib/number' # Number#to_s, VirtualDOM can't handle numbers as VDOM child nodes
require 'corelib/io'     # I think I needed this for XHR?
require 'corelib/proc'     # JS function/Proc conversion
require 'corelib/time'     # Time.now
require 'corelib/method' # I use Object#method in a few places for event handlers in the app
require 'corelib/unsupported' # I honestly can't remember why I needed this, but it changed my error message :-)
```

Comes out to 47KB for the runtime — a savings of 8KB (about 15%) from the full thing. I haven't gotten all the way through the the `opal/base` version yet. I agree with [@meh's comment](https://github.com/opal/opal/pull/1066#issuecomment-131998069) that most people won't care enough to do this unless that 8KB is seriously necessary.

I think there's still a little work to do in there to ensure proper dependencies are required in the `opal/base` case. I'll submit PRs if I see them again.

**Comment by meh** [comment]
@jgaskins yeah, the situation for cherry-picking is still a little messy for now, in the next week or so I'll try to fix some related stuff, for instance `Regexp` is needed in the base because it's used in `#const_get` because we're lazy.

**Comment by meh** [comment]
Also I'm unsure whether `unsupported` should go in the base or not, it's not needed per-se, but it provides stubs/meaningful errors for things that are actually unsupported by Opal, or almost dummy supported (like `private` and friends).

**Comment by meh** [comment]
Oh, also `corelib/number` shouldn't be required anymore after I push this, I just forgot to update it after I merged `numeric-redux`.

**Comment by meh** [comment]
@jgaskins ok, you should be able to reduce the requires to:

```ruby
require 'opal/mini'

require 'corelib/io'
require 'corelib/time'
require 'corelib/unsupported'
```

**Comment by jgaskins** [comment]
Nice!
