### ISSUE TITLE
require (and require_tree etc.) don't work with non .rb files

### ISSUE THREAD

**Issue by Qqwy** [opal/opal#1073]
I am trying to use opal-haml. (https://github.com/opal/opal-haml)
This library uses Opal to compile HAML to HTML.
The steps on the GitHub readme are very straightforward. However, requiring the `.haml` files as they do there is no longer possible in Opal 0.7.2:

`require_tree 'app/views'` 
has the following result
(Note that app/views contains one file, called `item.haml`)

    A file required by "application" wasn't found.
    can't find file: "views/item" in [...list of paths in Opal's path variable...]

The same happens with `require 'app/views/item'`

I notice the following behaviour
=> The file loads if specifying the full filename. But, as methods like require_tree are to be used on whole folders, this will not work for them.
=> A `.rb` file loads normally without needing to specify the extension manually.

**Comment by Qqwy** [comment]
I believe that this regex might be the reason the files are found.

https://github.com/opal/opal/blob/master/opal/corelib/runtime.js#L1686

Maybe this needs to strip away all extensions, except only .js, .rb and .opal?

**Comment by Papierkorb** [comment]
@Qqwy, try using Opal 0.8 - That fixed it for me:
````ruby
gem 'opal', github: 'opal/opal', tag: 'v0.8.0'
gem 'opal-rails', github: 'opal/opal-rails', tag: 'v0.8.0'
gem 'opal-haml', github: 'opal/opal-haml', tag: 'v0.4.0'
````

**Comment by Qqwy** [comment]
Thank you very much! Indeed, the problem is fixed in version 0.8.

**Comment by Qqwy** [comment]
Still, it seems to have some oddities.

require_tree 'views/*' works, but require_tree 'views/' does not.

However, when using require_tree 'views/*' like that, any calls to `Template['views/view_name.haml']` will return `nil`.

What is going wrong?

**Comment by elia** [comment]
_sorry for the late reply_

@Qqwy `require_tree` takes the path to a folder, no globs support, it's based on the require_tree directive from sprockets.
