### ISSUE TITLE
stdlib/source_map/vlq is broken

### ISSUE THREAD

**Issue by zetachang** [opal/opal#1075]
```ruby
require "source_map/vlq"
puts SourceMap::VLQ.encode([0])
```
It should output "A", but instead we got empty string. 

After investigation, the problem is due to `begin; end while` block around https://github.com/opal/opal/blob/master/stdlib/source_map/vlq.rb#L31-L36.

According to https://github.com/opal/opal/issues/575, Opal implemented differently compared to MRI.

A solution may be using a `loop do; break; end` to replace it.

Some context: I am working on https://github.com/zetachang/opalrb-loader, thus source map support will be utilized.

**Comment by elia** [comment]
Apparently I fixed this upstream but forgot to apply in our copy 

https://github.com/maccman/sourcemap/issues/10

**Comment by elia** [comment]
fixed by https://github.com/opal/opal/pull/1426
