### ISSUE TITLE
Class.to_s does not return full class name

### ISSUE THREAD

**Issue by wied03** [opal/opal#1079]
code:

```Ruby
module Foo
  class Bar
  end
end

puts Foo::Bar.to_s
puts Foo::Bar.name
```

MRI output:
```
Foo::Bar
Foo::Bar
```

Opal output:
```
Bar
Foo::Bar
```

**Comment by meh** [comment]
Fixed on master.

**Comment by wied03** [comment]
@meh - Sorry about that, checked the earlier one today but not that one

**Comment by wied03** [comment]
https://github.com/opal/opal/commit/3e0b1b305ca625c21dcf293dd38578fd17da6a74

**Comment by meh** [comment]
I meant I just fixed it, on master :panda_face:

**Comment by vais** [comment]
@meh, LOL, https://github.com/opal/opal/commit/9933c666c7dd276fd7d5ee601f828adb37468672
https://github.com/opal/opal/issues/816#issuecomment-96906072

**Comment by Ajedi32** [comment]
@vais Ha, well I guess that's what happens when we don't have regression tests. :wink:

**Comment by vais** [comment]
@Ajedi32 good point, I lean on RubySpec too much :smile:
