### ISSUE TITLE
Hash.new with JS object w/ arrays as values doesn't recurse into the array

### ISSUE THREAD

**Issue by jgaskins** [opal/opal#1095]
I noticed it because we're using `gon` to transfer state to our client apps. When I ran this on the opal side to get my initial state:

```ruby
Hash.new(`gon`)
```

The top-level values were good, and so were any nested hashes, except ones contained within arrays. For example ([try link](http://opalrb.org/try/?code:gon%20%3D%20%25x%7B%0A%20%20%7B%0A%20%20%20%20a%3A%20%7B%20b%3A%202%20%7D%2C%0A%20%20%20%20c%3A%20%5B%7B%20d%3A%201%20%7D%5D%2C%0A%20%20%7D%0A%7D%0A%0Agon_hash%20%3D%20Hash.new(gon)%0Aa%20%3D%20gon_hash%5B%3Aa%5D%0Ac%20%3D%20gon_hash%5B%3Ac%5D%0A%0Ap%20a%0Ap%20c):

```ruby
gon = %x{
  {
    a: { b: 2 },
    c: [{ d: 1 }],
  }
}

gon_hash = Hash.new(gon)
a = gon_hash[:a]
c = gon_hash[:c]

p a
p c
```

The output is:

```
{"b"=>2}
TypeError: undefined is not a function (evaluating 'i.$__id__()')
$inspect@http://opalrb.org/javascripts/try.js:7:9276
i@http://opalrb.org/javascripts/try.js:5:49029
yield1@http://opalrb.org/javascripts/try.js:4:49598
g@http://opalrb.org/javascripts/try.js:7:4626
http://opalrb.org/javascripts/try.js:5:49052

eval code
eval@[native code]
$eval_code@http://opalrb.org/javascripts/try.js:20:52222
$run_code@http://opalrb.org/javascripts/try.js:20:52122
$@http://opalrb.org/javascripts/try.js:20:77095
o@http://opalrb.org/javascripts/try.js:20:2773
dispatch@http://opalrb.org/javascripts/application.js:3:4887
a@http://opalrb.org/javascripts/application.js:3:780
```

**Comment by wied03** [comment]
I've noticed this as well

**Comment by wied03** [comment]
I suppose some fixes might need to be made to the Hash monkey patch in https://github.com/opal/opal/blob/master/stdlib/native.rb
