### ISSUE TITLE
How to access DOM?

### ISSUE THREAD

**Issue by xjlin0** [opal/opal#1112]
Is it possible to access DOM in Ruby then translated by Opal?

Say, grab an element such as $('#whateverID')?  Thanks!

**Comment by elia** [comment]
You can use [opal-jquery](https://github.com/Opal/Opal-jquery) or Opal-browser or require "native" from the standard lib and access the native browser Dom API 

Ping me if you need more details or ask in the gitter channel (see the readme).

**Comment by elia** [comment]
Almost forgo to point to the docs section of the Opal website: opalrb.org/docs :)
