### ISSUE TITLE
undef doesn't take a symbolized string

### ISSUE THREAD

**Issue by jgaskins** [opal/opal#1127]
I was trying to use the `hamster` gem in a Clearwater app. It uses `undef` in a few of its classes to reduce API size, but it passes a symbol wrapped in quotes: `undef :"<=>"`. I checked and the fact that the string contains non-alphanumeric characters doesn't matter. This code also doesn't compile:

```ruby
class Foo
  undef :"object_id"
end
```

The thing is, `:"<=>"` is valid Ruby according to the compiler. It only breaks when passed to `undef` and other directives like `alias`.

If you've got ideas as to where this would be in the compiler, I can go ahead and try to fix it.

**Comment by elia** [comment]
If we're lucky it's just the lexer (lexer.rb) otherwise it's the grammar (grammar.y) 

Keep me posted on this if you need any help, although I'm no expert when it comes to racc grammars :\

**Comment by jgaskins** [comment]
It shouldn't be the grammar, should it? Wasn't that just copied from MRI?

**Comment by elia** [comment]
> Wasn't that just copied from MRI?

From what I know it has been copied at some point and then modified, was adam's field :)

**Comment by wied03** [comment]
I'm no Adam, but from recent work in this area, I think the lexer is picking this up OK. It looks like a parser/grammar issue to me. I haven't yet had to rework the grammar clauses though (only the Ruby code within the YACC clauses).
