### ISSUE TITLE
Promises can only have one then/fail call.

### ISSUE THREAD

**Issue by jgaskins** [opal/opal#1142]
Consider this code:

``` ruby
Browser::HTTP.get(url).then do
  # ...
end.fail do
  # ...
end
```

The problem I'm having is that there is ambiguity around what triggered the `fail` block; it could be a 4xx/5xx HTTP response or an exception raised in the `then` block. If there could be separate `fail` blocks for each path, that would help, but unfortunately this doesn't work:

``` ruby
request = Browser::HTTP.get(url)
request.then { handle_successful_request }.fail { handle_exception_in_success_handler }
request.fail { handle_failed_request }
# ArgumentError: a promise has already been chained
```

Opal promises seem to be required to have a linear path. Most promise implementations (including native JS promises in browsers) allow multiple success/failure blocks at every level. It looks like Opal's `Promise` class uses a doubly linked list for the callback chain, which seems to be the limiting factor.

**Comment by hmdne** [comment]
This is already fixed. Promise(v1 and v2) do support multiple chains now, unless called with then!, fail! etc.
