### ISSUE TITLE
Include Class instead of Module

### ISSUE THREAD

**Issue by fazibear** [opal/opal#1146]
If I try to include `Class` instead if `Module` I'll get weird error:

```
Uncaught TypeError: Cannot read property 'push' of undefined
```

example:

```ruby
class Test
end

class Test2
  include Test
end
```

**Comment by Ajedi32** [comment]
Eh, not too big of a deal since that's supposed to throw a TypeError anyway: `TypeError: wrong argument type Class (expected Module)`

You're right that the message is a bit strange though. Probably a good idea to fix this.
