### ISSUE TITLE
Ability to turn off object freeze warning?

### ISSUE THREAD

**Issue by wied03** [opal/opal#1157]
It might be nice to be able to suppress warnings re: the new object freeze warning in Opal 0.9. It's used in the rspec code base with constants all over the place, which makes it impossible to monkey patch away in order to avoid the warning.

Open to having a setting like for dynamic require severity?

**Comment by meh** [comment]
It should warn just once, is that too much?

**Comment by wied03** [comment]
I was thinking about it adding noise when trying to capture JSON/XML output from an rspec run, but you're right, it's only once, and it's going to $stderr, so with a little tweaking w/ phantom/node, it ought to be easy to redirect error output on the command line using 2> error.txt. Sorry for the noise.
