### ISSUE TITLE
Redesign block and metadata passing.

### ISSUE THREAD

**Issue by meh** [opal/opal#1181]
Right now blocks are handled with a property on the `Function` object that expects a block, `$$p` is the block, and `$$s` is the `self` value to use.

This can cause very weird bugs in case the special properties are cleared or set incorrectly.

I'm pretty sure the following bugs are caused by the current design: #1176, #1173, #811.

Just fix bugs
-------------
We could litter the whole codebase with try/catch blocks to properly reset or set to the previous values all the block calls, this is going to have a huge performance hit.

Make `$$p` and `$$s` a stack
----------------------------
If `$$p` and `$$s` were a stack, the prelude for the block could pop the values that have been set from the caller, thus removing the problem of resetting the values and no need for try/catch because the handling would be before any exceptions can happen.

This has the downside of keeping around a lot of values that might be useless, and if the call stack gets deep enough the block stack could get fairly big.

I'm also not sure this would actually work properly, because if every block in the chain automatically pops and there was no argument set, then you'd find yourself in even a worse situation.

Pass metadata as last parameter
-------------------------------
Alternatively the `&block`, `self` and other metadata like `$$eval` in the case of `class_eval` and friends could be passed as last parameter to blocks, methods and whatnot.

The downside here is that the prelude will get a little more complex, because in the case of `*args` it will have to ignore the last argument, and in case of optional parameters it will have to check all of them to reset the default value and move the block where it has to be.

In practice the downside shouldn't be too big, because we're already generating a prelude to set the default value, so it's just another check.

**Comment by meh** [comment]
The metadata part would likely look something like this when there's just a block passed.

```js
Opal.Kernel.$whatever(1, 2, Opal.metadata(function(x, y) {
  // prelude
  return Opal.Kernel.$puts(x, y);
}));
```

And in case of some metadata it would look something like this:

```js
Opal.Kernel.$whatever(1, 2, Opal.metadata({ self: something }, function(x, y) { ... }))
```

Basically the metadata gets set on the block `Function` directly if there is any, this is because it makes it possible to pass a block to a native JS function.

**Comment by elia** [comment]
It's not clear how the block is marked as block vs proc object: `foo.bar {|baz| … }` vs. `foo.bar -> baz {}`.

A possible alternative to me is to use a marker that anticipates that the next arg is a block, something like:

```js
foo.$bar(1,2,"three", Opal.block, function(){ … })
```

or if we need metadata:

```js
foo.$bar(1,2,"three", Opal.block({self: something}), function(){ … })
```

Then the prelude would cycle through the args and when it encounters a _block marker_ it fetches the block and stops the loop:

```js
for (var i = 0; i < args.length; i++) {
  arg = args[i]
  if (arg instanceof Opal.blockMarker) {
    $iter_metadata = arg
    $iter = arg[i+1]
  }
}
```

---
That said I'm all for moving the block to the last param. 

- less temporary locals (like `$a` and friends)
- less method locals (eg. `$TMP_1`)
- greatly improved readability and usability from JS (it's easier to write `Opal.MyClass.$new(Opal.block, function(){ … })`)

**Comment by meh** [comment]
@elia yes, that's how it'd work, `Opal.metadata` would mark it.

**Comment by vais** [comment]
@elia then why not include the function itself into the Opal.block metadata object instead of having it trail after it?

**Comment by vais** [comment]
Oops, I think that's what @meh had in mind in the first place :blush: But one thing is clear: looks like everyone's in favor of the argument passing approach!

**Comment by elia** [comment]
@vais that would be fine too, but as @meh pointed out we should consider carefully this:

> Basically the metadata gets set on the block Function directly if there is any, this is because it makes it possible to pass a block to a native JS function.

though I'm not sure it's necessary

@meh I'm a bit conflicted between avoiding object allocations (by setting metadata on `Function`) and keeping the metadata more local to the call (by having a separate metadata obj for each call).

**Comment by meh** [comment]
Well, we're basically always going to do an allocation anyway if the metadata contains anything that isn't a block.

Honestly I think it's a better idea to put the metadata on the `Function` itself rather than not, unless it has any performance implications. /cc @jgaskins

**Comment by catmando** [comment]
My thoughts: I am also in favor of passing as an argument.

1) the negatives have to do with added complexity in processing the params *inside* the ruby method, but the external interface is simplified.  A win.
2) its not clear the negatives are negatives, after all the prelude must have to already deal with opts and *args, so how much complex could it be?

**Comment by meh** [comment]
@catmando yeah, it would basically just be an added check in the already present prelude checks, I'm mostly concerned about performance tho.

**Comment by meh** [comment]
I'm already working on it by the way, at least we can try and benchmark it.

**Comment by meh** [comment]
Mmh, there is a problem with the metadata passing, blocks have an inherent self which is now defined on `$$s`, and the metadata stuff doesn't really work that well that way.

**Comment by elia** [comment]
I think the self makes sense as a property of the `Function`. Also this looks quite atomic reset:

```js
(TMP_1 = function() {
  self = TMP_1.$$self || this;
  TMP_1.$$self = TMP_1.$$original_self;
  // function body
}, TMP_1.$$original_self = TMP_1.$$self = self, TMP_1)
```
