### ISSUE TITLE
Class#method_name overrides Module#method_name

### ISSUE THREAD

**Issue by iliabylich** [opal/opal#1187]
``` ruby
class Class
  def my_method
    puts "Called from Class"
  end
end

class Module
  def my_method
    puts "Called from Module"
  end
end

Module.new.my_method
Class.new.my_method
```
Prints
```
Called from Class
Called from Class
```

Tested on Opal master

**Comment by iliabylich** [comment]
Same issue:
``` ruby
class Array
  def method1
    puts 'Array called'
  end
end

class UserArray < Array
end

class Object
  def method1
    puts 'Object called'
  end
end

UserArray.new.method1
# => Object called
```

**Comment by iliabylich** [comment]
Can the first example be somehow related to the fact that `Module.new.singleton_class` is a `Class`?

The second example is pretty weird, `UserArray` is actually an `Array::Wrapper` that relies on `method_missing` to delegate everything to its `@literal`. But there's a method defined on `Object`, so `method_missing` is never fired, and delegation doesn't work in that case. Don't even know how to fix that.

/cc @elia

**Comment by elia** [comment]
> Can the first example be somehow related to the fact that Module.new.singleton_class is a Class?

That would be interesting and somehow makes sense…

> The second example…

I'd say that maybe having the wrapper inheriting from BasicObject could help, but I didn't check the code and it could be easily be already the case.

/cc @meh added to the 0.9 milestone, if it's not fixable in the current status feel free to revert

**Comment by iliabylich** [comment]
It seems that the issue is with a `singleton_class` of  a`Module` instance
``` ruby
class Class
  def is_a_class?
    true
  end
end

[Module.new, Class.new].each do |mod|
  puts "For #{mod}"
  puts mod.singleton_class.methods.grep(/is_a_class/).inspect
  puts mod.singleton_class.instance_methods.grep(/is_a_class/).inspect
end
```

Output for opal master:
```
For #<Module:0x100>
["is_a_class?"]
["is_a_class?"]
For #<Class:0x102>
["is_a_class?"]
["is_a_class?"]
```

Output for ruby 2.2.3:
```
For #<Module:0x000000018723b8>
[:is_a_class?]
[]
For #<Class:0x00000001872390>
[:is_a_class?]
[:is_a_class?]
```

So the difference is in `Module.new.singleton_class.instance_methods` (or, as I understand opal's runtime, in `ModuleClass.constructor.prototype` - it contains wrong methods from the beginning). It looks like a `singleton_class` of a module is not the same thing as a `singleton_class` of a class
