### ISSUE TITLE
inherited issues

### ISSUE THREAD

**Issue by cj** [opal/opal#1196]
[This](http://opalrb.org/try/?code:class%20Wedge%0A%20%20module%20ClassMethods%0A%20%20%20%20def%20inherited%28subclass%29%0A%20%20%20%20%20%20store%20%3D%20Class.new%20self%3A%3AStore%0A%20%20%20%20%20%20puts%20%22wedge_class%20%3D%20%23%7Bsubclass%7D%22%0A%20%20%20%20%20%20store.wedge_class%20%3D%20subclass%0A%20%20%20%20%20%20subclass.const_set%20%3AStore%2C%20store%0A%20%20%20%20end%0A%20%20end%0A%20%20%0A%20%20extend%20ClassMethods%0A%20%20%0A%20%20module%20StoreClass%0A%20%20%20%20attr_accessor%20%3Awedge_class%0A%20%20%20%20%0A%20%20%20%20def%20inspect%0A%20%20%20%20%20%20%22%23%7Bwedge_class.inspect%7D%3A%3AStore%22%20%0A%20%20%20%20end%0A%20%20end%0A%20%20%0A%20%20class%20Store%0A%20%20%20%20extend%20StoreClass%0A%20%20end%0Aend%0A%0Aclass%20TestWedge%20%3C%20Wedge%3B%20end%0A%0Aputs%20TestWedge%3A%3AStore.inspect#) will show two `puts`, if you then run the command again it will only show one `puts` which is wrong…. if you then run against `opal 9` it will fail completely saying wedge_class is nil.

**Comment by cj** [comment]
Here is a better example that straight out fails in Opal.

http://opalrb.org/try/?code:class%20Wedge%0A%20%20module%20ClassMethods%0A%20%20%20%20def%20inherited(subclass)%0A%20%20%20%20%20%20%25w%60Store%20ClientStore%60.each%20do%20%7Ctype%7C%0A%20%20%20%20%20%20%20%20store%20%3D%20Class.new%20self.const_get(type)%0A%20%20%20%20%20%20%20%20store.wedge_class%20%3D%20subclass%0A%20%20%20%20%20%20%20%20subclass.const_set%20%3A%22%23%7Btype%7D%22%2C%20store%0A%20%20%20%20%20%20end%0A%20%20%20%20end%0A%20%20end%0A%20%20%0A%20%20extend%20ClassMethods%0A%20%20%0A%20%20module%20StoreClass%0A%20%20%20%20attr_accessor%20%3Awedge_class%0A%20%20%20%20%0A%20%20%20%20def%20store%0A%20%20%20%20%20%20if%20RUBY_ENGINE%20!%3D%20%27opal%27%0A%20%20%20%20%20%20%20%20Thread.current%5B%3A%22__%23%7Bname%7D__%22%5D%20%7C%7C%3D%20%7B%7D%0A%20%20%20%20%20%20else%0A%20%20%20%20%20%20%20%20%24__wedge_store__%20%7C%7C%3D%20%7B%7D%0A%20%20%20%20%20%20%20%20%24__wedge_store__%5Bname%5D%20%7C%7C%3D%20%7B%7D%0A%20%20%20%20%20%20end%0A%20%20%20%20end%0A%20%20%20%20%0A%20%20%20%20def%20%5B%5D(key)%0A%20%20%20%20%20%20store%5Bkey%5D%0A%20%20%20%20end%0A%20%20end%0A%20%20%0A%20%20class%20ClientStore%0A%20%20%20%20extend%20StoreClass%0A%20%20%20%20%20%0A%20%20%20%20def%20self.store%0A%20%20%20%20%20%20s%20%3D%20super%0A%20%20%20%20%20%20wedge_class%3A%3AStore.store.merge%20s%0A%20%20%20%20end%0A%20%20end%0A%20%20%0A%20%20class%20Store%0A%20%20%20%20extend%20StoreClass%0A%20%20end%0A%20%20%0Aend%0A%0Aclass%20TestWedge%20%3C%20Wedge%3B%20end%0A%0Aputs%20TestWedge%3A%3AClientStore%5B%3Afoo%5D

If you run that in ruby there's no error.

**Comment by cj** [comment]
The issue appears to be `super` in this case as this works:

http://opalrb.org/try/?code:class%20Wedge%0A%20%20module%20ClassMethods%0A%20%20%20%20def%20inherited(subclass)%0A%20%20%20%20%20%20%25w%60Store%20ClientStore%60.each%20do%20%7Ctype%7C%0A%20%20%20%20%20%20%20%20store%20%3D%20Class.new%20self.const_get(type)%0A%20%20%20%20%20%20%20%20store.wedge_class%20%3D%20subclass%0A%20%20%20%20%20%20%20%20subclass.const_set%20%3A%22%23%7Btype%7D%22%2C%20store%0A%20%20%20%20%20%20end%0A%20%20%20%20end%0A%20%20end%0A%20%20%0A%20%20extend%20ClassMethods%0A%20%20%0A%20%20module%20StoreClass%0A%20%20%20%20attr_accessor%20%3Awedge_class%0A%20%20%20%20%0A%20%20%20%20def%20store%0A%20%20%20%20%20%20if%20RUBY_ENGINE%20!%3D%20%27opal%27%0A%20%20%20%20%20%20%20%20Thread.current%5B%3A%22__%23%7Bname%7D__%22%5D%20%7C%7C%3D%20%7B%7D%0A%20%20%20%20%20%20else%0A%20%20%20%20%20%20%20%20%24__wedge_store__%20%7C%7C%3D%20%7B%7D%0A%20%20%20%20%20%20%20%20%24__wedge_store__%5Bname%5D%20%7C%7C%3D%20%7B%7D%0A%20%20%20%20%20%20end%0A%20%20%20%20end%0A%20%20%20%20%0A%20%20%20%20def%20%5B%5D(key)%0A%20%20%20%20%20%20store%5Bkey%5D%0A%20%20%20%20end%0A%20%20%20%20%0A%20%20%20%20def%20%5B%5D%3D(key%2C%20value)%0A%20%20%20%20%20%20store%5Bkey%5D%20%3D%20value%0A%20%20%20%20end%0A%20%20end%0A%20%20%0A%20%20class%20ClientStore%0A%20%20%20%20extend%20StoreClass%0A%20%20%20%20%0A%20%20%20%20class%20%3C%3C%20self%0A%20%20%20%20%20%20alias_method%20%3Aoriginal_store%2C%20%3Astore%0A%20%20%20%20%20%20def%20store%0A%20%20%20%20%20%20%20%20wedge_class%3A%3AStore.store.merge%20original_store%0A%20%20%20%20%20%20end%0A%20%20%20%20end%0A%20%20end%0A%20%20%0A%20%20class%20Store%0A%20%20%20%20extend%20StoreClass%0A%20%20end%0A%20%20%0Aend%0A%0Aclass%20TestWedge%20%3C%20Wedge%3B%20end%0A%0ATestWedge%3A%3AStore%5B%3Afoo%5D%20%3D%20%27bar%27%0Aputs%20TestWedge%3A%3AStore%5B%3Afoo%5D%0Aputs%20TestWedge%3A%3AClientStore%5B%3Afoo%5D#

p.s. if you hit `RUN` again it will fail.  I think you might be using two version of opal or something.

**Comment by iliabylich** [comment]
The first issue seems to be fixed, but the second one is still there

**Comment by iliabylich** [comment]
In the second example methods `Foo#foo` and `Bar.foo` are defined on the same object (singleton class).
+ `Kernel#extend` invokes `mod.append_features` on that singleton class
``` ruby
module Kernel
  def extend(*mods)
    %x{
      var singleton = #{singleton_class};

      for (var i = mods.length - 1; i >= 0; i--) {
        var mod = mods[i];

        if (!mod.$$is_module) {
          #{raise TypeError, "wrong argument type #{`mod`.class} (expected Module)"};
        }

        #{`mod`.append_features `singleton`};
        #{`mod`.extended self};
      }
    }

    self
  end
end
```
+ method `Bar.foo` is defined on the same singleton class

So these methods just override each other

**Comment by iliabylich** [comment]
As far as I understand, module `Foo` should be placed into the prototype chain of `Bar` (right after its singleton class, i.e Foo -> Foo.singleton_class -> Bar -> Class.singleton_class -> Object.singleton_class -> BasicObject.singleton_class). But instead, `Opal.append_features` just manually copies methods and constants from module to class.

@elia Do you have any ideas why was `Opal.append_features` implemented this way? Modifying a prototype chain looks easier than copying everything from one place to another.

Also it happens with constants inheritance:
``` ruby
module Foo
  A = 1
end

class Bar
  A = 2

  extend Foo
end

puts Bar::A
# MRI:
2
# Opal master:
1
```
(but that's a different issues with scopes inheritance)

**Comment by elia** [comment]
> (but that's a different issues with scopes inheritance)

→ #1240

**Comment by elia** [comment]
> @elia Do you have any ideas why was Opal.append_features implemented this way? Modifying a prototype chain looks easier than copying everything from one place to another.

Modifying prototypes is not ideal and the only way it could would be by modifying `__proto__` because switching the `.prototype` on the constructor has no effect on its instances.

The grand plan is to rebuild that part of the runtime completely, and that's what I'm actually going to do :)
But might be worth releasing 0.9 before changing the runtime heavily. (cc @opal/core wdyt?)

The way it's supposed to work anyway is that classes prototypes will hold methods from included modules along with their own, and the actual JS prototype chain will be the same as traversing `.$$super` on classes. While the Ruby inheritance chain is the one that comes out from traversing `.$$parent` (which will include modules). `Module#extend` is considered just an `#include` done on the `singleton_class` with just a couple of differences with regards to hooks (eg. `.included` vs `.extended`).

**Comment by elia** [comment]
(@iliabylich also forgot to mention that this issue is fixed in https://github.com/opal/opal/tree/elia/superfix but unfortunately a number of other specs fail so it never became a PR.)

**Comment by iliabylich** [comment]
@elia Could take a look at this gist please - https://gist.github.com/iliabylich/61869c588776ca60a15f4d68cb25e681 ? Is it what you described above?

**Comment by elia** [comment]
```
opal:master ⤑ pbpaste |bin/opal                                         ~/C/opal
"foo"
foo
opal:master ⤑ pbpaste |ruby                                             ~/C/opal
:foo
foo
```

fixed on master, presumably by https://github.com/opal/opal/pull/1826
