### ISSUE TITLE
nil::User not working

### ISSUE THREAD

**Issue by cj** [opal/opal#1197]
I ran into this randomly: http://goo.gl/Lp9MQa it works in MRI.

Issue is line 28: `user = ((nil).$$scope.get('User')).$new("Bob");`

**Comment by elia** [comment]
The reduced test case is:

```
Foo = 123
nil::Foo
```

**Comment by vais** [comment]
After 10 years of Ruby, I don't understand why this even works in MRI :confused:

**Comment by elia** [comment]
Was wondering the same, sounds like a good question for @matz…

**Comment by vais** [comment]
Or for @eregon (there should be a spec for that :wink:)

**Comment by matz** [comment]
seems like a bug. Submit to our redmine.

**Comment by vais** [comment]
:sparkles: :sparkles: :sparkles:

**Comment by cj** [comment]
I thought this might be a bug :)

**Comment by vais** [comment]
[Bug #11718](https://bugs.ruby-lang.org/issues/11718) Thanks for looking into this @matz!
