### ISSUE TITLE
Symbol from String as Hash key

### ISSUE THREAD

**Issue by fazibear** [opal/opal#1202]
```ruby
hash = { 'test': :test }
```

throws exception

```
parse error on value ":" (tCOLON) :application:24
Source: application:24:14
sh = { 'test': :test }
~~~~~~~~~~~~~^
```

**Comment by alexdowad** [comment]
Adding `-t` (enable debugging output at runtime) flag to the parser build command, once I build a debugging parser I'll run `Opal::Parser` on this input and see what it prints out.

I've just looked at a couple of source files, but already I can say I really like your clean, well-organized code.

**Comment by elia** [comment]
Great to hear! then we could add a additional CLI option (`--lex`?) alongside `--sexp` which shows the syntax expressions / AST

**Comment by alexdowad** [comment]
Hmm. The lexer converts that ':' into `tCOLON`, but there are no rules which actually use `tCOLON`.

`parser` lexes `'test':` as `tSTRING_BEG tSTRING_CONTENT tLABEL_END`. Then they have a rule which converts a string followed by `tLABEL_END` and an arg value to `assoc`.

They generate `tLABEL_END` at the close of a string, if the next char is ':', and the char after that is not ':'... but only *if* the lexer is in a specific state. I'm just trying to see how the lexer gets into that state (and how it exits it).

**Comment by alexdowad** [comment]
I figured out why the lexer has to be in a specific state: they don't want to mix up `cond ? 'string':'another string'`.

**Comment by alexdowad** [comment]
Nice... I see you have `#cond?`, `#cond_pop`, and `#cond_push` in your lexer already, which is exactly what is needed to avoid the problem mentioned above.

The way you do this is a bit cleaner than `parser`. They call `cond_pop` and `cond_push` from within parser actions; you manage the "cond" state entirely within the lexer, which is much better.
