### ISSUE TITLE
Implement Kernel.open() method

### ISSUE THREAD

**Issue by Mogztter** [opal/opal#1218]
In Asciidoctor.js we have a basic implementation of `Kernel.open()` that allow to read files:

```ruby
module Kernel
  # basic implementation of open, enough to work
  # with reading files over XmlHttpRequest
  def open(path, *rest)
    file = File.new(path, *rest)
    if block_given?
      yield file
    else
      file
    end
  end
end
```

With this implementation, the following code in Ruby is working fine with Opal:

```ruby
open(include_file, 'r') {|f| f.read }
```

**Comment by elia** [comment]
I think everything (including the block) should be forwarded to File.open. Ruby ensures the file is closed after executing the block.
