### ISSUE TITLE
Stabby lambda without parantheses breaks the parser

### ISSUE THREAD

**Issue by Papierkorb** [opal/opal#1228]
Hello.

The following code breaks Opal (master @ 9d3d2ec):

```ruby
def within(some_proc, &block)
end

# This breaks: (Giving error: parse error on value "do" (kDO))
within ->{ whatever } do
end

# This works:
within(->{ whatever }) do
end
```

This code worked fine with Opal 0.8.1, so looks like a regression to me.

**Comment by Papierkorb** [comment]
This test shows the issue. I added it to `opal/spec/lib/parser/lambda_spec.rb`:

```ruby
  it "can parse do..end after lambda body" do
    expected = [:call, nil, :a, [:arglist, [:call, nil, :lambda, [:arglist], [:iter, nil, [:call, nil, :b, [:arglist]]]]], [:iter, nil]]
    parsed("a ->{b} do; end").should == expected
  end
```

I took the `expected` value from the previously working version of Opal.

**Comment by alexdowad** [comment]
@Papierkorb, you are very right; this is a regression. *My* regression. Thanks for finding it, and thanks even more for providing the test case which helps verify the fix!

Contributors, any comments on the PR before it gets merged in?

**Comment by elia** [comment]
@alexdowad if the tests are green merge at will.

The only thing that comes to mind is wether we want to start a branch for switching to `parser` already or we need some preparatory work first.

**Comment by alexdowad** [comment]
@elia, a good first step towards switching to `parser` would be to use the `ast` gem for your parse tree. That's what `parser` uses.

**Comment by alexdowad** [comment]
Merged. Thanks again to @Papierkorb.

**Comment by Papierkorb** [comment]
Thanks for the quick fix! :+1:

**Comment by elia** [comment]
@alexdowad started the work for `parser`/`ast` in #1235 and https://github.com/elia/ast :)
