### ISSUE TITLE
Switch to Parser

### ISSUE THREAD

**Issue by elia** [opal/opal#1235]
ref #604 

- [ ] use the `ast` gem, which is the same one used by `parser`
- [ ] ensure source maps still work
- [ ] move to an AST structure as similar as possible to the one emitted by `parser`
- [ ] switch to `parser` 
- [ ] implement all the missing stuff in the compiler

_this list is a draft, it's expected to change down the road and adjust to how things turn out be *in the "real world"™*_

--- 

**Notes**

- a fork of the AST gem with passing specs, the only actual changes are for `#inspect` like methods that were using `String#<<` https://github.com/elia/ast

**Comment by elia** [comment]
@alexdowad I drafted the list of stuff that needs to be done to switch to parsers, please edit if you see anything that can be improved or done differently

**Comment by wied03** [comment]
@elia - Can we add that it should be bootstrap friendly?

**Comment by elia** [comment]
@wied03 what do you mean?

**Comment by wied03** [comment]
@elia - that this change does not break the ability to run the Opal compiler in Node, which currently works

**Comment by whitequark** [comment]
@elia I'm confused about your changes to `ast`. What's that for?

**Comment by elia** [comment]
@whitequark were mostly related to make the tests pass under opal, which translates to avoiding string mutation and string/symbol difference. I basically replaced `String#<<` with `Array#<<`+`Array#join` and tweaked a couple of specs to use `:symbol.inspect` instead of `":symbol"` so that it passes when `String` == `Symbol`. Finally I think I have some local bacon changes that I still need to push.

Feel free to point out specific lines in https://github.com/elia/ast/commit/6f76f4e4ba6871f5f638285f478991e2d93d9e75 if there's anything else that's unclear.

That said I think all of that will stay on hold until #1465 is in a good shape.

**Comment by elia** [comment]
solved by #1465
