### ISSUE TITLE
Scopes inheritance with extend

### ISSUE THREAD

**Issue by elia** [opal/opal#1240]
```rb
module Foo
  A = 1
end

class Bar
  A = 2

  extend Foo
end

puts Bar::A
# MRI:
2
# Opal master:
1
```

_source: https://github.com/opal/opal/issues/1196#issuecomment-163907523 by @iliabylich_

**Comment by iliabylich** [comment]
This issue seems to be fixed in https://github.com/opal/opal/commit/6044d30d239363907aa5ae19fd03578101102b81, good job! :smile:

**Comment by elia** [comment]
😎
