### ISSUE TITLE
Add an option to suppress "not supported" warning message

### ISSUE THREAD

**Issue by Mogztter** [opal/opal#1253]
It would be great if we could suppress "not supported" warning message. In Asciidoctor we are using `freeze` method but we don't want to display a warning message.

We could add a config parameter `OPAL_CONFIG.suppress_warning_freezing` ?

**Comment by vais** [comment]
:+1: I'd even use it to suppress warnings when running the spec suite.

**Comment by Mogztter** [comment]
@elia I think we can close this issue, fixed by:

 * 1219c20 (Manually manage Opal runtime config)
 * 0815306 (Fix the name of Opal.dynamic_require_severity)
* b418bdd (Decouple runtime/compiletime require errors config)

https://github.com/opal/opal/pull/1345#issuecomment-200085541
