### ISSUE TITLE
"break" behavior in yielded lambda

### ISSUE THREAD

**Issue by elia** [opal/opal#1254]
> @elia About the Proc#call case: I forgot about that one :disappointed: , it behaves as if block-calling methods catch it, so Proc#call but also `yield`, {instance,class}_{eval,exec}:
> 
> ``` ruby
> [1] pry(main)> l=lambda {break 42}
> => #<Proc:0x005615f3878ac0@(pry):1 (lambda)>
> [2] pry(main)> def foo; p yield; :after; end
> => :foo
> [3] pry(main)> foo(&l)
> 42
> => :after
> ```
> 
> An alternative is of course to catch it at the top of the lambda compiled body (if it contains a `break`)

_Posted by @eregon – https://github.com/opal/opal/pull/1250#issuecomment-165745130_

**Comment by hmdne** [comment]
I have an idea on how to implement this as I'm starting to understand how break actually works.

**Comment by eregon** [comment]
FWIW in TruffleRuby I think this work by giving each `break` an ID, and the implicitly-added try/catch around the lambda body catches it. Then it doesn't matter at parse we can't know if it's a lambda or not.

**Comment by hmdne** [comment]
What's interesting is that for lambda all 3 give the same result:

```ruby
[1] pry(main)> -> { break 4; 5 }.()
=> 4
[2] pry(main)> -> { next 4; 5 }.()
=> 4
[3] pry(main)> -> { return 4; 5 }.()
=> 4
[4] pry(main)> 
```

Also

```ruby
[8] pry(main)> nil.then(&->(*){ break 4; 5 })
=> 4
[9] pry(main)> nil.then(&->(*){ next 4; 5 })
=> 4
[10] pry(main)> nil.then(&->(*){ return 4; 5 })
=> 4
[11] pry(main)> 
```

This means we will be able to easily integrate this with what I'm planning for #2357. Here's a very preliminary and loose logic (not yet taking lambda for break into account):

https://github.com/opal/opal/pull/2357/files#diff-b595c9ee65cfc6b969e1ef965ad9cb73f0f51fe5ede2aa3db7b99a767c56a4e8R58-R95

The two other cases for break are a loop and an iter.
