### ISSUE TITLE
String#split returns extra field if limit exceeds number of fields in data

### ISSUE THREAD

**Issue by mojavelinux** [opal/opal#1267]
If the value of limit exceeds the number of fields found in the data, String#split is returning an extra field at the end of the result array (which repeats the second-to-last entry).

Example:

```
opal> "1,2".split ',', 3
   => ["1", "2", "2"]
```

Expected:

```
irb> "1,2".split ',', 3
  => ["1", "2"]
```

The following test case should be added to spec/rubyspec/core/string/split_spec.rb to verify this result.

```ruby
"1,2".split(',', 3).should == ["1", "2"]
```

It may be a good idea to add a couple other scenarios where limit exceeds number of fields just to be sure.

**Comment by mojavelinux** [comment]
:+1: Thanks!

**Comment by mojavelinux** [comment]
Should we add a test somewhere?

**Comment by vais** [comment]
@mojavelinux :beers:

**Comment by mojavelinux** [comment]
\o/ Nice job! :beers: indeed!

**Comment by elia** [comment]
👏🏼
