### ISSUE TITLE
Exception instead of NoMethodError when method is missing

### ISSUE THREAD

**Issue by iliabylich** [opal/opal#1271]
``` ruby
begin
  1 <=> []
rescue Exception => e
  puts e.class
end
# MRI:
# blank output (comparison returns nil)
# Opal master
Exception
```
Don't even know why CI is still green, I'm getting [this spec](https://github.com/ruby/rubyspec/blob/master/core/array/comparison_spec.rb#L76) failing locally (it invokes internally pretty much the same code, but it expects to catch a `StandardError`, that's why the spec fails for me).

And it seems that that code was [ok](http://opalrb.org/try/?code:begin%0A%20%201%20%3C%3D%3E%20%5B%5D%0Arescue%20Exception%20%3D%3E%20e%0A%20%20puts%20e.class%0Aend) before (on 0.8), so it looks like a regression.

Looks like in this case Opal doesn't generate method missing stubs correctly.

**Comment by elia** [comment]
Closed by #1273
