### ISSUE TITLE
Empty rescue with native JS Exceptions

### ISSUE THREAD

**Issue by wied03** [opal/opal#1280]
Before https://github.com/opal/opal/commit/73707394c288ed43a134b62559b92ba924c73fe6, the rescue worked as noted below

```ruby
begin
  `throw 42`
  return
rescue
  puts 'rescue ran!'
end
```

After that commit, `rescue Exception =>...` is needed because a native JS exception is not considered an instance of `StandardError`.

What's the best way to handle this? Modify the compiler to add an 'empty_rescue' flag and then have the `Opal.rescue` function look at the flag and match on StandardError or native exception?

**Comment by elia** [comment]
I'm against a flag, what about being explicit?

```rb
begin
  `throw 42`
rescue JS::Error
end
```

**Comment by wied03** [comment]
That's another option, although if it's not automatic, I think it would be more streamlined to just say `rescue Exception`

**Comment by meh** [comment]
I think the explicit way fits better, we already have machinery behind the `JS` constant.
