### ISSUE TITLE
File.expand_path('.') should return the current directory

### ISSUE THREAD

**Issue by Mogztter** [opal/opal#1296]
Consider the following code:

.Ruby
```ruby
path = File.expand_path "."
puts "#{path}" # returns '/home/guillaume/workspace/opensource/asciidoctor.js'
```

. JavaScript with Opal master (0.10.0.dev)
```javascript
console.log(Opal.get('File').$expand_path('.')); // returns '.'
```

I think `File.expand_path` should return the current directory instead of the path passed as an argument.
We could use a special case if the path is `.` and return `Dir.pwd`.

**Comment by elia** [comment]
The rationale for the current behavior is that in the browser the best approximation we have to the current directory is "."

The browser is still the primary target, but of course running on other platforms (eg node) we can have a much better idea of what is the real current directory, that should be supported by the nodejs library in stdlib. 

It's entirely possible too that the current implementation of expand_path already relies on the current dir, but that is not updated or implemented accordingly for all platforms.
