### ISSUE TITLE
Can't define variable with opal-parser

### ISSUE THREAD

**Issue by ruspython** [opal/opal#1297]
I'm trying to execute this code:
```
require 'native'

def func
    $global.a = $global.b
end

$global.func = func
```
I get error `Uncaught b: undefined method 'b' for nil`
What am I doing wrong?

**Comment by iliabylich** [comment]
@ruspython It's a ruby code, so `func` is actually a `func()` (which invokes `$global.b()`). You can try to use `method(:func)` or define a method directly on a `$global`. In case you are working with properties, use `.JS.` syntax

**Comment by ruspython** [comment]
I'm not familiar with Ruby syntax, just trying to compile simple js function. I tried this code on opalrb.org/try/ and it executed without any errors. Don't you know why?

**Comment by ruspython** [comment]
Sorry, silly mistake, I've forgotten to load 'native' lib

**Comment by iliabylich** [comment]
(In case you are interested)

Your method `$global.b` is a method missing stub (that must raise an error). But your object is native, and opal has (don't know why) custom implementation of `method_missing` - https://github.com/opal/opal/blob/master/stdlib/native.rb#L312-L321 that doesn't raise any errors.

**Comment by elia** [comment]
> But your object is native, and opal has (don't know why) custom implementation of method_missing - https://github.com/opal/opal/blob/master/stdlib/native.rb#L312-L321 that doesn't raise any errors.

cc @meh

**Comment by meh** [comment]
Because it might be a property access on the `Native::Object`, so you'd be getting `nil`.
