### ISSUE TITLE
Compile to most performant JS

### ISSUE THREAD

**Issue by Thyra** [opal/opal#1300]
How can I compile my Opal code to the most performant JS possible? Via the command line I can turn on *inline_operators* with the **-I** flag but then *freezing*, *method_missing* and *tainting* are enabled. I don't need those features so I would like to turn them off. I can do that via 

```ruby
Opal::Builder.build("main", {method_missing: false, freezing: false, tainting: false}).to_s
```

But then *inline_operators* are not turned on. Is there any way to combine both? And are there other things I can do to speed up my code (besides X-Strings)?

**Comment by wied03** [comment]
@iliabylich might be able to correct me here, but I'm not sure that method_missing being enabled slows down your code. It adds to its size but unless you're actually hitting method_missing cases, I'm not sure it would slow down much.

Arity checking would slow it down, but that's opt in anyways. As to freezing/tainting, Opal doesn't really support those yet to my knowledge, so the configuration is more about suppressing warnings (that config has changed some on master and I'm not update to date there).

I would say avoiding arity checking (in production, for unit testing it's important) and enabling inline operators get you the most improvement there.

**Comment by iliabylich** [comment]
@Thyra 
``` ruby
source = "1 + 1"
file = "(inline)"
options = {method_missing: false, freezing: false, tainting: false}
puts Opal::Builder.new.build_str(source, file, options).to_s
```

``` js
(function(Opal) {
  function $rb_plus(lhs, rhs) {
    return (typeof(lhs) === 'number' && typeof(rhs) === 'number') ? lhs + rhs : lhs['$+'](rhs);
  }
  var self = Opal.top, $scope = Opal, nil = Opal.nil, $breaker = Opal.breaker, $slice = Opal.slice;

  return $rb_plus(1, 1)
})(Opal);
```

`inline_operators` optimization works, `$rb_plus` performs `lhs + rhs` for numbers (this is the idea of the optimization)

Where's the bottleneck in your case? Compilation/parsing generated javascript/runtime execution?

**Comment by meh** [comment]
I did some benchmarking of `method_missing` back in the day when we went from a weird-ass dispatcher to stubs, and there was almost no performance hit, it all gets inlined.

**Comment by elia** [comment]
I'll consider this answered, closing.
