### ISSUE TITLE
Delegation and scope

### ISSUE THREAD

**Issue by Mogztter** [opal/opal#1323]
Recently I've implemented `Pathname.expand_path` (#1296).

`Pathname.expand_path` method (defined in `stdlib`) delegates to `File.expand_path` method (also defined in `stdlib`). 
`File.expand_path` method uses `Dir.pwd` method to find out the current directory. We have defined a method in `stdlib/nodejs` to use `process.cwd()`. We also have an implementation of `Dir.pwd` method in `corelib`.

Here's a "flow chart" of the method call:

```
Pathname.expand_path (stdlib) ---> File.expand_path (stdlib) ---> Dir.pwd (stdlib/nodejs)
                                                             ---> Dir.pwd (corelib)
```

The problem is that the method `Dir.pwd` defined in `stdlib/nodejs` is not called.
I think the scope (Opal) defined in `File.expand_path` is not "updated/overloaded" with the methods defined in the module `nodejs`.
Does that make any sense ? :8ball:

I tried to debug the `Opal.defn` function but my knowledge of Opal internals are very limited...

**Comment by iliabylich** [comment]
@Mogztter Well, that's kind of strange, but check out this line - https://github.com/opal/opal/blob/master/stdlib/nodejs/dir.rb#L9 :smile: . Opal works correctly, there's no issue with overloading (can't stop laughing):
``` sh
opal -rnodejs -e "require 'nodejs/dir'; puts Dir.new.pwd"
# like nix pwd
```

**Comment by elia** [comment]
really nice catch btw, didn't get that until I saw the PR 🙈
