### ISSUE TITLE
map.with_index returns the original values

### ISSUE THREAD

**Issue by jgaskins** [opal/opal#1325]
Running against the `master` branch:

```ruby
p [1,2,3].map.with_index { |n, index| 4 }
```

Expected: `[4, 4, 4]`
Actual: `[1, 2, 3]`

[Example on opalrb.org/try](http://opalrb.org/try/?code:p%20%5B1%2C2%2C3%5D.map.with_index%20%7B%20%7Cn%7C%204%20%7D)

**Comment by elia** [comment]
cc @meh
