### ISSUE TITLE
Different behavior of block.call and yield with break

### ISSUE THREAD

**Issue by iliabylich** [opal/opal#1335]
Here's the code I used for testing:

``` ruby
class A
  include Enumerable

  def each
    yield :value1
    yield :value2
  end

  def method1(&block)
    map { |a| block.call(a) }
  end

  def method2(&block)
    map { |a| yield(a) }
  end
end

a = A.new
puts a.method1 { break :broken }
puts a.method2 { break :broken }
```

MRI:

```
broken
broken
```

Opal:

```
["broken", "broken"]
broken
```

So, `yield` works correctly, `block.call` stops `break` from re-throwing.
cc @elia You've made some changes to `break` behavior about a month ago. Can it be related?

**Comment by elia** [comment]
> @elia You've made some changes to break behavior about a month ago. Can it be related?

absolutely ☹️ especially if it used to work properly, otherwise could be one of the cases that have entries in the `bugs/` filters (https://github.com/opal/opal/blob/master/spec/filters/bugs/language.rb#L233-L237)
