### ISSUE TITLE
String#to_proc triggers function deoptimizations

### ISSUE THREAD

**Issue by jgaskins** [opal/opal#1343]
I'm writing a real-time dashboard app in Clearwater that receives thousands of updates over a websocket per minute (porting it from one of our React apps). The good news is that it's handling it really well, considering literally every single order in progress can potentially be shown in this app, but I noticed while profiling it that about 15% of CPU time is spent in `String#to_proc` and that that function is deoptimized due to "Assignment to parameter in arguments object", which is caused by reassigning one of the function arguments. So it could be going even faster.

It looks like it's happening in [`Opal::Nodes::IterNode`](https://github.com/opal/opal/blob/723f47c5c07f918c0ee410c58df2b95cd53b8f71/lib/opal/nodes/iter.rb#L53), where all of the params to the function (including splat params) are injected.

While investigating, I also noticed that it's using the [`Array.prototype.slice.call(arguments)` thing](https://github.com/opal/opal/blob/723f47c5c07f918c0ee410c58df2b95cd53b8f71/lib/opal/nodes/iter.rb#L34), which triggers another deoptimization for the same call.

Methods used to suffer these same deoptimizations, but that was fixed in 121eff369b4de925e8a86f50927dd1635ca33b4b. Block splat args seem to be handled a bit differently. I spent most of last night trying to figure out how to remove those deoptimizations, but I couldn't figure it out. I tried to extract the common functionality to `Opal::Nodes::ScopeNode` so `Opal::Nodes::DefNode` and `Opal::Nodes::IterNode` could both use the same functionality, but I couldn't get it working for both regular and splat args. :-\

**Comment by iliabylich** [comment]
This is the proc that `String#to_proc` returns:
``` ruby
proc do |*args, &block|
  raise ArgumentError, "no receiver given" if args.empty?
  obj = args.shift
  obj.__send__(sym, *args, &block)
end
```
It takes a splat, that's why we have to call `$slice.call(arguments)` here. MRI says that proc returned by `Symbol#to_proc` has `arity = -1` (which means that most probably proc's parameters are correct)

Maybe we can change it to something like
``` ruby
def to_proc
  # Give name to self in case this proc is passed to instance_eval
  sym = self

  result = proc do |obj, &block|
    raise ArgumentError, "no receiver given" unless obj
    obj.__send__(sym, &block)
  end

  `result.$$arity = -1;`

  result
end
```
Just tested it on the latest master and it works, all specs from `ruby/spec` are green.

cc @elia What do you think?

**Comment by elia** [comment]
Makes sense, it's more correct to use `obj = undefined` and check for `!= null` to raise the error, but overall seems the right implementation, probably MRI's arity comes from it being implemented in C and it's possible that it should be considered a :bug:… cc @eregon 

```rb
irb(main):002:0> a = :inspect.to_proc
=> #<Proc:0x007fb134010850(&:inspect)>
irb(main):003:0> [].instance_eval(&a)
=> "[]"
irb(main):004:0> a[123]
=> "123"
irb(main):005:0> a[:asdf]
=> ":asdf"
irb(main):006:0> a[:asdf, :qwer]
ArgumentError: wrong number of arguments (given 1, expected 0)
	from (irb):6:in `inspect'
	from (irb):6
	from /Users/elia/.rvm/rubies/ruby-2.3.0/bin/irb:11:in `<main>'
irb(main):008:0> a[]
ArgumentError: no receiver given
	from (irb):8
	from /Users/elia/.rvm/rubies/ruby-2.3.0/bin/irb:11:in `<main>'
irb(main):009:0> a.arity
=> -1
irb(main):010:0> proc {|a| a.inspect }.arity
=> 1
irb(main):011:0> proc {|a=nil| a.inspect }.arity
=> 0
irb(main):012:0> proc {|*a| a.inspect }.arity
=> -1
irb(main):013:0> a[nil]
=> "nil"
```

**Comment by jgaskins** [comment]
> It takes a splat, that's why we have to call `$slice.call(arguments)` here.

What I mean is that it doesn't have to be `$slice.call`. I added #1096 to optimize splats in method definitions a while back. It was originally an almost identical set of deoptimizations as in these blocks (block args being modified as well as passing `arguments` to another function).

I'd actually like to be able to remove `$slice` from the runtime at some point. It's convenient, but it's a guaranteed deoptimization. #1096 resulted in 50%-200% speed improvement for my splat-arg test methods (which were simple; a complex method would have a more dramatic improvement), depending on the browser.

@elia later updated the iterator to use a name that wouldn't collide with Ruby variable names, but otherwise the parser still results in a C-style `for` loop for splat args in methods AFAIK.

**Comment by eregon** [comment]
@elia Yeah, the arity thing seems a implementation detail of MRI, I'd be happy to relax that spec.
@iliabylich I think the implementation you show would only work if the method called does not take any arguments, it would not work for ` :to_s.to_proc.call(8, 2)` if I'm not mistaken.

**Comment by elia** [comment]
just for the record:

```
irb(main):015:0* :to_s.to_proc.call(8, 2)
=> "1000"
```

**Comment by jgaskins** [comment]
Yeah, I had to check that out in the console, too. :-)

**Comment by iliabylich** [comment]
@eregon I see, so we still need this splat.
@jgaskins Just did a simple benchmark, for me `$slice` is 4-5 times slower that copying args one by one. It can be very easily fixed in https://github.com/opal/opal/blob/master/lib/opal/nodes/args/restarg.rb#L28 (since args logic is common for blocks and methods)

**Comment by jgaskins** [comment]
@iliabylich Converging the two is exactly what I've been wanting to do, but I'm not familiar enough with the implementation. I flailed for quite a while on #1096 to figure out what I was doing. :-) Your PR might just do the trick!
