### ISSUE TITLE
Base64 encoding can insert extra NUL byte

### ISSUE THREAD

**Issue by bk2204** [opal/opal#1362]
I'm using Opal 0.9.2. Opal seems to sometimes encode an extra NUL byte that isn't present when generating Base64:

```sh
vauxhall ok % opal -rbase64 -e 'puts Base64.encode64("abcdefg")'
YWJjZGVmZwA=
vauxhall ok % ruby -rbase64 -e 'puts Base64.encode64("abcdefg")'
YWJjZGVmZw==
```

I've confirmed using the GNU coreutils base64 utility that MRI is encoding this correctly.

**Comment by elia** [comment]
Apparently most browsers support `btoa` `atob` http://caniuse.com/#search=btoa
Maybe we can switch to this polyfill https://github.com/davidchambers/Base64.js/blob/master/base64.js

cc @meh @vais

**Comment by vais** [comment]
@elia :+1:
