### ISSUE TITLE
Super issues with included modules/subclass

### ISSUE THREAD

**Issue by wied03** [opal/opal#1370]
Tried to fix this in #1237 but was unable to

From a failing rubyspec in super_spec - "sees the included version of a module a method is alias from"

The Opal.find_super... functions are not working properly here. the super call within the BS1 module is passing in self as the Trigger class. Opal.find_super then returns the same (recursive) function within BS1 and we get an infinite loop.

Code:
```ruby
module AS1
  def foo
    :a
  end
end

module BS1
  def foo
    [:b, super]
  end
end

class Base
  extend AS1
  extend BS1
end

class Trigger < Base
  class << self
    def foo
      super
    end
  end
end

puts "value is #{Trigger.foo}"
```

MRI: ```value is [:b, :a]```

Opal via `bundle exec opal -A test.rb`
```
/tmp/opal-nodejs-runner-20160229-2693-19nh6gl:0
(function (exports, require, module, __filename, __dirname) { (function(undefi
^
RangeError: Maximum call stack size exceeded
```

**Comment by elia** [comment]
can you add the command you use to run the code? 
often I found helpful to run `bin/opal -Rserver` and inspect from the browser debugger on `localhost:3000`

**Comment by iliabylich** [comment]
@wied03 Your example works correctly on the latest master. I'm pretty sure it was fixed in one of your PRs related to `super` fixes, but I can't find it :smile: Can we close it?

**Comment by wied03** [comment]
@iliabylich - Yes I think we can close it. I forgot to reference this in my last `super` PR.

**Comment by wied03** [comment]
For reference, that was https://github.com/opal/opal/pull/1423
