### ISSUE TITLE
Bug in Regex

### ISSUE THREAD

**Issue by MichaelSp** [opal/opal#1394]
Opal:

    p ("abc" =~ /\A[_A-Za-z]\w*\z/)
    => nil

IRB:

    p ("abc" =~ /\A[_A-Za-z]\w*\z/)
    => 0

Version: 0.10.0.dev - dfdc82bfdb80c47f013e8e20c9a81fdce56ba0e9

**Comment by iliabylich** [comment]
Try this:
``` ruby
p ("abc" =~ /^[_A-Za-z]\w*$/)
# => 0
```

It's not really a bug. Opal doesn't implement its own Regex system, it uses bulitin JS regexes, `\A` and `\z` are not supported by JS.

If you need to write an isomorphic regexp (that works in both MRI and Opal), you can use [these constants](https://github.com/opal/opal/blob/6f8844c267af88ae8babc86c561142fa197cc117/lib/opal/regexp_anchors.rb#L2-L3) ([example](https://github.com/opal/opal/blob/204dde019bfdd83e35af2a5d1999d87bcda19260/lib/opal/nodes/call.rb#L156))

If not - just use the code from example.

**Comment by MichaelSp** [comment]
Oh, I see. 
Thanks for the quick and extensive answer.
