### ISSUE TITLE
SyntaxError in Chrome/Firefox

### ISSUE THREAD

**Issue by jgaskins** [opal/opal#1421]
I've noticed over the past couple weeks that none of my apps that run against Opal's master branch are loading on Chrome/Firefox. I'm getting this on them:

![screen shot 2016-04-03 at 8 32 53 pm](https://cloud.githubusercontent.com/assets/108205/14235978/46bdec0c-f9db-11e5-96a0-13bb17cac2b9.png)

I've pinned it down to 508b4ab.

![screen shot 2016-04-03 at 8 46 46 pm](https://cloud.githubusercontent.com/assets/108205/14236079/3e905752-f9dd-11e5-89a7-a9daca873703.png)
![screen shot 2016-04-03 at 8 34 43 pm](https://cloud.githubusercontent.com/assets/108205/14236081/41b5b6d4-f9dd-11e5-9748-d126943a7b50.png)

That character getting placed in front of the function names seems to be parsed fine in Safari, but Chrome and Firefox are borked at the moment.

I wouldn't have noticed this except that I use Chrome for profiling because it's one of two things it does that I need that Safari doesn't yet (the other being memory usage in the timeline). :-)

**Comment by elia** [comment]
@jgaskins just to be sure, do the page have the meta charset tag set to utf8?

**Comment by elia** [comment]
@jgaskins I'm quite sure it will be ok by adding `<meta charset="utf-8">` to the head tag, personally I think it's fine to expect the page to be utf8, but if a good case against it comes up I'm willing to reconsider. Feel free to reopen if needed :)

**Comment by jgaskins** [comment]
You're probably right. I thought it was using `Opal::Server`, but I guess it was one of my Rails apps.
