### ISSUE TITLE
Opal 0.10 Compiler Bootstrap SyntaxError Handling

### ISSUE THREAD

**Issue by wied03** [opal/opal#1427]
https://github.com/opal/opal/pull/1426 has a quasi fix/workaround for this.

source foo.rb:
```ruby
def problem
```
`bundle exec opal foo.rb` results on opal-master:
```
/usr/local/bundle/bundler/gems/opal-919e43442a1d/lib/opal/parser.rb:82:in `on_error': An error occurred while compiling: foo (RuntimeError)

parse error on value false ($end) :foo:2
Source: foo:2:0
```
opal 0.9.2
```
/usr/local/bundle/gems/opal-0.9.2/lib/opal/parser.rb:82:in `on_error': An error occurred while compiling: foo (RuntimeError)

parse error on value false ($end) :foo:2
Source: foo:2:0

^
```

Bootstrap compilation:

compiler.rb:
```ruby
require "opal"
require "opal-parser"

puts Opal::Compiler.new('def problem', {}).compile
```

When I run `opal compiler.rb`:

Opal master:
```
/tmp/opal-nodejs-runner-20160409-1431-w93ayr:31565
          } else { throw $err; }
                         ^
SyntaxError: unexpected 'false'
```

With https://github.com/opal/opal/pull/1426:
```
/tmp/opal-nodejs-runner-20160409-1446-1ev6afo:4382
      throw exception;
            ^
SyntaxError: An error occurred while compiling: (file)
unexpected 'false'
```

With opal 0.9.2:
```
/tmp/opal-nodejs-runner-20160409-10041-e0r81o:4298
      throw exception;
      ^
SyntaxError: An error occurred while compiling: (file)

unexpected 'false'
Source: (file):1:11
def problem
~~~~~~~~~~^
```
Neither of the bootstrap cases look as good as 0.10 compiled from MRI and none of them look as good as 0.9.2's bootstrap compilation. No filename is expected because I didn't pass that into the compiler. It would be nice to get the line number, etc. though.

**Comment by elia** [comment]
fixed by:

- f8d0152dbf (Update Racc::Parser to v1.4.6)
- c4e5eeb0f6 (Ensure all parsing errors are SyntaxError)
