### ISSUE TITLE
Can't parse ->(a: b=1) {}

### ISSUE THREAD

**Issue by iliabylich** [opal/opal#1448]
The issue is somewhere in the `grammar.y`, parser performs wrong reduce operations.
It must reduce `b` to `lhs`, but instead it reduces it to `primary` and `a: b` becomes kwarg pair before reading the `tEQL`

**Comment by wied03** [comment]
@iliabylich @elia - How many things like this would go away if https://github.com/opal/opal/issues/1235 was done?

**Comment by iliabylich** [comment]
@wied03 Most of them. But it's not that easy, opal and parser generate a different AST in many places (which requires some changes also in `opal/nodes`). But the answer is - yes, opal's lexer and parser are not ideal :smile: .

Also I have no idea how to inject opal-specific syntax (like `.JS.`) to parser's lexer/grammar, it can also be challenging.

**Comment by whitequark** [comment]
Adding a `.JS.` token would be straightforward (add a single lexer rule recognizing `.JS.` to, iirc, `expr_end`, then add a production rule) but this would make opal's parser diverge with upstream parser. So, it seems to me that a better solution would be to make an AST transformer, guarded by a check based on source maps that verifies that the three tokens in `.JS.` are adjacent.
