### ISSUE TITLE
Singleton Object/Class Ancestor Regression

### ISSUE THREAD

**Issue by wied03** [opal/opal#1449]
When a module defines the case compare operator, it also breaks usages of the case compare operator when that module is on the RHS of the operator.

```ruby
module Foo
  def self.===(*)
    raise 'method contents are irrelevant to bug'
  end
end

puts Class === Foo
```
MRI:
```
false
```
Opal master via `bundle exec opal -A ancestors.rb`:
```
true
```
Opal 0.9.2 executed same way
```
false
```

**Comment by wied03** [comment]
Might be a side effect of https://github.com/opal/opal/commit/bf22586c0fc2a4a98f5f9b6c31aa39f65ea64493

**Comment by wied03** [comment]
I created a Rubyspec for this - https://github.com/ruby/spec/pull/244

**Comment by wied03** [comment]
I keep trying to find alternatives to this code in `Opal.is_a` to fix this:
```js
    ancestors = Opal.ancestors(object.$$meta);
    for (i = 0, length = ancestors.length; i < length; i++) {     
      if (ancestors[i] === klass) {
        return true;
      }
    }
```
I thought about a guard to bail out of the function to if `===` is defined on object before iterating over the meta ancestors might work. Except I'm not sure that would really fix this since a module like the one in this example might be used a singleton case like in the specs.

Should `Class` be an ancestor of the singleton class for `Foo` in this case? Maybe that's the issue.

**Comment by wied03** [comment]
Along those lines, ran this test:
```ruby
module Foo
  def self.===(*)
    raise 'method is irrelevant to bug'
  end
end

class << Foo
  puts self.ancestors
end
```
MRI:
```
#<Class:Foo>
Module
Object
Kernel
BasicObject
```
Opal:
```
[#<Class:0x10c>, #<Class:0x16>, #<Class:0x14>, #<Class:0x12>, Class, Module, Object, Kernel, BasicObject]
```

Class isn't there in the MRI version.

**Comment by jgaskins** [comment]
This may just be a really weird edge case. An instance of `Class` isn't necessarily a subclass of `Class`. In fact, you should probably never _actually_ inherit from `Class`. :-)

I wonder why it's showing up in the ancestor chain.

**Comment by wied03** [comment]
I looks more like the `===` stuff is just a symptom of the problem and that `Class` being in the ancestor chain is the real problem

**Comment by wied03** [comment]
https://github.com/ruby/spec/pull/245 - more directly target the ancestor issue
