### ISSUE TITLE
Opal 0.10.0.beta3 is considerably slower than Opal 0.9.0.beta2

### ISSUE THREAD

**Issue by Mogztter** [opal/opal#1459]
Hello,

We've setup a benchmark in Asciidoctor.js and Opal 0.10.0.beta3 is considerably slower than Opal 0.9.2.beta2. See: https://github.com/asciidoctor/asciidoctor.js/issues/183

I've created a repository to reproduce this issue: https://github.com/Mogztter/asciidoctor.js-benchmark
Any help to find the root cause will be greatly appreciated :smile: 

NOTE: We've also found that Opal 0.9.2 is slightly faster than Opal 0.9.0.beta2 :+1:

**Comment by wied03** [comment]
@Mogztter - I can't see easily what all ascii doctor does, but have you done any profiling? If ascii doctor uses lots of `Enumerable` stuff, @jgaskins has an outstanding PR (https://github.com/opal/opal/pull/1450) that might improve on that a lot. The enumerable code was changed a lot from 0.9.2 to 0.10.0.beta3.

**Comment by Mogztter** [comment]
> I can't see easily what all ascii doctor does, but have you done any profiling?

Not yet, I tried to install `dtrace` to profile Node.js but unfortunately this isn't working on my Ubuntu 14.04 :disappointed: 
I will try to profile in Chrome and will let you know.

> If ascii doctor uses lots of Enumerable stuff, @jgaskins has an outstanding PR (#1450) that might improve on that a lot. 

Interesting...  I will try to apply #1450 on Opal 0.10.0.beta3 to see if there's any improvement on speed.

**Comment by Mogztter** [comment]
I've done a CPU profile with Chrome DevTools (.cpuprofile files):

https://drive.google.com/open?id=0B1rPjnFlfglqSktvd2UtZTR6TjA
https://drive.google.com/open?id=0B1rPjnFlfglqUFd3YWdZZ2gtOXM

Indeed `Opal.new_brk` is slower:

 * Opal 0.9.2: `242.1 ms 9.68 %	242.4 ms 9.70 %	asciidoctor-all.js:1149`
 * Opal 0.10.0.beta3: `436.6 ms 15.37 %	 437.1 ms 15.39 %	asciidoctor-all.js:1167`

**Comment by Mogztter** [comment]
The difference seems more important on Node.js so I've run a flamegraph:

 * Opal 0.9.2: https://drive.google.com/open?id=0B1rPjnFlfglqeHMwU0F6dkxXR1k
 * Opal 0.10.0.beta3: https://drive.google.com/open?id=0B1rPjnFlfglqdUxiYy1zbVY1dWM


`next_section`, `next_block` and `next_labeled_list` are taking more time on Opal 0.10.0.beta3. In these methods we are using `Opal.to_ary`. Maybe this is related ?

*Opal 0.10.0.beta3*
```javascript
Opal.defs(self, '$next_labeled_list', TMP_24 = function ːnext_labeled_list(reader, match, parent) {
  var $a, $b, $c, $d, self = this, list_block = nil, previous_pair = nil, sibling_pattern = nil, term = nil, item = nil;

  list_block = $scope.get('List').$new(parent, "dlist");
  previous_pair = nil;
  sibling_pattern = $scope.get('DefinitionListSiblingRx')['$[]'](match['$[]'](2));
  while ((($b = ((($c = match) !== false && $c !== nil) ? $c : (($d = reader['$has_more_lines?'](), $d !== false && $d !== nil ?(match = sibling_pattern.$match(reader.$peek_line())) : $d)))) !== nil && (!$b.$$is_boolean || $b == true))) {
    $c = self.$next_list_item(reader, list_block, match, sibling_pattern), $b = Opal.to_ary($c), term = ($b[0] == null ? nil : $b[0]), item = ($b[1] == null ? nil : $b[1]), $c;
    if ((($b = (($c = previous_pair !== false && previous_pair !== nil) ? previous_pair['$[]'](-1)['$!']() : previous_pair)) !== nil && (!$b.$$is_boolean || $b == true))) {
      previous_pair.$pop();
      previous_pair['$[]'](0)['$<<'](term);
      previous_pair['$<<'](item);
    } else {
      list_block.$items()['$<<']((previous_pair = [[term], item]))
    };
  match = nil;};
  return list_block;
}, TMP_24.$$arity = 3);
```

*Opal 0.9.2*
```javascript
Opal.defs(self, '$next_labeled_list', function(reader, match, parent) {
  var $a, $b, $c, $d, self = this, list_block = nil, previous_pair = nil, sibling_pattern = nil, term = nil, item = nil;

  list_block = $scope.get('List').$new(parent, "dlist");
  previous_pair = nil;
  sibling_pattern = $scope.get('DefinitionListSiblingRx')['$[]'](match['$[]'](2));
  while ((($b = ((($c = match) !== false && $c !== nil) ? $c : (($d = reader['$has_more_lines?'](), $d !== false && $d !== nil ?(match = sibling_pattern.$match(reader.$peek_line())) : $d)))) !== nil && (!$b.$$is_boolean || $b == true))) {
  $b = Opal.to_ary(self.$next_list_item(reader, list_block, match, sibling_pattern)), term = ($b[0] == null ? nil : $b[0]), item = ($b[1] == null ? nil : $b[1]);
  if ((($b = (($c = previous_pair !== false && previous_pair !== nil) ? previous_pair['$[]'](-1)['$!']() : previous_pair)) !== nil && (!$b.$$is_boolean || $b == true))) {
    previous_pair.$pop();
    previous_pair['$[]'](0)['$<<'](term);
    previous_pair['$<<'](item);
  } else {
    list_block.$items()['$<<']((previous_pair = [[term], item]))
  };
  match = nil;};
  return list_block;
});
```

**Comment by wied03** [comment]
@Mogztter - Is your latest benchmark using that new enumerable code?

**Comment by Mogztter** [comment]
@wied03 No but I did apply the patch on Enumerable and I didn't notice any improvement

Here's the Flamegraph with the Enumerable patch and Opal 0.10.0.beta3:

![opal0100beta3-enumerable](https://cloud.githubusercontent.com/assets/333276/14865680/0316dc82-0cc0-11e6-88a2-2d3423a3ad2a.png)

If you want to reproduce this graph, I recommend using `perf` command line: http://www.brendangregg.com/blog/2014-09-17/node-flame-graphs-on-linux.html

**Comment by wied03** [comment]
@Mogztter - I don't see any changes to `Opal.to_ary` since 0.9.2. What's being passed in there might have `#to_ary` defined on it now, which could change how it works.

**Comment by Mogztter** [comment]
Using WebStorm V8 CPU Profiling, `copy_instance_variables` takes 13.6% of the total execution time

Opal 0.10.0.beta3
![ws-opal0100beta3](https://cloud.githubusercontent.com/assets/333276/15407013/35f4df78-1e09-11e6-995b-c06b9de9694e.png)

Opal 0.9.2
![ws-opal092](https://cloud.githubusercontent.com/assets/333276/15407014/3747b1b6-1e09-11e6-8bee-37ab047a4589.png)


By the way, Opal 0.10.0.beta3 stack trace are way easier to read! :+1:
In Opal 0.9.2 almost everything is anonymous function :cry:

**Comment by Mogztter** [comment]
Method `copy_instance_variables` is basically the same between Opal 0.9.2 and Opal 0.10.0.beta3.
But I've add a counter inside this method:
 * Opal 0.9.2: 0
 * Opal 0.10.0.beta3: 3824

I think I found something `dup` method for array in Opal 0.9.2:

```javascript
    Opal.defn(self, '$dup', function() {
      var self = this, copy = nil;

      copy = [];
      copy.$initialize_dup(self);
      return copy;
    });
```

In Opal 0.10.0.beta3 this method doesn't exist anymore, so we are using `dup` method for kernel:

```javascript
    Opal.defn(self, '$dup', TMP_17 = function ːdup() {
      var self = this, copy = nil;

      copy = self.$class().$allocate();
      copy.$copy_instance_variables(self);
      copy.$initialize_dup(self);
      return copy;
    }, TMP_17.$$arity = 0);
```

(which is considerably slower)

**Comment by Mogztter** [comment]
I've copy/paste `$dup` for array and now Opal 0.10.0.beta3 is a bit faster than Opal 0.9.2! 
Can someone confirm this result ?

**Comment by elia** [comment]
> I've copy/paste $dup for array and now Opal 0.10.0.beta3 is a bit faster than Opal 0.9.2!

That's impressive! …and relieving! 😄 
Looking up the commit that removes it to find out why it's been done.

**Comment by elia** [comment]
https://github.com/opal/opal/commit/1e3979a58961bfb76a43e500bad09e494d3a586d

Probably a special case should be added to use a faster version of dup when self isn't an Array subclass.

**Comment by wied03** [comment]
@Mogztter - Before you had said 0.10 was slower. Is that still the case?

**Comment by Mogztter** [comment]
@elia Hmmm, what is the problem with this implementation (in Array)?
```ruby
def dup
  copy = []
  copy.initialize_dup(self)
  copy
end
```
@wied03 0.10 is slower without the above implementation because `Array.dup` is effectively using `Kernel.dup` (which is slower). If I reintroduce the above implementation in `corelib/array.rb` then 0.10 is faster (in my context) because we are using `dup` method a lot.

**Comment by jgaskins** [comment]
@Mogztter @elia Another alternative is to use `Array#map` and pass an identity function or just return `self.splice(0)`. I ran a benchmark of these two against the `initialize_dup` version — it does a dry run for 500ms and then checks how many times we can run the function in 2 seconds. Overhead is kept to a minimum.

## Benchmark Code

```ruby
array = [1, 2, 3, 4, 'omg']
init_dup = proc do
  copy = []
  copy.initialize_dup array
  copy
end
slice = proc { `array.slice(0)` }
map = proc { array.map { |i| i } }

def benchmark message, function
  finish = nil

  # dry run
  start = `performance.now()`
  while `(finish = performance.now()) - start < 500`
    function.call
  end

  count = 0
  start = `performance.now()`
  while `(finish = performance.now()) - start < 2000`
    function.call
    `count++`
  end
  puts "#{message}: #{count}"
end

benchmark "initialize_dup", init_dup
benchmark "map", map
benchmark "slice", slice
```

## Results:

- Safari 9.1
  - initialize_dup: 3017612
  - map: 5109036 (69% faster)
  - slice: 7619887 (152% faster)
- Chrome 50
  - initialize_dup: 2941951
  - map: 3120475 (6% faster)
  - slice: 4489207 (53% faster)
- Firefox 46
  - initialize_dup: 2764031
  - map: 2277893 (17% slower)
  - slice: 9732678 (253% faster)

`Array#map` is a little bit slower on Firefox, but `slice` decimates the rest of the benchmarks on all three browsers tested. Would there be any problem with just using one of these for `Array#dup`?

**Comment by Mogztter** [comment]
Thnaks @jgaskins for the benchmark!
Since we are calling this method, 3824 times in Asciidoctor, the faster the better! :+1:

**Comment by elia** [comment]
That's great, alas the problem with that approach (direct slice/map) is that it ignores both instance variables and singleton_methods, plus there's support for array subclasses. 

If there was a way to check if the objects has no custom properties (i.e. singleton methods and ivars) and then use an optimized JS implementation that would be great, and could be used directly in Kernel#dup so that every object could benefit. That I think is something that's done in MRI too.

here's how it could look like (see below the line for the code):

```
⤑ pbpaste | opal                                                               ~
baseline                                           -> 19554 (1.00x)
skip #allocate                                     -> 19594 (1.00x)
skip #copy_instance_variables                      -> 1814010 (92.77x)
skip #initialize_dup                               -> 19529 (1.00x)
native #copy_instance_variables                    -> 497687 (25.45x)
check if it's not a subclass (tiny overhead)       -> 19811 (1.01x)
slice if everything's pristine                     -> 6009235 (307.31x)
```

Looks like there's some potential, now, I'm still a bit unsure about how to set the pristine flag, but probably it's enough to set it manually where we leverage it (I sense this technique could be expanded with great perf benefits). 

_Thanks @jgaskins for the initial benchmarking code._

--


```rb
array = [1, 2, 3, 4, 'omg']


dup1 = -> do
  copy = ::Array.allocate
  copy.copy_instance_variables(array)
  copy.initialize_dup(array)
  copy
end

dup2 = -> do
  copy = []
  copy.copy_instance_variables(array)
  copy.initialize_dup(array)
  copy
end

dup3 = -> do
  copy = ::Array.allocate
  # copy.copy_instance_variables(array)
  copy.initialize_dup(array)
  copy
end

dup4 = -> do
  copy = ::Array.allocate
  copy.copy_instance_variables(array)
  # copy.initialize_dup(array)
  copy
end

dup5 = -> do
  copy = ::Array.allocate
  # copy.copy_instance_variables(array)
  %x{
    var name, keys = Object.keys(array)
    for (var i = keys.length - 1; i >= 0; i--) {
      name = keys[i]
      if (name.charAt(0) !== '$') {
        copy[name] = array[name];
      }
    }
  }
  
  copy.initialize_dup(array)
  copy
end

dup6 = -> do
  `if (array.$$class !== Opal.Array) return #{array.dup};`
  copy = ::Array.allocate
  copy.copy_instance_variables(array)
  copy.initialize_dup(array)
  copy
end

# mark method as pristine
%x{
array.$allocate.$$pristine = true;
array.$copy_instance_variables.$$pristine = true;
array.$initialize_dup.$$pristine = true;
}

dup7 = -> do
  `if (array.$$class !== Opal.Array 
      && array.$allocate.$$pristine
      && array.$copy_instance_variables.$$pristine
      && array.$initialize_dup.$$pristine
      ) return #{array.dup};`
  copy = `array.slice(0)`
  copy
end

`
performance = (
Opal.global.performance || {
    offset: Date.now(),
    now: function now(){
        return Date.now() - this.offset;
    }
}
);
`

def benchmark message, function
  finish = nil

  # dry run
  start = `performance.now()`
  while `(finish = performance.now()) - start < 500`
    function.call
  end

  count = 0
  start = `performance.now()`
  while `(finish = performance.now()) - start < 2000`
    function.call
    `count++`
  end
  $baseline ||= count
  puts "#{message.ljust(50)} -> #{count} (#{'%.2f' % (count / $baseline)}x)"
end

benchmark 'baseline', dup1
benchmark 'skip #allocate', dup2
benchmark 'skip #copy_instance_variables', dup3
benchmark 'skip #initialize_dup', dup4
benchmark 'native #copy_instance_variables', dup5
benchmark "check if it's not a subclass (tiny overhead)", dup6
benchmark "slice if everything's pristine", dup7
```

**Comment by jgaskins** [comment]
> the problem with that approach (direct slice/map) is that it ignores both instance variables and singleton_methods, plus there's support for array subclasses.

I intentionally ignored ivars and singleton methods because arrays don't need ivars and `dup` doesn't copy singleton methods, but you're right, I hadn't taken into account array subclasses which might need those ivars.

It might not be a bad idea, though, to optimize for duping a normal array even if the subclass scenario is handled.

> `message.ljust(50)`

lolleftpad

**Comment by elia** [comment]
> lolleftpad

yeh, you know, those little things… wait! it's not fair to mock Node while we run benchmarks on it!  ☝️😹

**Comment by wied03** [comment]
@elia - I think it is fair to complain about JS's lack of a core library that leads to such a package explosion.

**Comment by wied03** [comment]
So carry on :)
