### ISSUE TITLE
Compiled JS is using Opal.to_a instead of Opal.to_ary due to array splats

### ISSUE THREAD

**Issue by jaredcwhite** [opal/opal#1466]
Using Opal 0.9.2, the following kinds of Ruby code that uses array splats results in compiled JS code that calls `Opal.to_a` rather than `Opal.to_ary`:

``` ruby
    def self.new_with_parent(parent, *arr)
      new_object = self.new(*arr)  # problem line
      new_object.parent_view = parent
      new_object
    end
```

The problem line above generates:

``` js
new_object = ($a = self).$new.apply($a, Opal.to_a(arr));
```

Another example:

``` ruby
    def self.bind_accessor(*arr)
      bind_setup
      @bind_defs[:vars] += arr
      attr_accessor(*arr)  # problem line
    end
```

problem line generates:

``` js
return ($a = self).$attr_accessor.apply($a, Opal.to_a(arr));
```

**Comment by wied03** [comment]
@jaredcwhite - What about opal master? @jgaskins had a PR go in recently that might affect this.

**Comment by elia** [comment]
Still true on _master_: `    new_object = ($b = self).$new.apply($b, Opal.to_a(arr));`

**Comment by iliabylich** [comment]
It doesn't look like an issue.

MRI calls `#to_a` for:
  + mass assignment with splat
  + method call with splat

MRI calls `#to_ary` for:
  + mass assignment without splat

``` ruby
class ToA
  def to_a
    [1, 2]
  end
end

class ToAry
  def to_ary
    [3, 4]
  end
end

obj_to_a = ToA.new
obj_to_ary = ToAry.new

a, b = *obj_to_a
p [a, b]

a, b = obj_to_ary
p [a, b]


def method_that_takes_splat(*splat)
  p splat
end

method_that_takes_splat(*obj_to_a)
method_that_takes_splat(*obj_to_ary)
```

Output (MRI 2.3:)
``` ruby
[1, 2]
[3, 4]
[1, 2]
[#<ToAry:0x0000000179a788>]
```

Opal master:
``` ruby
[1, 2]
[3, 4]
[1, 2]
[#<ToAry:0x118>]
```

I guess we can close it since reported behavior seems to be correct.

**Comment by jaredcwhite** [comment]
@iliabylich My issue was I was getting an error that Opal.to_a didn't exist. It was a JS runtime error. So while I'm sure you're correct on how Opal *should* be working, that doesn't explain why I was getting the error. If you need more information on how to reproduce the error, I'll see what I can do.

**Comment by iliabylich** [comment]
@jaredcwhite  Yeah, that would be nice. And could you also make it as small as possible? :smile: 

`Opal.to_a` was introduced in `0.9.0.beta1` - https://github.com/opal/opal/blob/v0.9.0.beta1/opal/corelib/runtime.js#L1087-L1097. Are you sure that you are on 0.9.2?

**Comment by jgaskins** [comment]
@jaredcwhite Are you using `opal/mini` or `opal/base` rather than the full `opal` payload? If so, it could be a bug there. The runtime depends on some things that don't exist in `base` and `mini`, including in both `Opal.to_a` and `Opal.to_ary`.

I started #1481 to fix that, but it's incomplete and breaks CI. I need to find some time to work on it, but if I can't maybe someone else can.

**Comment by elia** [comment]
I'll close this one, probably not relevant anymore.
