### ISSUE TITLE
--map command line not working

### ISSUE THREAD

**Issue by h4ck3rm1k3** [opal/opal#1493]
--map and -m do not work
```
mdupont@mdupont-Aspire-7750G:~/experiments/opal$ ruby -I lib/ bin/opal --map
/home/mdupont/experiments/opal/lib/opal/cli.rb:64:in `initialize': unknown options: {:map=>true} (ArgumentError)
	from bin/opal:15:in `new'
	from bin/opal:15:in `<main>'
```

```
mdupont@mdupont-Aspire-7750G:~/experiments/opal$ ruby -I lib/ bin/opal -m   
/home/mdupont/experiments/opal/lib/opal/cli.rb:64:in `initialize': unknown options: {:map=>true} (ArgumentError)
	from bin/opal:15:in `new'
	from bin/opal:15:in `<main>'
```

**Comment by elia** [comment]
is that on master?

**Comment by h4ck3rm1k3** [comment]
yes, all on master. 
```
commit df31c8a1d2f1d0b441ca37ae7dbc6183d437bd04 (HEAD -> refs/heads/master, refs/remotes/origin/master, refs/remotes/origin/HEAD)
Author: Ilya Bylich <ibylich@gmail.com>
Date:   Thu Jun 23 20:15:42 2016 +0300

    Added support for complex and rational number literals. (#1487)
```

**Comment by elia** [comment]
This is a genuine bug, some glue code between cli_options.rb and cli.rb is missing.

**Comment by h4ck3rm1k3** [comment]
I dont know if this works... but it does not crash. how to verify?

**Comment by h4ck3rm1k3** [comment]
I have gotten the map to be emitted, see pr, but it is not what I am looking for. I want annotated source with source lines or some line by line mapping.

**Comment by elia** [comment]
fixed by https://github.com/opal/opal/commit/80d5938e9a8d657b18d9139f9328b41436e1649e and https://github.com/opal/opal/commit/80d5938e9a8d657b18d9139f9328b41436e1649e.

There's still room for improvement but at least it should be working now, thanks!
