### ISSUE TITLE
std lib Logger missing

### ISSUE THREAD

**Issue by h4ck3rm1k3** [opal/opal#1496]
Hi, How to handle the std lib Logger class, It does not seem to be shipped and compiling the code itself is causing errors.

**Comment by iliabylich** [comment]
@h4ck3rm1k3 What exactly do you need from the `Logger` class?

If you need it to compile some external library that depends on `Logger` you can implement some limited stubbed `Logger` class that simulates MRI logger's interface and prints all incoming messages using `Kernel#puts`.

``` ruby
class Logger
  def initialize(*)
  end

  [:info, :warn, :error, :fatal, :unknown].each do |level|
    define_method(level) { |message| puts message }
  end
end
```

If you really need a fully-functional logger class (I guess it's possible to use it from nodejs) you can copy it from the [MRI source](https://github.com/ruby/ruby/blob/trunk/lib/logger.rb) and remove all mutex/logrotate dependencies from its code (so it will contain only printing/formatting/log levels). If so, could you send a PR to opal with that changeset?

**Comment by h4ck3rm1k3** [comment]
The question was if we have core ruby libs ported, so I guess the answer is no. Thanks,
mike
