### ISSUE TITLE
obscure case of block params getting whacked

### ISSUE THREAD

**Issue by catmando** [opal/opal#1499]
Try this:
```ruby
class Foo 
  def self.register(object, name, &block)
    puts "defining method #{name} block = #{block}"
    define_method name do 
      puts "calling #{name}: object = #{object} block = #{block}"
      block.call if block
    end
  end
end

class BreakFoo
  def initialize(name)
    @klass = Class.new(Foo)
    @klass.class_eval { register("breaker", :breaker) { puts "say hi" } }
  end
end

class Baz < Foo
  register(BreakFoo.new, :doit) { puts "another block" }
end

class Works < Foo 
  @x = BreakFoo.new
  register(@x, :doit2) { puts "working block" }
end

Baz.new.doit
Works.new.doit2
```

(try it [here](http://opalrb.org/try/?code:class%20Foo%20%0A%20%20%0A%20%20def%20self.register(object%2C%20name%2C%20%26block)%0A%20%20%20%20puts%20%22defining%20method%20%23%7Bname%7D%20block%20%3D%20%23%7Bblock%7D%22%0A%20%20%20%20define_method%20name%20do%20%0A%20%20%20%20%20%20puts%20%22calling%20%23%7Bname%7D%3A%20object%20%3D%20%23%7Bobject%7D%20block%20%3D%20%23%7Bblock%7D%22%0A%20%20%20%20%20%20block.call%20if%20block%0A%20%20%20%20end%0A%20%20end%0A%20%20%0Aend%0A%0Aclass%20BreakFoo%0A%20%20%0A%20%20def%20initialize(name)%0A%20%20%20%20%40klass%20%3D%20Class.new(Foo)%0A%20%20%20%20%40klass.class_eval%20%7B%20register(%22breaker%22%2C%20%3Abreaker)%20%7B%20puts%20%22say%20hi%22%20%7D%20%7D%0A%20%20end%0A%20%20%0Aend%0A%0Aclass%20Baz%20%3C%20Foo%0A%20%20%0A%20%20register(BreakFoo.new%2C%20%3Adoit)%20%7B%20puts%20%22another%20block%22%20%7D%0A%20%20%0Aend%0A%0Aclass%20Works%20%3C%20Foo%20%0A%20%20%0A%20%20%40x%20%3D%20BreakFoo.new%0A%20%20%0A%20%20register(%40x%2C%20%3Adoit2)%20%7B%20puts%20%22working%20block%22%20%7D%0A%20%20%0Aend%0A%0ABaz.new.doit%0AWorks.new.doit2)

one would expect both Baz and Works to behave the same, but sadly in Baz the block passed to `register` is nil!!!

**Comment by iliabylich** [comment]
Simplified example:
``` ruby
def m(arg = nil, &blk)
  p blk.nil?
  blk.call if blk
end

m(m { puts 1 }) { puts 2 }
```

+ opal (and MRI) evaluates arguments **before** method call
+ in opal block pass is a `$$p` property on the function that represents a method
+ after calling a method opal flushes this property.

i.e. `opal -c --no-opal -e "def m(&blk); end; block = proc{}; m(&block)"` produces
``` js
  Opal.defn(Opal.Object, '$m', TMP_1 = function ːm() {
    var self = this, $iter = TMP_1.$$p, blk = $iter || nil;

    TMP_1.$$p = null;
    return nil
  })

  block = self.$proc();

  (var tmp = self.$m; tmp.$$p = block; tmp).call()
```

1. method call `m(...) { puts 2 }` assigns `Opal.Object.$m.$$p` to its block
2. argument `m { puts 1 }` assigns `Opal.Object.$m.$$p` to its block
3. opal calculates argument which calls its block (which prints 1) and flushes `Opal.Object.$m.$$p`
4. opal invokes a method which doesn't have this property
5. no block given :cry: 

https://github.com/opal/opal/pull/1334 completely fixes this issue

**Comment by iliabylich** [comment]
@elia How about:
``` js
// def m(a=nil, &blk)
//   puts a.inspect
//   puts blk.call.inspect;
//   'm returned';
// end;


var nil = "nil", context = null;

TMP_m = function(a) {
  if (a == null) {
    a = nil;
  }

  console.log(a);
  console.log(TMP_m.$$p.call());
  return "m returned";
}

// blk1 = proc { puts 1; 1 }
// blk2 = proc { puts 2; 2 }

blk1 = function() { console.log(1); return 1; }
blk2 = function() { console.log(2); return 2; }

// m(m(&blk1), &blk2)

// Now (simplified)
console.log("NOW:");

result = (
  TMP_m.$$p = blk2,
  TMP_m
).call(
  context, (
    TMP_m.$$p = blk1,
    TMP_m
  ).call(context)
)

// Must be (simplified)
console.log("MUST BE:");

result = (
  args_tmp1 = [
    (args_tmp2 = [], TMP_m.$$p = blk1, TMP_m).apply(context, args_tmp2)
  ],
  TMP_m.$$p = blk2,
  TMP_m
).apply(context, args_tmp1)
```

Ruby code:
``` ruby
def m(a=nil, &blk)
  puts a.inspect
  puts blk.call.inspect
  'm returned'
end

blk1 = proc { puts 1; 1 }
blk2 = proc { puts 2; 2 }

m(m(&blk1), &blk2)
```

From what I see it matches MRI behavior.
Block must be
+ assigned to a method body **after** arguments calculation (to prevent `$$p` resetting by arguments)
+ extracted in the method body before populating optargs (to prevent resetting it by calculating default values for method arguments)

I still don't like that we pass `$$p` as a function property, but passing it with other arguments is a nightmare in cases like
``` ruby
def m(a,b=1,*c,d,e:,f:1,**g,&blk)
end
```

Are there any other ways to pass data to a function except plain arguments / static properties?

**Comment by catmando** [comment]
hey thanks a lot!!! this one of the few bugs I have found... thanks for fixing
