### ISSUE TITLE
 Invalid flags supplied to RegExp constructor 'n

### ISSUE THREAD

**Issue by h4ck3rm1k3** [opal/opal#1508]
SyntaxError: Invalid flags supplied to RegExp constructor 'n'

# error
Invalid flags supplied to RegExp constructor 'n
# input 
```
UTF8_RE = /\A(?:
        [\x00-\x7f]
       |[\xc0-\xdf][\x80-\xbf]
       |[\xe0-\xef][\x80-\xbf][\x80-\xbf]
       |[\xf0-\xf7][\x80-\xbf][\x80-\xbf][\x80-\xbf]
       |[\xf8-\xfb][\x80-\xbf][\x80-\xbf][\x80-\xbf][\x80-\xbf]
       |[\xfc-\xfd][\x80-\xbf][\x80-\xbf][\x80-\xbf][\x80-\xbf][\x80-\xbf])\Z/nx;
```

# source
https://github.com/boukeversteegh/chise/blob/342df4be600e2e9790cba880dd9b3cf54c436831/ruby/chise/string.rb

**Comment by iliabylich** [comment]
This flag is not supported by native javascript regexps and it can't be fixed without using shims like XRegExp. See https://github.com/opal/opal/pull/591 for more information

**Comment by h4ck3rm1k3** [comment]
This is still a bug, it is unsupported code that is valid ruby. If we are going to claim it is a ruby compiler, we need to keep this open.

**Comment by elia** [comment]
> If we are going to claim it is a ruby compiler, we need to keep this open.

Yes, but it's enough to keep track of this under  the umbrella issue that is #591. The deal for now is that native JS regexps are used (as we do with numbers, arrays, and procs).

**Comment by h4ck3rm1k3** [comment]
xarasho

**Comment by h4ck3rm1k3** [comment]
the flag \n means ascii encoding. 
http://ruby-doc.org/core-2.1.1/Regexp.html
> Regular expressions are assumed to use the source encoding. This can be overridden with one of the following modifiers.
>     /pat/u - UTF-8
>     /pat/e - EUC-JP
>     /pat/s - Windows-31J
>     /pat/n - ASCII-8BIT

So I was able to transform them into unicode constants

      |[\xc0-\xdf][\x80-\xbf]

becomes

     |[\u00c0-\u00df][\u0080-\u00bf]

So I think the compiler could support that easily.

**Comment by h4ck3rm1k3** [comment]
I would like to treat this a separate issue, because I don't see the encoding types being handled in the other issue. If unsupported please mark as such.
