### ISSUE TITLE
missing code for Array#pack (pack: undefined method `pack' for [9]:Array)

### ISSUE THREAD

**Issue by h4ck3rm1k3** [opal/opal#1522]
No implementation for :
http://ruby-doc.org/core-2.3.1/Array.html#method-i-pack

See example imps here: 

https://github.com/rubinius/rapa/blob/master/machines/pack.rl
https://github.com/thousandparsec-obsolete/libtpproto-rb/blob/bbba5e34682887210d44be1a7ee0c20c9c5b40df/pack.rb
# Derived from

https://github.com/h4ck3rm1k3/rubysl-rexml/blob/opal/lib/rexml/text.rb#L36
# input

https://github.com/h4ck3rm1k3/jschef/blob/master/tests/regex.rb

```
VALID_CHAR = [
      0x9, 0xA, 0xD,
      (0x20..0xD7FF),
      (0xE000..0xFFFD),
      (0x10000..0x10FFFF)
]

VALID_XML_CHARS = Regexp.new('^['+
                             VALID_CHAR.map { |item|
                               case item
                               when Fixnum
                                 [item].pack('U').force_encoding('utf-8')
                               when Range
                                 [item.first, '-'.ord, item.last].pack('UUU').force_encoding('utf-8')
                               end
                             }.join +
                             ']*$')

```
# error

https://github.com/h4ck3rm1k3/jschef/blob/96867bb5d963072cc1d49553f75a4f41ea790f10/tests/regex.rb.out

```
+ ruby -I ../opal/lib/ ../opal/bin/opal tests/regex.rb
/tmp/opal-nodejs-runner-20160708-8803-1yd75h7:4679
      throw exception;
      ^
pack: undefined method `pack' for [9]:Array
    at Opal.defs.TMP_1 [as $new] (/tmp/opal-nodejs-runner-20160708-8803-1yd75h7:4894:15)
    at Array.ːmethod_missing (/tmp/opal-nodejs-runner-20160708-8803-1yd75h7:3448:70)
    at Array.method_missing_stub [as $pack] (/tmp/opal-nodejs-runner-20160708-8803-1yd75h7:1079:35)
    at /tmp/opal-nodejs-runner-20160708-8803-1yd75h7:19805:57
    at Opal.cdecl.$scope.get.$new.$a.$$p.TMP_1 (/tmp/opal-nodejs-runner-20160708-8803-1yd75h7:19805:247)
    at Opal.yield1 (/tmp/opal-nodejs-runner-20160708-8803-1yd75h7:1271:14)
    at Array.ːcollect (/tmp/opal-nodejs-runner-20160708-8803-1yd75h7:11003:26)
    at /tmp/opal-nodejs-runner-20160708-8803-1yd75h7:19805:301
    at Object.<anonymous> (/tmp/opal-nodejs-runner-20160708-8803-1yd75h7:19806:3)
    at Module._compile (module.js:409:26)

```

**Comment by karimmtarek** [comment]
Hey @elia I'm interested in this, how should I go about it? Use any of the mentioned examples above? What about specs? Any docs how to write/run specs for the project?

**Comment by elia** [comment]
@karimmtarek great! Most of what you need to get going is in our [HACKING.md guide](https://github.com/opal/opal/blob/master/HACKING.md)

Essentially we use [The Ruby Spec Suite](https://github.com/ruby/spec#readme), and a filter system to exclude unsupported and/or unimplemented features: https://github.com/opal/opal/tree/master/spec/filters

Be sure to also check out this WIP PR https://github.com/opal/opal/pull/1557 by @camertron

Feel free to ask if anything is unclear or can be improved, also you can ask things in https://gitter.im/opal/opal.

**Comment by hmdne** [comment]
Opal now supports Array#pack and String#unpack (not fully though, but enough for this issue's code to work... except for Regexp having >BOM issues without 'u' flag). I'm closing this issue, but it's important to keep in mind the >BOM problems.
