### ISSUE TITLE
handling of backticks

### ISSUE THREAD

**Issue by h4ck3rm1k3** [opal/opal#1524]
unquoted string 

# input
```
# from chef/lib/chef/provider/package/zypper.rb
zypper_version ||=
  `zypper -V 2>&1`.scan(/\d+/).join(".").to_f
  ```
# emitted js
```
/* Generated by Opal 0.11.0.dev */
(function(Opal) {
  var $a, self = Opal.top, $scope = Opal, nil = Opal.nil, $breaker = Opal.breaker, $slice = Opal.slice, zypper_version = nil;

  Opal.add_stubs(['$to_f', '$join', '$scan']);
  return ((($a = zypper_version) !== false && $a !== nil && $a != null) ? $a : (zypper_version = (zypper -V 2>&1).$scan(/\d+/).$join(".").$to_f()))
})(Opal);
```

# error 
```
/home/mdupont/experiments/scriops/jschef/tmp/tests/zyper.rb.js:19797
  return ((($a = zypper_version) !== false && $a !== nil && $a != null) ? $a : (zypper_version = (zypper -V 2>&1).$scan(/\d+/).$join(".").$to_f()))
                                                                                                            ^

SyntaxError: Unexpected number
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
```
# expected output 
none

**Comment by elia** [comment]
@h4ck3rm1k3 backticks are used to interleave ruby with raw javascript so it's not supported for now.

There's a chance though for this to be supported if we add support for leading comments and we use those to disable backticks special treatment. But for now it's very speculative.

**Comment by h4ck3rm1k3** [comment]
the usage above is just for executing a shell command like perl does. It would be done as sys exec and capture output.

**Comment by h4ck3rm1k3** [comment]
ruby -e 'print `ls`' will list the current directory.

**Comment by elia** [comment]
Yeah I know how that works in MRI, for now it's just unsupported, that might change once we allow some compiler configuration via comments as described above.

**Comment by h4ck3rm1k3** [comment]
@elia how come you closed this?

**Comment by elia** [comment]
Because it's unsupported, that means that it's not considered a bug (for now). In addition to that I also explained future plans that may include support for this. 

We try to keep the number of open issues low and relevant.

**Comment by h4ck3rm1k3** [comment]
How about we tag the issue as "unsupported" so we can track it later on ? How many of these closed bugs are unsupported?

**Comment by elia** [comment]
@h4ck3rm1k3 you can find a list of unsupported stuff in this folder: https://github.com/opal/opal/tree/master/spec/filters/unsupported
