### ISSUE TITLE
CLI skip_opal_require option treatement

### ISSUE THREAD

**Issue by bryanjhv** [opal/opal#1526]
For now, we have in `lib/opal/cli.rb`:

```ruby
    # ...
    def skip_opal_require?
      @skip_opal_require
    end
    # ...
    def initialize options = nil
      # ...
      @skip_opal_require = options.delete(:skip_opal_require)
      # ...
    end
    # ...
    def build
      # ...
      builder.build 'opal' unless skip_opal_require?
      # ...
    end
    # ...
```

Then, is there any reason not to do:

```ruby
    def initialize options = nil
      # ...
      @skip_opal_require = options.delete(:skip_opal_require)
      @requires << 'opal' if @skip_opal_require
      # ...
    end
```

instead of taking it in the `build` method, treating it as a normal `-r` switch?

Also, it could also remove the need to set explicit `requires: ['opal']` in #1523 and for sure increase readability.

**Comment by elia** [comment]
@bryanjhv I agree that things can be improved on that side generally, as for `skip_opal_require` the current sequence can't be replaced just by moving `opal` to requires as there's a couple other things that happen between the two

```rb
      builder.build 'opal' unless skip_opal_require?

      preload.each { |path| builder.build_require(path) }

      # FLAGS
      builder.build_str '$VERBOSE = true', '(flags)' if verbose
      builder.build_str '$DEBUG = true', '(flags)' if debug

      # REQUIRES: -r
      requires.each do |local_require|
        builder.build(local_require)
      end
```

https://github.com/opal/opal/blob/e1ca27aa3c0f19bab37273a4da80b66db00239bf/lib/opal/cli.rb#L99-L110

**Comment by bryanjhv** [comment]
But does the preloader need the `opal` require ready before it takes each preloaded thing into account?

**Comment by elia** [comment]
> I get it, but does the preloader need the opal require ready before it takes each preloaded thing into account?

That's probably a 🐛, given probably no-one is using the CLI preload feature 😄

**Comment by bryanjhv** [comment]
A :bug:? Maybe someone is using it, but I guess developers mostly want to preload its things, using the default stdlib in Ruby or its own gems, but thinking "why should I want to preload something using `opal` if I'm calling the CLI to **use** it?".

**Comment by elia** [comment]
the usecase for preload is this:

```
$ opal --preload base64 --eval 'require "base#{2**6}"; p Base64'
WARNING: Cannot handle dynamic require -- -e:1
Base64
```

In this case the compiler is unable to tell what you're going to require because the argument is dynamic. Preloading will make it work because you know in advance what's going on. 

That kind of situation is not so uncommon when using existing gems.

In fact when used in conjunction with `--no-opal` it breaks:

```
$ opal --preload base64 --no-opal --eval 'require "opal"; require "base#{2**6}"; p Base64'
WARNING: Cannot handle dynamic require -- -e:1
/private/var/folders/w0/yjfqr9n94ld7ft4j3hlz_fsm0000gn/T/opal-nodejs-runner-20160810-97272-1wmks4c:2
Opal.modules["base64"] = function(Opal) {
^

ReferenceError: Opal is not defined
    at Object.<anonymous> (/private/var/folders/w0/yjfqr9n94ld7ft4j3hlz_fsm0000gn/T/opal-nodejs-runner-20160810-97272-1wmks4c:2:1)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (node.js:348:7)
    at startup (node.js:140:9)
    at node.js:463:3
```

**Comment by bryanjhv** [comment]
That's a clear explanation of `--preload`. With your commit (07bd402e77770b127e440acc052c4aeeb0e24656) it's now handling things better, covering both switches, and in order.
Going back to the initial comment in this issue, and the added comment on the commit, this can be closed now (I guess)?
