### ISSUE TITLE
Opal::Builder.build cannot find clearwater gem

### ISSUE THREAD

**Issue by mxvanzant** [opal/opal#1542]
Here is my application.rb and Rakefile and the output when I run: 'rake build'. I don't know why Opal::Builder.build cannot find the clearwater gem. But, I can require 'clearwater' in irb no problem. Any ideas?

```ruby
#application.rb in app folder:
require 'clearwater'
require 'opal'
require 'ostruct'

class Layout
  include Clearwater::Component

  def render
    div({ id: 'app' }, [
      header({ class_name: 'main-header' }, [
        h1('Hello, world!'),
      ]),
      outlet, # This is what renders subordinate routes
    ])
  end
end
#... more
```

```ruby
# Rakefile
require 'opal'

desc "Build our app to build.js"
task :build do
  Opal.append_path "app"
  File.binwrite "./public/lib/app/build.js", Opal::Builder.build("application").to_s
end
```

Output:

```
Opal::Builder::MissingRequire: A file required by "application" wasn't found.
can't find file: "clearwater" in ["/home/mxvanzant/.rvm/gems/ruby-2.2.2@rsproto/gems/opal-0.10.1/opal", "/home/mxvanzant/.rvm/gems/ruby-2.2.2@rsproto/gems/opal-0.10.1/stdlib", "/home/mxvanzant/.rvm/gems/ruby-2.2.2@rsproto/gems/opal-0.10.1/lib", "/home/mxvanzant/dev/tg/reactionstream/code/reactionstream-backend/app"]
```

**Comment by elia** [comment]
@mxvanzant try requiring `clearwater` in the rakefile too, that way clearwater will have a chance to add its path to those searched by opal (`Opal.paths`).

cc @jgaskins

**Comment by jgaskins** [comment]
@elia Bingo.

@mxvanzant You'll also want to require `opal` before `clearwater` in your `application.rb`. This will load the Opal runtime first so it can store Clearwater's classes and modules inside it. :-) If you've got any questions about Clearwater, feel free to hit me up in the [Gitter channel](https://gitter.im/clearwater-rb/clearwater).

**Comment by jgaskins** [comment]
For a little background on the require order there: You used to be able to leave out `require 'opal'` and Clearwater would load it for you, but I wanted to allow people to load Opal from a CDN if they wanted.

**Comment by mxvanzant** [comment]
Thanks! I will try that and let you know how it goes.

**Comment by elia** [comment]
@mxvanzant closing this for now, let me know if anything is still not working and I'll reopen promptly :)
