### ISSUE TITLE
Error when running tests on master

### ISSUE THREAD

**Issue by Mogztter** [opal/opal#1544]
The test suite is currently failing on master:

```
Module#include recursively includes new mixins ERROR
TypeError: wrong argument type Class (expected Module)
TypeError: wrong argument type Class (expected Module)
    at Opal.defs.TMP_1 [as $new] (/tmp/opal-nodejs-runner-20160803-24348-185k8gs:5160:15)
    at ːexception (/tmp/opal-nodejs-runner-20160803-24348-185k8gs:5177:31)
    at module_constructor.ːraise (/tmp/opal-nodejs-runner-20160803-24348-185k8gs:4903:31)
    at module_constructor.ːinclude (/tmp/opal-nodejs-runner-20160803-24348-185k8gs:2956:16)
    at /tmp/opal-nodejs-runner-20160803-24348-185k8gs:156064:16
    at /tmp/opal-nodejs-runner-20160803-24348-185k8gs:156065:11
    at Object_alloc.$c.$$p.TMP_25 (/tmp/opal-nodejs-runner-20160803-24348-185k8gs:156090:9)
    at Object_alloc.ːinstance_eval (/tmp/opal-nodejs-runner-20160803-24348-185k8gs:3566:24)
    at module_constructor.ːprotect (/tmp/opal-nodejs-runner-20160803-24348-185k8gs:50373:78)
    at $a.$$p.TMP_29 (/tmp/opal-nodejs-runner-20160803-24348-185k8gs:49971:113)
```

https://travis-ci.org/opal/opal/jobs/148887254 (`RANDOM_SEED=50914`)

I can reproduce this issue locally but I could find the conflicting specs :disappointed: 

NOTE: This is working with `RANDOM_SEED=40654`

**Comment by iliabylich** [comment]
[This](https://gist.github.com/iliabylich/fdda8fa928fed624d766971d05524fc0) is a sample of `mspec_nodejs.rb` that fails (generated using @Mogztter 's `RANDOM_SEED`)

`ruby/language/constants_spec.rb` conflict with `ruby/core/module/include_spec.rb` and that's a bug in Opal.

Here's a minimal example of this issue:
``` ruby
# part of fixtures/constants_sclass (required by `constants_spec`)
module ConstantSpecs
  obj = Object.new
  class << obj
    class X
      # creates <singleton class::X>
    end
  end
end

begin
  p X.class
rescue
  p "undefined ::X"
end

# part of "Module#include recursively includes new mixins"
module ModuleSpecs
  module X
  end

  p X.class

  module V
    p X.class
    include X
  end
end
```

MRI output:
```
"undefined ::X"
Module
Module
```

Opal master output:
```
Class
Module
Class

/tmp/opal-nodejs-runner-20160803-10234-jexfsl:4792
      throw exception;
            ^
TypeError: wrong argument type Class (expected Module)
```

**Comment by Mogztter** [comment]
Thanks @iliabylich !
That'ss really helpful, I will try to debug further :smile: :bug:

**Comment by Mogztter** [comment]
@iliabylich I have a different output:

Opal master (with Node 0.12):
```
$ node -v
v0.12.0
```
```
$ cat issue-1544.rb 
# part of fixtures/constants_sclass (required by `constants_spec`)
module ConstantSpecs
  obj = Object.new
  class << obj
    class X
      # creates <singleton class::X>
    end
  end
end

begin
  p X.class
rescue
  p "undefined ::X"
end

# part of "Module#include recursively includes new mixins"
module ModuleSpecs
  module X
  end

  p X.class

  module V
    p X.class
    include X
  end
end
```
```
$ bin/opal --compile issue-1544.rb > issue-1544.js
```
```
$ node issue-1544.js 
Class
Module
Module
```

MRI (with Ruby 2.3.0):
```
$ ruby -v
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]
```
```
ruby issue-1544.rb 
"undefined ::X"
Module
Module
```

**Comment by Mogztter** [comment]
MRI output (with Ruby 2.3.0):

```ruby
module ConstantSpecs
  obj = Object.new
  class << obj
    class X
      # creates <singleton class::X>
    end
  end
end

begin
  p X.class
rescue Exception => e
  p "undefined ::X"
  p e
end
```
```
"undefined ::X"
#<NameError: uninitialized constant X>
```

Here's the same code compiled in JavaScript:

```javascript
(function(Opal) {
  var self = Opal.top, $scope = Opal, nil = Opal.nil, $breaker = Opal.breaker, $slice = Opal.slice, $module = Opal.module, $klass = Opal.klass, e = nil;

  Opal.add_stubs(['$new', '$p', '$class']);
  (function($base) {
    var $ConstantSpecs, self = $ConstantSpecs = $module($base, 'ConstantSpecs');

    var def = self.$$proto, $scope = self.$$scope, obj = nil;

    obj = $scope.get('Object').$new();

    (function(self) {
      var $scope = self.$$scope, def = self.$$proto;

      return (function($base, $super) {
        function $X(){};
        var self = $X = $klass($base, $super, 'X', $X);

        var def = self.$$proto, $scope = self.$$scope;

        return nil;
      })($scope.base, null)
    })(Opal.get_singleton_class(obj));
  })($scope.base);
  try {
    return self.$p($scope.get('X').$class())
  } catch ($err) {
    if (Opal.rescue($err, [$scope.get('Exception')])) {e = $err;
      try {
        self.$p("undefined ::X");
        return self.$p(e);
      } finally { Opal.pop_exception() }
    } else { throw $err; }
  };
})(Opal);
```

The following code should throw an exception but `$scope.get('X')` is resolved when running in JavaScript:
```javascript
$scope.get('X').$class()
```

So this is most likely a scope issue.

Here's the `Opal.get` function:
```javascript
  Opal.get = function(name) {
    var constant = this[name];

    if (constant == null) {
      return this.base.$const_get(name);
    }

    return constant;
  };
```
When running in debug, we can see that `this[name]` can resolve `this['X']`.

If we use `self` instead of an Object instance this is working as expected:
 
```ruby
module PrivateSpecs
  class << self
    class Y
      # create <singleton class::Y>
    end
  end
end

begin
  p Y.class
rescue Exception => e
  p "undefined ::Y"
  p e
end
```

MRI output:
```
"undefined ::Y"
#<NameError: uninitialized constant Y>
```
Opal master output:
```
"undefined ::Y"
#<NameError: uninitialized constant Y>
```

The only difference in the compiled code is this line:
```diff
-(Opal.get_singleton_class(obj))
+(Opal.get_singleton_class(self))
```

In the first case we are "binding" the X class to a "global" scope (Object class) and in the second case we are "binding" the Y class to a "module" scope (PrivateSpecs module).

**Comment by Mogztter** [comment]
I'm not sure to fully understand the Ruby code:

```ruby
module ConstantSpecs
  obj = Object.new
  class << obj
    class X
      # creates <singleton class::X>
    end
  end
end
```

So we create an anonymous class tied to a particular object instance and inside this anonymous class we define an X class (which somehow is instantiated as a singleton) ?
Does this make sense in a "real world" application ? And if so, what is the purpose ?

To return to this issue, I think we shouldn't "bind" the X class to the "singleton class Object" but to the particular Object instance. @iliabylich Wdyt ?

Having said that I have no idea how to fix it :wink:

**Comment by iliabylich** [comment]
@Mogztter Are you sure that you are on the latest master? Scopes logic has changed in [this commit](https://github.com/opal/opal/commit/e1ca27aa3c0f19bab37273a4da80b66db00239bf), now Opal uses a stack of scopes. Looks like your code is a little bit outdated.

The bug is not in the constant lookup, constant `X` appears on the global `Opal` object (e.g. `Opal.X`). This means that this constant was defined incorrectly.

``` ruby
obj = []

class << obj
  X = 1
end

p X
```

And now Opal raises a `NameError` (just like MRI) :smile: I guess the bug is [here](https://github.com/opal/opal/blob/master/opal/corelib/runtime.js#L755).

When you define a constant `CONST` on the singleton class of the object `a` of the class `A`, Opal produces a constant `A::CONST` (instead of `a.singleton_class::X`)

Scope of the singleton class of `Object.new` is the scope of `Object` (which equals to a global scope).

With the previous code snippet constant `Array::X` becomes available.

Don't know how to fix it. Singleton classes should have their own scopes. It doesn't look like a ten minutes fix.

**Comment by Mogztter** [comment]
> Are you sure that you are on the latest master? Scopes logic has changed in this commit, now Opal uses a stack of scopes. Looks like your code is a little bit outdated.

My working copy was up to date, but I didn't use  `bundle exec opal` :unamused: 
Now I have the same output:

```
Class
Module
Class

/home/guillaume/workspace/opensource/opal/issue-1544.js:4792
      throw exception;
            ^
TypeError: wrong argument type Class (expected Module)
```

> And now Opal raises a NameError (just like MRI) :smile: 

True

> I guess the bug is here.

Are you sure about that ?
Basically the code is doing:

```javascript
obj = Opal.const_get($scopes, 'Object', true, true).$new();
Opal.get_singleton_class(obj);
```

And the `get_singleton_class` returns immediately because `$$meta` is defined on `obj`:

```javascript
  Opal.get_singleton_class = function(object) {
    if (object.$$meta) {
      return object.$$meta;
    }

    if (object.$$is_class || object.$$is_module) {
      return Opal.build_class_singleton_class(object);
    }

    return Opal.build_object_singleton_class(object);
  };
```

During my tests the `build_object_singleton_class` method wasn't called.

> Don't know how to fix it. Singleton classes should have their own scopes. It doesn't look like a ten minutes fix.

Indeed

**Comment by elia** [comment]
I'd put that in `filters/bug` on master and open a failing PR, that way any other PR can get green specs and we still are reminding ourselves this should be fixed.

@Mogztter @iliabylich wdyt?

**Comment by Mogztter** [comment]
OK

**Comment by Mogztter** [comment]
I think we can close this issue and open a new issue when a particular seed fails (eg. https://github.com/opal/opal/issues/1607)

@elia wdyt ?
