### ISSUE TITLE
JSON.parse not throwing StandardError

### ISSUE THREAD

**Issue by catmando** [opal/opal#1545]
This works in IRB
`JSON.parse('foo') rescue 'foo'`
but not in opal 0.10

**Comment by elia** [comment]
The solution would be to wrap the call to `$parse` [here](https://github.com/opal/opal/blob/e1ca27aa3c0f19bab37273a4da80b66db00239bf/stdlib/json.rb#L70) with a JS `try/catch` and throw the correct Ruby errors instead of the native ones.
