### ISSUE TITLE
Load-time performance slowing down

### ISSUE THREAD

**Issue by jgaskins** [opal/opal#1548]
I checked the load-time performance on a minified/gzipped build of a hello-world Clearwater app compiled with Opal 0.10.1 and found that it seems to be a fair bit slower than the same app on 0.8.1. Then I checked with 0.7.1 and it looks like there's a trend toward slower boot times. Between 0.7 and 0.8 it wasn't a huge jump, but between 0.8 and 0.10 it was pretty significant.

Load times:

Chrome:
0.7.1: 125ms
0.8.1 : 151ms (+21%)
0.10.1: 223ms (+78%)

Safari:
0.7.1: 63ms
0.8.1 : 74ms (+17%)
0.10.1: 97ms (+54%)

Part of this is probably caused just by the increase in the size of the Opal runtime+corelib (63kb in 0.10.1 vs 37kb in 0.7.1, an increase of 70%), but I also wonder if it's caused by method arity being injected into every method on boot. Any other ideas?

**Comment by elia** [comment]
> but I also wonder if it's caused by method arity being injected into every method on boot

arity can be disabled with `Opal::Config`:

```rb
Opal::Config.arity_check_enabled = false
```

https://github.com/opal/opal/blob/master/lib/opal/config.rb#L8

opal-rails should have it enabled in dev and disabled in prod by default.

--

If that's not the problem it's probably worth finding out what's the culprit.

**Comment by jgaskins** [comment]
Not the arity check, the arity assignment. The `$$arity` property on the function.

**Comment by jgaskins** [comment]
I don't know how much time that takes, but it does get run on every single Ruby method at the time of definition.

**Comment by iliabylich** [comment]
Opal has ~1k methods, each method starting from  0.10 has a `$$arity` property (which is just a number):

With `$$arity` prop (master):
```
opal -ce '123' > tmp/opal_with_arity_attrs.js
grep -F '.$$arity =' tmp/opal_with_arity_attrs.js | wc -l
1045

repeat 5 time node tmp/opal_with_arity_attrs.js 
node tmp/opal_with_arity_attrs.js  0,12s user 0,01s system 100% cpu 0,129 total
node tmp/opal_with_arity_attrs.js  0,12s user 0,01s system 100% cpu 0,128 total
node tmp/opal_with_arity_attrs.js  0,11s user 0,01s system 100% cpu 0,123 total
node tmp/opal_with_arity_attrs.js  0,12s user 0,00s system 100% cpu 0,123 total
node tmp/opal_with_arity_attrs.js  0,11s user 0,01s system 100% cpu 0,124 total
```

Without `$$arity` (i.e. without [these](https://github.com/opal/opal/blob/master/lib/opal/nodes/def.rb#L98) [lines](https://github.com/opal/opal/blob/master/lib/opal/nodes/iter.rb#L49))
```
opal -ce '123' > tmp/opal_without_arity_attrs.js
grep -F '.$$arity =' tmp/opal_without_arity_attrs.js | wc -l
2 (coming from `define_method`)

repeat 5 time node tmp/opal_without_arity_attrs.js
node tmp/opal_without_arity_attrs.js  0,12s user 0,01s system 100% cpu 0,132 total
node tmp/opal_without_arity_attrs.js  0,13s user 0,00s system 100% cpu 0,129 total
node tmp/opal_without_arity_attrs.js  0,12s user 0,00s system 100% cpu 0,122 total
node tmp/opal_without_arity_attrs.js  0,10s user 0,02s system 100% cpu 0,122 total
node tmp/opal_without_arity_attrs.js  0,11s user 0,01s system 100% cpu 0,122 total
```

So I guess it's not a `$$arity` prop.

**Comment by elia** [comment]
> Part of this is probably caused just by the increase in the size of the Opal runtime+corelib (63kb in 0.10.1 vs 37kb in 0.7.1, an increase of 70%), but I also wonder if it's caused by method arity being injected into every method on boot. Any other ideas?

I'll close this, the corelib size has surely increased over time (which by itself is good) and arity can be easily turned off (which is the default).
