### ISSUE TITLE
Use "real world" librairies for benchmarks

### ISSUE THREAD

**Issue by Mogztter** [opal/opal#1552]
The current benchmarks do a good job but I think it would be nice to add "real world" librairies.
One big advantage is that we will benchmark much more cases however it will be harder to find the root cause of a performance regression. This is why it's important to have both.

I think [Asciidoctor](https://github.com/asciidoctor/asciidoctor) can be a good candidate for three reasons:
- the library is optimized to run as fast as possible (in Ruby)
- it's easy to measure performance (ie. convert the same AsciiDoc document to HTML)
- no runtime dependencies

You can take a look at this [file](https://github.com/asciidoctor/asciidoctor/blob/master/benchmark/benchmark.rb) to see an Asciidoctor benchmark.

Of course, I will gladly help you setting this up :smile:

**Comment by elia** [comment]
I like very much the idea of this kind of check and would be great to have it as part of the CI build. Alas I don't know of any service that will store historical data for performance checks… maybe the Travis cache can be used to that effect but seems a bit of a hack and not straightforward.

@Mogztter you do that check manually for asciidoctor?

**Comment by Mogztter** [comment]
> I like very much the idea of this kind of check and would be great to have it as part of the CI build. Alas I don't know of any service that will store historical data for performance checks… maybe the Travis cache can be used to that effect but seems a bit of a hack and not straightforward.

Indeed this is not straightforward and as far I as know it's not recommend to do performance testing on Travis: https://github.com/travis-ci/travis-ci/issues/352#issuecomment-11371473

> The general issue here is that we just can't guarantee that builds are run on equally powerful VMs. We might switch to bigger boxes at any time, run on a cloud provider or just have two slightly different boxes hooked up.

> @Mogztter you do that check manually for asciidoctor?

Yes when a new version comes out, I run the same benchmark script on Asciidoctor.js with Opal X and Asciidoctor.js with Opal X+1.
Maybe we could use a cheap server (Amazon EC2, Digitalocean) to run benchmarks and store results ?

**Comment by hmdne** [comment]
This is implemented by #2276, we can later think about a service that will graph this over time.
