### ISSUE TITLE
Block mistakenly gets assigned to method argument

### ISSUE THREAD

**Issue by jgaskins** [opal/opal#1553]
Consider the following code:

```
class NoBlock
  def initialize(&block)
    puts self if block
  end
end

class HasBlock
  def initialize(arg, &block)
    puts self if block
  end
end

HasBlock.new(NoBlock.new) { 'whatever' }
```

The block should be associated with the `HasBlock` object, but it prints `#<NoBlock:0x6fe>`. The same thing happens whether I use `{}` or `do` / `end` blocks.

[Try link](http://opalrb.org/try/?code:class%20NoBlock%0A%20%20def%20initialize(%26block)%0A%20%20%20%20puts%20self%20if%20block%0A%20%20end%0Aend%0A%0Aclass%20HasBlock%0A%20%20def%20initialize(arg%2C%20%26block)%0A%20%20%20%20puts%20self%20if%20block%0A%20%20end%0Aend%0A%0AHasBlock.new(NoBlock.new)%20%7B%20'whatever'%20%7D%0A%0A) — also verified on latest `master` branch.

**Comment by iliabylich** [comment]
Looks like a duplicate of https://github.com/opal/opal/issues/1499

**Comment by jgaskins** [comment]
Ah, indeed it is.
