### ISSUE TITLE
compatibility with rails 5.0.0.1

### ISSUE THREAD

**Issue by MichaelSp** [opal/opal#1555]
```
DEPRECATION WARNING: Sprockets method `register_engine` is deprecated.
Please register a mime type using `register_mime_type` then
use `register_compressor` or `register_transformer`.
https://github.com/rails/sprockets/blob/master/guides/extending_sprockets.md#supporting-all-versions-of-sprockets-in-processors
 (called from <top (required)> at /home/michael/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/opal-0.10.1/lib/opal/sprockets/processor.rb:144)
```

Versions:
opal (0.10.1)
sprockets (3.7.0)
sprockets-rails (2.3.3)

**Comment by jgaskins** [comment]
The short-term hack to silence the warnings is to restrict the sprockets version to `'~> 3.6.0'` in your app until Opal can be updated to use the new Sprockets methods.

**Comment by elia** [comment]
Working on this btw :)

**Comment by elia** [comment]
Fixed with https://github.com/opal/opal/commit/247ad9ec5e59c2c12aabbb92de0f8c464386d07e, will do a release later today, after that I'll close this issue :)

**Comment by elia** [comment]
Done: https://twitter.com/opalrb/status/774364733151580160
