### ISSUE TITLE
KLIPSE plugin uses Opal to evaluate ruby code in any webpage

### ISSUE THREAD

**Issue by viebel** [opal/opal#1562]
The [KLIPSE plugin](https://github.com/viebel/klipse) uses Opal to evaluate ruby code in any webpage
Take a look here: 

- http://blog.klipse.tech/ruby/2016/06/20/blog-ruby.html
- http://blog.klipse.tech/lambda/2016/08/13/almost-y-combinator-ruby.html

Disclaimer: I'm the author of KLIPSE

I just wanted to thank your for Opal: it's amazing.

**Comment by elia** [comment]
😄💛
