### ISSUE TITLE
UserDef type cannot be demarshaled yet

### ISSUE THREAD

**Issue by zetachang** [opal/opal#1579]
Is this possible to be implemented in Opal ? I am trying to marshal object which needs custom allocation when demarshaling.

**Comment by iliabylich** [comment]
@zetachang Which version of Opal are you using? I'm not 100% sure but it seems that master has support for UserDef (https://github.com/opal/opal/blob/master/opal/corelib/marshal/write_buffer.rb#L194)
And could please you provide some simplified example that shows the prolem?

**Comment by iliabylich** [comment]
aha, finally got it. `DEmarshalled` - that comes from [this](https://github.com/opal/opal/blob/master/opal/corelib/marshal/read_buffer.rb#L64) place

**Comment by iliabylich** [comment]
sorry, accidently closed it. Yes, of course it can be implemented, please, check an opposite implemetation of `WriteBuffer` - it has everything that you may need. Opal can marshal it, it can't unmarshal it back :smile:

**Comment by zetachang** [comment]
Just FYI, what I am trying to do is marshaling a method..

```ruby
class Method
  def _dump level
    Marshal.dump([receiver, name])
  end

  def self._load args
    receiver, name = Marshal.load(args)
    receiver.method(name)
  end
end

class Foo
  def initialize
    @name = "David"
  end

  def greeting
    puts "Hello #@name"
  end
end

m  = Foo.new.method(:greeting)

d = Marshal.dump(m)

Marshal.load(d).call # => Hello David
```

**Comment by iliabylich** [comment]
Yes, it should work after implementing read_userdef [here](https://github.com/opal/opal/blob/master/opal/corelib/marshal/read_buffer.rb#L64). It will be very similar to the way [how Opal writes user defined marshalled object](https://github.com/opal/opal/blob/master/opal/corelib/marshal/write_buffer.rb#L356-L367).

May I ask you why do you need to dump a method :smile: ? Your implementation doesn't dump method body. Are you using it to send some "commands" over http?

btw, I believe this is the first usage of Opal's `Marshal` library, so something can be broken :smile:

**Comment by zetachang** [comment]
Yeah, this is useful for **prerender** an UI component on server side, those method are considered as callback attached on the rendered component. As Proc might capture local variable from outer scope (which is hard/impossible to serialize), so `Method` is used instead.

**Comment by hmdne** [comment]
It works in 1.1 :)
