### ISSUE TITLE
autoload lookup differs from MRI

### ISSUE THREAD

**Issue by patrickkettner** [opal/opal#1581]
A gem I am using has a custom module called `Array`, which is an extension of another class called `Generator`.
When compiled with Opal, anything that extends the custom `Array` is broken because the builtin `Array` is always returned from `Opal.get`, even when the full namespace is given (e.g. `Opal.get('Foo').$$scope.get('Bar').$$scope.get('Generator').$$scope.get('Array')`). 

The `$$parent` is `Enumerable`, rather than the expected `Generator`.

**Comment by elia** [comment]
This code:

```rb
module Generator
end

module Foo
  module Bar
    class Array < Generator
    end
  end
end
p ::Foo::Bar::Array.JS['$$parent'].JS['$$name']
```

returns `Generator` on both master and v0.10.3, can you provide an example demonstrating the :bug:?

**Comment by patrickkettner** [comment]
apologises, haven't been able to create a trimmed down repro.

I believe the issue is because they are in separate files, so they stubbing process is different. But thats a very poorly informed hunch. I'll try to get a repro quickly

**Comment by patrickkettner** [comment]
I still haven't been able to create a reduced test case because of my lack of ruby knowledge, however I did [create a gist](https://gist.github.com/patrickkettner/1c102194d978d6c2a940ce49f4b3d883) that shows how to reproduce this in the hope that someone might be able to figure out the root cause. Full steps are included within

**Comment by elia** [comment]
@patrickkettner the gist was perfect! here's the reduced test case:

https://gist.github.com/elia/ad02a7713706f6ba9fc7dd41a736d456

main.rb
```rb
module Foo
  autoload :Array, 'foo'
end

puts Foo::Array.superclass
```

foo.rb
```rb
class Bar
end
module Foo
  class Array < Bar
  end
end
```

and here's the output from ruby and opal:

```
⤑ ruby -I. main.rb
Bar
⤑ opal -I. main.rb
Object
```

which means that the problem is with autoload/const_missing accepting `::Array` instead of `Foo::Array`

**Comment by elia** [comment]
Now working correctly since v1
