### ISSUE TITLE
An error occurred while compiling: (eval)↵Unsupported use of `def`

### ISSUE THREAD

**Issue by illogikal** [opal/opal#1590]
I want to dynamically define some instance methods on a class like below and I got the error in the title. If someone wants to reproduce and can't with this information, I'll provide more specific information. Opal version 0.9.4. I am using this in the context of a hyper react component class.

http://apidock.com/ruby/Module/included
```
class FooClass
  include ClassModule
end
module ClassModule
  def ClassModule.included(mod)
    mod.define_method(:bar) do
      :baz
    end
  end
end
```

**Comment by elia** [comment]
@illogikal I saw it's working on both `v0.10.3` and `master` (see below for the code I used), so I'm closing this as it's probably non-trivial to backport the fix to the `0-9-stable` branch.

Best thing would be for reactrb/hyperloop to upgrade/support to 0.10 if they didn't already, cc @catmando
