### ISSUE TITLE
regexs with interpolated values lose their flags

### ISSUE THREAD

**Issue by patrickkettner** [opal/opal#1596]
```rb
a = //
b = /#{a}/i
puts b.casefold?
```

this returns true in MRI, and nil in Opal. Looking at the compiled source shows that the flags are not added on compiled regexs

```js
a = /(?:)/;
b = (new RegExp("" + a));
```

As a workaround, you can use the `Regexp` class, passing flags as a second value.

```rb
a = //
b = Regexp.new("#{a}", Regexp::IGNORECASE)
puts b.casefold?
```

**Comment by mojavelinux** [comment]
As far as I can tell, this works in master. It does not work on 0.10.3.

**Comment by elia** [comment]
@mojavelinux thanks for noticing

```
opal:master ⤑ be bin/opal -ve "puts (/#{ // }/i).casefold?"                                     ~/C/opal
Opal v0.11.0.dev
true
```
