### ISSUE TITLE
splitting a string with a regex group and limit returns non compatible result

### ISSUE THREAD

**Issue by patrickkettner** [opal/opal#1599]
In every ruby engine I have been able to test in (except mruby, which doesn't allow for regex splits)
```rb
'aBa'.split(/(B)/, 2)
=> ["a", "B", "a"]
```

in Opal
```js
'aBa'.$split(/(B)/, 2)
=> ["a", "B"]
```

Which is consistent with javascript, but not ruby. Considering that the `2` is supposed to represent `"at most [the] number of fields [to] be returned"`, I am not sure why ruby is giving three. There does not seem to be any ruby spec covering this behavior, so I am trying to read through the C to figure out what the logic is.

**Comment by patrickkettner** [comment]
still haven't deciphered the C, however from trial and error it seems that any groups includes as a result of regex groups do not count towards supplied limit. If that is the case, than the limit supplied and used [here](https://github.com/opal/opal/blob/4cb3aed3d8af39b686dcc971619229d56468973e/opal/corelib/string.rb#L1012-L1022) should be incremented for each matched group that is inserted. All I see is edge cases with trying to figure out those groups, however :[

**Comment by eregon** [comment]
Actually the doc mentions a bit about this behavior, which I find surprising as well:
http://ruby-doc.org/core-2.4.1/String.html#method-i-split
```
If pattern is a Regexp, str is divided where the pattern
matches. Whenever the pattern matches a zero-length string, str is
split into individual characters. If pattern contains groups, the
respective matches will be returned in the array as well.
```

which leads to funny cases like:
```ruby
'aBa'.split(/(B)()()/, 2)
=> ["a", "B", "", "", "a"]
```

**Comment by hmdne** [comment]
In the current master, the behavior changed slightly from what was reported back then, but it's still incorrect.

```ruby
>> 'aBa'.split(/(B)/, 2)
=> ["a", "a"]
>> 'aBaBa'.split(/(B)/, 2)
=> ["a", "aBa"]
>>
```
