### ISSUE TITLE
`Uncaught Error: unexpected return` for singleton method in instance method

### ISSUE THREAD

**Issue by AlexWayfer** [opal/opal#1604]
Hello!

`define_singleton_method` in top-level works good.

But `return` in `define_singleton_method`, defined in other instance method, doesn't.

[Here is my snippet](https://gist.github.com/AlexWayfer/c175f338b5c3812f0d7222b2ffcfa417).

Opal version is `0.10.2`.

Thanks.

**Comment by elia** [comment]
Confirmed on master as well

**Comment by hmdne** [comment]
Related to #260? Should some methods work in similar fashion?

**Comment by hmdne** [comment]
Ah, it got fixed by #2357 :)
