### ISSUE TITLE
Owner of a class method is not the singleton class

### ISSUE THREAD

**Issue by zetachang** [opal/opal#1617]
```ruby
class Foo
  def self.bar; end
end

puts Foo.method(:bar).owner == Foo.singleton_class
```

In MRI (2.3.3) , it outputs `true`, while testing against opal-master and opal-0.10.3, it outputs `false`.

**Comment by elia** [comment]
Should be fixed by https://github.com/opal/opal/commit/2f6cd21907120393b90e6021c21ed24fc097ccfd

**Comment by zetachang** [comment]
Thanks! It works fine now.
