### ISSUE TITLE
Invalid regular expression in PathReader.expand

### ISSUE THREAD

**Issue by Mogztter** [opal/opal#1630]
### Stack trace
`SyntaxError: Invalid regular expression: /\A\.?\.\/: \ at end of pattern`

### Code

```ruby
    def expand(path)
      if Pathname.new(path).absolute? || path =~ %r{\A\.?\.#{File::SEPARATOR}}
        path
      else
        file_finder.find(path)
      end
    end
```
https://github.com/opal/opal/blob/d2883ad0de65461d6f17e1cf233e9a59b2b1e545/lib/opal/path_reader.rb#L16

### JavaScript

The generated code is:
```javascript
new RegExp("\\A\\.?\\.\\");
```

### Fix

When running Node.js on Windows `File.SEPARATOR` is equals to `\\` ([nodejs/file.rb#L49](https://github.com/opal/opal/blob/d2883ad0de65461d6f17e1cf233e9a59b2b1e545/stdlib/nodejs/file.rb#L49)).
I think we need to escape the double backslashes since we are using the RegExp constructor: `new RegExp("\\A\\.?\\.\\\\");`

**Comment by Mogztter** [comment]
Not sure how to fix this issue.
As far as I understand, we are creating a RegexpNode in [literal.rb#L120](https://github.com/opal/opal/blob/d2883ad0de65461d6f17e1cf233e9a59b2b1e545/lib/opal/nodes/literal.rb#L120):

```
(dstr
  (str "\\A\\.?\\.")
  (begin
    (const
      (const nil :File) :SEPARATOR)))
```
At this point we know that we are in a Regexp and that we need to escape `File.SEPARATOR` but I don't think I can or should evaluate this expression `(const nil :File) :SEPARATOR`.

Any idea ?

**Comment by elia** [comment]
@Mogztter in the meanwhile I pushed this: 2b01d36

Let me know if it does any good.

**Comment by Mogztter** [comment]
@elia Thanks, I will try but there is little hope since the regexp still contains `File::SEPARATOR`

**Comment by Mogztter** [comment]
@elia I could wrap everything that's not a `str` inside a function to escape backslash ? The downside is that this operation si done at runtime (and not a "compile" time). Do you have another idea ?
Also I didn't find where in the code the `\.` is escaped to `\\.` ?

**Comment by Mogztter** [comment]
Here's a simple Ruby file to reproduce this issue:

```ruby
FILE_SEPARATOR = '\\'
RELATIVE_PATH_REGEXP = %r{^\.?\.#{FILE_SEPARATOR}}

path = '/home/guillaume/foo.adoc'
puts 'relative path' if path =~ RELATIVE_PATH_REGEXP
```

```
$ bundle exec opal hello.rb 
/tmp/opal-nodejs-runner-20170213-6598-1r42u75:20199
  Opal.cdecl($scope, 'RELATIVE_PATH_REGEXP', new RegExp("" + "^\\.?\\." + (Opa
                                             ^
SyntaxError: Invalid regular expression: /^\.?\.\/: \ at end of pattern
    at new RegExp (native)
    at /tmp/opal-nodejs-runner-20170213-6598-1r42u75:20199:46
    at Object.<anonymous> (/tmp/opal-nodejs-runner-20170213-6598-1r42u75:20206:3)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

**Comment by elia** [comment]
> Here's a simple Ruby file to reproduce this issue:

That's very useful, thanks

**Comment by elia** [comment]
@Mogztter somthing's wrong, MRI complains too:

```rb
FILE_SEPARATOR = '\\'
RELATIVE_PATH_REGEXP = %r{^\.?\.#{FILE_SEPARATOR}}
```

```
opal:master ⤑ pbpaste | ruby
-:2:in `<main>': too short escape sequence (ArgumentError)
```

**Comment by Mogztter** [comment]
What is `pbpaste` ?
So what you are saying is that we should use an escaped version of `File.SEPARATOR` in RegExp block (`%r{}`) ?

> To match them literally they must be backslash-escaped. To match a backslash literally backslash-escape that: \\\.

https://ruby-doc.org/core-2.2.0/Regexp.html

I thought that "metacharacters" were automatically escaped :)

**Comment by elia** [comment]
> What is pbpaste ?

It's an [OSX command line utility](https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man1/pbpaste.1.html) to paste from the clipboard (aka **p**aste**b**oard)

> I thought that "metacharacters" were automatically escaped :)

Me too, but if MRI has the same problem I'm kinda ok with having it in Opal too.

**Comment by meh** [comment]
>Me too, but if MRI has the same problem I'm kinda ok with having it in Opal too.

Yeah, bug for bug 🐼
