### ISSUE TITLE
__LINE__ is not correct if an \n occurs in sourcecode

### ISSUE THREAD

**Issue by bwl21** [opal/opal#1631]
Running 

```ruby
puts %Q{#{__LINE__} should be 1}
a=%Q{\n\n\n}
puts %Q{#{__LINE__} should be 3}
````
yields 

```
1 should be 1
6 should be 3
```

It appears that the \n in the string also increases __LINE__

can be reproduced by this link:

http://opalrb.org/try/?code:puts%20%25Q%7B%23%7B__LINE__%7D%20should%20be%201%7D%0Aa%3D%25Q%7B%5Cn%5Cn%5Cn%7D%0Aputs%20%25Q%7B%23%7B__LINE__%7D%20should%20be%203%7D%0A

**Comment by elia** [comment]
@bwl21 it's fixed on master, hopefully I'll release 0.11 soon 😄 

```
opal:master ⤑ pbpaste | be bin/opal -A
1 should be 1
3 should be 3
```

cc @opal/core
