### ISSUE TITLE
Kernel#=== is called on Numeric comparison (switch/case)

### ISSUE THREAD

**Issue by Mogztter** [opal/opal#1639]
Follow-up: https://github.com/opal/opal/pull/1628

#### How to reproduce

.numeric-switch.rb
```ruby
value = 12

case value 
when 80 then
  p 'Hello!'
else
  p 'Bonjour!'
end
```

Edit `opal/corelib/kernel.rb`

```diff
   def ===(other)
+    p 'Kernel#=== is called'
     self.object_id == other.object_id || self == other
   end
```

Run!

```
bundle exec opal -- numeric-switch.rb 
```
```
"Kernel#=== is called"
"Bonjour!"
```

**Comment by meh** [comment]
What's the MRI behavior?

**Comment by Mogztter** [comment]
@meh that's a good question and I have no idea :laughing:

**Comment by Mogztter** [comment]
@meh Do you have a procedure to test ?

**Comment by iliabylich** [comment]
@Mogztter 
``` ruby
class Fixnum
  $m = instance_method(:===)

  def ===(other)
    puts "called #{self}.===(#{other})"
    $m.bind(self).call(other)
  end
end

case 1
when 2
  puts '2'
when 1
  puts '1'
end
```

``` sh
$ ruby -v
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]
$ ruby test.rb   
called 2.===(1)
called 1.===(1)
1
```

Looks like it's not an issue

**Comment by iliabylich** [comment]
@Mogztter Theoretically you can write something like
``` ruby
class Fixnum
  $m = instance_method(:===)

  def ===(other)
    $m.bind(self).call(other + 1)
  end
end

case 1
when 2
  puts '1 === 2'
when 1
  puts '1 === 1'
end
```

``` sh
$ ruby test.rb
1 === 2
```

:disappointed:

**Comment by Mogztter** [comment]
> Looks like it's not an issue

I must be missing something but `Fixnum` is a "numeric" ? Maybe we should provide a specific implementation on `Numeric#===` no ?

If we define a `===` method in `Numeric`, `Kernel#===` should not be called right ?

**Comment by meh** [comment]
The `Numeric` business is pretty weird, and we don't have `Fixnum` we have `Number`, and `Number` is a bridged class with a different superclass (`Numeric`) so it may be some funky interaction with that.
