### ISSUE TITLE
ALT_SEPARATOR should be the platform specific alternative separator

### ISSUE THREAD

**Issue by Mogztter** [opal/opal#1643]
On Node.js, I think `ALT_SEPARATOR` should be set to `__path__.sep`: https://github.com/opal/opal/blob/47c2e60d9ec02d5c8fdaf2feee1308772a145e84/stdlib/nodejs/file.rb#L48

It's unclear if `SEPARATOR` should stay `/` or not... I think this is what Ruby C is doing in [file.c]( https://github.com/ruby/ruby/blob/trunk/file.c#L6026) but I don't read C fluently :wink:

**Comment by elia** [comment]
@Mogztter you're right, the CRuby code stores `\` inside ALT_SEPARATOR. A fix is incoming 😄.

**Comment by Mogztter** [comment]
Thanks @elia !
