### ISSUE TITLE
Passing a symbol proc to an enumerable method instead of a block is considerably slower

### ISSUE THREAD

**Issue by mojavelinux** [opal/opal#1659]
Passing a symbol proc to an iteration method of an enumerable is considerable slower than passing a block.

Consider the following case:

```ruby
lines.map {|line| line.strip }
```

If we rewrite this as:

```ruby
lines.map(&:strip)
```

The code takes almost twice as long to execute when running in Opal. (whereas MRI executes it slightly faster).

I would expect for Opal to produce the same JavaScript in both cases, effectively expanding the symbol proc to long form. Instead, it does the resolution of the proc from the symbol at runtime.

**Comment by mojavelinux** [comment]
I tested this against master.

**Comment by mojavelinux** [comment]
@Mogztter this seems like it would be relatively easy to fix, esp for the map method where this is idiom is used most frequently (almost exclusively).

**Comment by mojavelinux** [comment]
I created the following benchmark scenarios:

bm_map_block.rb

```ruby
a = []
  
50.times do |i|
  a << %(#{i}\n)
end

1000.times do
  a.map {|it| it.chomp }
end
```

bm_map_symbol.rb

```ruby
a = []
  
50.times do |i|
  a << %(#{i}\n)
end
  
1000.times do
  a.map(&:chomp)
end
```

Here are the results on MRI:

```
benchmark/bm_map_block.rb  0.009013066010084003
benchmark/bm_map_symbol.rb 0.00871041399659589
```

Here are the results on Opal:

```
benchmark/bm_map_block.rb  0.09892900000000004
benchmark/bm_map_symbol.rb 0.2045030000000001
```

**Comment by elia** [comment]
> Instead, it does the resolution of the proc from the symbol at runtime.

I'm not sure how it can be done at compile time since apparently the generated proc must be able accept any number of arguments plus the block. I think MRI skips the proc altogether when a symbol is passed and `#to_proc` is not overridden, but I didn't check the source.

Anyway I moved part of the `Symbol#to_proc` implementation to raw JS and got an improvement from x2.58 to x1.41 which at least is something 😄  (see 6ce0619e0e1acdb2ba8ca406263bd8a2a329a91f)

**Comment by elia** [comment]
PS. In case anyone want push the optimization a little further, this is the command that would run the IPS benchmark attached with the commit: `bundle exec rake bench:ips FILE=benchmark-ips/bm_symbol_to_proc.rb`

**Comment by mojavelinux** [comment]
First, nice work!

Okay, so I thought it was just a matter of overriding map with native code, but now I understand that the proc is created earlier than that. Hmm. If it's possible, what I'm suggesting is checking for the pattern `.map(&:name)` in the parser and transform it. But perhaps that's really complicated. It just seems like it should be possible since `.map(&:name)` is just shorthand for `.map {|it| it.name }`. (I think it's reasonable to assume that to_proc on symbol wouldn't be monkeypatched...just seems like it's asking for trouble).

**Comment by mojavelinux** [comment]
Here are the numbers from my benchmark with this patch applied:

```
benchmark/bm_map_block.rb  0.0968469999999999
benchmark/bm_map_symbol.rb 0.12559200000000004
```

So the symbol version is 1.3x the block version in my tests. That's much more reasonable.
