### ISSUE TITLE
Implement File.write method

### ISSUE THREAD

**Issue by Mogztter** [opal/opal#1663]
Implement the static write method on File. Create an alias of this method on IO as well.

The write method provides a shorthand for the following.
```ruby
File.open('target', 'w') {|f| f.write content }
```

```ruby
File.write 'target', content
```

Reference: http://ruby-doc.org/core-2.0.0/IO.html#method-c-write

**Comment by mojavelinux** [comment]
It appears this is already implemented.

https://github.com/opal/opal/blob/master/opal/corelib/io.rb

That means we just have some outdated code in Asciidoctor.js. It's probably a good time to start dropping IO-related methods in Asciidoctor.js to see what isn't implemented. We don't have a clear picture right now.

**Comment by Mogztter** [comment]
https://github.com/opal/opal/blob/aabc78a24ab911493e99c87ac23b379a2b86e197/opal/corelib/io.rb#L16-L19

`IO#write` is implemented not not `IO::write` (static). I might be wrong but the method does not have the `self` keyword and does not support a file name (first argument).

https://ruby-doc.org/core-2.1.2/IO.html#method-i-write

**Comment by mojavelinux** [comment]
Oops! You are absolutely right. It tricked me ;)

In that case, we should also pull in the read method from Asciidoctor.js. We have a split IO personality right now ;)

See https://github.com/asciidoctor/asciidoctor.js/blob/master/lib/asciidoctor/js/opal_ext/file.rb#L144-L150

**Comment by Mogztter** [comment]
I don't think we can implement this method in a browser environment and it's already implemented in Node.js: https://github.com/opal/opal/blob/aabc78a24ab911493e99c87ac23b379a2b86e197/stdlib/nodejs/file.rb#L55-L58

So, the following code should work:
```ruby
File.write 'target', content
```

**Comment by mojavelinux** [comment]
That's excellent. I think we should also map IO.write / read in that file since they are basically just aliases. As far as I understand, the method is actually on IO in Ruby MRI.

**Comment by mojavelinux** [comment]
Nice!
