### ISSUE TITLE
Inheriting from Native::Object changes scoping of constants

### ISSUE THREAD

**Issue by fkchang** [opal/opal#1670]
Inheriting from Native::Object requires one to define top level scope

```ruby
require 'native'
class Foo < Native::Object
  def print
    Kernel.puts "printing"
  end
end

Foo.new.print
```
results in 
```
$ opal --version
Opal v0.11.0.rc1
$ opal src/scope_test.rb

/private/var/folders/ry/9tb5pfdd5xz1r0k_jjy_crmc0000gq/T/opal-nodejs-runner-20170528-82555-1kqgoha:4985
      throw exception;
      ^
Kernel: uninitialized constant Foo::Kernel
```
It is fixed by fully qualifying ::Kernal
```ruby
require 'native'
class Foo < Native::Object
  def print
    ::Kernel.puts "printing"
  end
end

Foo.new.print


```
Not inheriting, or inheriting from a plain class works as expected
```ruby
require 'native'
class Foo
  def print
    Kernel.puts "printing"
  end
end

Foo.new.print

```
prints out printing

**Comment by iliabylich** [comment]
@fkchang This behavior is expected, `Native::Object` is inherited from `BasicObject` - https://github.com/opal/opal/blob/4a412695b2ad2ba835209f9b715e7074910a5bfb/stdlib/native.rb#L247

MRI resolves constants in a `BasicObject` subclass in the same way:
``` ruby
class A < BasicObject
  def initialize
    @a = Array.new
  end
end

A.new
# => NameError: uninitialized constant A::Array
```

@elia @meh Can we change `Native::Object` to inherit from `Object`?

**Comment by meh** [comment]
On Sun, May 28, 2017 at 08:42:58AM -0700, Ilya Bylich wrote:
> @elia @meh Can we change `Native::Object` to inherit from `Object`?

Nope, that's going to break everything, it must be a `BasicObject`.
