### ISSUE TITLE
Support a callback or ENV can inject some code into Opal.

### ISSUE THREAD

**Issue by zw963** [opal/opal#1677]
Try to describe with a example:

I have some project, which all use opal, because I use Opal not skilled, 
so I want to add some helper method to all Opal locally. (not add in every project).

e.g. I write following code into a file named `ext.rb`

```rb
# /dir1/dir2/ext.rb
class Object
  def local_methods
    self.class.instance_methods -
      Enumerable.instance_methods -
      Object.instance_methods -
      Kernel.instance_methods -
      BasicObject.instance_methods
  end
end
```

If use normal Ruby, it so easy to inject this logic to every ruby instance with:

```sh
export RUBYLIB=$RUBYLIB:/dir1/dir2
export RUBYOPT=-rext
```

Just it.

I could add a directory into Opal.load_path with:

```rb
Opal.append_path('/dir1/dir2')
```

But, I still have to ``require 'ext'`` in my all project to enable this
hack, Is there exist a idea add `ext.rb` into all project like `RUBYOPT`?

So, I think I should add create a issue for this.

Thanks

**Comment by elia** [comment]
@zw963 we don't plan to add something like `RUBYOPT` for Opal, the correct way is to explicitly append the path and require the file. When used from the command line the `-I` and `-r` options are available, e.g. `opal -I/dir1/dir2 -rext myfile.rb`

**Comment by zw963** [comment]
thank，i think so too after  create this issue，we can append path in
Ruby，the only need is  just require a extend  file when  need  debug.

2017年6月13日 23:28，"Elia Schito" <notifications@github.com>写道：
