### ISSUE TITLE
Some example code (worked in 0.6.0) is not worked in opal 0.10.4

### ISSUE THREAD

**Issue by zw963** [opal/opal#1678]
I know this issue maybe not completely suite for asked here.

But, some codes which teach us to use opal, which should work well
in opal 0.6.0, current not worked with 0.10.4 

following link is original author blog link: [part1](https://www.sitepoint.com/opal-ruby-browser-basics/) [part2](https://www.sitepoint.com/opal-ruby-browser-game-life/)

here is my fork of blog codes, it should work, except a broken change from hash, which caused a dead 
loop. following is a snapshot.

![Screenshot_2017-06-12_12-00-31.png](http://zw963.github.io/images/158012333615835.png)

[this](https://github.com/RubySource/opal_article)  is original author github project, basically same as mine.  I just hack make it partially worked in opal 0.10.4.

**Comment by zw963** [comment]
after some debug, I found the error is raised in following method:

```rb
def is_alive?(x, y)
    state[[x, y]] == 1
  end
```

And, state is a struct like following: (Firefox console pp output)

```js
{[0, 0]=>0, [0, 1]=>0, [0, 2]=>0, [0, 3]=>0, [0, 4]=>0, [0, 5]=>0, [0, 6]=>0, [0, 7]=>0, [0, 8]=>0, [0, 9]=>0, [0, 10]=>0, [0, 11]=>0, [0, 12]=>0, [0, 13]=>0, [0, 14]=>0, [0, 15]=>0, [0, 16]=>0, [0, 17]=>0, [0, 18]=>0, [0, 19]=>0, [0, 20]=>0, [0, 21]=>0, [0, 22]=>0, [0, 23]=>0, [0, 24]=>0, [1, 0]=>0, [1, 1]=>0, [1, 2]=>0, [1, 3]=>0, [1, 4]=>0, [1, 5]=>0, [1, 6]=>0, [1, 7]=>0, [1, 8]=>0, [1, 9]=>0, [1, 10]=>0, [1, 11]=>0, [1, 12]=>0, [1, 13]=>0, [1, 14]=>0, [1, 15]=>0, [1, 16]=>0, [1, 17]=>0, [1, 18]=>0, [1, 19]=>0, [1, 20]=>0, [1, 21]=>0, [1, 22]=>0, [1, 23]=>0, [1, 24]=>0, [2, 0]=>0, [2, 1]=>0, [2, 2]=>0, [2, 3]=>0, [2, 4]=>0, [2, 5]=>0, [2, 6]=>0, [2, 7]=>0, [2, 8]=>0, [2, 9]=>0, [2, 10]=>0, [2, 11]=>0, [2, 12]=>0, [2, 13]=>0, [2, 14]=>0, [2, 15]=>0, [2, 16]=>0, [2, 17]=>0, [2, 18]=>0, [2, 19]=>0, [2, 20]=>0, [2, 21]=>0, [2, 22]=>0, [2, 23]=>0, [2, 24]=>0, [3, 0]=>0, [3, 1]=>0, [3, 2]=>0, [3, 3]=>0, [3, 4]=>0, [3, 5]=>0, [3, 6]=>0, [3, 7]=>0, [3, 8]=>0, [3, 9]=>0, [3, 10]=>0, [3, 11][…]
```

I have no idiea about why this code can cause issue ...

**Comment by CicholGricenchos** [comment]
https://github.com/RubySource/opal_article/blob/master/app/conway.rb#L65

The `is_underpopulated?` accepts 3 arguments but the method call inside `get_state_at` only gives 2.
Thus `y` is `undefined`, and `[0, undefined].$hash()` yields that error.

**Comment by iliabylich** [comment]
@zw963 You can enable arity checking (`-A` option for `opal` executable, `arity_check` option for `Opal::Compiler` - [source](https://github.com/opal/opal/blob/master/lib/opal/compiler.rb#L87)).

Consider the following code:
``` ruby
def m(a, b)
  %x{
    console.log("m invoked with a = ", a, "b = ", b);
  }
end

m
m(1)
m(2)
```

Without arity checking it prints
```
m invoked with a =  undefined b =  undefined
m invoked with a =  1 b =  undefined
m invoked with a =  2 b =  undefined
``` 

With arity checking it raises an error on the first call:
```
ArgumentError: [Object#m] wrong number of arguments(0 for 2)
```

It's recommended to enable arity checking in development environment.

**Comment by zw963** [comment]
@CicholGricenchos , thanks, worked!

missing source map in this project code, lead me to the wrong way ...

**Comment by zw963** [comment]
@iliabylich , Cool, added, thank you.

when refresh browser, exist following error message:4

```sh
ArgumentError: [Conway#is_underpopulated?] wrong number of arguments(2 for 3)
```
