### ISSUE TITLE
Don't touch Object.prototype

### ISSUE THREAD

**Issue by jods4** [opal/opal#1684]
Opal does modify some built-in objects.
For example it adds `$require` on `Object.prototype`.

That's a terrible idea that breaks all kind of things.
For example, it's impossible to load `nodegit` after Asciidoctor, which uses Opal.

>Sidenote: because `nodegit` uses `promisify-node`, which iterates exports to promisify everything, which finds `$require`, which then goes down the rabbit hole and eventually crashes on some objects.

Admittedly, `promisify-node` could be better and probably ignore non-own properties. 
But modifying `Object` is still a terrible idea and guaranteed to run into trouble with one library or another.

You should avoid it.
Installing your properties as non-enumerable would be a first layer of safety that hides them from `for..in`, which would at least avoid some crashes (including the one with `promisify-node`).

**Comment by iliabylich** [comment]
@jods4 Do you mean something like
``` js
Object.defineProperty(Array.prototype, '$flatten', {
  value: function() {
    return []
  },
  enumerable: false
})
```

I'm sure we can use it (since it's [widely supported](http://kangax.github.io/compat-table/es5/#test-Object.defineProperty)) if there's no difference in performance.

**Comment by meh** [comment]
@iliabylich the downside is it would increase code size and clarity by a lot.

**Comment by iliabylich** [comment]
@meh Not really, since we have `Opal.def`/`Opal.defn`. `Module#define_method/define_singleton_method` also uses it under the hood.

**Comment by iliabylich** [comment]
``` js
var Benchmark = require('benchmark');

Object.defineProperty(Object.prototype, 'throughDefineProperty', {
  value: function() {
    return null;
  },
  enumerable: false
});

Object.prototype.directlyOnPrototype = function() {
  return null;
};

var object = {};

var suite = new Benchmark.Suite;

suite.add('throughDefineProperty', function() {
  object.throughDefineProperty();
}).add('directlyOnPrototype', function() {
  object.directlyOnPrototype();
}).on('cycle', function(event) {
  console.log(String(event.target));
}).run({ 'async': true })
```

``` sh
$ node --version
v6.10.1
$ node test.js
throughDefineProperty x 108,281,919 ops/sec ±1.50% (81 runs sampled)
directlyOnPrototype x 112,527,379 ops/sec ±1.64% (84 runs sampled)
```

It seems that there's no difference, I'll try to fix it today. @elia @meh any comments?

**Comment by meh** [comment]
@iliabylich oh yeah, I forgot about that, go ahead, I have no issues with it.

**Comment by jods4** [comment]
I mean that, yes. It will help.

Ideally, you should not modify built-ins at all as that can have unintended side-effects on other libraries.
Any reason you have to?

**Comment by meh** [comment]
@jods4 there's no other performant way to add common methods to all objects.

**Comment by jods4** [comment]
> there's no other performant way to add common methods to all objects.

Yet everyone else seems to be able to do without?

If you need one base class for Ruby objects with some Ruby methods, you could add your base `Object` class that derives from the built-in one.

**Comment by meh** [comment]
>Yet everyone else seems to be able to do without?

Any examples of other transpiled languages that do without, and do not get a performance hit because of it?

There are high chances that they don't have anywhere near close semantics to Ruby while maintaining interoperability and performance.

Most of the Ruby core classes are actually the same exact object as the JavaScript one, but with added methods, you do not want to wrap every single thing because then you need some sort of FFI to translate from one to the other and that makes it harder to use.

A library breaking because they're going over all properties of an object with likely a `for in` loop is as bad as touching the prototypes of `Object` and friends, except we have a good reason for it.

**Comment by jods4** [comment]
> A library breaking because they're going over all properties of an object with likely a for in loop is as bad as touching the prototypes of Object and friends, except we have a good reason for it.

Sure, and I said so in my first post.

There are various compilers to JS (e.g. from Java or C#) but I am not into them enough to know if they all hack built-in prototypes.

You should still acknowledge that if everyone did so, (e.g. those other compilers), we simply could not mix and match code. There would be collisions, incompatible behaviors... doing `Object.seal()` on pretty much any built-in breaks Opal.

At the moment I worked around the issue by loading Asciidocs (great project, uses Opal) last, after every other library has been loaded.

**Comment by jods4** [comment]
BTW I have not understood why you couldn't do this:
```
class RubyObject {
  $require() { } // and co.
}
```
And then have every object be an instance of `RubyObject`?

Other built-ins are more tricky as `class RubyArray extends Array` only works in modern browsers.

**Comment by jods4** [comment]
> A library breaking because they're going over all properties of an object with likely a for in loop is as bad as touching the prototypes of Object and friends, except we have a good reason for it.

I just noticed... `promisify-node` has a good reason for doing a `for..in`, ah the irony 😄 
They want to automatically wrap callback apis in to promise apis and for that they need to look at every function, which are _typically_ in prototypes.

They have a bug, though, because they end up finding something they don't like in Opal and crash (a lambda probably) when they definitely should not. Hopefully they'll fix it.

"**We** have a good reason" is a rabbit hole 😟

**Comment by meh** [comment]
No, I understand, I know it sucks, but there's no other way without giving something up, that I know of at least.

Using wrappers for everything loses you performance and the fact you can call Opal methods on normal JavaScript objects, and that's a huge usability boon.

There were plans to only define methods inside a special object and add only that object to the prototypes, method tables something something, but it had its set of downsides and they weren't deemed worth it at the time.

This kind of thing happens, JavaScript sucks, two hacks explode with eachothers, life is hard 🐼

**Comment by jods4** [comment]
> Using wrappers for everything loses you performance

Adding a prototype in the chain should not affect performance noticeably.

> and the fact you can call Opal methods on normal JavaScript objects, and that's a huge usability boon.

That's usually regarded as a bad idea. For example Underscore doesn't add all its utilities to arrays (would be super helpful?); or consider the "ponyfills" rather than "polyfills" mentality.

Anyway, I can understand this is a complex change. I have a workaround so I'm fine, but that's something I wish could be different.

**Comment by meh** [comment]
>Adding a prototype in the chain should not affect performance noticeably.

Yeah but then you need to *box* and *unbox* the inner type when you want to talk with JavaScript APIs, which is often times a literal or an object literal, that's what takes performance away. And that is already a huge pain in the ass with the whole `#to_n` bullshit.

>That's usually regarded as a bad idea. For example Underscore doesn't add all its utilities to arrays (would be super helpful?); or consider the "ponyfills" rather than "polyfills" mentality.

And that is for JavaScript, but Ruby is not JavaScript, the whole idea behind Opal is to make life less painful by using Ruby in the browser instead of JavaScript.

While using `Object.defineProperty` is a fine bandaid, somehow managing to find a solution to keep everything while using wrapper objects would require huge changes to the runtime and to any core/noncore library depending on implementation details for performance reasons.

**Comment by jods4** [comment]
Object literals easily work:
```
let person = {
  __proto__: RubyObject.prototype,
  name: "John Doe",
  age: 42
};
```
But that would be a problem for numbers, Date or string indeed. :(

**Comment by elia** [comment]
> It seems that there's no difference, I'll try to fix it today. @elia @meh any comments?

@iliabylich fine by me too, I tried that in the past and there be dragons 🐉, there's a bunch of places relying on `for...in` that will force you to store the list of methods somewhere since the whole thing is making them non-enumerable. If you get there I suggest using a `$$methods` property that is actually useful down the line for the _correct_ implementation of `include/prepend`.

**Comment by elia** [comment]
_It's beyond the fair point of not touching native prototypes, but just wanted to clarify that Opal doesn't set any property on `Object.prototype`, instead the presence of `Object.$require` is due to the fact that adds methods to `Function.prototype` (that is bridged to `Proc`) since of course `typeof Object === 'function'`._

**Comment by mojavelinux** [comment]
I'm bumping into this too. If I require Opal (or something that uses it, like Asciidoctor.js) before nodegit, then nodegit fails to load. However, if I require nodegit first, then it works. I just thought I'd mention that workaround.

**Comment by Hoten** [comment]
I have run into package issues when using this + NewRelic's node runtime module. This error occurs when attempting to use the New Relic module:

```
{
  "component": "remote_method",
  "hostname": "ConnorClarkMacbookPro.local",
  "level": 50,
  "message": "this is not a Date object.",
  "msg": "Unable to serialize payload for method connect.",
  "name": "newrelic",
  "pid": 23920,
  "stack": "TypeError: this is not a Date object.\n    at Object.valueOf (<anonymous>)\n    at Object.[Symbol.toPrimitive] (<anonymous>)\n    at Object.toJSON (<anonymous>)\n    at JSON.stringify (<anonymous>)\n    at stringify (<root>/node_modules/json-stringify-safe/stringify.js:5:15)\n    at RemoteMethod.serialize (<root>/node_modules/newrelic/lib/collector/remote-method.js:43:15)\n    at RemoteMethod.call [as invoke] (<root>/node_modules/newrelic/lib/collector/remote-method.js:65:8)\n    at getEnvDict (<root>/node_modules/newrelic/lib/collector/api.js:167:25)\n    at factMapCb (<root>/node_modules/newrelic/lib/collector/facts.js:67:12)\n    at <root>/node_modules/async/dist/async.js:3874:9",
  "time": "2018-03-06T06:56:39.505Z",
  "v": 0
}
```

I have isolated it to this the opal package. I believe it's related to editing builtin objects (in this case, the Date), but the specifics beyond that are unclear.

The best course of action in my situation is to remove this dependency, but I wanted to share here to potentially help others.

**Comment by iliabylich** [comment]
Finally fixed in https://github.com/opal/opal/pull/1821. All props are not enumerable anymore, there's a test that validates it: https://github.com/opal/opal/blob/master/spec/opal/core/iterable_props_spec.rb, feel free to reopen it if there are still any issues.

**Comment by mojavelinux** [comment]
:tada: :tada: :tada: So much yes!
