### ISSUE TITLE
AkashaCMS becomes extremely slow when integrated with asciidoctor.js 

### ISSUE THREAD

**Issue by robogeek** [opal/opal#1689]
[Asciidoctor.js](https://github.com/asciidoctor/asciidoctor.js) is a project built using Opal.  I am integrating asciidoctor.js into [AkashaCMS](https://akashacms.com) to add Asciidoc capability (it currently supports Markdown).  

The integration is trivially simple but unfortunately it makes rendering a website with AkashaCMS an excruciatingly slow process.  Certain functions unrelated to anything asciidoctor.js become extremely slow, and the Mac OS X Activity Monitor shows a `node` process pegged at 95% or so CPU.

Details: https://github.com/asciidoctor/asciidoctor.js/issues/359

I was asked to report it here because it's likely an Opal problem.  Steps to reproduce the issue are in the issue at https://github.com/asciidoctor/asciidoctor.js/issues/359#issuecomment-317281179

**Comment by elia** [comment]
I'm closing this, looking at the original issue seems like it was an issue with cloning JS objects with recursive references and possibly with a `for…of` loop. Feel free to ping to reopen if something's come up that's directly relatable to an Opal issue. /cc @asciidoctor
