### ISSUE TITLE
accessing the DOM

### ISSUE THREAD

**Issue by log69** [opal/opal#1693]
Hi, I can't really find any documentation in Opal docs and on the net about how to access the DOM from Opal. Could you direct me to some info? Thanks.

**Comment by elia** [comment]
@log69 you have a couple options available:

With a library [using jQuery via `opal-jquery`](https://github.com/opal/opal-jquery#interacting-with-the-dom) or for a [more Ruby-esque experience with opal-browser](https://github.com/opal/opal-browser#dom).

Using vanilla DOM APIs in one of the several ways that are available for using JavaScript from Ruby (see the **JavaScript from Ruby** section in [this guide](http://opalrb.org/docs/guides/v0.10.5/compiled_ruby.html)).

I'll close the issue, but let me know if something's missing or can be improved in the docs or even better send a PR with the improvement! 😉

**Comment by log69** [comment]
Thanks.
