### ISSUE TITLE
Problem if inline javascript ends with a semicolon

### ISSUE THREAD

**Issue by bwl21** [opal/opal#1696]
I wanted to update to 0.11.rc1 and found a difference in the compilateion result:

```ruby
    abc          = `localStorage.setItem('abc_data', #{abc});`
  end
```

transpiles to (0.10.5)

```javascript
      return abc = localStorage.setItem('abc_data', abc);;
```
in 0.11.rc1 it compiles to

```javascript
      return (abc = localStorage.setItem('abc_data', abc););
```
Chrome complains the semicolon before the closing paranthesis as error.

Of course the trailing ';' ist not required. Nevertheless it is an issue which might break existing sources.

@elia considered this as a bug which needs to be fixed

**Comment by iliabylich** [comment]
@elia Why do you think that it should be fixed? I just feel that JS manipulation may introduce some weak rules that are good for some cases, but are bad for some other corner cases. Maybe I'm wrong, but I think that it's better to always return JS that was initially written in `xstr`, without any manipulations.

To be fair, I think that it's better to not touch `xstr` at all.

For example https://github.com/opal/opal/pull/1698 fixes it, but it introduces another issue:
``` ruby
def m
  %x{
    var a = 1;
    return a;}
end
```

becomes

``` js
Opal.defn(Opal.Object, '$m', TMP_m_1 = function $$m() {
  var self = this;
  var a = 1;
  return a
}, TMP_m_1.$$arity = 0)
```

(No trailing `;` after return)

Yes, we don't have such code in Opal corelib/stdlib, but developers that use Opal can write it. For me this corner case is as real as the one provided by @bwl21 

Introducing such xstr-rewrites makes Opal something similar to JS linter, I don't think that we should do it. For me one simple rule `we don't touch xstr-s` is enough.

**Comment by bwl21** [comment]
I agree that the xstr shall not be changed ore rewritten. In my case it was such that the xstr was embedded in a way that is no valid javascript. And it is a backwards compatibility issue because it worked in Opal 0.9.

Of course it is easy to find and to fix on the ruby side. So IMHO this issue can also be fixed by a proper note in the release notes. I agree, that a fix in the code might introduce more problems than it fixes.

The question is, do we have a rule how to write xstr such that it safely works in all cases?
In this case the rule for opal users might be: "do not terminate xstr with semicolon.

**Comment by iliabylich** [comment]
@bwl21 The rule is `do not terminate one-line xstr with semicolon`.

Also we do rewrite single-line xstr that is a last statement and doesn't have `return` inside like:
``` ruby
def m
  `0`
end
```

to `return 0` (it happens [here](https://github.com/opal/opal/blob/master/lib/opal/compiler.rb#L443))

**Comment by bwl21** [comment]
Mabe we should add " do not have an xstr as last statement in a ruby method.

**Comment by elia** [comment]
_sorry for the delay_

@bwl21 xstr are fine as last statement, so much that there's explicit support for adding return to xstr in last statement.

@iliabylich point is valid, yet the broken code is real, my proposal is to just send a warning if we end up in the `:js_return` branch and there's a semicolon in the xstr source, maybe the presence of a newline is another case where a warning is appropriate.

https://github.com/opal/opal/blob/a1a8c5d261be09a42636744cc0b96454453a0e8c/lib/opal/nodes/literal.rb#L228-L237

@CicholGricenchos you think you can add your PR with the warning?

**Comment by CicholGricenchos** [comment]
@elia 
I added warning to the PR.
```ruby
# warning: Xstr ends with semicolon
a = `1;`

# warning: Xstr ends with semicolon
def a
  `1;`
  1
end

# no warning
def a
  `0;`
end
```

Actually the warning is not yielded in `:js_return` branch, but in `:str` branch.

**Comment by bwl21** [comment]
I highly appreciate this solution. Thanks.

**Comment by elia** [comment]
fixed in https://github.com/opal/opal/pull/1776
