### ISSUE TITLE
JS Reflection

### ISSUE THREAD

**Issue by AndyObtiva** [opal/opal#1705]
JRuby lets you reflect on Java objects and instantiate/use in Ruby syntax. For example, you can type include_package 'org.eclipse.swt' and then start using GridLayout.new(2, false) in Ruby.

I realize Opal allows using the backtick operator to make JavaScript calls, but is there a way in Ruby syntax (no backtick) to reflect and invoke JS object functions and anonymous functions as blocks? For example, maybe something like JS.tinymce.init({}) where JS gives us access to the JavaScript global namespace.

Thanks.

**Comment by elia** [comment]
@AndyObtiva yes!

There are three main ways to interact with native objecs:

1. The aforementioned backtics

```rb
`tinymce.init({})`
```

2. Native wrappers

```rb
require 'native'
$$[:tinymce].init({}.to_n)
```

3. special `.JS` calls

```
require 'js'
JS.global.JS[:tinymce].JS.init(`{}`)
```

Learn more in the ["Compiled Ruby Code" guide](http://opalrb.com/docs/guides/v0.10.5/compiled_ruby.html) at the section "JavaScript from Ruby".

_I'm closing this, but let me know if you need anything else and I'll reopen right away_
