### ISSUE TITLE
Time.parse bug -  V8 vs Apple JSVirtualMachine 

### ISSUE THREAD

**Issue by fatal10110** [opal/opal#1714]
`Time.parse` compiled as `new Date(Date.parse(date))`

V8 (chrome)
```
Date.parse("2017-11-16T10:57:47+0200")
1510822667000
```

Apple JSVirtualMachine (safari)
```
Date.parse("2017-11-16T10:57:47+0200")
NaN
```

:(

**Comment by elia** [comment]
Just for reference, here's the line where `Time.parse` is implemented:

https://github.com/opal/opal/blob/29ee05354d848b442472a5dcb22f5af71d02a20f/stdlib/time.rb#L3

**Comment by Gaelan** [comment]
Looks like the ES standard states that there should be a colon in the time zone (`2017-11-16T10:57:47+02:00`). For `Date.parse`, browsers are required to support that format but allowed to support whatever else they want, so it looks like V8 is going above and beyond here and JavaScriptCore isn't.

**Comment by elia** [comment]
Thanks for looking into this @Gaelan! 👍 

I don't think we're replacing the use of `new Date()` with a custom implementation any time soon, I'll ascribe this to platform differences and track support through ruby/spec.
