### ISSUE TITLE
Opal: The Answer for a Crystal Isomorphic Solution

### ISSUE THREAD

**Issue by ylluminate** [opal/opal#1715]
Hey guys, given that a webasm Crystal is probably some time out, but that Crystal itself is really heating up with projects like Amber and Lucky, we probably should consider what could be done in Opal to answer the call for the need of isomorphic Crystal. For the moment I think that Opal is close enough to be able to be used directly as the answer for this call, but it might be worth thinking about how to make a more Crystal-like Opal subset or variant that would accept Crystal differences directly. It may not take that much extra work and could end up being simply a subset of Opal vs some beast that's altogether different...  Sure would be slick if both could be done in the same codebase.

With [the de-emphasis of Ruby coming to Hyperloop](https://github.com/ruby-hyperloop/ruby-hyperloop.io/issues/99) (used to be React.rb) and it's growing popularity, I think that this is a prime opportunity to take advantage of the excitement behind Crystal in the much needed marketing arena for Opal.

Even the Thoughtbot author of the Crystal Lucky Framework [has expressed sincere interest](https://github.com/ruby-hyperloop/ruby-hyperloop.io/issues/98) in Hyperloop mating up with it. I suspect Amber is also in the same boat.

**Comment by ylluminate** [comment]
So I didn't realize just how big Crystal was becoming at such an insanely fast rate until I started looking at [TOBE](https://www.tiobe.com/tiobe-index/) and the TIOBE archives closely.

Just to show you how exciting a fast Ruby is to everyone, Crystal has blown past Kotlin, Clojure, Hack, Julia, Erlang, Rust, Lua, D, Scala, and on and on in no time flat.

It's gone from not even being in the top 50 six months ago to position 24 this month of November. Last month it was at 28 and in September it was at 31. It finally popped out of position 60 in August to 32 with TIOBE saying this: 

> "_Especially Crystal with its jump from position 60 to 32 in one month is doing very well. The Crystal programming language is a statically typed Ruby variant. Since it is compiled it is superfast and has a small memory footprint without losing the feeling of being easy to use. It seems worthwhile to give it a try._"

**Comment by elia** [comment]
> but it might be worth thinking about how to make a more Crystal-like Opal subset or variant that would accept Crystal differences directly.

I think it would be better to go to straight crystal support, and reuse the compiler harness of Opal to start accepting `cr` files with their own runtime. Personally I can't do that but I'm more than open to give any attempt at this "official" support and help.

**Comment by ylluminate** [comment]
@elia @meh so just FYI, [from this thread](https://github.com/WebAssembly/binaryen/issues/1312), it seems that perhaps the Opal path is the more sane route for the time being until WASM matures. Just thought you'd want to review this to be aware of things, especially in context of the future of Opal and why it's really still quite valid even in the face of all this WASM excitement.

**Comment by elia** [comment]
@ylluminate thanks for looking more into this, I'll close both this issue and #956 for the time being. We'll surely reconsider wasm if something viable comes down the pike.
