### ISSUE TITLE
How to pass nested Hash object into compiled ruby function from js?

### ISSUE THREAD

**Issue by Oberonhive** [opal/opal#1719]
I compiled ruby method into static js. Then from JS I'm trying to pass some Hash object loaded from json into my ruby class. But I getting the error `TypeError: obj.$[]`. I guess Hash objects should be wrapped with `Opal.Hash.$new(obj)`, but its not applied to nested objects.

How to pass nested JS Hash object into compiled ruby method correctly?

**Comment by elia** [comment]
You need to `require 'native'` first and then you can proceed with `Hash.new`:

```
⤑ be opal -v -rnative -e'p Hash.new(`{a:{b:{c:1}}}`)'
{"a"=>{"b"=>{"c"=>1}}}
```
