### ISSUE TITLE
node_require does not work with bundlers like browserify

### ISSUE THREAD

**Issue by bwl21** [opal/opal#1720]
When I use opal builder to compile a JS file to be used with node, this file still requires node_modules to be around. I wanted to make a standalone file which could be copied around. I even tried to make an executable with `nexe`.

The problem is that browserify does rewrites the code by resolving `requires`. But `node_require` wraps the (javascript) `require` in a function specified by a ruby constant. So it cannot be recognized by browserify.

In order to solve the issue, i have the following statements in my application-cli.rb

```ruby
%x{
...
  // these requires are requred by nodejs/dir, nodejs/file
  fs = require('fs')
  glob = require("glob") 
}
```

Maybe it would make sense that the the opal/nodejs libs use x-string instead of node_require:

```
class Dir
  @__glob__ = node_require :glob
  @__fs__ = node_require :fs
...
```
to be rewritten as
```
  @__glob__ = %x{require('glob')}
  @__fs__ = %x{require('fs')}
```

**Comment by hmdne** [comment]
node_require has been deprecated

as of now it's only used in ./stdlib/nodejs/irb.rb but it's unused and we will revamp it later

**Comment by bwl21** [comment]
node_require was used in opal/nodejs at the time i opened the issue. Did you remove it there=

**Comment by hmdne** [comment]
It was removed by 1ede90e16a5eec515f45d30e6ca70ff690b4aa21 2 years ago
