### ISSUE TITLE
Implement OpenURI module

### ISSUE THREAD

**Issue by Mogztter** [opal/opal#1721]
As far as I understand, this module is part of the `stdlib` ?
https://ruby-doc.org/stdlib-2.1.0/libdoc/open-uri/rdoc/OpenURI.html

> It is possible to open an http, https or ftp URL as though it were a file:

I think we could just implement `http` and `https` with `XMLHttpRequest`.
In Asciidoctor.js we are considering using the Node module `xmlhttprequest` to read remote files synchronously: https://www.npmjs.com/package/xmlhttprequest

Currently the following code will throw an exception (when `nodejs` module is loaded):

```ruby
open("http://www.ruby-lang.org/") {|f|
  f.each_line {|line| p line}
}
```

The root cause is that `open` will instantiate a new `File` and, ss you can see below, we are using `openSync` which does not support URI.

https://github.com/opal/opal/blob/8a4f5a4cd1dedbb07bd81ad59a5e38a9b93519e2/stdlib/nodejs/file.rb#L169

So `open` function should create a special kind of `File` when the path starts with `http://` or `https://`.
With a few guidances on how to properly implement this feature, I will gladly send a pull request :wink:

**Comment by Mogztter** [comment]
Reference implementation: https://github.com/ruby/ruby/blob/trunk/lib/open-uri.rb

**Comment by Mogztter** [comment]
Since the reference implementation is in Ruby, I was thinking about doing the following:

1. Copy `open-uri.rb` to `opal/stdlib/open-uri.rb`
1. Remove `URI.FTP`
1. Implement `OpenURI.open_uri` using `XMLHttpRequest`
1. Create `opal/stdlib/nodejs/open-uri.rb` and implement `OpenURI.open_uri` using `xmlhttprequest` Node module

@elia Does it sound right to you ?

**Comment by elia** [comment]
@Mogztter the plan is sound, just one question, wouldn't it be better if you updated `open_loop` instead of `open_uri`?

**Comment by mojavelinux** [comment]
Perhaps a useful reference: https://github.com/publicclass/open-uri (open-uri for node inspired by Ruby's open-uri)

Though, truthfully, we really only need support for reading from http(s):// in Asciidoctor.js.

**Comment by mojavelinux** [comment]
> Implement OpenURI.open_uri using XMLHttpRequest

Why not the built-in http and https modules?

```js
const http = require('http')

const readUri = (uri) => {
  return new Promise((resolve, reject) => {
    http.get(uri, (res) => {
      let data = ''
      res.setEncoding('utf8')
      res.on('data', (chunk) => { data += chunk })
      res.on('end', () => { resolve(data) })
    })
  })
}

!(async function() {
  console.log(await readUri('http://example.com'))
})()
```

Of course, there's lots of stuff to handle like redirects and gzip, so probably best just to use the open-uri module (or copy from it).

**Comment by Mogztter** [comment]
> Why not the built-in http and https modules?

I thought it was not possible to use the built-in `http` and `https` modules to read a remote file synchronously.

@mojavelinux Does the following example will work ?

```ruby
def read(path)
  %{
    return !(async function() {
      await readUri(#{path});
    })();
  }
end
```

> the plan is sound, just one question, wouldn't it be better if you updated open_loop instead of open_uri?

You're right, I think it would be better to update `open_loop`

**Comment by Mogztter** [comment]
Making progress! :sunglasses: 

@elia When I execute `bundle exec rake minitest_cruby_nodejs`, the file `stdlib/nodejs.rb` is not loaded. As a consequence the specific implementation for Node.js (defined in `stdlib/nodejs/open-uri.rb` and required in `stdlib/nodejs.rb`) is not loaded. Is that intended ?

The full command is: 
```
ruby -rbundler/setup exe/opal -ghike -Itest -Ilib -Ivendored-minitest -Itest/cruby/test -soptparse -sio/console -stimeout -smutex_m -srubygems -stempfile -smonitor -Rnodejs -Dwarning -A --enable-source-location tmp/minitest_cruby_nodejs.rb
```

If I add an explicit `-rnodejs` in the command line, then the file is loaded.

**Comment by Mogztter** [comment]
> Does the following example will work ?

That's what I thought, the whole execution must be in an `async` block otherwise `await` is ignored.
I think our only choice is to fetch remote file synchronously and as far as I know Node.js does not provide built-in synchronous `http` and `https` modules :disappointed: 
@mojavelinux Am I missing something ?

**Comment by mojavelinux** [comment]
Yes, I forgot that the whole program has to be wrapped in an async function for the await keyword to work. Here's a working example:

```js
const http = require('http');

function get() {
  return new Promise((resolve) => {
    http.get({
      host: 'asciidoctor.org',
      path: '/docs/user-manual/'
    }, (res) => {
      let data = ''
      res.on('data', (chunk) => { data += chunk })
      res.on('end', () => resolve(data))
    })
  })
}

;(async function () {
  console.log('getting it')
  const html = await get()
  console.log('got it')
  console.log(html)
})()
```

We could say that this is a prerequisite for using this feature. Antora, for example, runs Asciidoctor.js in this context, so it would work.

The alternative is to use a sync http library. For native support, it seems XmlHttpRequest is the only way to go.

**Comment by mojavelinux** [comment]
I can confirm we can do it sync with XMLHttpRequest.

```js
const XMLHttpRequest = require('xmlhttprequest-ssl')

const url = 'http://asciidoctor.org/docs/user-manual/'
let data
const xhr = new XMLHttpRequest()
xhr.open('GET', url, false)
xhr.addEventListener('load', function () {
  if (this.readyState === 4) {
    data = this.responseText
  }
})
xhr.send()

console.log(data)
```

(There seems to be a bug in the library with status, which returns the whole body in the status field).

**Comment by Mogztter** [comment]
I think we can close this issue.
Initial support for OpenURI has been merged in https://github.com/opal/opal/pull/1735
