### ISSUE TITLE
Implement Matrix module

### ISSUE THREAD

**Issue by Mogztter** [opal/opal#1739]
http://ruby-doc.org/stdlib-2.0.0/libdoc/matrix/rdoc/Matrix.html

**Comment by iliabylich** [comment]
Did you have a chance to check if we can use MRI version of `Matrix`? From what I see in https://github.com/ruby/ruby/blob/trunk/lib/matrix.rb it's doable (and from the first glance doesn't require too much patching. Only `ExceptionForMatrix` and two `autoload` calls must be commented out, there are no `while/for/break` calls, only pure arrays and enumerators).

**Comment by Mogztter** [comment]
Not yet, I filled this issue when I was trying to compile [Prawn](https://github.com/prawnpdf/prawn) to JavaScript but didn't get the chance to work again on this task.
