### ISSUE TITLE
Problem if inline javascript in %x does not ends with a semicolon

### ISSUE THREAD

**Issue by yhara** [opal/opal#1742]
(related: #1696)
After upgrading to Opal 0.11.0, I found [this code](https://github.com/yhara/dxopal/blob/88a71f4534161e5e3d3fd68d139661cb27256623/opal/dxopal/image.rb#L251-L256) does not work as expected. 

Here is a shorter version:

```rb
def foo
  %x{
    console.log(1)
  }
end
foo
```

This opal program prints nothing because it is compiled to the following code,

```js
  Opal.defn(Opal.Object, '$foo', TMP_foo_1 = function $$foo() {
    var self = this;

    return
    console.log(1)

  }, TMP_foo_1.$$arity = 0);
```

and unfortunately, this is equivalent to this.

```
    return;
    console.log(1)
```

**Comment by yhara** [comment]
(FYI: in the [real example](https://github.com/yhara/dxopal/blob/88a71f4534161e5e3d3fd68d139661cb27256623/opal/dxopal/image.rb#L251-L256), I just forgot to write a semicolon, not intentional.)

**Comment by iliabylich** [comment]
Opal thinks that your x-string [is not multiline](https://github.com/opal/opal/blob/master/lib/opal/compiler.rb#L432) and injects a `return` for the first line (as it thinks that this is the only line)

**Comment by elia** [comment]
fixed in https://github.com/opal/opal/pull/1776
