### ISSUE TITLE
Feature Request - Implement DateTime from date_core.c --> ISO8601 DateTime is essential for Databases.

### ISSUE THREAD

**Issue by mistergibson** [opal/opal#1743]
Dear Developers:

I want to suggest that you port the DateTime kernel object from date_core.c ( found here: https://github.com/ruby/ruby/blob/b366c4d4104d9273d011f7daec343bdced8bde17/ext/date/date_core.c ) over to Opal core and ensure the Marshal::dump/load functions are exactly like regular Ruby with respect to this class. This way a much needed basic element can be serialized, passed, and reconstituted without additional 'shim' code.

I tried to do a Opal.eval("require 'date_core'"); but DateTime remains undefined. It is an essential part of all my Database code as it can span -999,999 to +999,999 years (**Ideal** for scientific and archival records) whereas if you attempt a date prior to 1970, Jan 1 - midnight with a Time object, you get jenky, or inaccurate, results - not reliable I have found. Time class simply won't suffice for the need. Date class is insufficient as it lacks time and time zone information. Only a real DateTime will do the job.

So ... purdy-please will you implement DateTime in Opal.core as a Kernel class, and ensure it serializes/reconstitutes properly?

Thank you for your attention to this issue.

**Comment by iliabylich** [comment]
Thank you for your request!

In JavaScript there's only one date/time/datetime class: `Date`. Both `Date` and `Time` classes in Opal are based on JS `Time`. If it's not reliable enough - then nothing can be reliable. Also there are no timezones support in Opal (again, because there are no TZs support in JS).

Could you please provide some examples where MRI's `Time` class doesn't work for you?

**Comment by mistergibson** [comment]
Sure:

Time.new("1865-07-28T09:00:00") => 1865-01-01 00:00:00 -0812

Notice it utterly flubs the month, day, and time? It just isn't designed to go back that far in time - which historical archives, and some scientific computing will absolutely require. The problem is with Time class - the world began on Midnight Jan. 1, 1970 ... So, If someone *could* port the C code to a ruby class or javascript function to support a true ISO8601 DateTime class - then the sky's the limit for what can be done with Opal.

**Comment by mistergibson** [comment]
If it is any help - I looked over the source code JRuby uses to implement DateTime class, and I think it might be helpful. They make some calls to Java for heavy lifting, and made me wonder if native calls to Time as a toolbox might help with those same issues to support the class. Source code as follows: https://github.com/jruby/jruby/blob/c24081ec3888c3be21096717dccc67dc235f3952/lib/ruby/stdlib/date.rb#L632
