### ISSUE TITLE
Deprecation Warning while using require_remote on Firefox

### ISSUE THREAD

**Issue by mistergibson** [opal/opal#1744]
Got this warning while doing (a successful) require_remote call:

Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user’s experience. For more help http://xhr.spec.whatwg.org/

Just thought I might bring it to your attention - wondering if async fetch is as effective?

**Comment by elia** [comment]
@mistergibson thanks for raising attention on this!

Of course using sync calls should generally be avoided, but in this case it's necessary to maintain a "require"-like functionality and ensure that the next line has the stuff it needs without using a callback.

Maybe if there's enough support from the browser that will be replaced by `await/async` but it's still kinda recent: https://caniuse.com/#feat=async-functions.

That said `require_remote` is intended to be used only for experiments and the like and should be avoided in hi-performing production apps.

I'll close this, but let me know if there's any reason to reopen let me know and I'll do right away 😄
