### ISSUE TITLE
Implement String#prepend

### ISSUE THREAD

**Issue by Mogztter** [opal/opal#1753]
Because why not ?! 😜🤘

https://ruby-doc.org/core-2.1.1/String.html#method-i-prepend

A pull request is coming!

**Comment by iliabylich** [comment]
@Mogztter Can we close this issue?

**Comment by Mogztter** [comment]
It will be implemented as "not implemented" in https://github.com/opal/opal/pull/1754 🤣

**Comment by iliabylich** [comment]
Fixed in https://github.com/opal/opal/pull/1754
