### ISSUE TITLE
When using Array.dup, attribute $$id is added to the string representation

### ISSUE THREAD

**Issue by Mogztter** [opal/opal#1755]
Consider the following code:

```js
const sourceLines = ["== Test", "This is the first paragraph.", "", "This is a second paragraph."];
const result = sourcesLine.$dup();
console.log('result', result);
// prints:

// [ '== Test',
// 'This is the first paragraph.',
// '',
// 'This is a second paragraph.',
// '$$id': 630 ]
```

Please note that the size of the array is right.
I don't know if it's intended or not but this is a new behavior introduced in the 0.11.0 release.

**Comment by iliabylich** [comment]
I think I know the reason.
```
opal-repl
>> `console.log(Opal.Array.$$proto.$allocate)`
function method_missing_stub() {
      // Copy any given block onto the method_missing dispatcher
      this.$method_missing.$$p = method_missing_stub.$$p;

      // Set block property to null ready for the next call (stop false-positives)
      method_missing_stub.$$p = null;

      // call method missing with correct args (remove '$' prefix on method name)
      var args_ary = new Array(arguments.length);
      for(var i = 0, l = args_ary.length; i < l; i++) { args_ary[i] = arguments[i]; }

      return this.$method_missing.apply(this, [method_name.slice(1)].concat(args_ary));
    }
=> nil
>> `console.log(Opal.Array.$allocate)`
function $$allocate() {
      var self = this;


      var obj = new self.$$alloc();
      obj.$$id = Opal.uid();
      return obj;

    }
```

`Array#dup` has an optimization to return `self.slice(0)` (introduced in 0.11) if three methods are not redefined:
+ `Array.allocate`
+ `Array#copy_instance_variables`
+ `Array#initialize_dup`

There's a bug in the optimization, `Opal.pristine` marks `Array#allocate` (which obviously doesn't exist, it's a `method_missing_stub`) as "original untouched method" and later `Array#dup` checks that this method wasn't changed (again, check on the `missing_missing_stub`).

I guess it makes sense to rewrite `Opal.pristine` to take a list of functions and call it like:
``` ruby
class Array
  # ...
  Opal.pristine `self.$allocate`,
    `self.$$proto.$copy_instance_variables`,
    `self.$$proto.$initialize_dup`
  # ...
end
```

Have no ideas how we missed it but the optimization just doesn't do anything (even more, there are 4 redundant checks in `Array#dup`) 😄 

@elia What do you think?

**Comment by Mogztter** [comment]
> I think I know the reason.

Thanks for the detailed analysis @iliabylich !

> Have no ideas how we missed it but the optimization just doesn't do anything 

We should probably add a test to check that `slice` is called when the optimization must be used.
Let me know if I can help on this issue as I want to upgrade Asciidoctor.js on the latest release of Opal 😉

**Comment by iliabylich** [comment]
@Mogztter Could you send a PR for this? I think passing functions to Opal helper methods is fine.
`Opal.pristine` can take a list a functions and mark them as `pristine` (by adding a `$$pristine` attribute. The method is there, it just need to be reworked into something like
``` ruby
def pristine(*functions)
  functions.each do |function|
    `f.$$pristine = true`
  end
end
```
And `Array` class needs to be changed to have the code from my comment above.
About the specs - the following spec seems to match the behavior
``` ruby
subclass = Class.new(Array)
a = subclass.new
`a.slice = function() { return 'sliced' }`
subclass.define_singleton_method(:allocate) { raise 'Should not be invoked' }
lambda { a.dup }.should_not raise_error
a.dup.should == ['sliced']
```
This test fails on the current master.

Setting an expectation directly on Array can be false-positive as we have a test framework that definitely allocates some arrays. But maybe you have a better idea how to test it :)

Just realized that `Array#dup` uses `super` for non-optimized case, so probably another alternative is to extend an empty array with some module with a `#dup` method that throws an error. This solution is cleaner from the code perspective (it doesn't require a subclass), but it sticks too much to implementation details.

Feel free to ping me in gitter if you have any questions

**Comment by Mogztter** [comment]
> Could you send a PR for this? 

Sure I will give it a try this week-end 😀 

> Setting an expectation directly on Array can be false-positive as we have a test framework that definitely allocates some arrays.

That's a good point

> But maybe you have a better idea how to test it :)

Your spec looks fine to me

> Just realized that Array#dup uses super for non-optimized case, so probably another alternative is to extend an empty array with some module with a #dup method that throws an error. This solution is cleaner from the code perspective (it doesn't require a subclass), but it sticks too much to implementation details.

I agree

> Feel free to ping me in gitter if you have any questions

Ok!
Thanks again 👍

**Comment by elia** [comment]
@Mogztter @iliabylich 

This:

```rb
  Opal.pristine singleton_class, :allocate
  Opal.pristine self, :copy_instance_variables, :initialize_dup
```

combined with:

```rb
  def dup
    %x{
      if (
        self.$$class === Opal.Array &&
        self.$$class.$allocate.$$pristine && // <==== added .$$class
        self.$copy_instance_variables.$$pristine &&
…
```

seems to be a working solution, it still needs to be properly tested.

_On a side note we should expand the use of this technique, especially looking for potential optimizations among the hot paths in the initial load of the runtime/corelib 🏎_

**Comment by Mogztter** [comment]
Thanks for the fix @elia 
I can confirm that the `slice` optimization is now called but unfortunately the spec described by @iliabylich does not work:

Here's what I get when I run the spec:

```js
self.$$class === Opal.Array false
self.$$class.$allocate.$$pristine undefined
self.$copy_instance_variables.$$pristine true
self.$initialize_dup.$$pristine true
```

The first one is a bit confusing but since we use a subclass `self.$$class` is not an Array but a subclass of Array. Instead we could check that `slice` function is available because that's the only thing that matters here no ?
Probably the same explanation as above, since we are using a subclass `$$pristine` is undefined on `$allocate`. Is this intended or is there a bug in `Class.new(Array)` ?

**Comment by iliabylich** [comment]
@Mogztter Array subclass has a different allocate method (as it needs to create an object of Array subclass)

> Instead we could check that slice function is available because that's the only thing that matters here no ?

No. `#dup` method calls `.allocate -> #initialize_dup -> #copy_instance_variables`. Instances of the Array class usually have no instance variables. If Array class has original methods `.allocate` and `#copy_instance_variables` then we can go fast way and call `.slice()`. Otherwise we treat as a regular Ruby object and go through all those methods.

**Comment by Mogztter** [comment]
> No. #dup method calls .allocate -> #initialize_dup -> #copy_instance_variables. Instances of the Array class usually have no instance variables. If Array class has original methods .allocate and #copy_instance_variables then we can go fast way and call .slice(). Otherwise we treat as a regular Ruby object and go through all those methods.

Understood, but we still need to remove `self.$$class === Opal.Array` right ?
