### ISSUE TITLE
is_a? leads false if Native is included

### ISSUE THREAD

**Issue by janbiedermann** [opal/opal#1769]
[Try here](http://opalrb.com/try/?code:class%20User%0A%20%20include%20Native%0A%0A%20%20def%20initialize(arr)%0A%20%20%20%20puts%20arr.is_a%3F%20Array%0A%20%20%20%20%40native%20%3D%20arr%0A%20%20end%0A%0Aend%0A%0Auser%20%3D%20User.new(%5B1%2C2%5D)%0A)
```
class User
  include Native

  def initialize(arr)
    puts arr.is_a? Array # <--- here
    @native = arr
  end

end

user = User.new([1,2])
```
--> false

**Comment by iliabylich** [comment]
That's expected, that exactly what MRI does (thanks to @elia 😄 )
``` ruby
module Native
  module Array
  end
end

class User
  include Native

  def initialize(arr)
    puts arr.is_a? Array
    puts Array.name
  end
end

user = User.new([1,2])
```

``` sh
$ ruby test.rb
false
Native::Array
```

You have a `Native` module included (so it's placed **before** `Object in your ancestors chain).

**Comment by elia** [comment]
@iliabylich I think we should discourage including `Native` and offer an alternative instead, like `Native::DSL`, `Native::Wrapper`, `Native::Base` or something similar.

a warning should be added when `::Native` is included:

```
module Native
  def self.included(base)
    warn "Including ::Native is deprecated. Please include Native::????? instead."
  end
end
```

I'd like to head from you guys what names look better to you (@meh included), once we set the name I'll fix it (or merge a PR HINT HINT 😉).

**Comment by iliabylich** [comment]
I prefer `Native::Wrapper` as the only thing that this module does is wrapping an object. Other class methods are placed in the `Native::Helpers` module.
