### ISSUE TITLE
Cache dynamic regular expressions

### ISSUE THREAD

**Issue by mojavelinux** [opal/opal#1793]
Certain methods such as String#gsub and String#match dynamically generate a JavaScript regular expression from a Ruby regular expression in order to prepend additional flags (specifically the 'g' flag). For programs that hit these methods thousands of times using complex regular expressions, this can have a measurable impact on performance.

I'd like to suggest that Opal cache these generated regular expressions so they only have to be compiled once.

Here's an example that demonstrates how a regexp cache could be used in the String#gsub method:

```rb
const GSUB_RX_CACHE = new Map();
const GSUB_RX_CACHE_I = new Map();

...

if (pattern.$$is_regexp) { 
  const ignoreCase = pattern.ignoreCase;
  const rxCache = ignoreCase ? GSUB_RX_CACHE_I : GSUB_RX_CACHE;
  const patternSource = pattern.source;
  pattern = rxCache.get(patternSource);
  if (pattern) {
    pattern.lastIndex = 0;
  } else {
    pattern = new RegExp(patternSource, ignoreCase ? 'gmi' : 'gm');
    rxCache.set(patternSource, pattern);
  }
} else {
  ...
}
```

(I use two different caches because it's faster than generating a dynamic key).

Here are the methods that could benefit from this cache:

* String#gsub
* String#scan
* String#split
* String#match
* String#match? *

\* For String#match?, it may not even be necessary to recreate the regular expression since the 'g' flag isn't actually need. And I'm not sure the 'g' flag is need for String#match either (or perhaps there are just cases when it isn't needed).

**Comment by mojavelinux** [comment]
cc: @Mogztter

**Comment by iliabylich** [comment]
`WeakMap` would be better for this feature to prevent memory leaking when the code generates dynamic regexes and uses it in methods listed above.

> For String#match?, it may not even be necessary to recreate the regular expression since the 'g' flag isn't actually need

True

> And I'm not sure the 'g' flag is need for String#match either

`String#match` returns all matches, how can you get them without the `g` flag?

This feature will be used in multiple places, so I vote for implementing it as a runtime helper:

``` ruby
# lib/opal/nodes/runtime_helpers.rb
helper :cached_regexp_copy do
  # the code from issue that uses Opal.regexpCache
end

# runtime.js
Opal.regexpCache = new WeakMap();
# ... 2nd map is optional, maps support composite keys.

# opal/string.rb
def gsub(pattern, replacement = undefined, &block)
  %x{
    if (pattern.$$is_regexp) {
      pattern = #{Opal.cached_regexp_copy(pattern)};
    }
    // ... the rest of existing logic
  }
end
```

In general I like this proposal because apps usually have a static list of regexes, caching them is a good idea.

**Comment by iliabylich** [comment]
`WeakMap` doesn't support primitive keys. Using simple `Map` is dangerous

**Comment by mojavelinux** [comment]
> WeakMap doesn't support primitive keys.

Yep. I bumped into that right away. That's why I didn't suggest it.

> Using simple Map is dangerous

Why is that? The number of entries in the Map isn't going to be very large because it's just holding regular expressions already defined in the code. (Unless the code itself is creating regular expressions dynamically).

**Comment by mojavelinux** [comment]
> String#match returns all matches, how can you get them without the g flag?

I don't think so. The match method returns MatchData for a single match.

http://ruby-doc.org/core-2.5.0/String.html#method-i-match

But now I remember why match does what it does. It matches in a loop in order to support offset. So in that case, it should only do the loop if the second argument (the offset) is set (which happens to be rare).

**Comment by mojavelinux** [comment]
I'd be happy to follow-up with a patch for String#match? and String#match to skip generating a regexp if pos is not set. I think that's a separate issue.
