### ISSUE TITLE
File.expand_path on Windows root should include trailing slash

### ISSUE THREAD

**Issue by mojavelinux** [opal/opal#1794]
When File.expand_path is run on a Windows root (i.e., bare drive letter), it should include a trailing slash (to be consistent with MRI). However, it does not. It also has difficulty expanding a raw drive letter.

Here's what MRI does:

```rb
Dir.pwd
#=> C:/Users/Usename/directory

File.expand_path 'C:'
#=> C:/Users/Username/directory

File.expand_path 'C:/'
#=> C:/

File.expand_path 'D:'
#=> D:/

File.expand_path 'D:/'
#=> D:/
```

Here's what Opal does (with nodejs support enabled):

```rb
Dir.pwd
#=> C:\Users\Usename\directory

File.expand_path 'C:'
#=> C:/Users/Username/directory/C:

File.expand_path 'C:/'
#=> C:

File.expand_path 'D:'
#=> C:/Users/Username/directory/D:

File.expand_path 'D:/'
#=> D:
```

The correct behavior for `C:` is debatable.

(the value of `Dir.pwd` is show here for context, but note that the value it returns is also incorrect).

**Comment by mojavelinux** [comment]
Without nodejs support enabled, we get different results (but still no trailing slash):

```rb
Dir.pwd
#=> .

File.expand_path 'C:'
#=> C:

File.expand_path 'C:/'
#=> C:

File.expand_path 'D:'
#=> D:

File.expand_path 'D:/'
#=> D:
```

**Comment by Mogztter** [comment]
Expanding paths on different operating systems and programming languages :disappointed: :sob: 
@mojavelinux Did you find a quick way to test Ruby on Windows ? Or at least the win32 implementation of File related methods ?

**Comment by mojavelinux** [comment]
I run Windows tests on AppVeyor. Some of the tests in Asciidoctor's test
suit fake Windows behavior because the PathResolver class supports
emulation. But there are a few that only run on Windows.
