### ISSUE TITLE
Method argument is wrong when using the splat operator

### ISSUE THREAD

**Issue by Mogztter** [opal/opal#1797]
Consider the following code:

```rb
def method(type, one, two, three, four, five)
  p "type: #{type}, one: #{one}, two: #{two}, three: #{three}, four: #{four}, five: #{five}"
end

method(:while, ['a', 'b'], *['c', ['d', 'e']], 'f', ['g', 'h'])
```

**MRI**
```
ruby test.rb
"type: while, one: [\"a\", \"b\"], two: c, three: [\"d\", \"e\"], four: f, five: [\"g\", \"h\"]"
```

**Opal**
```
bundle exec opal test.rb
"type: while, one: a,b, two: c, three: d,e, four: f, five: g"
```

The fifth argument should be `["g", "h"]`.

**Comment by iliabylich** [comment]
Minimized case:
``` ruby
def m(*args)
  p args
end

m(*[], [1])
```

``` sh
$ ruby test.rb && opal test.rb
[1]
1
```

**Comment by iliabylich** [comment]
ok, any post-rest argument that is an array is affected by this issue.
the reason is that arglist `(*one, two)` compiles to `Opal.to_ary(one).concat(two)` which is ok in most cases. But in JS `[1].concat([2])` is `[1, 2]`, so it works incorrectly when `two` is an array.

**Comment by Mogztter** [comment]
Thanks for the fix @iliabylich 
And sorry for the "over-complicated" code to describe the issue 😳
