### ISSUE TITLE
Add basic support for Logger

### ISSUE THREAD

**Issue by mojavelinux** [opal/opal#1801]
In order to log messages, many libraries (including Asciidoctor) depend on at least having the basic interface / base class provided by the Logger class. I think that Opal should provide enough of the Logger so that it can be used for writing messages to stdout/stderr and extended. I don't think we need to get into file support right now (esp since that's not portable in Opal).

Here's the basic API that I have in mind.

```rb
class Logger
  module Severity
    DEBUG = 0
    INFO = 1
    WARN = 2
    ERROR = 3
    FATAL = 4
    UNKNOWN = 5
  end
  include Severity

  attr_reader :level
  attr_accessor :progname
  attr_accessor :formatter

  def initialize pipe
    @pipe = pipe
    @level = DEBUG
  end

  def info(progname = nil, &block); ...; end
  def debug(progname = nil, &block); ...; end
  def warn(progname = nil, &block); ...; end
  def error(progname = nil, &block); ...; end
  def fatal(progname = nil, &block); ...; end
  def unknown(progname = nil, &block); ...; end
  def info?; @level <= INFO; end
  def debug?; @level <= DEBUG; end
  def warn?; @level <= WARN; end
  def error?; @level <= ERROR; end
  def fatal?; @level <= FATAL; end
  def level=(level); ... end
  def add(severity, message = nil, progname = nil, &block)
    severity ||= UNKNOWN
    return true if severity < @level
    progname ||= @progname
    unless message
      if block_given?
        message = yield
      else
        message = progname
        progname = @progname
      end
    end
    @pipe.write(format_message(severity, Time.now, progname, message))
  end
  def format_message severity, datetime, progname, message; ...; end
end
```

The Asciidoctor project can help with getting this implemented. cc: @Mogztter 

(I'll fill in the rest of the implementation in a PR).

**Comment by elia** [comment]
Sounds great! 
Of course the more the API is compatible with [MRI's](https://github.com/ruby/ruby/blob/aa2b32ae4bac4e1fcfc5986977d9111b32d0458e/lib/logger.rb) the better

**Comment by mojavelinux** [comment]
For sure. We'll take it one step at a time. I'll put together a first draft
tonight.

>
