### ISSUE TITLE
Modules names are now prefixed by the working directory ?

### ISSUE THREAD

**Issue by Mogztter** [opal/opal#1810]
I'm running the following command on master `bundle exec rake dist`:

```diff
-Opal.modules["stringio"] = function(Opal) {
+Opal.modules["/Users/guillaume/dev/opal/stdlib/stringio"] = function(Opal) {
```

This change was introduced in 72b3d28f300b0e006204412f4ca93568c1b6c289
Is this intended ?

**Comment by elia** [comment]
Not at all, is this happening when compiling in MRI or nodejs?

**Comment by Mogztter** [comment]
When compiling in MRI, do you reproduce this issue or is it just me ?

**Comment by Mogztter** [comment]
I can reproduce this issue on another computer, I will investigate :nerd_face:

**Comment by Mogztter** [comment]
I think I found the issue:

https://github.com/opal/opal/blob/fcc3f7800c701308c5ab9dae8a0720561453878e/lib/opal/nodes/top.rb#L49

`compiler.file` is an absolute path for stdlib files (eg: `/home/guillaume/workspace/opensource/opal/opal/stdlib/bigdecimal.rb`). Previously `compiler.file` was just `bigdecimal`.

I can do a quick fix in `opal/nodes/top.rb` but I'm pretty sure we should fix it somewhere "upstream" ?

```rb
module_basename = (Pathname.new(compiler.file).absolute?) ? File.basename(compiler.file) : compiler.file
line "Opal.modules[#{Opal::Compiler.module_name(module_basename.inspect}] = function(Opal) {"
```
What do you think @elia  ?

**Comment by elia** [comment]
@Mogztter it's surely due to recent changes made to have better stack traces and error reporting, if you have a simple way to reproduce please post it, with a quick check I wasn't able to reproduce it:

```
opal:master ⤑ bin/opal -e 'require "stringio"; ' -cEO|head                                                                                                                             ~/C/opal
/* Generated by Opal 0.11.1.dev */
Opal.modules["stringio"] = function(Opal) {
  function $rb_ge(lhs, rhs) {
    return (typeof(lhs) === 'number' && typeof(rhs) === 'number') ? lhs >= rhs : lhs['$>='](rhs);
  }
  function $rb_gt(lhs, rhs) {
    return (typeof(lhs) === 'number' && typeof(rhs) === 'number') ? lhs > rhs : lhs['$>'](rhs);
  }
  function $rb_plus(lhs, rhs) {
    return (typeof(lhs) === 'number' && typeof(rhs) === 'number') ? lhs + rhs : lhs['$+'](rhs);
```

maybe it's related to sprockets or some other env condition?

**Comment by Mogztter** [comment]
@elia What about:

```
$ cat build-stringio 
```
.build-stringio
```rb
#!/usr/bin/env ruby

require 'opal'
$stdout.puts Opal::Builder.build('stringio', requirable: true).to_s
```
```
$ chmod +x build-stringio
```
```
$ bundle exec build-stringio | head -n2
/* Generated by Opal 0.11.1.dev */
Opal.modules["/home/guillaume/workspace/opensource/opal/opal/stdlib/stringio"] = function(Opal) {
```

**Comment by elia** [comment]
@Mogztter confirmed thanks, WIP 👨🏻‍🏭🚧

**Comment by Mogztter** [comment]
Thank you 😄
