### ISSUE TITLE
The https://opalrb.org/ seems to be hacked

### ISSUE THREAD

**Issue by alexbottoni** [opal/opal#1843]
As long as I can see, the https://opalrb.org/ domain now points to "Best Casino Sites in UK".

Please, have a look at your site and/or DNS.

(I'm looking at it from Italy)

**Comment by elia** [comment]
@alexbottoni thanks for the report!

Unfortunately that domain has been lost and was reclaimed by some domain squatter, the whole show now runs on https://opalrb.com
I'd like to regain access but I have to find the necessary time & money in order to do it.

**Comment by elia** [comment]
I did a bit of minimal research, but apparently the domain is secured at least until next march.

I'll close the issue, but if anyone have any suggestions on how to take it back it would be much appreciated 🙇
