### ISSUE TITLE
Cannot load JS assets with `require`

### ISSUE THREAD

**Issue by jgaskins** [opal/opal#1858]
Clearwater loads the `virtual-dom` library, vendored into its `opal/` directory, [with a plain `require` directive](https://github.com/clearwater-rb/clearwater/blob/b3d9fc6d6f128dc401d7bfa1a3fa2653b5b63158/opal/clearwater/virtual_dom.rb#L1). This works as of `0.11.1.pre`, but not on `master`, so I feel like something may have changed.

On `0.11.1.pre` and earlier, `clearwater/virtual_dom/js/virtual_dom` doesn't seem to be a key in the `Opal.modules` object, which seems strange but I never really questioned it since it always just worked. :-) It feels like Clearwater may have just been using an unintentional feature, but it was _really_ handy to just be able to `require` JS files the same as we do with Ruby files.

Any possibility of bringing that back? If not, adding a new API specifically for JS files would be cool, too. Just want to be able to load JS assets without imposing it on application developers. :-)

**Comment by elia** [comment]
I'll close this, has been probably fixed in a later release
