### ISSUE TITLE
Support multiple ensure blocks

### ISSUE THREAD

**Issue by graywolf** [opal/opal#1871]
Only last `ensure` block on `Promise` is executed without any warning
that other block was already set.

    $ Promise.new.ensure { puts "Ensure 1" }.ensure { puts "Ensure 2" }.resolve
    Ensure 2

I think is would be nice to support multiple ensure block. The order
of execution would be reverse order of addition (similar to destructors
in C++).

So I would like to have `Promise` support

    $ Promise.new.ensure { puts "Ensure 1" }.ensure { puts "Ensure 2" }.resolve
    Ensure 2
    Ensure 1

Clearing the previous ensures could be done like (to get current behaviour)

    $ Promise.new.ensure { puts "Ensure 1" }.ensure(:clear) { puts "Ensure 2" }.resolve
    Ensure 2

I guess I have two questions:

1. Is this already possible and I've just missed it?
2. If I make a PR with this, would it be accepted?

Since this is breaking change it would be for next major version, right?

**Comment by elia** [comment]
I have no objection, but maybe you can solve it by fixing chaining.

This seems to work as desired:

```rb
pro = Promise.new
pro.ensure { puts "Ensure 1" }
pro.ensure { puts "Ensure 2" }
pro.resolve
```

```
⤑ pbpaste |opal -rpromise                                                 ~/C/opal
Ensure 1
Ensure 2
```

Consider that each ensure/then/etc. basically adds a promise to a chain of promises. 
Your example was resolving just the last promise that was containing the second ensure.

---

I'll close, let me know if I'm missing something and I'll reopen 🙂
