### ISSUE TITLE
setting `Opal::Config.method_missing_enabled = false` causes runtime error

### ISSUE THREAD

**Issue by balmoral** [opal/opal#1876]
Setting compiler option

`Opal::Config.method_missing_enabled = false`

causes runtime error:

`app.js:1 Uncaught TypeError: Cannot set property '$$pristine' of undefined`

<img width="730" alt="screen shot 2018-08-27 at 11 54 12" src="https://user-images.githubusercontent.com/2087785/44636638-4a624700-a9f0-11e8-9956-624a7f83b168.png">

**Comment by elia** [comment]
Thanks for the report, aside from fixing it I think we should consider removing the option altogether after ensuring it has no noticeable impact on performance 
cc @opal/core

**Comment by balmoral** [comment]
I had a vague recollection that it impacted performance. It reduced code size by maybe 100kb out of 3mb, before uglify. Just experimenting. So no concern if you drop the option. Anything else that might speed things in production?

**Comment by elia** [comment]
@balmoral I'd like to add the ability to skip unused methods in the future, especially from core+stdlib, either manually or automatically, that should reduce startup time. For now I think avoiding or deferring requires to the latest moment should help a bit with startup time and memory.

Of course talking about performance every situation is different, have you already tried to identify where a slowdown might occur in your app? 

We might be able do address that specifically and improve things for everyone.

**Comment by balmoral** [comment]
@elia I've no glaringly obvious bottlenecks, and the app is doing some pretty compute intensive stuff on the client side. Generally happy with speed, but was looking for some easy gains! I'll do some more detailed profiling as the app stabilises and see what I come up with. 

Anything which eliminates unused code would be great. Uglify is minifying 3MB of Opal compiled code down to 1.3MB, some of which may be due to dead code elimination.

Really appreciate all the hard work going into Opal. Couldn't live without it!

**Comment by elia** [comment]
There was an actual bug in `Array#dup`, I backported the fix from master in #1877, I'll merge it once it passes the CI + code-review

**Comment by elia** [comment]
Released! https://rubygems.org/gems/opal/versions/0.11.3
