### ISSUE TITLE
require function is used in a way in which dependencies cannot be statically extracted

### ISSUE THREAD

**Issue by Mogztter** [opal/opal#1883]
This warning message is thrown by Webpack when it processes this file: https://github.com/Mogztter/opal-node-runtime/blob/master/src/nodejs.js

```
WARNING in ./node_modules/opal-runtime/src/nodejs.js
28:48-55 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
 @ ./node_modules/opal-runtime/src/nodejs.js
 @ ./node_modules/opal-runtime/src/index.js
 @ ./node_modules/asciidoctor.js/dist/browser/asciidoctor.js
 @ ./index.jsx
 @ multi ./index.jsx
```

I think that Webpack is confused because `require` is registered as a constant and we are using a function to require Node modules in the Kernel class: https://github.com/opal/opal/blob/d77bd3ce19e101988578cdb6314d659491a77844/stdlib/nodejs/kernel.rb#L3-L22

I'm wondering if we could generate code that we will be easier to parse for static analysis ? I don't really see the value of `@__fs__ = node_require :fs` (but I'm might be missing something ?)
Maybe we should use:

```js
@__fs__ = `require('fs')`
```

Original issue: https://github.com/asciidoctor/asciidoctor.js/issues/508

**Comment by elia** [comment]
> Maybe we should use:
> 
>     @__fs__ = `require('fs')`

Yes, let's deprecate `node_require` and migrate all uses to the backticks version.

Can you prepare a PR? 🙂

**Comment by Mogztter** [comment]
Sure thing I will 😉

**Comment by Mogztter** [comment]
Actually Webpack complains about this line:

```js
Opal.const_set($nesting[0], 'NODE_REQUIRE', require);
```

```
WARNING in ../asciidoctor.js/node_modules/opal-runtime/src/nodejs.js 15:48-55
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
 @ ../asciidoctor.js/node_modules/opal-runtime/src/index.js
 @ ../asciidoctor.js/dist/browser/asciidoctor.js
 @ ./src/index.js
```

I guess our only option is to remove the deprecated method in a few version ?
