### ISSUE TITLE
Symbols are Strings?

### ISSUE THREAD

**Issue by sancarn** [opal/opal#1884]
In my specific use case for Opal I need to be able to distinguish between symbols and strings.

Unfortunately the following:
```
Opal.top.$eval("{:a=>1,\"a\"=>2}")
```

Returns the following object:

```
{"$$smap":{"a":2},"$$map":{},"$$keys":["a"]}
```

I.E. `"a"` is overwriting the value of `:a`

**Comment by sancarn** [comment]
I just noticed that:

```
Opal.top.$eval(":a")
```
and

```
Opal.top.$eval("a")
```

So I assume this is intended and documented behaviour?

**Comment by sancarn** [comment]
#285 Apparently resolved this issue, but I guess the changes were undone?

**Comment by iliabylich** [comment]
Yes, symbols are strings, it's documented here - http://opalrb.com/docs/guides/v0.11.1/unsupported_features.html

**Comment by sancarn** [comment]
I see, that is a shame. Thanks :)
