### ISSUE TITLE
Exit code is not captured

### ISSUE THREAD

**Issue by youchan** [opal/opal#1893]
cf. https://github.com/opal/opal/blob/master/docs/headless_chrome.md#using-exit-codes

with nodejs

    $ opal -ropal/platform -e "exit(1)"; echo $?
    0

I expect to get exit code 1.

**Comment by elia** [comment]
I think we need a spec for exit code and ARGS support for every CLI runner we have

**Comment by elia** [comment]
Fixed by https://github.com/opal/opal/pull/1898, I'll close this when I port the fix to master and release 0.11.4

**Comment by youchan** [comment]
Thank you!!
