### ISSUE TITLE
Opal initialization in a Jest test (using Node.js runtime)

### ISSUE THREAD

**Issue by Mogztter** [opal/opal#1897]
When Opal is run in a Jest environment, dates are not lifted to Ruby Time when instantiated from the `fs` core module.

Here's a simple test case:

**test.js**
```js
test('Date lifted', function() {
  const date1 = new Date();

  require('./build/opal.js')
  require('./build/nodejs.js')
  Opal.load("nodejs")

  const date2 = Opal.const_get_relative([], 'File').$new("test.js").$mtime()
  const date3 = require('fs').statSync('./test.js').mtime // File.mtime implementation in Node.js
  const date4 = new Date()

  expect(date1.getFullYear()).toEqual(2018) // date1 is a JavaScript Date
  expect(date2.getFullYear()).toEqual(2018) // date2 is a JavaScript Date
  expect(date3.getFullYear()).toEqual(2018) // date3 is a JavaScript Date
  expect(date4.getFullYear()).toEqual(2018) // date4 is a JavaScript Date

  expect(typeof date1.$strftime).toEqual('function')   // date1 is lifted
  expect(typeof date2.$strftime).toEqual('undefined')  // date2 is not lifted :(
  expect(typeof date3.$strftime).toEqual('undefined')  // date3 is not lifted :(
  expect(typeof date4.$strftime).toEqual('function')   // date4 is lifted
})

```

To run this test with `npm`:

```
npm init -y
npm i jest --save-dev
npm i xmlhttprequest --save-dev
```

Then run `jest`:

```
jest
```

As mentioned by @martijnthe in https://github.com/asciidoctor/asciidoctor.js/issues/565 it's possible to workaround this issue with a custom Jest environment:

**opal-jest-environment.js**
```js
const NodeEnvironment = require('jest-environment-node');

class OpalNodeEnvironment extends NodeEnvironment {
  async setup() {
    require('opal-runtime');
    await super.setup();
  }
}

module.exports = OpalNodeEnvironment;
```

**package.json**
```json
  "jest": {
    "testEnvironment": "<rootDir>/opal-jest-environment.js",
  }
```

I believe that this issue is broader than just date. But hopefully the reproduction case is simple enough.

I'm not sure if we can do something about it in Opal or if someone has a better workaround to offer ?

**Comment by elia** [comment]
@Mogztter I think the problem stems from the jest-env replacing core classes (probably to support mocking) and having some libraries hook to original ones. My guess is that in this case `fs` or `graceful-fs` (which is a drop-in replacement for `fs`) are still hooked to the original date, while Opal being required inside the test uses the replaced one.

I don't think there's much we can do, Opal is a runtime and operates at the level of core classes, so probably the best solution is to have a dedicated environment and let the libraries "talk the same language" so to speak.

Except for that the only other option is maybe to re-instantiate Date objects (but I didn't try that).

---

You can tell all of the above just by adding this expectation:

```js
  expect(typeof date1.constructor).toEqual(date2.constructor)
```

**Comment by Mogztter** [comment]
> My guess is that in this case fs or graceful-fs (which is a drop-in replacement for fs) are still hooked to the original date, while Opal being required inside the test uses the replaced one.

Yes I forgot to mention this part but indeed Jest is using `graceful-fs`.

Thanks for your investigation @elia :+1:
I will document the workaround in the Asciidoctor.js documentation.
