### ISSUE TITLE
ENV missing key? method in nodejs module

### ISSUE THREAD

**Issue by mojavelinux** [opal/opal#1923]
In the nodejs module for Opal, the global ENV object is missing the key? method.

The following code throws an error, though it should work:

```ruby
require 'nodejs'

ENV.key? 'HOME'
```

**Comment by mojavelinux** [comment]
Technically, ENV should quack like a Hash (even though Hash === ENV is false on CRuby). But `key?` happens to be a very important method for checking if an environment variable is set.

**Comment by Mogztter** [comment]
@mojavelinux we can start using `ENV.key?` in Asciidoctor Ruby :wink:

**Comment by mojavelinux** [comment]
:tada:
