### ISSUE TITLE
Move Kernel#format to a dedicated module (reduce runtime size)

### ISSUE THREAD

**Issue by Mogztter** [opal/opal#1927]
This method does not depend on other method and is quite huge (500 lines of code for 21 KB).
So if an application does not use `format` or `String#%` then an advanced user could save some bits by not requiring this module.

The idea is to still require this module in `base.rb`:

```rb
require 'corelib/kernel'
require 'corelib/kernel/format'
```

**Comment by Mogztter** [comment]
OH! `sprintf` is an alias :cold_sweat:

**Comment by elia** [comment]
Makes sense!

> OH! sprintf is an alias 😰

Then `sprintf` should go away with format 👍
