### ISSUE TITLE
Implement String#each_codepoint

### ISSUE THREAD

**Issue by Mogztter** [opal/opal#1943]
https://ruby-doc.org/core-2.5.3/String.html#method-i-each_codepoint
https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/String/codePointAt

**Comment by mojavelinux** [comment]
Here's a script that shows why we can't just alias each_codepoint to each_byte.

```
require 'corelib/array/pack' if RUBY_ENGINE == 'opal'
puts '视图'.each_byte.inject([]) {|acc, b| acc << b }.pack 'U*'
```

The same script would work on CRuby if each_byte is replaced with each_codepoint.

**Comment by mojavelinux** [comment]
The proposed implementation passes this test.

**Comment by mojavelinux** [comment]
Interesting to note that in JavaScript (like Ruby), a string's length is the number of codepoints, not bytes.
