### ISSUE TITLE
0.times.size returns null in strict mode

### ISSUE THREAD

**Issue by Mogztter** [opal/opal#1958]
Opal generates the following code for `times`:

```js
return $send(self, 'enum_for', ['times'], ($$61 = function () {
  var self = $$61.$$s || this

  if ($$61.$$is_lambda || $$61.$$define_meth) {
    var $arity = arguments.length
    if ($arity !== 0) { Opal.block_ac($arity, 0, 'times') }
  }
  return self
}, $$61.$$s = self, $$61.$$arity = 0, $$61.$$parameters = [], $$61))
```

The problem is that `$$61.$$s` is falsy (the value is 0) so we are using `this` instead. But `this` in strict mode is `null`.

Thus, the following returns null instead of 0:

```js
(0).$times().$size() // returns null
```

**Comment by elia** [comment]
I don't think it's related to strict mode, but rather that we should fix this check `var self = $$61.$$s || this` to be a check against `null/undefined`: `var self = $$61.$$s == null ? $$61.$$s : this`

**Comment by Mogztter** [comment]
Small correction, `this` is `undefined` in strict mode but the code is using `yieldX` which uses `block.apply(null, args)` so `this` will be `null`:

```js
  Opal.yieldX = function(block, args) {
    if (typeof(block) !== "function") {
      throw Opal.LocalJumpError.$new("no block given");
    }

    if (block.length > 1 && args.length === 1) {
      if (args[0].$$is_array) {
        return block.apply(null, args[0]);
      }
    }

    if (!args.$$is_array) {
      var args_ary = new Array(args.length);
      for(var i = 0, l = args_ary.length; i < l; i++) { args_ary[i] = args[i]; }

      return block.apply(null, args_ary);
    }

    return block.apply(null, args);
  };
```


```js
'use strict'
  
function fun() { return this; }
console.log(fun.apply(null)) // prints null
```

So effectively, `this` is `null` in strict mode, while in non strict-mode `this` is the global object but that's not why the method returns null in strict mode.
In fact, in non-strict mode `$$61.$$s` is a `Number {[[PrimitiveValue]]: 0}` (as reported by WebStorm) but in strict-mode `$$61.$$s` is just reported as `0`...
