### ISSUE TITLE
Remove blocks when the condition is unless RUBY_ENGINE == 'opal'

### ISSUE THREAD

**Issue by Mogztter** [opal/opal#1965]
For example:
```rb
unless RUBY_ENGINE == 'opal'
  puts 'not opal'
end
```

produces:

```js
(function(Opal) {
  var self = Opal.top, $nesting = [], nil = Opal.nil, $$$ = Opal.const_get_qualified, $$ = Opal.const_get_relative, $breaker = Opal.breaker, $slice = Opal.slice;

  Opal.add_stubs(['$==']);
  if ($$($nesting, 'RUBY_ENGINE')['$==']("opal")) {
    return nil
  } else {
    return nil
  }
})(Opal);
```

To reduce the generated file, it could be nice to remove these blocks:
```js
(function(Opal) {
  // noop
})(Opal);
```

Maybe we should add this feature behind a flag ?

**Comment by ahmadine** [comment]
As you can see in this code (or you missed it), it already (kind of) works. Do note that there's no body of the block, only the block is left.

https://github.com/opal/opal/blob/master/lib/opal/rewriters/opal_engine_check.rb

I don't feel competent enough to touch this part yet, but it doesn't look that hard to update it to some more proper behaviour.

**Comment by Mogztter** [comment]
> As you can see in this code (or you missed it), it already (kind of) works. Do note that there's no body of the block, only the block is left.

Yes that's exactly what I described in the issue.
The code:

```rb
unless RUBY_ENGINE == 'opal'
  puts 'not opal'
end
```

produces:

```js
if ($$($nesting, 'RUBY_ENGINE')['$==']("opal")) {
  return nil
} else {
  return nil
}
```

The idea is to remove the block completely to reduce the size of the generated file.
Another example would be:

```rb
if RUBY_ENGINE == 'opal'
  # NOTE In JavaScript, ^ and $ match the boundaries of the string when the m flag is not set
  AttributeEntryPassMacroRx = /^pass:([a-z]+(?:,[a-z-]+)*)?\[(#{CC_ALL}*)\]$/
else
  AttributeEntryPassMacroRx = /\Apass:([a-z]+(?:,[a-z-]+)*)?\[(.*)\]\Z/m
end
```

The above code produces:
```js
if ($$($nesting, 'RUBY_ENGINE')['$==']("opal")) {
  Opal.const_set($nesting[0], 'AttributeEntryPassMacroRx', new RegExp("" + "^pass:([a-z]+(?:,[a-z-]+)*)?\\[(" + ($$($nesting, 'CC_ALL')) + "*)\\]$"))
} else {
  nil
};
```

It would be more efficient and less verbose to produce:

```js
Opal.const_set($nesting[0], 'AttributeEntryPassMacroRx', new RegExp("" + "^pass:([a-z]+(?:,[a-z-]+)*)?\\[(" + ($$($nesting, 'CC_ALL')) + "*)\\]$"))
```

In other words, we can safely remove the condition since we know that the Ruby engine is "opal" and it won't change.

**Comment by Mogztter** [comment]
Thanks @hmdne 👏🏻
