### ISSUE TITLE
opal parser does a freeze

### ISSUE THREAD

**Issue by catmando** [opal/opal#1968]
If you want to run the compiler on the client (i.e. for something like a hotloader, test harness, etc) you get 

`Object freezing is not supported by Opal`

raised from Parser line 9

**Comment by elia** [comment]
That behavior can be controlled with `Opal.config.unsupported_features_severity` and defaults to `warning`, can you add some context on how to trigger the unexpected behavior?

https://github.com/opal/opal/blob/41aedc0fd62aab00d3c117ba0caf00206bedd981/opal/corelib/unsupported.rb#L5

**Comment by catmando** [comment]
how do you set it to ignore completely?

**Comment by elia** [comment]
@catmando for now the only way is to add `Opal.config.unsupported_features_severity = 'ignore'` just after `require "opal"`

See all the supported configurations here: https://github.com/opal/opal/blob/5f1ef2ddc024ed2b071bfa47db2a4db8be3756ce/opal/corelib/runtime.js#L61-L66
