### ISSUE TITLE
Nashorn will soon be deprecated

### ISSUE THREAD

**Issue by elia** [opal/opal#1971]
Nashorn will soon be deprecated and we should probably remove this runner: https://openjdk.java.net/jeps/335 (but not as part as this pull request). I'm thinking about it because I saw this file in the diff.

_Originally posted by @Mogztter in https://github.com/opal/opal/pull/1970_

Probably good to have a transition period with a deprecation notice

**Comment by eregon** [comment]
FWIW, GraalVM's JavaScript implementation might be a replacement if wanted:
https://medium.com/graalvm/oracle-graalvm-announces-support-for-nashorn-migration-c04810d75c1f

It also fully supports running as a Node.js engine.
