### ISSUE TITLE
[Documentation / Tutorial] Opal tutorial 1.0?

### ISSUE THREAD

**Issue by rubyFeedback** [opal/opal#1975]
I just read the announcement on opal 1.0.

Now, 1.0, or 0.1, or 2.0 ... is just a random version string, but nonetheless, congrats!

To the topic at hand:

- I was using opal some years ago but did not follow it lateron. I was able to get the intro-stuff going (not sure if it was hello world or something ... but I remember it worked back when I tried it).

I think the biggest problem I have had was ... to answer the question what to do next, after the intro. I am still not sure about this ... :)

However had, some weeks ago I started to dive into sinatra more seriously and I have actually also started changing many of my gems to also allow a sinatra-interface through routes. For example, without going into all details - one gem that I use shows information about the local computer system, on the commandline; I recently modified it a bit to also show this information in sinatra via a route (and to also add component-routes so that people can just query the version... even via a webpage, such as foobar.bla/query/glibc or something like that... glibc_version, to query the glibc version.

Anyway - I am naturally interested to comine this with opal, but I sort of wonder whether there are useful tutorials, and how extensive these are; and if they are not very extensive, would it be possible to improve them?

Sinatra has lots of examples but for advanced stuff, they are not that great from the official website. I actually learned more things looking at other people's code, and finding blog entries or examples on gist github - this is an odd way of learning, but it helped me a lot more than the official sinatra documentation ... :P 

(I also found padrino too complex ... it is unfortunate because I actually think the gist of padrino should instead be used via sinatra primarily, since sinatra is so super-simple which I love; and in many ways sinatra is just syntax sugar over rack, but still)

Anyway, if you think there is a great tutorial already please disregard it; and if it takes too much time then that is fine. I am only raising an issue beforehand, since I have opal on my todo-list (to use more seriously actually), in particular in combination with sinatra. Actually - that would help me the most, sinatra + opal examples, but I don't want to specifically tailor the issue here solely to my use case, and instead ask more generally. To me tutorials are extremely important because it determines whether I can use a given software project or not. Often without documentation I just don't bother, no matter how awesome the code is, simply because it would take me too much time to get "on par" (It's ok if you are already experienced in some framework, but it is very tedious if you have to start, and everything seems complicated and complex to use - I mean this in general, not confined to opal or any other project as-is).

**Comment by elia** [comment]
Thanks, both for the question and the congratulations!

About tutorials:

- Hyperstack has awesome documentation with a great tutorial section https://hyperstack.org/edge/docs/tutorials
- Since you seem to like simple solutions like Sinatra I suggest also looking at Inesita https://inesita.fazibear.me/ which comes with great documentation and a number of example projects.

I'll try to think about some kind of tutorial for Opal without using any framework, but given the limited time I have I can't guarantee anything. Meanwhile I'll close this issue, but feel free to reply or add more feedback 👍
