### ISSUE TITLE
Uncaught ReferenceError: Opal is not defined opal-parser.js:231 (anonymous function)

### ISSUE THREAD

**Issue by kokizzu** [opal/opal#200]
hi, i tried to include opal-parser.js in a html file using latest version on git, but it shows an error on browser's console:

```
Uncaught ReferenceError: Opal is not defined opal-parser.js:231 (anonymous function)
```

that line contains:

```
      return nil;
   })(Racc, null)    
  })(self)
})(Opal); // this part
```

i got opal-parser.js from rackup localhost:9292/assets/opal-parser.js
is there any way that rake could produce single js file that i could include without any error?

**Comment by yahel-ck** [comment]
when compiling a Ruby file to JS, this error can occure if you forget to `require 'opal'`
