### ISSUE TITLE
Opal 1.0.0 can not parse hash, 0.11.4 can

### ISSUE THREAD

**Issue by farrel** [opal/opal#2000]
I'm using Opal in a browser in a <script type="text/ruby"> block. Opal 1.0.0 throws an exception parsing a large hash with accented characters (I am not sure if they are the cause of the issue, but another smaller example with regular ASCII characters works fine), however downgrading to Opal 0.11.4 parses it fine. The error thrown is 
> uncaught exception: SyntaxError: unexpected token tIDENTIFIER

Here is the hash 

    <script type="text/ruby">
      json_data = {"cap_version"=>"1.2", "identifier"=>"urn:oid:2.49.0.1.124.2128156370.2019", "sender"=>"cap-pac@canada.ca", "sent"=>"2019-07-23T18:07:23-00:00", "status"=>"Actual", "msg_type"=>"Update", "source"=>"Env. Can. - Can. Met. Ctr. – Montréal", "scope"=>"Public", "addresses"=>[], "codes"=>["profile:CAP-CP:0.4", "layer:SOREM:1.0", "layer:EC-MSC-SMC:1.0", "layer:WPAM:1.0", "layer:EC-MSC-SMC:1.1", "layer:SOREM:2.0"], "note"=>"Service Notice: Changes to ECCC CAP, of importance to users of ECCC CAP, are planned for deployment over the coming 2019 year. The first of these include a fix to an occasional but long standing CAP references issue. Coming later this Spring will be new and improved polygons. To have access to notices as they become available you are invited to subscribe to the following mailing list: http://lists.cmc.ec.gc.ca/mailman/listinfo/dd_info | Notification de service: Des changements au PAC d’ECCC, et qui sont d’importance aux utilisateurs, sont en développement pour un lancement au courant de l’année 2019. Un de ces premiers changements est un ajustement afin de résoudre un problème de longue date au niveau des références du PAC. Plus tard ce printemps, il y aura de nouveaux polygones améliorés. Afin d’avoir accès aux notifications dès qu’elles sont disponibles, vous êtes invités à vous inscrire à la liste de diffusion suivante: http://lists.cmc.ec.gc.ca/mailman/listinfo/dd_info", "references"=>["cap-pac@canada.ca,urn:oid:2.49.0.1.124.1634388885.2019,2019-07-23T11:50:13-00:00", "cap-pac@canada.ca,urn:oid:2.49.0.1.124.1558044061.2019,2019-07-23T11:51:13-00:00", "cap-pac@canada.ca,urn:oid:2.49.0.1.124.3681597925.2019,2019-07-23T13:53:18-00:00", "cap-pac@canada.ca,urn:oid:2.49.0.1.124.3530671066.2019,2019-07-23T13:54:18-00:00", "cap-pac@canada.ca,urn:oid:2.49.0.1.124.3035796889.2019,2019-07-23T18:06:23-00:00"], "incidents"=>[], "infos"=>[{"language"=>"en-CA", "categories"=>["Met"], "event"=>"weather", "response_types"=>["Monitor"], "urgency"=>"Future", "severity"=>"Minor", "certainty"=>"Possible", "audience"=>"general public", "effective"=>"2019-07-23T18:06:23-00:00", "expires"=>"2019-07-24T02:06:23-00:00", "sender_name"=>"Environment Canada", "headline"=>"special weather statement in effect", "description"=>"A heavy band of rain is expected to develop Wednesday afternoon between Fort Nelson and Fort St John, and extending westwards to the Rockies and Muncho Lake area. Heavy rain is forecast to continue through Wednesday night before easing through the day on Thursday. \n\nLocally, rainfall amounts of 30 to 50 mm are possible on Wednesday, with additional amounts possibly exceeding 40 mm Wednesday night.\n \nAt this time, the exact location, and amounts expected are uncertain and rainfall warnings may be issued later if necessary.\n\nPlease continue to monitor forecasts and alerts issued by Environment Canada.\n\n###\n\nPlease continue to monitor alerts and forecasts issued by Environment Canada. To report severe weather in British Columbia or Yukon, send an email to BCstorm@canada.ca or YTstorm@canada.ca or tweet reports using #BCStorm or #YTStorm.", "web"=>"http://weather.gc.ca/warnings/index_e.html", "resources"=>[], "event_codes"=>[{"profile:CAP-CP:Event:0.4"=>"weather"}], "parameters"=>[{"layer:EC-MSC-SMC:1.0:Alert_Type"=>"statement"}, {"layer:EC-MSC-SMC:1.0:Broadcast_Intrusive"=>"no"}, {"layer:SOREM:1.0:Broadcast_Immediately"=>"No"}, {"layer:EC-MSC-SMC:1.1:Parent_URI"=>"msc/alert/environment/hazard/alert-3.0-ascii/consolidated-xml-2.0/20190723180623921/WS_19_79_CWVR/SPS/10252351682658741201907230502_WS_19_79_CWVR/actual/en_proper_complete_u-fr_proper_complete_c/NinJo"}, {"layer:EC-MSC-SMC:1.1:CAP_count"=>"A:3610 M:22320 C:39689"}, {"profile:CAP-CP:0.4:MinorChange"=>"text"}, {"layer:EC-MSC-SMC:1.0:Alert_Location_Status"=>"active"}, {"layer:EC-MSC-SMC:1.0:Alert_Name"=>"special weather statement"}, {"layer:EC-MSC-SMC:1.0:Alert_Coverage"=>"Yukon and Northern British Columbia"}, {"layer:EC-MSC-SMC:1.1:Designation_Code"=>"WS_19_79_CWVR"}, {"layer:SOREM:2.0:WirelessImmediate"=>"No"}], "areas"=>[{"area_desc"=>"Muncho Lake Park - Stone Mountain Park", "circles"=>[], "geocodes"=>[{"layer:EC-MSC-SMC:1.0:CLC"=>"088200"}, {"profile:CAP-CP:Location:0.3"=>"5959007"}], "polygons"=>[{"points"=>[[58.4841, -123.8173], [58.4669, -123.833], [58.4331, -124.7028], [58.4669, -125.6669], [58.7982, -126.2569], [59.1829, -126.817], [59.3444, -126.3618], [59.4669, -125.9169], [59.4884, -124.8878], [59.4674, -123.817], [58.9859, -123.7664], [58.4844, -123.817], [58.4841, -123.8173]]}]}]}, {"language"=>"fr-CA", "categories"=>["Met"], "event"=>"météo", "response_types"=>["Monitor"], "urgency"=>"Future", "severity"=>"Minor", "certainty"=>"Possible", "audience"=>"grand public", "effective"=>"2019-07-23T18:06:23-00:00", "expires"=>"2019-07-24T02:06:23-00:00", "sender_name"=>"Environnement Canada", "headline"=>"bulletin météorologique spécial en vigueur", "description"=>"Une bande de pluie forte devrait se former mercredi après-midi entre Fort Nelson et Fort St John et s'étendre vers l'ouest jusqu'aux Rocheuses et au secteur de Muncho Lake.   La pluie forte devrait persister dans la nuit de mercredi à jeudi avant de cesser progressivement au cours de la journée de jeudi.\n\nOn prévoit de 30 à 50 mm de pluie par endroits mercredi et une quantité supplémentaire possiblement de plus 40 mm mercredi soir et dans la nuit de mercredi à jeudi.\n\nActuellement, il y a de l'incertitude quant aux endroits touchées par ce système et aux quantités prévues, mais des avertissements de pluie pourraient être émis plus tard s'il y a lieu.\n\nVeuillez continuer de surveiller les prévisions et les avertissements émis par Environnement Canada.\n\n###\n\nVeuillez continuer à surveiller les alertes et les prévisions émises par Environnement Canada. Pour signaler du temps violent en Colombie-Britannique ou au Yukon, envoyez un courriel à meteoBC@canada.ca ou à meteoYT@canada.ca ou publiez un gazouillis en utilisant le mot-clic #BCMeteo ou #YTMeteo.", "web"=>"http://meteo.gc.ca/warnings/index_f.html", "resources"=>[], "event_codes"=>[{"profile:CAP-CP:Event:0.4"=>"weather"}], "parameters"=>[{"layer:EC-MSC-SMC:1.0:Alert_Type"=>"statement"}, {"layer:EC-MSC-SMC:1.0:Broadcast_Intrusive"=>"no"}, {"layer:SOREM:1.0:Broadcast_Immediately"=>"No"}, {"layer:EC-MSC-SMC:1.1:Parent_URI"=>"msc/alert/environment/hazard/alert-3.0-ascii/consolidated-xml-2.0/20190723180623921/WS_19_79_CWVR/SPS/10252351682658741201907230502_WS_19_79_CWVR/actual/en_proper_complete_u-fr_proper_complete_c/NinJo"}, {"layer:EC-MSC-SMC:1.1:CAP_count"=>"A:3610 M:22320 C:39689"}, {"profile:CAP-CP:0.4:MinorChange"=>"text"}, {"layer:EC-MSC-SMC:1.0:Alert_Location_Status"=>"active"}, {"layer:EC-MSC-SMC:1.0:Alert_Name"=>"bulletin météorologique spécial"}, {"layer:EC-MSC-SMC:1.0:Alert_Coverage"=>"Yukon et le nord de la Colombie-Britannique"}, {"layer:EC-MSC-SMC:1.1:Designation_Code"=>"WS_19_79_CWVR"}, {"layer:SOREM:2.0:WirelessImmediate"=>"No"}], "areas"=>[{"area_desc"=>"Muncho Lake Park et Stone Mountain Park", "circles"=>[], "geocodes"=>[{"layer:EC-MSC-SMC:1.0:CLC"=>"088200"}, {"profile:CAP-CP:Location:0.3"=>"5959007"}], "polygons"=>[{"points"=>[[58.4841, -123.8173], [58.4669, -123.833], [58.4331, -124.7028], [58.4669, -125.6669], [58.7982, -126.2569], [59.1829, -126.817], [59.3444, -126.3618], [59.4669, -125.9169], [59.4884, -124.8878], [59.4674, -123.817], [58.9859, -123.7664], [58.4844, -123.817], [58.4841, -123.8173]]}]}]}]} 
      puts json_data
    </script>

I'm not using sprockets, I'm precompiling Opal into an app.js that I then include on my webpage and is being run in Firefox 68.0.1 on Linux.

**Comment by farrel** [comment]
Putting the code inside the <script> tags in a file and then running it with opal on the command line works as well for 1.0.0.

**Comment by elia** [comment]
On first sight it may be related to encoding, like utf-8 and similar things, works fine in the terminal (copied from the script tag you posted):

```
⤑ pbpaste | opal -v -                                                          ~
Opal v1.0.0
{"cap_version"=>"1.2", "identifier"=>"urn:oid:2.49.0.1.124.2128156370.2019", "sender"=>"cap-pac@canada.ca", "sent"=>"2019-07-23T18:07:23-00:00", "status"=>"Actual", "msg_type"=>"Update", "source"=>"Env. Can. - Can. Met. Ctr. – Montréal", "scope"=>"Public", "addresses"=>[], "codes"=>["profile:CAP-CP:0.4", "layer:SOREM:1.0", "layer:EC-MSC-SMC:1.0", "layer:WPAM:1.0", "layer:EC-MSC-SMC:1.1", "layer:SOREM:2.0"], "note"=>"Service Notice: Changes to ECCC CAP, of importance to users of ECCC CAP, are planned for deployment over the coming 2019 year. The first of these include a fix to an occasional but long standing CAP references issue. Coming later this Spring will be new and improved polygons. To have access to notices as they become available you are invited to subscribe to the following mailing list: http://lists.cmc.ec.gc.ca/mailman/listinfo/dd_info | Notification de service: Des changements au PAC d’ECCC, et qui sont d’importance aux utilisateurs, sont en développement pour un lancement au courant de l’année 2019. Un de ces premiers changements est un ajustement afin de résoudre un problème de longue date au niveau des références du PAC. Plus tard ce printemps, il y aura de nouveaux polygones améliorés. Afin d’avoir accès aux notifications dès qu’elles sont disponibles, vous êtes invités à vous inscrire à la liste de diffusion suivante: http://lists.cmc.ec.gc.ca/mailman/listinfo/dd_info", "references"=>["cap-pac@canada.ca,urn:oid:2.49.0.1.124.1634388885.2019,2019-07-23T11:50:13-00:00", "cap-pac@canada.ca,urn:oid:2.49.0.1.124.1558044061.2019,2019-07-23T11:51:13-00:00", "cap-pac@canada.ca,urn:oid:2.49.0.1.124.3681597925.2019,2019-07-23T13:53:18-00:00", "cap-pac@canada.ca,urn:oid:2.49.0.1.124.3530671066.2019,2019-07-23T13:54:18-00:00", "cap-pac@canada.ca,urn:oid:2.49.0.1.124.3035796889.2019,2019-07-23T18:06:23-00:00"], "incidents"=>[], "infos"=>[{"language"=>"en-CA", "categories"=>["Met"], "event"=>"weather", "response_types"=>["Monitor"], "urgency"=>"Future", "severity"=>"Minor", "certainty"=>"Possible", "audience"=>"general public", "effective"=>"2019-07-23T18:06:23-00:00", "expires"=>"2019-07-24T02:06:23-00:00", "sender_name"=>"Environment Canada", "headline"=>"special weather statement in effect", "description"=>"A heavy band of rain is expected to develop Wednesday afternoon between Fort Nelson and Fort St John, and extending westwards to the Rockies and Muncho Lake area. Heavy rain is forecast to continue through Wednesday night before easing through the day on Thursday. \n\nLocally, rainfall amounts of 30 to 50 mm are possible on Wednesday, with additional amounts possibly exceeding 40 mm Wednesday night.\n \nAt this time, the exact location, and amounts expected are uncertain and rainfall warnings may be issued later if necessary.\n\nPlease continue to monitor forecasts and alerts issued by Environment Canada.\n\n###\n\nPlease continue to monitor alerts and forecasts issued by Environment Canada. To report severe weather in British Columbia or Yukon, send an email to BCstorm@canada.ca or YTstorm@canada.ca or tweet reports using #BCStorm or #YTStorm.", "web"=>"http://weather.gc.ca/warnings/index_e.html", "resources"=>[], "event_codes"=>[{"profile:CAP-CP:Event:0.4"=>"weather"}], "parameters"=>[{"layer:EC-MSC-SMC:1.0:Alert_Type"=>"statement"}, {"layer:EC-MSC-SMC:1.0:Broadcast_Intrusive"=>"no"}, {"layer:SOREM:1.0:Broadcast_Immediately"=>"No"}, {"layer:EC-MSC-SMC:1.1:Parent_URI"=>"msc/alert/environment/hazard/alert-3.0-ascii/consolidated-xml-2.0/20190723180623921/WS_19_79_CWVR/SPS/10252351682658741201907230502_WS_19_79_CWVR/actual/en_proper_complete_u-fr_proper_complete_c/NinJo"}, {"layer:EC-MSC-SMC:1.1:CAP_count"=>"A:3610 M:22320 C:39689"}, {"profile:CAP-CP:0.4:MinorChange"=>"text"}, {"layer:EC-MSC-SMC:1.0:Alert_Location_Status"=>"active"}, {"layer:EC-MSC-SMC:1.0:Alert_Name"=>"special weather statement"}, {"layer:EC-MSC-SMC:1.0:Alert_Coverage"=>"Yukon and Northern British Columbia"}, {"layer:EC-MSC-SMC:1.1:Designation_Code"=>"WS_19_79_CWVR"}, {"layer:SOREM:2.0:WirelessImmediate"=>"No"}], "areas"=>[{"area_desc"=>"Muncho Lake Park - Stone Mountain Park", "circles"=>[], "geocodes"=>[{"layer:EC-MSC-SMC:1.0:CLC"=>"088200"}, {"profile:CAP-CP:Location:0.3"=>"5959007"}], "polygons"=>[{"points"=>[[58.4841, -123.8173], [58.4669, -123.833], [58.4331, -124.7028], [58.4669, -125.6669], [58.7982, -126.2569], [59.1829, -126.817], [59.3444, -126.3618], [59.4669, -125.9169], [59.4884, -124.8878], [59.4674, -123.817], [58.9859, -123.7664], [58.4844, -123.817], [58.4841, -123.8173]]}]}]}, {"language"=>"fr-CA", "categories"=>["Met"], "event"=>"météo", "response_types"=>["Monitor"], "urgency"=>"Future", "severity"=>"Minor", "certainty"=>"Possible", "audience"=>"grand public", "effective"=>"2019-07-23T18:06:23-00:00", "expires"=>"2019-07-24T02:06:23-00:00", "sender_name"=>"Environnement Canada", "headline"=>"bulletin météorologique spécial en vigueur", "description"=>"Une bande de pluie forte devrait se former mercredi après-midi entre Fort Nelson et Fort St John et s'étendre vers l'ouest jusqu'aux Rocheuses et au secteur de Muncho Lake.   La pluie forte devrait persister dans la nuit de mercredi à jeudi avant de cesser progressivement au cours de la journée de jeudi.\n\nOn prévoit de 30 à 50 mm de pluie par endroits mercredi et une quantité supplémentaire possiblement de plus 40 mm mercredi soir et dans la nuit de mercredi à jeudi.\n\nActuellement, il y a de l'incertitude quant aux endroits touchées par ce système et aux quantités prévues, mais des avertissements de pluie pourraient être émis plus tard s'il y a lieu.\n\nVeuillez continuer de surveiller les prévisions et les avertissements émis par Environnement Canada.\n\n###\n\nVeuillez continuer à surveiller les alertes et les prévisions émises par Environnement Canada. Pour signaler du temps violent en Colombie-Britannique ou au Yukon, envoyez un courriel à meteoBC@canada.ca ou à meteoYT@canada.ca ou publiez un gazouillis en utilisant le mot-clic #BCMeteo ou #YTMeteo.", "web"=>"http://meteo.gc.ca/warnings/index_f.html", "resources"=>[], "event_codes"=>[{"profile:CAP-CP:Event:0.4"=>"weather"}], "parameters"=>[{"layer:EC-MSC-SMC:1.0:Alert_Type"=>"statement"}, {"layer:EC-MSC-SMC:1.0:Broadcast_Intrusive"=>"no"}, {"layer:SOREM:1.0:Broadcast_Immediately"=>"No"}, {"layer:EC-MSC-SMC:1.1:Parent_URI"=>"msc/alert/environment/hazard/alert-3.0-ascii/consolidated-xml-2.0/20190723180623921/WS_19_79_CWVR/SPS/10252351682658741201907230502_WS_19_79_CWVR/actual/en_proper_complete_u-fr_proper_complete_c/NinJo"}, {"layer:EC-MSC-SMC:1.1:CAP_count"=>"A:3610 M:22320 C:39689"}, {"profile:CAP-CP:0.4:MinorChange"=>"text"}, {"layer:EC-MSC-SMC:1.0:Alert_Location_Status"=>"active"}, {"layer:EC-MSC-SMC:1.0:Alert_Name"=>"bulletin météorologique spécial"}, {"layer:EC-MSC-SMC:1.0:Alert_Coverage"=>"Yukon et le nord de la Colombie-Britannique"}, {"layer:EC-MSC-SMC:1.1:Designation_Code"=>"WS_19_79_CWVR"}, {"layer:SOREM:2.0:WirelessImmediate"=>"No"}], "areas"=>[{"area_desc"=>"Muncho Lake Park et Stone Mountain Park", "circles"=>[], "geocodes"=>[{"layer:EC-MSC-SMC:1.0:CLC"=>"088200"}, {"profile:CAP-CP:Location:0.3"=>"5959007"}], "polygons"=>[{"points"=>[[58.4841, -123.8173], [58.4669, -123.833], [58.4331, -124.7028], [58.4669, -125.6669], [58.7982, -126.2569], [59.1829, -126.817], [59.3444, -126.3618], [59.4669, -125.9169], [59.4884, -124.8878], [59.4674, -123.817], [58.9859, -123.7664], [58.4844, -123.817], [58.4841, -123.8173]]}]}]}]}
⤑                                                                              ~
```
