### ISSUE TITLE
Documentation suggestions for Opal

### ISSUE THREAD

**Issue by AstonJ** [opal/opal#2001]
What do you think Opal docs should cover? 
#### Here are some initial thoughts/suggestions:
- Introduction (what is Opal? What can you do with it? What can't you do with it? Why should you use it? etc) (page)
- Setting up Opal (page)
- Setting up Opal in a project (such as in Rails, in Sinatra, and other popular f/works) (page or two)
- The basics of Opal (chapter)
- Using Opal to do things that you'd usually use JS for - basics (such as https://pragmaticstudio.com/tutorials/rails-jquery-ajax and https://gorails.com/episodes/jquery-ujs-and-ajax) (chapter)
- Using Opal to do things that you'd usually use JS for - advanced (using frameworks or creating frameworks etc) (chapter)
- Then move on to other more complex stuff (chapter)
- Troubleshooting / debugging etc (chapter)

**Comment by elia** [comment]
Closing, this will still pop up in searches in case we need inspiration.
