### ISSUE TITLE
Object.__proto__.constructor.$$base_module is enumerable

### ISSUE THREAD

**Issue by ZeekoZhu** [opal/opal#2019]
When using asciidoctot.js with [object-hash](https://www.npmjs.com/package/object-hash), object-hash will throw error during hashing `Object.__proto__.constructor`, because it finds the `$$base_module` property on `Object.__proto__.constructor`, then try to hash it.

The `$$base_module` property on `Object.__proto__.constructor` is enumerable:

![image](https://user-images.githubusercontent.com/13861843/66839892-bc517300-ef99-11e9-9352-e9ebbb1bde6c.png)

Maybe related to https://github.com/opal/opal/blob/83bc62baa06a5387d1ed8bcf7bee382646f08c9d/opal/corelib/runtime.js#L309

**Comment by hmdne** [comment]
I can't reproduce it anymore.

**Comment by elia** [comment]
Closing it! Thanks for checking @hmdne 👍
