### ISSUE TITLE
define_method problem at main

### ISSUE THREAD

**Issue by jeezs** [opal/opal#2028]
define_method(:my_meth) do |opts|;puts 'ok';end => define_method: undefined method `define_method' for main undefined
the error occur when using static version of opal.

**Comment by ahmadine** [comment]
Make sure you load opal like this:

`<script src="https://cdn.opalrb.com/opal/current/opal.js" onload="Opal.load('opal')"></script>`

Not like this:

`<script src="https://cdn.opalrb.com/opal/current/opal.js"></script>`

**Comment by jeezs** [comment]
Thanks for your reply,
Opal is loaded using  
`<script src="https://cdn.opalrb.com/opal/current/opal.js" onload="Opal.load('opal')"></script>`
but define_method doesn't work.

**Comment by ahmadine** [comment]
Could you provide a script in a larger context, so we would be able to reproduce the issue?

**Comment by jeezs** [comment]
The project is pretty large i have just shrink it at its minimum vital size here is:
`<!DOCTYPE html>
<html>
<head>
    <meta name='viewport' content='initial-scale=1, width=device-width, viewport-fit=cover'>
    <meta charset='UTF-8'/>
    <title>atome</title>
    <meta name='msapplication-tap-highlight' content='no'>
    <meta name='format-detection' content='telephone=no'>
    <script src='js/opal.min.js'></script>
    <script type='text/javascript'>
        Opal.load('opal')
    </script>
    <script src='js/native.min.js'></script>
    <script type='text/javascript'>
        Opal.load('native')
    </script>
    <script src='js/opal-parser.min.js'></script>
    <script type='text/javascript'>
        Opal.load('opal-parser')
    </script>
    <script src='js/opal-source-maps.min.js'></script>
   <script type='text/javascript'>
      Opal.load('opal-source-maps')
   </script>
   <script>
		Opal.eval("define_method(:my_meth) do |opts|;puts 'ok';end ")
   </script>
</head>
</html>
`
 pleas note that opal, native and opal parser comes fromhttp://cdn.opalrb.com/opal/master/
Thanks for help

**Comment by elia** [comment]
I've tried and the problem seems to be linked to just the main object, in fact using `singleton_class.define_method` works. I'll send a PR to fix that soon 👍
