### ISSUE TITLE
opal-repl doesn't work in master

### ISSUE THREAD

**Issue by ahmadine** [opal/opal#2042]
opal-repl doesn't work in master due to this error:

```
Traceback (most recent call last):
        11: from bin/opal-repl:4:in `<main>'
        10: from bin/opal-repl:4:in `load'
         9: from /home/user/opal/exe/opal-repl:86:in `<top (required)>'
         8: from /home/user/opal/exe/opal-repl:23:in `run'
         7: from /usr/local/share/gems/gems/mini_racer-0.2.6/lib/mini_racer.rb:198:in `eval'
         6: from /usr/local/share/gems/gems/mini_racer-0.2.6/lib/mini_racer.rb:198:in `synchronize'
         5: from /usr/local/share/gems/gems/mini_racer-0.2.6/lib/mini_racer.rb:200:in `block in eval'
         4: from /usr/local/share/gems/gems/mini_racer-0.2.6/lib/mini_racer.rb:286:in `timeout'
         3: from /usr/local/share/gems/gems/mini_racer-0.2.6/lib/mini_racer.rb:201:in `block (2 levels) in eval'
         2: from /usr/local/share/gems/gems/mini_racer-0.2.6/lib/mini_racer.rb:201:in `eval_unsafe'
         1: from JavaScript at <anonymous>:2449:4
JavaScript at <anonymous>:25:28: TypeError: Cannot read property 'console' of undefined (MiniRacer::RuntimeError)
```

I did a git bisect to note what started this behaviour and it's this commit:

```
390f302b8e2a9d8334f9c990009b7b1257ece0aa is the first bad commit
commit 390f302b8e2a9d8334f9c990009b7b1257ece0aa
Author: Elia Schito <elia@schito.me>
Date:   Sun Nov 10 23:53:06 2019 +0100

    Typo, was supposed to be "use strict";

 opal/corelib/runtime.js | 5 ++++-
 1 file changed, 4 insertions(+), 1 deletion(-)
```

**Comment by ahmadine** [comment]
390f302b8e2a9d8334f9c990009b7b1257ece0aa

**Comment by ahmadine** [comment]
This is the code that tries to trigger the issue on the smallest surface possible:

```ruby
#!/usr/bin/env ruby
require 'mini_racer'

JS = <<endjs
  (function() {
    "use strict";
    var global_object = this;
    // MiniRacer defines neither window nor global and this is undefined in the strict mode
    typeof (global_object.console); // Whoops
  }());
endjs

v8 = MiniRacer::Context.new
v8.eval(JS)
```

**Comment by ahmadine** [comment]
This code succeeds:

```
#!/usr/bin/env ruby
require 'mini_racer'

JS = <<endjs
  (function() {
    "use strict";
    var global_object = this;
    // MiniRacer defines neither window nor global and this is undefined
    typeof (global_object.console); // Yay!
  }).call(this);
endjs

v8 = MiniRacer::Context.new
v8.eval(JS)
```

**Comment by ahmadine** [comment]
This commit replaced the `}).call(this)` line in runtime.js with `}).call()`: ca41d7ff60eb93ccc3048c7dfad530a4bb5a3c99

**Comment by ahmadine** [comment]
CC @Mogztter

**Comment by Mogztter** [comment]
> That means, among other things, that in browsers it's no longer possible to reference the window object through this inside a strict mode function.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode#Securing_JavaScript


The `global_object` should be defined by one of these lines:
https://github.com/opal/opal/blob/ca41d7ff60eb93ccc3048c7dfad530a4bb5a3c99/opal/corelib/runtime.js#L19-L20

> This code succeeds:

Is it working if you move the `"use strict";` before the function?

```rb
#!/usr/bin/env ruby
require 'mini_racer'

JS = <<endjs
  "use strict";
  (function() {
    var global_object = this;
    // MiniRacer defines neither window nor global and this is defined now
    typeof (global_object.console); // should fail?
  }).call(this);
endjs

v8 = MiniRacer::Context.new
v8.eval(JS)
```

I guess no, right?

**Comment by Mogztter** [comment]
It seems to work if we use `call`, the `window` object will be bound to `this` in the function.
But I wonder why the following line is not working:

```js
if (typeof(window) !== 'undefined') { global_object = window; }
```

**Comment by ahmadine** [comment]
>Is it working if you move the `"use strict";` before the function?

Yes, it does. It looks like the semantics of the strict mode are that in the strict mode call-ed functions set `this` to `undefined` instead of the global object, and that's all the difference on this part.

>The `global_object` should be defined by one of these lines:

MiniRacer is not a browser, so it doesn't set `window`

MiniRacer is not Node (just V8), it's a minimal environment, so it doesn't set `global`

**Comment by ahmadine** [comment]
And, for the record, the global object of the Web Workers, is called, yes, you guessed it, `self`! No, not `this` (which is a reserved keyword), `self`. If I'm correct, this means that this bug currently extends to the Web Workers as well.

**Comment by ahmadine** [comment]
This further describes the behaviour of `call` in the strict mode and it correctly notes this issue:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/call

**Comment by Mogztter** [comment]
It makes sense. 
I misunderstood the strict mode restriction... I thought that `this` was no longer a reference to the global object.
Another useful link on the global object where `self` is mentioned: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis

Could you please try the following code on MiniRacer:

```js
var getGlobal = function () { 
  if (typeof self !== 'undefined') { return self; } 
  if (typeof window !== 'undefined') { return window; } 
  if (typeof global !== 'undefined') { return global; } 
  throw new Error('unable to locate global object'); 
}; 

var globals = getGlobal(); 
```

We could a similar function to resolve the global object in the Opal runtime.
But ideally we should not use the global object but instead `export` to create an Opal module: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/export

**Comment by ahmadine** [comment]
Nope. That doesn't work, unfortunately.

In the ideal world we would not pollute the prototypes as well, but Opal works the way Opal works. Besides, we also need the global object to set Opal.global.

**Comment by elia** [comment]
We probably should use [globalThis](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis) and fallback to the current code for older envs

**Comment by ahmadine** [comment]
globalThis works in MiniRacer

```ruby
#!/usr/bin/env ruby
require 'mini_racer'

JS = <<endjs
  "use strict";

  var getGlobal = function () {
    if (typeof globalThis !== 'undefined') { return globalThis; }
    if (typeof self !== 'undefined') { return self; }
    if (typeof window !== 'undefined') { return window; }
    if (typeof global !== 'undefined') { return global; }
    throw new Error('unable to locate global object');
  };

  var globals = getGlobal();
endjs

v8 = MiniRacer::Context.new
v8.eval(JS)
```

**Comment by Mogztter** [comment]
> We probably should use [globalThis](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis) and fallback to the current code for older envs

Yes 👍

**Comment by ahmadine** [comment]
For the most compatible solution I would use something like `new Function("return this;")();` as a fallback, because it seems like (according to this documentation), Function returns to the global context, but it may not work in environments with CSP enabled and configured to disallow eval statements.
