### ISSUE TITLE
Problem accessing  js function from ruby

### ISSUE THREAD

**Issue by jeezs** [opal/opal#2055]
hello here is a very simple code that shows a problem calling  js function from ruby.
`
%x{
function verif(){
alert("verfified!");
}
}
$$.verif()
`
the function is not called

**Comment by elia** [comment]
That's because that functions is quite surely not defined on the global scope.

If you want to maintain the definition as is you should then call the function with an x-string, e.g.:

```rb
%x{ function verif(){ alert("verfified!"); } }
`verif()` 
```


If you want to call it via `$$` then it's better to define it on the global object, e.g.:

```rb
%x{window.verif = function(){ return "verified!" }}
$$.verif # => "verified!"
```
