### ISSUE TITLE
wrong method called

### ISSUE THREAD

**Issue by jeezs** [opal/opal#2059]
Hello,
there's a problem call a method of a class if this method exist outside the class the method is call here is an example :

```rb
def my_fct()
  puts "function 'my_fct' should not be called"
end

class My_class
  def another_meth()
    puts "dummy meth"
  end
end

my_var=My_class.new
my_var.my_fct()
```

**Comment by janbiedermann** [comment]
Opal doesn't really have a `main` Object, instead `Object` is used. If you define a global method, it is defined on `Object`. As most classes inherit from Object, the method is then also available there.
You may give `my_fct` its own scope/class/module.

**Comment by jeezs** [comment]
Thanks for the answer.
I use Opal for education purpose.
Its only  a problem when students use pure ruby code example found on he net, then  the result is not the one expected.

**Comment by elia** [comment]
To add on what @janbiedermann said, the top-level object is actually an `Object` instance with a couple of tweaks, including the one that makes methods defined at the root will be added to the `Object` class. To define methods that will only work at the root you can use `def self.`:


```rb
def self.my_fct
  puts "function 'my_fct' should not be called"
end

class My_class
  def another_meth
    puts "dummy meth"
  end
end

my_var=My_class.new
my_var.my_fct # => NoMethodError: undefined method ‘my_fct’ for #<My_class:0x00007fdbbd0d28e8>
```
