### ISSUE TITLE
require('path_in_ruby_gem') can't find file

### ISSUE THREAD

**Issue by DanielHeath** [opal/opal#2082]
I'm using bundler, if that helps.

When running a script with `bundle exec my_script.rb`, `require('some_gem')` works fine. 

When compiling the script with `bundle exec opal my_script.rb`, the require isn't found.

Is there a way to make the command-line automatically able to resolve everything within the bundle?

**Comment by elia** [comment]
@DanielHeath sure, there's the `--gem some_gem` option. E.g.:

```
⤑ gem install rgb
Successfully installed rgb-0.1.0
Parsing documentation for rgb-0.1.0
Done installing documentation for rgb after 0 seconds
1 gem installed
⤑ opal -v --gem rgb -rrgb -e'p RGB::Color.from_rgb_hex("#333333").darken_percent(10).to_rgb_hex'
Opal v1.0.3
Failed to load WithCLexer, using pure Ruby lexer
"#2E2E2E"
⤑ 
```
