### ISSUE TITLE
Source maps get broken in Firefox by this code snippet

### ISSUE THREAD

**Issue by BenjiFlaming** [opal/opal#2084]
I've identified a small code snippet which causes source maps to break in Firefox:

```ruby
require 'opal'

class Foo
  def self.bar=(value)
    puts value # same results for any method body
  end
end

Foo.bar = 'baz' # same results for any value

raise "This is an exception!"
```

If the `Foo.bar = 'baz'` line is commented out, or if it is replaced with

```ruby
Foo.send(:bar=, 'baz')
```

then the backtrace generated by the exception contains a working source map.  With the line unmodified, however, under Firefox (but not Chrome) the backtrace links only to the compiled JS output.

Regardless, the method call works correctly (the value supplied to `bar` is printed to the console), so Opal itself is parsing things correctly, but something seems to be going slightly wrong with source map generation.

I've confirmed this behavior with Opal 1.0.3, and the current master branch - both with and without the `c_lexer` gem.

If there's anything else I can do to help with this (short of digging into the source map generation code itself - just don't have time right now), let me know.  I'm hoping that this might be a quick and easy fix for somebody who knows the appropriate parts of the Opal sources.  :)

**Comment by hmdne** [comment]
Apparently Firefox 77.0 has improved source map support. Can you recheck the issue?

**Comment by elia** [comment]
> I'm hoping that this might be a quick and easy fix for somebody who knows the appropriate parts of the Opal sources. :)

Unfortunately reasoning around sourcemaps is not that easy, debugging and tracing back a bug within the firefox implementation it's probably even harder. Let's see if firefox has fixed itself first 😊

**Comment by hmdne** [comment]
Most probably it was related to -1 lines being generated before #2273 because now it works well
