### ISSUE TITLE
accent crash opal

### ISSUE THREAD

**Issue by atomecorp** [opal/opal#2094]
any  accented char crash opal ex :
`puts "règle"`

**Comment by elia** [comment]
I can get opal 1.0.3 running on node.js correctly printing the accented char, which version/platform are you getting the crashes on?

Please note the Opal assumes to run inside web-pages encoded in utf-8 when running in a browser.

**Comment by atomecorp** [comment]
﻿Hello Elia,

I use Opal V 1.0.3. 
I have the problem my html file have the  utf-8 tag. 

I’ve try the following code : « puts  ’été’ » on  https://opalrb.com/try/ it show the problem 

Thanks for your help. 


Jean-Eric Godard

atome
CEO
+ 33 (0)6 52 57 55 17
jean-eric.godard@atome.io

74 bis avenue des Thermes - 63400 Chamalières

**Comment by atomecorp** [comment]
it seems that it's the parser that have problem with encoding not Opal.
