### ISSUE TITLE
POSIX bracket expressions not supported

### ISSUE THREAD

**Issue by strathmeyer** [opal/opal#2101]
opal (1.0.3)

In IRB:
```
> "Player   1".gsub(/[[:space:]]+/, " ")
 => "Player 1"
```

In Opal:
```
puts "Player   1".gsub(/[[:space:]]+/, " ").inspect
"Player   1"
```

As a workaround, I am using `.gsub(/\s+/, " ")` which only matches ASCII whitespace.

**Comment by hmdne** [comment]
Opal mostly doesn't emulate Ruby regexp engine, it just uses the JS regexp engine which has no support for POSIX expressions. I have 2 answers to that question, probably none of which will satisfy you.

1. Option 1 - doesn't work in Safari
/[[:space:]]+/ has a JS equivalent in a form of /[\p{Z}\t\r\n\v\f]+/u
Do note /u.

See: https://regular-expressions.mobi/posixbrackets.html?wlr=1

2. Option 2 - will increase your code size considerably (possibly even by a megabyte) and will require some special care when handling
There is an Opal-Onigmo library which basically wraps the Ruby Regexp engine in a WebAssembly module.

https://github.com/interscript/opal-onigmo

See also: https://github.com/interscript/interscript/blob/master/opal-onigmo.md
