### ISSUE TITLE
Hash#delete(key) bug if key is the same primitive string as actual key but different string object

### ISSUE THREAD

**Issue by lionelchauvin** [opal/opal#2104]
This code properly works on ruby MRI but h.inspect crashes with Opal 0.11.4:
`h = {'a' => 'a'}; k = String.new(h.keys.first); h.delete(k); puts h.inspect`

This is because === is used at this line:
https://github.com/opal/opal/blob/master/opal/corelib/runtime.js#L2048

As a reminder:
```javascript
`#{String.new('a')} === #{String.new('a')}` # => false
```

So the key is not removed from h.$$keys and at this line
https://github.com/opal/opal/blob/master/opal/corelib/hash.rb#L675
value is undefined then value.$inspect() can't work.

**Comment by elia** [comment]
https://github.com/opal/opal/pull/2106 should fix the problem, thanks for the report!
