### ISSUE TITLE
Ruby program creates a file - can I read this file from JavaScript

### ISSUE THREAD

**Issue by donalffons** [opal/opal#2110]
Hi, this might be a super simple question, but I wasn't able to find an answer to it:

Can I read files, created by a ruby program, from JavaScript code to process its contents? If yes, how?

I do greatly appreciate your help and your work on this project. Thanks :-)

**Comment by hmdne** [comment]
I see 2 possibilities.
1. You work with your webserver. It serves files and JS (Opal) loads them via Ajax.
2. You can make a file named "files.js.erb" in your Opal load path. This file can look something like this:

```
window.files = <%= JSON.dump(Dir["files/*"].map(&File.method(:read))) %>;
```

Then in your Opal code you do something like this:

```
require "files" # Yes, this will load the "files.js.erb" just like it would load "other.rb"
require "native" # For Native::Object

files = Native::Object.new(`window.files`)
files["files/xyz.txt"] # => contents of file files/xyz.txt
```

I know this will work with Opal::Builder and Opal::Sprockets. I have no experience with webpack loaders.

**Comment by donalffons** [comment]
Thanks a lot! That's super useful information. Possibility 2 sounds like what I want to do. I will start digging deeper into Opal, then. Cheers!
