### ISSUE TITLE
Runtime Referrence Error: NodeJS / Electron : stdlib/nashorn.rb : print is not defined

### ISSUE THREAD

**Issue by mistergibson** [opal/opal#2125]
If I require nashorn.rb in my project I get a runtime error. Evidently 'print' is being referenced without it existing. It compiles ok, it just throws this error:
![Error](https://user-images.githubusercontent.com/174752/95652912-6084d180-0aa9-11eb-9153-4de99203ffec.png)
If I recall it occurs when I attempt to call 'puts' on a test script.

**Comment by hmdne** [comment]
Don't do it unless you are running Opal under Nashorn.

https://en.wikipedia.org/wiki/Nashorn_(JavaScript_engine)
