### ISSUE TITLE
LoadError: cannot load such file -- erb

### ISSUE THREAD

**Issue by ghaiklor-wix** [opal/opal#2126]
We are using `opal-build` command to build separate modules of the system; we don't need the whole runtime for our purposes. In the build step it looks like this:

```
bundle exec opal-build erb > ruby/erb.js && bundle exec opal-build opal/erb > ruby/opal-erb.js && and so on
```

It worked just fine until we upgrade to v1.0.3. After upgrade it started throwing:

```
LoadError: cannot load such file -- erb
```

Our build scripts:

```
   "build:opal:base64": "bundle exec opal-build base64 > ruby/base64.js",
    "build:opal:compiler": "bundle exec opal-build opal/compiler > ruby/opal-compiler.js",
    "build:opal:corelib-string-unpack": "bundle exec opal-build corelib/string/unpack > ruby/corelib-string-unpack.js",
    "build:opal:erb": "bundle exec opal-build erb > ruby/erb.js && bundle exec opal-build opal/erb > ruby/opal-erb.js",
    "build:opal:json": "bundle exec opal-build json > ruby/json.js",
    "build:opal:runtime": "bundle exec opal-build opal > ruby/opal.js",
    "build:opal:template": "bundle exec opal-build template > ruby/template.js",
    "build:opal": "mkdir -p ruby && npm run build:opal:base64 && npm run build:opal:compiler && npm run build:opal:corelib-string-unpack && npm run build:opal:erb && npm run build:opal:json && npm run build:opal:runtime && npm run build:opal:template",
    "build:vendor": "bundle install --path vendor/bundle",
    "build": "npm run build:vendor && npm run build:opal",
```

What we are trying to achieve with v1.0.3 is to render the erb template in JavaScript like so:

```
eval(globalThis.Opal.Opal.ERB.$compile(Buffer.from('__TEMPLATE__', 'base64').toString('utf8'), 'mytemplate'));

var ctx = globalThis.Opal.get('Object').$new();
var json = Buffer.from('__FIELDS__', 'base64').toString('utf8');
var jsFields = JSON.parse(json);
var rubyFields = globalThis.Opal.get('JSON').$parse(json);
Object.keys(jsFields).forEach(function (field) {
  ctx.$instance_variable_set("@" + field, rubyFields['$[]'](field));
});

output = globalThis.Opal.Template['$[]']('mytemplate').$render(ctx);
```

**Comment by hmdne** [comment]
From what I understand, you may want to use stubbing. Depending on what your opal-build script is, if it uses Opal::Builder, you can do this thing:

https://github.com/opal/opal/blob/master/lib/opal/builder.rb#L135

So, for example:

```ruby
b = Opal::Builder.new
b.stubs << "erb"
```

This will make Opal not try to add a file to your build, but resolve it at runtime.

**Comment by ghaiklor-wix** [comment]
We don't have custom `opal-build` command; I thought it is triggering your task 🤔

**Comment by hmdne** [comment]
Right, I haven't heard about `opal-build` before (I used `opal` mostly). But anyway it has a `-s` switch which may come useful to you.

**Comment by ghaiklor-wix** [comment]
I've added `bundle exec opal-build --stub erb --output ruby/opal-erb.js opal/erb` and still getting the same error

**Comment by hmdne** [comment]
To make sure we are on the same page - does this happen at build time or runtime?

**Comment by ghaiklor-wix** [comment]
runtime, I'll try add more details...

we use `opal-build` for several parts of Opal runtime, like base64, template, erb, etc... so we are compiling your stdlib to JavaScript files, but not all of them, only required parts. The process it pretty straithforward, for each lib we call `opal-build --ouput somewhere <your stdlib here>`.

We are bundling everything togehter as one file that provides Opal runtime for our needs. Afterwards, we are doing some voodo I'm not proud of:

```
<HERE LIES OPAL RUNTIME>

eval(globalThis.Opal.Opal.ERB.$compile(Buffer.from('__TEMPLATE__', 'base64').toString('utf8'), 'mytemplate'));

var ctx = globalThis.Opal.get('Object').$new();
var json = Buffer.from('__FIELDS__', 'base64').toString('utf8');
var jsFields = JSON.parse(json);
var rubyFields = globalThis.Opal.get('JSON').$parse(json);
Object.keys(jsFields).forEach(function (field) {
  ctx.$instance_variable_set("@" + field, rubyFields['$[]'](field));
});

output = globalThis.Opal.Template['$[]']('mytemplate').$render(ctx);
```

So, we are using the code above, to interop with Opal runtime, create a template there, an object with the fields and render the template itself. Afterwards, we can use `output` as a rendered template and get the result back to JavaScript context (the callee, I mean).

**Comment by hmdne** [comment]
I think I got it. You need to add this file to your `<HERE LIES OPAL RUNTIME>` part:

https://github.com/opal/opal/blob/master/stdlib/erb.rb

I assume it's probably because Opal in the older versions didn't automatically require this in the built templates, but now it does.

**Comment by hmdne** [comment]
And by the way you can disregard the stubbing tip. It doesn't appear to be needed.

**Comment by ghaiklor-wix** [comment]
Hm, I tried add both `stdlib/erb` and `opal/erb`, no luck. Let me double check that.

**Comment by ghaiklor-wix** [comment]
Ok, we have the following build

```
"build:opal:erb": "bundle exec opal-build --output ruby/erb.js erb && bundle exec opal-build --output ruby/opal-erb.js opal/erb",
```

Afterwards, we are bundling them in the following order:

```
      '../../ruby/opal.js',
      '../../ruby/opal-compiler.js',
      '../../ruby/opal-erb.js',
      '../../ruby/corelib-string-unpack.js',
      '../../ruby/json.js',
      '../../ruby/base64.js',
      '../../ruby/template.js',
      '../../ruby/erb.js'
```

Still getting the error 🤯

**Comment by hmdne** [comment]
OK I understand. See, the built erb.js file actually registers this thing as loaded:
`Opal.modules["template"] = function(Opal) {`
But not "erb". So it throws when trying to require it. This can be solved in either way:
During building of a template you can stub "erb" or you can add a line: `Opal.loaded("erb")` just after erb has been loaded but before the rest of your code is executed.

**Comment by ghaiklor-wix** [comment]
Trying...

```
__OPAL__

globalThis.Opal.loaded('erb');
eval(globalThis.Opal.Opal.ERB.$compile(Buffer.from('__TEMPLATE__', 'base64').toString('utf8'), 'mytemplate'));

// the rest of the code
```

**Comment by ghaiklor-wix** [comment]
Strange, I'm debuggint Opal runtime right now and I see that Opal object does not have the properties we are talking about here 😺

**Comment by ghaiklor-wix** [comment]
I think I got it

```
eval(globalThis.Opal.Opal.ERB.$compile(Buffer.from('__TEMPLATE__', 'base64').toString('utf8'), 'mytemplate'));
```

This line above, I don't know who and why wrapped it into `eval`, but while debugging I noticed that `eval` is running in separate context where Opal compiler only lives. How does it work on old version, I don't know.

But it seems like it is something, seems like I'm no more getting the error. Although, it still does not work, will continue debugging.

**Comment by hmdne** [comment]
eval is perfectly OK. $compile returns the JS code (which can be cached!).

**Comment by ghaiklor-wix** [comment]
Yeah, but `compile` returned a JS code that does not have `erb` module. I stepped into compile method and found out that that is the place where it tries to require an `erb` module, but since it runs in separate context, which does not have it, it throws an error.

**Comment by hmdne** [comment]
The context thing is weird. I never encountered such an issue, but I'm not familiar with the Node environment. Maybe try new Function()() instead of eval?

**Comment by hmdne** [comment]
Anyway, it's not that we "have" an erb module, because we don't. This approach just loaded this module as if it were in a Rubyesque "main" function. We did Opal.loaded, which is great, but still Opal compiler may try to read it, so maybe stubbing it in addition (during the template compilation phase) can help.

**Comment by hmdne** [comment]
Hm, seeing as the compilation actually worked, you can disregard the previous comment. It's quite weird to me that eval would reset the context.

**Comment by ghaiklor-wix** [comment]
Yeah, I was getting `cannot load such file` until I removed `eval()`

**Comment by ghaiklor-wix** [comment]
I see that runtime lacks `get()` method. What is the replacement for that?

**Comment by hmdne** [comment]
Oh, it's simply Opal.Object. I don't know, Opal has no get method.

**Comment by hmdne** [comment]
Didn't Opal.loaded help with this issue?

**Comment by ghaiklor-wix** [comment]
Ok, well, it seems like eval is required after all. Opal compiles the template and returns the JavaScript code, but we need to execute it AFAIU to template appear in `Opal.Template`, right?

**Comment by ghaiklor-wix** [comment]
That's for sure now, the problem with cannot load such file in the following line

```
eval(Opal.Opal.ERB.$compile(Buffer.from('__TEMPLATE__', 'base64').toString('utf8'), 'my-template'))
```

We have a Ruby code, that we are compiling to JavaScript code. That code in result emits a line of code with `require 'erb'` and somehow it can't be found when `eval`-uating.

**Comment by hmdne** [comment]
Of course eval is required.

This will fix all our problems: it's not `Opal.loaded("erb");` but `Opal.loaded(["erb"]);` :D

**Comment by ghaiklor-wix** [comment]
🎉 It worked 😆 

Still added `json` and `base64` modules as well, but it works now 👍

**Comment by hmdne** [comment]
Great. Anyway I still suggest you build the template in a different context and cache the built JS code. Then later don't include opal-compiler when executing it. This will greatly improve your performance.

**Comment by ghaiklor-wix** [comment]
Yeah, since I have a working solution with 1.0.3 now, I can optimize it. Thanks for the help and chatting! 🍷
