### ISSUE TITLE
Use stdlib in browser

### ISSUE THREAD

**Issue by log69** [opal/opal#2134]
Dear all, thanks for Opal, it is awesome. I've got the following ruby code:

    require "opal"
    require "date"
    p Date.parse("2020-01-01")

I translate it to js with "opal -e 'code' -c" and then include the result in an HTML page:

	<!doctype html>
	<html lang='en'>
	<head>
	<meta charset='utf-8'>
	<meta name='viewport' content='width=device-width'>
	<title>test</title>
	</head>
	<body>

	<script src='opal/opal.min.js'></script>
	<script>
	/* Generated by Opal 1.0.3 */
	(function(Opal) {
	var self = Opal.top, $nesting = [], nil = Opal.nil, $$$ = Opal.const_get_qualified, $$ = Opal.const_get_relative, $breaker = Opal.breaker, $slice = Opal.slice;

	Opal.add_stubs(['$require', '$p', '$parse']);

	self.$require("opal");
	self.$require("date");
	return self.$p($$($nesting, 'Date').$parse("2020-01-01"));
	})(Opal);
	</script>

	</body>
	</html>

When opening it in a browser I get the following error: "uninitialized constant Date". However running this from the console it works nicely printing "2020-01-01":

        opal -e 'require "date"; p Date.parse("2020-01-01")'

What am I missing here? Should I load some other scripts as well to be able to require classes from the stdlib? Thanks.

**Comment by hmdne** [comment]
Well, yes. `opal.min.js` doesn't include date. See this:

https://cdn.opalrb.com/opal/1.0.0/index.html

You may need to add `date.min.js` as well.

**Comment by log69** [comment]
Still cannot get it to work. Getting several kind of error messages when including date.min.js and referencing to this in the code by "require 'date'".

Anyways I've managed to handle it by running the following from the console and including dependencies from there:

    opal -r date -r time -r base64 -c mycode.rb > mycode.js

**Comment by elia** [comment]
@log69 with the latest command you posted you correctly generate a single file containing all you need, so you can also skip including `opal.min.js`. You'll have to minify it yourself but at that point at least you'll be minifying the whole bundle.

**Comment by log69** [comment]
Exactly what I did. I removed the script src reference and minified the whole thing. Thanks for the suggestion.

**Comment by log69** [comment]
Nice piece of work., Opal is.
