### ISSUE TITLE
"Enable/Disable source map"?

### ISSUE THREAD

**Issue by JunichiIto** [opal/opal#2146]
`opal --help` describes about `-P` / `--map` option like this:

```
-P, --map FILE                   Enable/Disable source map
```

However, as long as I tried, it is used to specify the output path of source map. Are there any options to disable to create source map?

**Comment by elia** [comment]
The option takes a path to the map-file, like this:

```
Last login: Wed Dec 16 20:09:25 on ttys004
⤑ cd /tmp                                                                      ~
⤑ echo "require 'opal'" > app.rb                                            /tmp
⤑ mkdir dist                                                                /tmp
⤑ opal -P dist/app.map --compile app.rb > dist/app.js                       /tmp
Failed to load WithCLexer, using pure Ruby lexer
⤑ ll dist/                                                                  /tmp
total 5184
-rw-r--r--  1 elia  wheel   1.8M Dec 16 20:11 app.js
-rw-r--r--  1 elia  wheel   792K Dec 16 20:11 app.map
⤑ opal -v                                                                   /tmp
Opal v1.0.4
⤑                                                                           /tmp
```

Can you confirm that it work when provided a file?

**Comment by JunichiIto** [comment]
> Can you confirm that it work when provided a file?

Yes, the map-file was created. However, my question is the description in `opal -- help`. It says "Enable/Disable source map." Is it correct? I guess it should be "Output path for map-file" or anything.

**Comment by elia** [comment]
Thanks, that's a good suggestion, I'll change that 👍

**Comment by elia** [comment]
Updated in v1.0.5

**Comment by JunichiIto** [comment]
Thank you for the change!
