### ISSUE TITLE
SecureRandom: Math.random() is not secure

### ISSUE THREAD

**Issue by hmdne** [opal/opal#2170]
https://github.com/opal/opal/blob/master/stdlib/securerandom.rb uses Math.random() which is not cryptographically secure and the name SecureRandom implies that.

**Comment by hmdne** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Crypto/getRandomValues

**Comment by hmdne** [comment]
https://stackoverflow.com/a/19203948

**Comment by martin-schoettler** [comment]
I am somewhat worried that this _security issue_ is not marked as a bug, not yet solved and no milestone assigned. (I see also a number of open issues marked as bugs, which are many years old.)

I fear, we cannot risk to use Opal in our projects until the state of Opal becomes more reliable. (I currently evaluate, whether we can replace CoffeeScript by Opal in our Rails projects.)

BTW: To use the Crypto API for true random values should be rather simple: One way is to implement "await" (see my proposal in https://github.com/opal/opal/issues/1956). But that would imply compiling all methods using Secure Random to async functions. Therefore I recommend to create a pool of random bytes in the background, which should be filled by calling Crypto.GetRandomValues() whenever the number goes below a low watermark. (That is also the approach of the SJCL and JSBN libraries.) 

Martin Schöttler, matique UG

**Comment by elia** [comment]
@martin-schoettler thanks for pointing this out, I added both `bug` and `help wanted`. That should reflect the current situation. 

The best would be to see a PR from someone willing to fix this issue, either by making `securerandom.rb` actually secure or as a temporary solution add a warning at the top that can clarify it's just a stub to make it easier to work with existing libraries when security is not a concern.

**Comment by hmdne** [comment]
@martin-schoettler We don't actually need async for this thing because this function is synchronous.

**Comment by martin-schoettler** [comment]
@hmdne: Yes you are right, _this_ function (crypto.getRandomValues()) is synchronous. (Sorry that I forgot to check that.)
