### ISSUE TITLE
Can we make freezing possible?

### ISSUE THREAD

**Issue by hmdne** [opal/opal#2176]
It seems like JS has a freezing method with similar semantics...

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/freeze

**Comment by elia** [comment]
I think I tried that in the past, but it's a vague memory, the main issue that can arise and we should verify is if an object has some lazy internal props that it will change even for a frozen object, e.g. if the singleton class is lazily initialized and it's called after a freeze what happens?
