### ISSUE TITLE
Can opal compile itself to JavaScript?

### ISSUE THREAD

**Issue by jcubic** [opal/opal#2179]
This is nice project, did you tried to compile the opal code itself using opal? How hard it would be. Can it compile a project or only single files?

I would like to create demo REPL (or editor + run button) that run Ruby in browser and this project is probably the closest.

If opal is transpiled to JS it should be possible to transpile to JS ruby code at runtime and run that code in browser without the server.

**Comment by hmdne** [comment]
Yes! It's possible, but in general you don't want the full compiling environment for your production applications (unless you want to do what you described actually).

What you asked about, has already been accomplished here: https://opalrb.com/try/

**Comment by jcubic** [comment]
Awesome thanks.
