### ISSUE TITLE
"unknown encoding name -" with Opal 1.1

### ISSUE THREAD

**Issue by rubys** [opal/opal#2181]
Summary: either parser 3.0 or Opal 1.1 changed in a way that likely will prevent https://opalrb.com/try/ from being upgraded to 1.1 (it currently claims to be based on 1.0.3).

Detail:

https://www.ruby2js.com/demo works with Opal 1.0.5.  When upgrading to Opal 1.1, the following is received:

```
ArgumentError: unknown encoding name - ArgumentError: unknown encoding name - 
    at Object.Opal.send2 (http://localhost:4001/demo/ruby2js.js:1729:17)
    at Opal.send (http://localhost:4001/demo/ruby2js.js:1719:17)
    at Function.$exception (http://localhost:4001/demo/ruby2js.js:5208:14)
    at Function.$raise (http://localhost:4001/demo/ruby2js.js:4886:31)
    at Function.$find (http://localhost:4001/demo/ruby2js.js:19529:14)
    at String.$force_encoding (http://localhost:4001/demo/ruby2js.js:19901:43)
    at Function.$reencode_string (http://localhost:4001/demo/ruby2js.js:27953:26)
    at constructor.$source= (http://localhost:4001/demo/ruby2js.js:28037:33)
    at Object.Opal.send2 (http://localhost:4001/demo/ruby2js.js:1729:17)
    at Opal.send (http://localhost:4001/demo/ruby2js.js:1719:17)
```

ruby2js.js:1729 corresponds to the following line:
https://github.com/ruby2js/ruby2js/blob/78c68cb23c196b493c8461ccd12534af567e6210/demo/patch.opal#L14

ruby2js.js:28037 contains:
`input = self.$class().$reencode_string(input);`

If I step into $reencode_string,
  * original_encoding is UTF-8 with Opal 1.0.5
  * original_encoding is nil (original_encoding.constructor is NilClass) with Opal 1.1.0

Note that the code that is failing was literally lifted from Opal:

https://github.com/opal/opal/blob/b2a27d2d263e11db715c1f042a0ce6b9be59105b/lib/opal/parser/patch.rb#L9

Ruby2JS uses the [whitequark parser](https://github.com/whitequark/parser) in substantially the same way as Opal does, with the Opal patches as a starter with a few additions.  Additions, by the way, that Opal is welcome to reuse and/or adapt.

**Comment by rubys** [comment]
Small test case:

```
$ ruby -e "p ''.encode('utf-8').encoding"
#<Encoding:UTF-8>

$ opal _1.0.5_ -e "p ''.encode('utf-8').encoding"
Failed to load WithCLexer, using pure Ruby lexer
#<Encoding:UTF-8>

$ opal _1.1.1_ -e "p ''.encode('utf-8').encoding"
nil
```

**Comment by Mogztter** [comment]
That's weird, the default value is `#<Encoding:UTF-8>`:

https://github.com/opal/opal/blob/6a6f5be986de544bb200a7c04530cc1db83ddffa/opal/corelib/string/encoding.rb#L234


I do not reproduce this issue on tag 1.1.1:

```
$ bundle exec rake opal -e "p ''.encode('utf-8').encoding"
#<Encoding:UTF-8>
```

**Comment by rubys** [comment]
What happens if you try:
```
opal _1.1.1_ -e "p ''.encode('utf-8').encoding"
```

**Comment by Mogztter** [comment]
What is `opal _1.1.1_` ?

**Comment by rubys** [comment]
First, answering your question.  Rubygems has the ability to control the version of the executable being run, and does so if the first argument is a version string surrounded by underscores.  Try a few variations:

```
$ opal _1.1.1_ --version
Opal v1.1.1
% opal _1.1.0_ --version
Opal v1.1.0
% opal _1.0.5_ --version
Opal v1.0.5
```

Now for an alternate approach to reproducing the problem.  Place the following in a file named `Rakefile` in an empty directory, then run `rake test` from that directory:

```ruby
file 'Gemfile' do
  IO.write 'Gemfile', "source 'https://rubygems.org'\ngem 'opal', '1.1.1'"
end

file 'Gemfile.lock' => 'Gemfile' do
  sh 'bundle install'
end

task :test => 'Gemfile.lock' do
  sh 'bundle exec opal --version'
  sh 'bundle exec opal --compile test.opal > test.js'
  sh 'node test.js'
end
```

What output do you get when you run the above?

**Comment by Mogztter** [comment]
> First, answering your question. Rubygems has the ability to control the version of the executable being run, and does so if the first argument is a version string surrounded by underscores. Try a few variations:

Oh I didn't know, that's quite nice.

> What output do you get when you run the above?

Now I can reproduce it:

```
bundle exec opal --version
Opal v1.1.1
bundle exec opal --compile test.opal > test.js
node test.js
nil
```

For reference, using `UTF-8` (uppercase) works:

```
$ bundle exec opal -e "p ''.encode('UTF-8').encoding"
#<Encoding:UTF-8>

```
