### ISSUE TITLE
Subclassing string

### ISSUE THREAD

**Issue by rubys** [opal/opal#2185]
test case:

```ruby
class C < String
  attr_reader :v
  def initialize(s, v)
    super(s)
    @v = v
  end
end

c = C.new('s', 5)
puts [c.to_s, c.v].inspect
```

When run with Ruby, the results are:

`["s", 5]`

When run with Opal, the results are:

`["s", nil]`

If I compile with Opal to a file, and modify the file, it is clear that the $initialize function is not called.

For completeness, while Strings are immutable in JS, they can be subclassed:

```javascript
class C extends String {
  constructor(s, v) {
    super(s)
    this.v = v
  }
}

c = new C('s', 5);
console.log([c.toString(), c.v]);
```

Running the above with node produces:

`[ 's', 5 ]`

**Comment by hmdne** [comment]
I have a pending commit, that helps with this. Problem is, that strings in JS are immutable and the first argument to #initialize sets the String. In our case, it's the first argument to .new which complicates things overall.
