### ISSUE TITLE
Opal 1.x does not eval (on the client) ascii chars with val >= 0x10

### ISSUE THREAD

**Issue by catmando** [opal/opal#2189]
Chars with ascii code in the range 0x80 - 0xFF cannot be compiled on the client.

For example:

`bundle exec opal -e 'require "opal-parser"; eval("©")'`

will fail.

Looks like the error is here: 

https://github.com/opal/opal/blob/6f71df4882f385dd0369bd6d4e5fdf1e762897d2/opal/corelib/string/unpack.rb#L49

but that should read `if (charcode < 0x80) utf.push(charcode)`

instead of `if (charcode < 0x100) utf.push(charcode)`  (extra zero)

**Comment by hmdne** [comment]
Duplicates of this bug: #2094, #2099

**Comment by hmdne** [comment]
It wasn't a typo, but a logic error, 0x100 (256) is a wrong value here certainly, but 0x10 (16) is no better. The correct value is 0x80 (128).

**Comment by catmando** [comment]
I have updated my original comment.  You are correct, I was doing math in binary and hex on a scrap of paper, and got mixed up!
