### ISSUE TITLE
String#start_with? should accept Regexp

### ISSUE THREAD

**Issue by esnya** [opal/opal#2197]
## TL;DR
According to the Ruby documentation (https://docs.ruby-lang.org/en/2.7.0/String.html#method-i-start_with-3F).

> Each of the prefixes should be a String or a Regexp.

But Opal does not accept Regexp.

## Snippet
```rb
"123abc".start_with?(/\d/)
```

# Ruby
```rb
irb(main):001:0> "123abc".start_with?(/\d/)
=> true
```
Tested on irb (Ruby  2.7.0p0)

## Opal
```
TypeError: no implicit conversion of Regexp into String
```
Tested on Opal 1.1.1
https://opalrb.com/try/?code=%22123abc%22.start_with%3F(%2F%5Cd%2F)#

**Comment by elia** [comment]
Thanks to @ysakasin for fixing this so quickly! 👏
