### ISSUE TITLE
Proposal: Opal versioning regarding components

### ISSUE THREAD

**Issue by hmdne** [opal/opal#2226]
We are now at Opal v1.1.1, let's assume we won't broke compatibility until v2.0.0. The version dependencies of our components like opal-rspec, opal-jquery, etc. all have different dependencies baked in and they all need to be updated every release. Let's fix it, so we will have easier time doing v1.x releases.

**Comment by elia** [comment]
Agree 👍 I merged everything, I'll add a note to the readme regarding the version policy.
