### ISSUE TITLE
Bug: TrueClass === false; FalseClass === true

### ISSUE THREAD

**Issue by hmdne** [opal/opal#2230]
**Describe the bug**

`TrueClass === false` returns true, `FalseClass === true` too.

Opal version: master

**To Reproduce**

```ruby
[user@localhost opal]# bin/opal-repl
>> TrueClass === false
=> true
>> 
[user@localhost opal]# pry
[1] pry(main)> TrueClass === false
=> false
[2] pry(main)> 
```

**Comment by hmdne** [comment]
This is an example on how to use getter properties:

https://github.com/opal/opal/blob/master/opal/corelib/runtime.js#L2063-L2075

This itself is a runtime part of the code responsible for supporting a lesser known kind of syntax syntax like

```ruby
alias $PROGRAM_NAME $0
```

**Comment by hmdne** [comment]
Hmmm... maybe the prototype thing isn't obvious. Prototypes in JS don't map that easily to Ruby world - they are like a class object (as in, eg. a return value of an expression `"string".class` - this is what I mean by a class object in the remainder of this text), but not really, a constructor is maybe more like a class object (a JS constructor is a bit more than JUST a constructor, it also holds "class object methods", like `Array.from`). First, let me somehow describe the construction an object in Ruby, this is obvious, but let's find some similarities:

`Klass.new` first does `Klass.allocate`, which creates us an empty object (1) and sets its class to become Klass (2), then calls `#initialize` on it (3)

A kind of similar thing happens in JavaScript, but not really:

`new Klass` first allocates an empty object (1), then it sets `Klass.prototype` as prototype of that object (2) (internally it sets `obj.__proto__` to the prototype - to make a Ruby equivalent, it's "kind of" like `obj.class`), and then it calls a constructor (3) (`Klass`, which is a function!) on it.

So in principle it is mostly the same. All steps (1), (2) and (3) have some kind of equivalent in both camps. But (2) is where a real difference is, because a class object in Ruby is rather a combination of a JS constructor and a JS prototype. In JS though - we lose a reference to a constructor from the object.

A prototype typically contains the methods and properties (this is unlike Ruby, but in JS methods are simply properties). So for `var k = new Klass` when we do `k.prop`  it first checks `k` itself if it contains a `prop` and if it doesn't, it tries `Klass.prototype.prop` (aka `k.__proto__.prop`)

For now I described just the difference in languages.

Now, how Opal deals with all this mess: a class object (ie. `Klass`) is actually a JS constructor (called `Klass` too, but more accurately - `Opal.Klass`) behind the scenes (not to confuse with #initialize, this is more like .allocate [1]). Then, `Klass` has a property `$$prototype` (for all intents and purposes - this is the same as just `prototype`). And then this prototype contains the methods of a Ruby class, for example Ruby `String#initialize` is JS `Opal.String.$$prototype.$initialize`. But also properties - which, again, is unlike Ruby, but we use them for internals in Opal. For example, we set `Opal.String.$$prototype.$$is_string` and then we can check on objects `str.$$is_string` to cheaply check if it's a String or not. Here are some examples:

https://github.com/opal/opal/blob/master/opal/corelib/string.rb#L9-L20
https://github.com/opal/opal/blob/master/opal/corelib/number.rb#L5

Or, in some places we set `Opal.Integer.$$is_number_class` - directly on a class object (a JS constructor), not on a prototype. So, `(11234).$$is_number_class` is obviously false (actually - `undefined`, which is falsy), but `Opal.Number.$$is_number_class` is true.

So, in Ruby you are more likely to say "you define a method 'a' on a Klass" to mean "`Klass#a`", while in JS it's "you define a method 'a' on a prototype of a Klass". Then, if you want to mean "`Klass.a`" you would say in Ruby "you define a method 'a' on a singleton class of a Klass", and in JS simply "you define a method 'a' on a Klass". So, this is the primary difference.

We also have a special property `$$class`, which is what is used by `#class` to get the class object of a function, but also by `Opal.is_a` which is used by `Class#===` (but to get methods, JS uses the prototype). Under the hood, `$$class` set on a prototype, not on an object.

To add something, which is less related to this issue, but expands on the topic, if you wonder how in JS actually superclasses are (were) done, it's by setting a prototype of a prototype.

[1] To actually construct an Opal object from JS, you would either do `Opal.String.$new()` - which is recommended, or `var str = new Opal.String; str.$initialize()`

I took a long time to understand this thing and fortunately understanding it isn't crucial to use Opal, but may be crucial to fix this particular bug. I tried to be as verbose as possible to eliminate some misconceptions. Just in case I'm leaving this piece of information to be consulted anytime and later I will redact it into documentation.

**Comment by ppmasa8** [comment]
I am very grateful for the detailed explanation.
However, I am not sure I understand the steps to solve this problem correctly.
In order to set the getter property $$class to return true or false as appropriate for the prototype Boolean, I am thinking of the following, but could you please correct me if I am wrong?

1, Create a TrueClass/FalseClass in boolean.rb that inherits from the Boolean class.
2、In that class, set Opal.defineProperty.

**Comment by hmdne** [comment]
The first step is correct.
The second step would require us to change a prototype for `true` and `false` to mean TrueClass and FalseClass respectively. That's not possible from what I know (we are already touch the limits of the JS object system). But - both `true` and `false` already have a prototype and it's `Boolean.prototype` aka `Opal.Boolean.$$prototype`. So, the getter property would need to be set there. Not on a subclass, but directly on Boolean.

If you are curious, this magic of making a JS class become also a Ruby class is called bridging with maybe a not so great syntax of ```class Boolean < `Boolean` ``` or with an ```Opal.bridge``` call.
