### ISSUE TITLE
Bug: Object Id is not being returned 

### ISSUE THREAD

**Issue by abhirampai** [opal/opal#2257]
**Describe the bug**

When I try to run the code "hello".object_id the output I am getting is hello but it should have actually returned the object_id.

**To Reproduce**
<img width="1001" alt="Screenshot 2021-07-21 at 3 37 20 PM" src="https://user-images.githubusercontent.com/36255896/126474161-ebe4ed60-3603-46a5-987c-6ecf3a8f106b.png">

You can try it out here in this [link](https://academy.bigbinary.com/learn-ruby/pages/what-is-symbol)

**Comment by hmdne** [comment]
Good catch. I must say this isn't exactly the most trivial bug to fix, as String is immutable in certain scenarios (in strict mode) and we need to somehow account for that.
