### ISSUE TITLE
Bug: Hash#delete(key) doesn't remove String keys

### ISSUE THREAD

**Issue by lionelchauvin** [opal/opal#2287]
I found an issue similar to #2104

The following example doesn't work with Opal 1.0.5+:
`h = {String.new('a') => 'a'}; k = h.keys.first; h.delete(k); puts h.inspect`

I think `key = key.valueOf();` should also be called before:
https://github.com/opal/opal/blob/1e907080187e99a5235e972c77c764941853e525/opal/corelib/runtime.js#L2083

An other solution is to call `keys[i].valueOf()` here:
https://github.com/opal/opal/blob/1e907080187e99a5235e972c77c764941853e525/opal/corelib/runtime.js#L2152

The fundamental problem is perhaps :
`'a'.$$is_string === new String('a').$$is_string === true `
but in javascript `'a' !== new String('a')`

**Comment by hmdne** [comment]
Related to #2104
