### ISSUE TITLE
Bug: 1/-0.0 == Infinity instead of - Infinity

### ISSUE THREAD

**Issue by lionelchauvin** [opal/opal#2288]
with opal 1.0.5:
```
1/-0.0
=> Infinity
```
but in ruby and javascript:
```
1/-0.0
=> - Infinity
```

**Comment by hmdne** [comment]
Very possible. Parser uses #inspect (which is an alias of #to_s) a lot.

We can patch it to this, unless there's a better way to check for -0 (no, `0 === -0` is true)

```ruby
  def to_s(base = 10)
    base = Opal.coerce_to! base, Integer, :to_int

    if base < 2 || base > 36
      raise ArgumentError, "invalid radix #{base}"
    end
    
    %x{
      if (self === 0 && 1/self === -1/0) {
        return '-0';
      }
	}    
    
    `self.toString(base)`
  end
```

**Comment by lionelchauvin** [comment]
@hmdne  I wrote tests and tried your code and it doesn't seems to work. I don't understand why `self === 0`  is never true.

I propose the following patch:

```
diff --git a/opal/corelib/number.rb b/opal/corelib/number.rb
index f029173e..e5f731fb 100644
--- a/opal/corelib/number.rb
+++ b/opal/corelib/number.rb
@@ -711,6 +711,14 @@ class Number < Numeric
       raise ArgumentError, "invalid radix #{base}"
     end
 
+    if self == 0
+      if `1/self === Infinity`
+        return '0.0'
+      elsif `1/self === -Infinity`
+        return '-0.0'
+      end
+    end
+
     `self.toString(base)`
   end
 
diff --git a/spec/opal/core/number/to_s_spec.rb b/spec/opal/core/number/to_s_spec.rb
new file mode 100644
index 00000000..6db3786c
--- /dev/null
+++ b/spec/opal/core/number/to_s_spec.rb
@@ -0,0 +1,13 @@
+require 'spec_helper'
+
+describe 'Number#to_s' do
+
+  it "should convert 0.0 to '0.0'" do
+    0.0.to_s.should == '0.0'
+  end
+
+  it "should convert -0.0 to '-0.0'" do
+    -0.0.to_s.should == '-0.0'
+  end
+
+end

```

**Comment by hmdne** [comment]
One thing in particular about this patch I don't like is that:

```
$ opal -e 'p 0; p 1'
0.0
1
$
```

We don't have a strict integer type and most of the time we actually work on Integers. So for a positive 0 it should return '0'.

**Comment by lionelchauvin** [comment]
@hmdne You are right `0.to_s.should == '0'`

I found out that the tests of my patch already exist in ruby but are disabled in opal:
https://github.com/opal/opal/blob/21c0523ecdf409a86d3f8d58e7cb83f02eb0b709/spec/filters/bugs/float.rb#L7
https://github.com/opal/opal/blob/21c0523ecdf409a86d3f8d58e7cb83f02eb0b709/spec/filters/bugs/float.rb#L15

About the second test it seems to be a javascript limitation: 0.0 is number 0.

In my opinion, with opal at least `-0.0.to_s.should == '-0'` in order to keep `-`
