### ISSUE TITLE
Bug:  debugger not always work when use with Firefox 91.0.2 64-bit. (But always work on Chrome 93.0.4577.63 64-bit)

### ISSUE THREAD

**Issue by zw963** [opal/opal#2295]
**Describe the bug**

Opal version: 1.2.0

**To Reproduce**

```rb
require 'opal'
require 'js'
require 'native'
require 'promise'
require 'browser/setup/mini'
require 'browser/http'

$document.ready do
  `debugger`
  p "hello"
end
```

Sorry for can't offer more detail, because i don't know how to debug this issue.

simple to say,  `debugger` is working first(though not every time), and it not work anymore suddenly.

i can add `alert "hello"` or `p "hello"` after `debugger`,  those code work as if never debugger exists.

after i try on chrome, it always work, so, i consider this is a issue anyway.

please help me for offer more detail i want.

thank you.

**Comment by hmdne** [comment]
You don't need to wrap debugger in ``` `` ```, simply debugger should work. As for this particular Firefox problem, I checked things out and it seems like you need to have your dev console opened before triggering the debugger statement.

**Comment by hmdne** [comment]
For the record, I used this particular example:
```bash
opal -Rserver -e "require 'promise';Promise.value(1).then { puts 1;debugger;puts 3 }"
```

**Comment by hmdne** [comment]
By the way I noted that Exception doesn't generate a backtrace in Chromium when dev console is off

**Comment by zw963** [comment]
Okay, let discuss the first question. (debugger is not trigger), i can not reproduce on your's opal command line promise example, but, i can always reproduce on my own project example.

## Following is reproduce:

### check out my branch

https://github.com/zw963/marketbet_crawler/tree/check_opal_bug

### start server with rackup.

please set env like this.

### open firefox development tools, console, and then try visit url

assume server is http://127.0.0.1:9393

please visit this url: 

http://127.0.0.1:9393/stocks/18

and click one of following button `C` button.

![image](https://user-images.githubusercontent.com/549126/132150768-55c32a43-3464-45bd-9e42-4c5e45df991a.png)


### see bug

You can always see a log in console like this before modal dialog is open.


![image](https://user-images.githubusercontent.com/549126/132151090-0360cc1a-f644-463d-8d69-658fa40bf46b.png)

but, debugger was never intercepted.

### but it always works when use with google chrome + very good rb call stacks + very good scope 

![image](https://user-images.githubusercontent.com/549126/132151232-02b9451b-bf61-44b2-8f7f-06782dde3e2c.png)

**Comment by hmdne** [comment]
Could you provide with a DB file? The one I generated with seeds isn't useful, when I enter the URL you gave me it returns:

>没有最新的结果！

I checked out the code and it seems this message denotes a failure condition due to an empty DB.

**Comment by zw963** [comment]
[marketbet_crawler_development.db.gz](https://github.com/opal/opal/files/7118948/marketbet_crawler_development.db.gz)


Please unzip this file, and throw it into db/files/

with following env:

```sh
export DEVELOPMENT_DATABASE_URL="sqlite://db/files/marketbet_crawler_development.db"
export TEST_DATABASE_URL="sqlite://db/files/marketbet_crawler_test.db"
export DATABASE_URL="sqlite://db/files/marketbet_crawler_production.db"
export APP_SESSION_SECRET="909f017cc94c96f8a1aff843d95920485376f4c997143cc3c39ca945c883ec88e310a2177a69b8b714d22af1b5fd7864833568b6bf93fc3bc811bcf6e112"
```

**Comment by hmdne** [comment]
As I wrote in the first post, it works if you have a Dev Console opened and doesn't work if you don't.

There is a particular bug when `debugger` is the last instruction in a block, it generates `return debugger;` which is invalid JS.

**Comment by zw963** [comment]
> As I wrote in the first post, it works if you have a Dev Console opened and doesn't work if you don't.

Sure i open dev console like this.

![image](https://user-images.githubusercontent.com/549126/132307785-d8a842fc-de02-49a8-bab3-f7044af976f4.png)


Are you try again ? what i means is,  after the first time break,  then i click continue, then, when i want to break again when click on `C`, it not works anymore.

even when i reboot browser, reboot my server, or refresh page with `Ctrl+F5`.

i almost disable all my firefox plugins, and try clean my cache, still not work.

but if use google chrome, i can always interceped when debugger is run.

> There is a particular bug when debugger is the last instruction in a block, it generates return debugger; which is invalid JS.

Yes, i know this, because so, i always add a expression after debugger,  this is another issue.

**Comment by hmdne** [comment]
Thing is, you need to have it opened all the time when triggering the debugger statement.

It never triggers when I click "Deactivate breakpoints" (icon in right top corner of Dev Console), or when I enable "Select an iframe..." (same location) - the first may be the case in your situation.

It all works for me, I can click it multiple times and each time I get the debugger started. I have a clean Firefox 91 with only uBlock Origin extension installed.

**Comment by zw963** [comment]
Okay, i test with a new firefox profile, debugger get break as expected now, so, that should be a firefox config issue.(i use this config for a long time), i will rsync my firefox to use a new profile instead.

BTW: this issue not caused by `Deactivate breakpoints`, and i could not find `"Select an iframe..."`.
i don't know what cause this, but anyway, this is not a issue.

Thank you.
