### ISSUE TITLE
Firefox has call-stack issues with source-maps

### ISSUE THREAD

**Issue by zw963** [opal/opal#2296]
### Bug: Firefox without good rb call stacks + neat scope, even, rb variable is inaccessible when debugger is intercepted

Then let discuss secondary issue (firefox without good rb call stacks + neat scope)

When firefox debugger still works,  exist following issue:

1.  maybe because some optimization, scope not always present, even when present, very messy, it hard to find out the correct variable.

2. i can not access those rb variable in console when debugger is intercepted.(but google chrome always can)

3. call stask is messy.

I consider this issue is always can be reproduce easy anyway, but, low priority, because above issue not exists on google chrome.

**Comment by hmdne** [comment]
Can you check how it works on this patch: https://github.com/opal/opal/pull/2279 ?

**Comment by zw963** [comment]
Yes, i test it on  my own firefox.  91.0.2 (64-bit)

1. scope present issue get fixed
2.  i can visit rb variable on console
3.  call stacks still not check, i will check it next time.

because #2295 still not fixed i guess, debugger on be intercepted the first time visit my page, 
after that, debugger invalid again, whatever i reboot server, or `C-F5` refresh browser, so,
because i can't do more test on this, my solution perhaps not accuracy anyway.

**Comment by zw963** [comment]
I test again this backtrace feature again today, it works on firefox 94

**Comment by sebnozzi** [comment]
I seem to be having this issue, or something related.

Backtraces are empty on Firefox when an exception is thrown, but they are filled in Chrome.

Firefox:
![Empty backtrace in Firefox](https://user-images.githubusercontent.com/1067921/238915143-5ca41d66-1e42-49b5-bad4-b7449b537089.png)

Chrome:
![Filled backtrace in Chrome](https://user-images.githubusercontent.com/1067921/238915143-5ca41d66-1e42-49b5-bad4-b7449b537089.png)

I created a gist with files to reproduce the issue:

https://gist.github.com/sebnozzi/f3d2dbd8a1473cb4676f3b337a63158b
