### ISSUE TITLE
Opal.eval()

### ISSUE THREAD

**Issue by peter-leonov** [opal/opal#230]
```javascript
var rubyCode = $.ajax('/bla/bla/bla')
var rubyValue = Opal.eval(rubyCode)
```
Just like `window.eval()` but for ruby code.

**Comment by dancinglightning** [comment]
great that this works.
The reason i comment is just that i had to google after my code went Boom.
eval is after all in Kernel in ruby, ie no require required.
Don't know where, but somewhere in the docs it should mention.

**Comment by Ajedi32** [comment]
In addition to documentation, couldn't we also:

```ruby
module Kernel
  def eval(*args)
    raise "To use Kernel#eval, you must first require opal-parser. See <docs link> for details."
  end
end
```

**Comment by kung-fu-tzu** [comment]
:+1: for a warning in `Kernel#eval`.

**Comment by dancinglightning** [comment]
sounds like a very good suggestion

**Comment by vais** [comment]
@Ajedi32 sounds like a PR just waiting to happen :wink:

**Comment by Ajedi32** [comment]
@vais Heh. Yeah, I really should get a dev environment for Opal set up on my PC so I can start making these changes directly instead of just suggesting them in comments. :laughing:

**Comment by elia** [comment]
@Ajedi32 ask at will if you need help while doing the setup :)

**Comment by vais** [comment]
@Ajedi32 it's super easy, just follow https://github.com/opal/opal/blob/master/CONTRIBUTING.md#quick-start and let me know if you have any questions.

**Comment by vais** [comment]
@elia beat me to it :) We are a super-eager-to-help bunch :stuck_out_tongue_winking_eye:

**Comment by orionz** [comment]
Ok.  Trying to get this working... 

In the browser off of the CDN master I need to

    Opal.modules["opal-parser"](Opal)
    Opal.eval("[1,2,3]")

In node I need to 

    require("opal")    // why oh why isn't this -- var opal = require('opal')
    Opal.module("opal-parser")
    Opal.eval("[1,2,3]")

Seems like in both cases you would just want

    Opal.eval("[1,2,3]")

Also there is zero documentation for opal-parser.js.  According to the docs the only parser is written in ruby.
