### ISSUE TITLE
Bug: block.binding throws Cannot read property '$new' of undefined

### ISSUE THREAD

**Issue by Mogztter** [opal/opal#2340]
**Describe the bug**

When using `block.binding`, Opal throws `Cannot read property '$new' of undefined` at runtime.

Opal version: 1.3.0

**To Reproduce**

```rb
def process *args, &block
  if block_given?
    puts block.binding
  else
    puts 'no block :('
  end
end

process { |name| puts "Hello #{name}" }
```

```
$ opal -v test.rb
Opal v1.3.0
test.rb:3:15:in `process': Cannot read property '$new' of undefined (Exception)
	from <internal:corelib/runtime.js>:1847:5:in `Opal.send2'
	from <internal:corelib/runtime.js>:1837:5:in `process'
	from test.rb:9:1:in `undefined'
	from <internal:corelib/runtime.js>:2693:7:in `<main>'
	from test.rb:1:1:in `null'
	from <js:internal/modules/cjs/loader.js>:1063:30:in `Module._compile'
	from <js:internal/modules/cjs/loader.js>:1092:10:in `Module._extensions..js'
	from <js:internal/modules/cjs/loader.js>:928:32:in `Module.load'
	from <js:internal/modules/cjs/loader.js>:769:14:in `Module._load'
```

For reference, it was working on Opal 1.2.0 (or at least no error was thrown):
```
$ opal -v test.rb
Opal v1.2.0

```

```js
Opal.queue(function(Opal) {/* Generated by Opal 1.3.0 */
  var self = Opal.top, $nesting = [], nil = Opal.nil, $$$ = Opal.$$$, $$ = Opal.$$, $gvars = Opal.gvars;

  return ($gvars.VERBOSE = true)
});

Opal.queue(function(Opal) {/* Generated by Opal 1.3.0 */
  var $process$1, $$2, self = Opal.top, $nesting = [], nil = Opal.nil, $$$ = Opal.$$$, $$ = Opal.$$, $send = Opal.send;

  Opal.add_stubs(['$puts', '$process']);
  
  
  Opal.def(self, '$process', $process$1 = function $$process($a) {
    var $iter = $process$1.$$p, block = $iter || nil, $post_args, args, self = this;

    if ($iter) $process$1.$$p = null;
    
    
    if ($iter) $process$1.$$p = null;;
    
    $post_args = Opal.slice.call(arguments, 0, arguments.length);
    
    args = $post_args;;
    if ((block !== nil)) {
      return self.$puts(Opal.Binding.$new(  function($code, $value) {    if (typeof $value === 'undefined') {      return eval($code);    }    else {      return eval($code + ' = $value');    }  },  ["$a", "block"],  self,  ['test.rb', 3]))
    } else {
      return self.$puts("no block :(")
    };
  }, $process$1.$$arity = -1);
  return $send(self, 'process', [], ($$2 = function(name){var self = $$2.$$s == null ? this : $$2.$$s;

    
    
    if (name == null) {
      name = nil;
    };
    return self.$puts("" + "Hello " + (name));}, $$2.$$s = self, $$2.$$arity = 1, $$2));
});
```

Real life usage in Asciidoctor: https://github.com/asciidoctor/asciidoctor/blob/d4b576c990ec001b13c1ea298b1ead91e8cf01f1/lib/asciidoctor/extensions.rb#L263

**Comment by hmdne** [comment]
Opal v1.3.0 does support binding now, but support for block.binding is... undefined behavior, as we don't store a binding in which block was defined (which Ruby does to keep track of the scope). Storing it would certainly incur a heavy performance penalty (a binding in our implementation is a container for a function that does eval and a few more metadata). The error stems from a fact, that you need to `require "corelib/binding"`. Actually, getting a receiver should be possible in this example by reading block.$$s.

Why it did work in v1.2.0 is a mystery to me though, but I will try to debug a little bit more.

**Comment by Mogztter** [comment]
Thanks for digging into it.

Code generation changed:

With Opal 1.2.0:

```js
    if ((block !== nil)) {
      return self.$puts(block.$binding())
    } else {
      return self.$puts("no block :(")
    };
```

With Opal 1.3.0:

```js
    if ((block !== nil)) {
      return self.$puts(Opal.Binding.$new(  function($code, $value) {    if (typeof $value === 'undefined') {      return eval($code);    }    else {      return eval($code + ' = $value');    }  },  ["$a", "block"],  self,  ['test.rb', 3]))
    } else {
      return self.$puts("no block :(")
    };
```

I guess Opal 1.2.0 was using the following implementation: https://github.com/opal/opal/blob/83a9bac33449b915e778c6463274efda99fd3bc4/opal/corelib/proc.rb#L96-L99

> The error stems from a fact, that you need to require "corelib/binding"

I see... 
I didn't write the code in Asciidoctor but since `block.binding` was always returning `nil` (until now) we might want to add a safeguard (i.e., `unless RUBY_ENGINE == 'opal'`).

**Comment by hmdne** [comment]
I'm now correcting this issue and hopefully we will be able to include it in v1.3.1

**Comment by Mogztter** [comment]
Thanks @hmdne 👍🏻
