### ISSUE TITLE
Bug: Preserve UNC path prefix on using File.join (Node.js implementation)

### ISSUE THREAD

**Issue by Mogztter** [opal/opal#2348]
### Describe the bug

Opal version: 1.3.0

#### Ruby
```
$ ruby -v -e "puts File.join('//a', 'b')"
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux]
//a/b
```

#### Opal 1.3.0 ✅

```
$ opal -v -e "puts File.join('//a', 'b')"
Opal v1.3.0
//a/b
```

#### Opal 1.3.0 (with nodejs) ❌ 

```
$ opal -v --require nodejs -e "puts File.join('//a', 'b')"
Opal v1.3.0
/a/b
```

As you can see, when the `nodejs` implementation is enabled, the UNC path prefix `//` is normalized to `/`:

https://github.com/opal/opal/blob/6ad0f920e49df8e3f280286f01b2f0993f47d759/stdlib/nodejs/file.rb#L178-L180) 

I think we need to detect `//` at the start of the path and restore it after running `path.join`. By itself, `path.join` (or `path.posix.join`) normalizes the leading `//` to `/`.

**Comment by hmdne** [comment]
Seems like it works correctly for `\\` though. In general I saw a lot of issues with the nodejs pathname parts.

**Comment by Mogztter** [comment]
@hmdne would you accept a pull request that does what I suggested? i.e., "detect `//` at the start of the path and restore it after running `path.join`" ?

**Comment by hmdne** [comment]
Sure!
