### ISSUE TITLE
Bug: New implicit super doesn't rename variables

### ISSUE THREAD

**Issue by hmdne** [opal/opal#2361]
**Describe the bug**
The new implicit super doesn't rename variables.

Opal version: >=v1.3.0

**To Reproduce**

```ruby
[user@localhost opal]# bin/opal
class A
  def a(arg)
    p arg
  end
end

class B < A
  def a(native)
    super
  end
end

B.new.a(1)
-:9:5:in `a': native is not defined (Exception)
	from -:13:6:in `undefined'
	from <internal:corelib/runtime.js>:2693:7:in `<main>'
	from -:1:1:in `null'
	from node:internal/modules/cjs/loader:1101:14:in `Module._compile'
	from node:internal/modules/cjs/loader:1153:10:in `Module._extensions..js'
	from node:internal/modules/cjs/loader:981:32:in `Module.load'
	from node:internal/modules/cjs/loader:822:12:in `Module._load'
	from node:internal/modules/run_main:79:12:in `executeUserEntryPoint'
	from node:internal/main/run_main_module:17:47:in `undefined'
[user@localhost opal]# 
```

Comparing this to Opal v1.2.0 (MRI exhibits the same behavior):

```ruby
[user@localhost opal]# opal _1.2.0_
class A
  def a(arg)
    p arg
  end
end

class B < A
  def a(native)
    super
  end
end

B.new.a(1)
# => 1
[user@localhost opal]# 
```

Reason:

```javascript
    return (Opal.def(self, '$a', $B_a$2 = function $$a(native$) {
      var $iter = $B_a$2.$$p, $yield = $iter || nil, self = this;

      if ($iter) $B_a$2.$$p = null;
      return $send2(self, $find_super(self, 'a', $B_a$2, false, true), 'a', [native], $iter)
    }, $B_a$2.$$arity = 1), nil) && 'a'
```

Do note how `native` is renamed to `native$`, but not in argument list to `$send2`

**Comment by hmdne** [comment]
This behavior was introduced with opal/opal@149e000 (#2315)

**Comment by sarhm** [comment]
> **Describe the bug** The new implicit super doesn't rename variables.
> 
> Opal version: >=v1.3.0
> 
> **To Reproduce**
> 
> ```ruby
> [user@localhost opal]# bin/opal
> class A
>   def a(arg)
>     p arg
>   end
> end
> 
> class B < A
>   def a(native)
>     super
>   end
> end
> 
> B.new.a(1)
> -:9:5:in `a': native is not defined (Exception)
> 	from -:13:6:in `undefined'
> 	from <internal:corelib/runtime.js>:2693:7:in `<main>'
> 	from -:1:1:in `null'
> 	from node:internal/modules/cjs/loader:1101:14:in `Module._compile'
> 	from node:internal/modules/cjs/loader:1153:10:in `Module._extensions..js'
> 	from node:internal/modules/cjs/loader:981:32:in `Module.load'
> 	from node:internal/modules/cjs/loader:822:12:in `Module._load'
> 	from node:internal/modules/run_main:79:12:in `executeUserEntryPoint'
> 	from node:internal/main/run_main_module:17:47:in `undefined'
> [user@localhost opal]# 
> ```
> 
> Comparing this to Opal v1.2.0 (MRI exhibits the same behavior):
> 
> ```ruby
> [user@localhost opal]# opal _1.2.0_
> class A
>   def a(arg)
>     p arg
>   end
> end
> 
> class B < A
>   def a(native)
>     super
>   end
> end
> 
> B.new.a(1)
> # => 1
> [user@localhost opal]# 
> ```
> 
> Reason:
> 
> ```js
>     return (Opal.def(self, '$a', $B_a$2 = function $$a(native$) {
>       var $iter = $B_a$2.$$p, $yield = $iter || nil, self = this;
> 
>       if ($iter) $B_a$2.$$p = null;
>       return $send2(self, $find_super(self, 'a', $B_a$2, false, true), 'a', [native], $iter)
>     }, $B_a$2.$$arity = 1), nil) && 'a'
> ```
> 
> Do note how `native` is renamed to `native$`, but not in argument list to `$send2`
