### ISSUE TITLE
Bug:  eval("<<~HEREDOC\nsquiggle heredoc is busted\nHEREDOC")

### ISSUE THREAD

**Issue by catmando** [opal/opal#2363]
**Describe the bug**
on the client 

eval("<<~HEREDOC\nsquiggle heredoc is busted\nHEREDOC") 

Throws an error cause it trys to use string.slice!

Opal version: …

1.2

**To Reproduce**

go into yer browser and type:

Opal.Object.$new().$eval('<<~HEREDOC\nsquiggle heredoc is busted\nHEREDOC')

change squiggly to "-" and all is well

**Comment by hmdne** [comment]
Duplicate of #2169
