### ISSUE TITLE
Bug:  Sprockets::FileOutsidePaths Error after update from 1.3.1 to 1.3.2

### ISSUE THREAD

**Issue by zw963** [opal/opal#2368]
Following is error info when run rack test.

Sprockets::FileOutsidePaths: /gems/opal-1.3.2/opal/opal.rb is no longer under a load path: /assets/css, /assets/js, /vendor/assets/materialize-src, /opal-1.3.2/opal, /opal-1.3.2/stdlib, /opal-1.3.2/lib, /ast-2.4.2/lib, /ast-2.4.2/lib, /parser-3.0.3.1/lib, /snabberb-1.5.4/opal, /opal-browser-0.3.1/opal, /paggio-0.3.0/lib
/sprockets-4.0.2/lib/sprockets/loader.rb:156:in load_from_unloaded' /sprockets-4.0.2/lib/sprockets/loader.rb:59:in block in load'
/sprockets-4.0.2/lib/sprockets/loader.rb:337:in fetch_asset_from_dependency_cache' /sprockets-4.0.2/lib/sprockets/loader.rb:43:in load'
/sprockets-4.0.2/lib/sprockets/cached_environment.rb:44:in `load'

It works when i use opal 1.3.1 before, after update to 1.3.2, those error is happen.

I report https://github.com/hmdne/roda-sprockets/issues/13 too.

Thank you.

**Comment by hmdne** [comment]
A known issue, but it's rather an opal-sprockets issue.

You need to erase your cache when gem paths change.

**Comment by zw963** [comment]
i create a new issue there, thank you.
