### ISSUE TITLE
Feature: DateTime

### ISSUE THREAD

**Issue by AndyObtiva** [opal/opal#2391]
**Is your feature request related to a problem? Please describe.**

In Ruby, when I `require 'date'`, I get a `DateTime` class. I noticed that I don't get it in Opal. 

I just upgraded to Opal 1.4.1, and I was surprised to find `DateTime` still missing from its API considering the announcement that it is fully compatible with Ruby 3.1.0. I thought it would be feature-complete, and that `DateTime` is finally implemented.

**Describe the solution you'd like**

A `DateTime` class that behaves exactly like the one we get in Ruby:

https://rubyapi.org/3.1/o/datetime

**Describe alternatives you've considered**

A while ago while using Opal 1.1.1, I implemented `DateTime` on my own in [glimmer-dsl-opal](https://github.com/AndyObtiva/glimmer-dsl-opal):

Here is the rough implementation, which might not be complete, but addressed my needs in the past:

```ruby
require 'date'
require 'time'

class DateTime < Date
  def initialize(*args, &block)
    @time = Time.new(*args, &block)
    methods_to_exclude = [:to_date, :to_time, :==, :eql?, :class]
    methods_to_define = @time.methods - methods_to_exclude
    methods_to_define.each do |method|
      singleton_class.define_method(method) do |*args, &block|
        @time.send(method, *args, &block)
      end
    end
  end
  
  def to_date
    @time.to_date
  end
  
  def to_time
    @time
  end
  
  def ==(other)
    return false if other.class != self.class
    year == other.year and
      month == other.month and
      day == other.day and
      hour == other.hour and
      min == other.min and
      sec == other.sec
  end
  alias eql? ==
end

class Date
  def to_datetime
    # TODO support timezone
    DateTime.new(year, month, day, hour, min, sec)
  end
end

class Time
  class << self
    alias new_original new
    def new(*args)
      if args.size >= 7
        Glimmer::Config.logger.debug "Dropped timezone #{args[6]} from Time.new(#{args.map(&:to_s)}) constructor arguments since Opal does not support it!"
        args = args[0...6]
      end
      new_original(*args)
    end
  end
  
  def to_datetime
    # TODO support timezone
    DateTime.new(year, month, day, hour, min, sec)
  end
end
```

At least, reusing `Time` as `DateTime` prevented Ruby API calls from breaking in Ruby gems! If you could at least provide an implementation like that at minimum, that would definitely help!

**Additional context**

Here is the code I expect to work in Opal, which works in Ruby (inside IRB);

```ruby
require 'date'
puts DateTime.new(2029, 10, 22, 11, 3, 0).inspect
# => #<DateTime: 2029-10-22T11:03:00+00:00 ((2462432j,39780s,0n),+0s,2299161j)>
```

**Comment by hmdne** [comment]
#1743 was marked for 1.5.
