### ISSUE TITLE
Bug: to_proc: method_missing is called with wrong method name

### ISSUE THREAD

**Issue by lionelchauvin** [opal/opal#2417]
```
$ opal -v -e ":a.to_proc.call(Object)"
Opal  v1.4.1
...
Object: undefined method `Object' for Object
```
see: https://opalrb.com/try/?code=%3Aa.to_proc.call(Object)

Why it is  **Object**  instead of **a** ?

The same code with ruby :
```
$ ruby -v -e ":a.to_proc.call(Object)"
ruby 2.7.3p183 (2021-04-05 revision 6847ee089d) [x86_64-linux]
Traceback (most recent call last):
-e:1:in `<main>': undefined method `a' for Object:Class (NoMethodError)
```

I didn't test it, but I think the following line:

https://github.com/opal/opal/blob/19fad560458f8c53a81497fa04c0519caed1c8b8/opal/corelib/string.rb#L1333

should be :

```
          return recv.$method_missing.apply(recv, [#{method_name}].concat(args.slice(1)));
```

**Comment by hmdne** [comment]
@lionelchauvin I improved the PR with @elia somewhat... also supporting blocks. I will force-push the branch in a moment.
