### ISSUE TITLE
Bug: kwrestarg (**kwargs) doesn't support non-String (Symbol) keys

### ISSUE THREAD

**Issue by hmdne** [opal/opal#2514]
**Describe the bug**
The non-String keys are dropped, because kwargs extraction logic is simplified.

Opal version: all/1.7

```
# opal -v -e 'def a **kwargs; kwargs; end; p a true => false'
Opal v1.7.0
{}
```

```
# ruby -v -e 'def a **kwargs; kwargs; end; p a true => false'
ruby 3.1.3p185 (2022-11-24 revision 1a6b16756e) [x86_64-linux]
{true=>false}
```

**Comment by janbiedermann** [comment]
with #2567 this can directly be supported in Hash by adding "boolean" to places like this https://github.com/opal/opal/blob/ec1f37963e27bb2f634fe0a4b37b5cd4ad0b401e/opal/corelib/runtime.js#L2243

**Comment by janbiedermann** [comment]
actually any object is possible, but if objects are used as keys and the compiler inlines new Map(), Hash#rehash must be called for object keys to be accessible (and a condition in there be changed, testing for $$keys)
Without object key kwarg:
`(new Map([['kwarg', '23']])`
with object key kwarg:
`(new Map([[some_object, '23']]).$rehash()`

**Comment by hmdne** [comment]
This is fixed now.
