### ISSUE TITLE
is it possible to require 'openssl' in opalrb?

### ISSUE THREAD

**Issue by MohabEG** [opal/opal#2588]
is it possible to require 'openssl' in opalrb?
is openssl supported by opal or not?

**Comment by hmdne** [comment]
The short answer is no. Opal, like JRuby, doesn't support Ruby's C API. So in general it's not possible to compile Ruby's OpenSSL extension for Opal.

Depending on your environment though, OpenSSL may be available. In particular, Node.js supports the following module: https://nodejs.org/api/tls.html . I am not aware of any bindings to that module in Opal, so you will have to write your own. Opal allows you to interpolate JavaScript code using the backtick operator or better you can use a `native` Opal stdlib library.

For browser (or any other) environment, you may be able to compile OpenSSL to WASM, then interface with it using Opal. But if you want to go that route, perhaps Ruby WASM may prove to be a better choice.
