### ISSUE TITLE
1.8.2 release was not completed

### ISSUE THREAD

**Issue by chenrui333** [opal/opal#2614]
👋 it looks like 1.8.2 release was not completed, raise an issue for awareness. Thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/155296

(I can see this run did get finished, maybe just missed publishing the release notes?)

<img width="1093" alt="image" src="https://github.com/opal/opal/assets/1580956/0e3fb4c3-422f-4dd9-82d5-ba83e53ecc10">

**Comment by hmdne** [comment]
We forgot to make a Github release. This is now amended, thanks :)

**Comment by chenrui333** [comment]
sounds great, thanks! :)
