### ISSUE TITLE
Bug: String interpolation with bridged classes does not call `to_s`

### ISSUE THREAD

**Issue by takaram** [opal/opal#2618]
**Describe the bug**
When some of bridged classes, such as `Array`, `Proc`, `Time`, are interpolated into a string, Opal does not call `to_s`.

Opal's string interpolation depends on JavaScript's `Object.prototype.toString` which is overwritten by Opal. However, since some of the native JavaScript classes have their own `toString`, they take priority over Object's one.

Opal version: v1.8.2 / v2.0.0dev

**To Reproduce**
```console
$ ruby -ve 'puts "#{[1, 2, 3]}\n#{Time.new}\n#{-> {}}"'
ruby 3.1.0p0 (2021-12-25 revision fb4df44d16) [x86_64-linux]
[1, 2, 3]
2023-11-26 19:40:53 +0900
#<Proc:0x00007fd0a26fd180 -e:1 (lambda)>
```

```console
$ bin/opal -ve 'puts "#{[1, 2, 3]}\n#{Time.new}\n#{-> {}}"'
Opal v2.0.0dev
1,2,3
Sun Nov 26 2023 19:40:47 GMT+0900 (Japan Standard Time)
function() {
      return arg;
    }
```

**Comment by hmdne** [comment]
Is perhaps #1068 related?
