### ISSUE TITLE
Bug: Segmentation fault when building with Opal::Builder#build_str

### ISSUE THREAD

**Issue by exastencil** [opal/opal#2643]
**Describe the bug**
I've been having a strange issue while using Opal::Builder as part of an Agoo server with WebSockets. I noticed that the builder would frequently segfault with an IO issue, with both the Prefork and Sequential schedulers.

Opal version: 1.8.2
OS: macOS Sonoma 14.2.1 (M1 Pro)

**To Reproduce**

In order to narrow in on the exact cause of the problem I tried to recreate the issue without all my code and I managed to get it to occur 100% of the time with the code in the following Gist:
[Running Opal::Builder inside an Agoo server with WebSockets segfaults](https://gist.github.com/exastencil/21b626ac5748a2e8d1c412ca0ba3b3d4)

To get the error `bundle install`, `bundle exec ruby server.rb` then open a browser to `http://localhost:9292`. It should segfault immediately thereafter.

What I'm trying to do is have an Agoo webserver hot-reload and live-reload by detecting file changes, reloading files and rebuilding the application using Opal and then send a websocket to the client to refresh the page. I have this working in another rep (exastencil/porous) but it segfaults quite frequently.

In the gist above I have all the components running, except rather than detect file changes I'm just rebuilding  every 250ms to trigger the behaviour faster. I'm not signalling the websocket handler since this doesn't seem to be needed to trigger the error. Starting the server seems to work flawlessly with the Opal::Builder building indefinitely without a hitch, but as soon as I load the page at `http://localhost:9292` the segfault occurs. Thinking it was a threading issue with the Prefork BuilderScheduler I tried it with the Sequential scheduler and while it gives a different error in my app, it also errors consistently here.

I've attached the output from my console as well as the Crash Report in the gist.

**Comment by hmdne** [comment]
Thanks for the report @exastencil ! I will try to look into it a little bit later, but first, can you try to disable cache? There is some kind of issue in Ruby that may be related.

**Comment by hmdne** [comment]
From other ideas, can you try it on other Ruby versions? This looks to me as a bug that happened while (or before) sorting directory entries. Could be it happened due to some race condition due to multithreading which will be hard to debug. I will still look into this, but I don't have an option for running a macOS on Arm, perhaps some other platform will give similar results.

**Comment by exastencil** [comment]
Turning the cache off still causes the issue. I'm assuming passing `cache: false` should do it? I didn't see it documented. I'll try a few other versions of Ruby to check if it happens there.

**Comment by exastencil** [comment]
It seems to keep running much longer with the combination of `cache: false` and `OPAL_PREFORK_DISABLE`, but it still crashes within anywhere from 1  - 30 seconds.

I've also tried the following Ruby's with the same results:

- 3.2.2
- 3.0.2
- 2.7.7

My Linux / Windows PC has died recently, otherwise I would test it there.

**Comment by hmdne** [comment]
I have attempted to reproduce the issue on the following platforms (to no avail - your program simply works).
- Fedora Linux 39 amd64 (Ruby 3.2.2-181)
- Fedora Linux 39 aarch64 (Ruby 3.2.2-181)

As a workaround for the time being, I would perhaps suggest using the `opal` command line utility via a `Kernel#system` method. It supports the `--watch` argument which is likely what you want to achieve.

**Comment by exastencil** [comment]
OK, the crashes seem to be infrequent enough with the sequential builder and the cache turned off that if I delay the rebuilds enough it seems manageable. Long term I'll probably do that for stability, since this isn't needed in production, only while developing.

I appreciate you taking the time to look into this! It was very helpful.
