### ISSUE TITLE
Bug: Array include? returns true when == returns nil

### ISSUE THREAD

**Issue by magnusrk-ch** [opal/opal#2659]
**Describe the bug**
The `include?` method in Array is implemented using a plain JS `if` on the result of `==`. However, `nil` is an object in JS, and objects are truthy, so when `==` returns `nil` the `include?` method returns `true`.

Opal version: v2.0.0dev

**To Reproduce**

```
$ opal -v -e "class NilEquals def ==(other) nil end end; puts [NilEquals.new()].include?(\"no match expected\")"
Opal v1.8.2
true

$ opal -v -e "class NilEquals def ==(other) nil end end; puts [NilEquals.new()].include?(\"no match expected\")"
Opal v2.0.0dev
true
```

Current implementation:
```
def include?(member)
    %x{
      for (var i = 0, length = self.length; i < length; i++) {
        if (#{`self[i]` == member}) {
          return true;
        }
      }

      return false;
    }
  end
```

One potential fix is to wrap ``#{`self[i]` == member}`` in `$truthy()`.

**Comment by hmdne** [comment]
Thanks for the report! We can also use $eqeq, to which expressions like `if a == b` are compiled:

```ruby
  def include?(member)
    %x{
      for (var i = 0, length = self.length; i < length; i++) {
        if ($eqeq(self[i], member)) {
          return true;
        }
      }

      return false;
    }
  end
