### ISSUE TITLE
Bug: `self` in a block passed to a JS function

### ISSUE THREAD

**Issue by yhara** [opal/opal#2668]
**Describe the bug**
`self` becomes different object when a block is passed to JS function.

Opal version: 1.8.2

(I'm not sure this is a bug or an expected behavior, but older Opal supported this.)

**To Reproduce**

Run this in https://opalrb.com/try/
```
class A
  def self.foo
    [1].JS.forEach{|time| `console.log(self)`; self._foo() }
  end
  def self._foo
	p "_foo"
  end
end 
A.foo
```

Expected result: "_foo" is shown

Actual result: `TypeError: self.$_foo is not a function`

**Workaround**

Save `self` to another variable.
```
  def self.foo
    self_ = self
    [1].JS.forEach{|time| self_._foo() }
  end
```

**Comment by hmdne** [comment]
The `self.foo` example is currently compiled to the following code:

```js
    $defs(self, '$foo', function $$foo() {
      var self = this;

      return [1].forEach(function $$1(time){var self = $$1.$$s == null ? this : $$1.$$s;
        if (time == null) time = nil;;
        console.log(self);
        return self.$_foo();}, {$$arity: 1, $$s: self})
    }, 0);
```

The behavior you describe could be fixed if the part `var self = $$1.$$s == null ? this : $$1.$$s;` was omitted. I see another problem though - there's an argument being incorrectly passed to forEach: `, {$$arity: 1, $$s: self}`
