### ISSUE TITLE
Don't add items to Array.prototype

### ISSUE THREAD

**Issue by peterneubauer** [opal/opal#400]
This is breaking any coordination with Angular.js, see https://github.com/angular/angular.js/issues/2653

Would be great to get that solved, so we can move gist.neo4j.org to angular (we use Opal.js and Asciidoctor there).

**Comment by ylluminate** [comment]
Anyone have any experience in this fast forward to 2016?

**Comment by peter-leonov** [comment]
The ultimate solution is to use Facebook's FLUX architecture. Just use any immutable library for Ruby and get a lightning fast rendering performance.

For further reading: https://translate.google.com/translate?hl=en&sl=ru&tl=en&u=http%3A%2F%2Ftonsky.me%2Ftalks%2F2015-frontendconf%2F

**Comment by rubys** [comment]
A demo using [Ruby2JS](https://rubygems.org/gems/ruby2js/) with Facebook's [React.JS](https://facebook.github.io/react/) can be found here: https://github.com/rubys/ruby2js/blob/master/demo/react-tutorial.rb

Ruby2JS's design point is quite different than Opal's.  Whereas Opal has a few JS warts (example: [Strings are immutable](https://github.com/opal/opal/blob/master/docs/faq.md#why-doesnt-opal-support-mutable-strings)), Ruby2JS has pretty much *all* of JS's warts (example: `0 == ''` produces `true`).  On the other hand, Ruby2JS compiles Ruby into clean JavaScript, and provides [filters](https://github.com/rubys/ruby2js#filters) that will do framework specific mappings (example: mapping classes that derive from `React` into React.js classes).

**Comment by brandondrew** [comment]
It's unclear from [Adam's comment](https://github.com/opal/opal/issues/400#issuecomment-28646403) if this was ever resolved, but it sounds (based on his comment and subsequent comments) like it was not. Can anyone confirm either way?

**Comment by elia** [comment]
@brandondrew we still add methods to `Array.prototype` direclty, but the fix for the `$inject` issue eventually landed on Angular.js v1.3.0 (circa Oct 2014) https://github.com/angular/angular.js/commit/b1a6baac2de84a1ecdc000085e8bbd016eb5c100

**Comment by brandondrew** [comment]
thanks @elia!   I eventually found the commit where they fixed it, but forgot to come back here and update.

**Comment by ylluminate** [comment]
Thanks for clarifying @elia!
