### ISSUE TITLE
Implement Time.parse without relying on the browser Date.parse

### ISSUE THREAD

**Issue by meh** [opal/opal#424]
There are many inconsistencies among what browsers can and cannot parse as dates, we should have an implementation supporting the same MRI heuristics for date parsing.

**Comment by ryanstout** [comment]
I've been running into this issue a bit lately.  I checked and rubinius uses the C to parse, but jruby has a pure ruby parser.  The time parser calls parse on date: https://github.com/jruby/jruby/blob/master/lib/ruby/stdlib/date.rb  Its pretty big, but since its behind a require, might be ok to use.

**Comment by elia** [comment]
Alas it uses a Java lib called joda, which kinda confirms this is a hard one

**Comment by ryanstout** [comment]
@elia ah, I missed that.

**Comment by ryanstout** [comment]
@elia does rubyspec have specs for Time.parse?

**Comment by elia** [comment]
Not sure, (On mobile now and can't check)

**Comment by vais** [comment]
@ryanstout @elia it does not look like there are any specs for `Time.parse` yet (at least I couldn't find any, and also saw [this comment](https://github.com/ruby/rubyspec/blob/master/library/time/httpdate_spec.rb#L9)). Maybe @eregon knows what's up.

**Comment by eregon** [comment]
Date (and therefore Date.parse) was initially a Ruby-only implementation. It is available in older MRI
https://github.com/ruby/ruby/blob/906aaa9c0029f47f42b0c833d4c63f1795d97a01/lib/date/format.rb#L1028 (also see [rubysl-date](https://github.com/rubysl/rubysl-date)).
There are specs but not so many (search with `T` then `parse_spec` on GitHub):
https://github.com/ruby/rubyspec/blob/master/library/date/parse_spec.rb
https://github.com/ruby/rubyspec/blob/master/library/date/shared/parse.rb
etc

Time.parse just uses Date.parse up to this day in MRI:
https://github.com/ruby/ruby/blob/trunk/lib/time.rb#L305-L365

And it seems indeed there are no specs for Time.parse directly. It would be nice to have some, especially in the case somebody wants to implement it without using Date._parse.

The Joda stuff in JRuby's date is my work, and I wouldn't recommend trying to port that on non-Java :wink:

**Comment by vais** [comment]
Thanks, @eregon! Especially for the tip that MRI uses `Date.parse` to implement `Time.parse`, it all makes sense now :smile: 

P.S. LOL re the Joda stuff

**Comment by elia** [comment]
Closing this, a PR that implements date/time stuff without using JS' Date class is still more than welcome
