### ISSUE TITLE
Changes in Numeric

### ISSUE THREAD

**Issue by meh** [opal/opal#474]
We all know the current way of handling numbers is wrong, but I realized it's wrong on a different level.

`Numeric` is supposed to be a parent class for numbers without actually providing any operators, `Complex` and `Rational` both inherit from it, but they don't inherit any methods from it.

Testing in Ruby a `class Foo < Numeric; end` and trying to create the `Foo` and doing any operation on it will result in a `NoMethodError` exception.

My proposal is to normalize this behaviour, have a basically empty `Numeric` and implementing a `class Number < Numeric` and then instead of setting `Fixnum = Number` do the same trick we currently have for `Integer` and `Float`.

This way we can implement `Complex` and `Rational` without reverting back to weird hacks. Implementing `Complex` and `Rational` is needed to ensure RubySpecs run correctly, I've been hitting this issue while enabling math specs.

@adambeynon is it possible with the current bridging to bridge an inherited class to a native?

**Comment by elia** [comment]
@meh, I think you solved this in #1064

Should we close?

**Comment by elia** [comment]
Closing this.

_At the same time I'll add that Ruby 2.4 is going to unify `Fixnum` and `Bignum` under `Integer`_ 😄
