### ISSUE TITLE
Merge Opal load path and ruby load path

### ISSUE THREAD

**Issue by adambeynon** [opal/opal#514]
Opal uses its own load path, which is shared with sprockets, to manage locations to search for opal libraries. This is awkward as gems built for opal cannot simply use a standard gem setup, they need a separate `opal/` directory for opal code, and `lib/` directory for code to run under mri. Somewhere inside `lib/` a gem must register itself with opal to add the `opal/` directory to the load path. All very ugly when ruby has a load path doing this for us.

The problem with just having the same load path is that gems added with bundler will get auto required unless explicitly told not to. Considering a lot of code in these gems are designed for the browser and probably have lots of xstrings, bad things could happen. A workaround would be for the main/root file in an opal gem to wrap its require statements in a simple platform check, e.g. `vienna.rb`:

```ruby
# lib/vienna.rb
require 'vienna/version'

if RUBY_ENGINE == "opal"
  require 'vienna/dom_stuff'
  require 'vienna/foo'
end
```

All very simple, and it wont break anything.

Thoughts, comments, suggestions etc.

**Comment by elia** [comment]
After a bunch of time having the shared `lib/` setup in opal-jquery I can say using a separate `opal/` dir is still less confusing, and it's good to make explicit when some code is shared by the two platforms.
