### ISSUE TITLE
Big performance overhead for Opal

### ISSUE THREAD

**Issue by davispuh** [opal/opal#520]
Basically JS generated by Opal is more than 100x slower (in my specific test) than just writing pure JS, so it seems all performance important code (heavy loops etc) must be written in JS. I also found that Ruby itself is quite slow when comparing to JS :(

Let's say I want to find next Prime number after a specified number, in my tests I used 1294268491 as starting point and so next prime is 1294268779

Results
#### Firefox 31

| Implementation | runs per sec | error | runs sampled |
| --- | --- | --- | --- |
| asm-js | 1 204 | ±0.43% | 62 |
| js | 1 171 | ±0.75% | 60 |
| opal | 4.58 | ±4.19% | 15 |
#### Chrome 33

| Implementation | runs per sec | error | runs sampled |
| --- | --- | --- | --- |
| asm-js | 1 215 | ±0.32% | 53 |
| js | 1 186 | ±0.73% | 53 |
| opal | 2.76 | ±21.96% | 12 |
#### Internet Explorer 11

| Implementation | runs per sec | error | runs sampled |
| --- | --- | --- | --- |
| asm-js | 128 | ±0.52% | 56 |
| js | 153 | ±0.93% | 53 |
| opal | 8.86 | ±2.54% | 27 |
#### Ruby 2.0 (MRI)

| runs per sec | runs sampled |
| --- | --- |
| 16.5 | 20 |

Here's Ruby code

``` ruby
module PrimeFinder
  # Check if given number is a Prime
  # @param [Fixnum] n number to be checked
  # @return [Fixnum]
  def self.isPrime?(n)
    to = Math.sqrt(n).to_i
    2.upto(to) do |i|
      return 0 if n % i == 0
    end
    1
  end

  # Find first prime after n
  # @param [Fixnum] n number after which start to look
  # @return [Fixnum]
  def self.findPrime(n)
    loop do
      n = n + 1
      return n if isPrime?(n) > 0
    end
    0
  end

end
```

And my implementation in asm.js (to test non-asm, just comment out "use asm")

``` js
function PrimeFinder(stdlib) {
  "use asm";

  var sqrt = stdlib.Math.sqrt;
  var floor = stdlib.Math.floor;

  function isPrime(n) {
    n = n | 0;
    var i = 2;
    var to = 0;
    to = ~~(+floor(+sqrt(+(n | 0))));
    do {
      if ((((n | 0) % (i | 0)) | 0) == 0) return 0;
      i = (i + 1) | 0;
    } while ((i | 0) <= (to | 0));
    return 1;
  }

  function findPrime(n) {
    n = n | 0;
    while (1) {
     n = (n + 1) | 0;
     if (isPrime(n | 0) | 0) return n | 0;
    }
    return 0;
  }
  return { isPrime: isPrime,  findPrime: findPrime};
}
```

To use `PrimeFinder(window).findPrime(1294268491);`

If that Ruby code could compile to this JS (doesn't even need to be asm.js) that would be really awesome as then this Ruby JS would be way faster than Ruby MRI :smile: 

So anyway because Ruby language have great meta-programming capabilities and very dynamic nature I guess it's not really possible to directly translate it and that's why I propose special directive for compiling limited subset of Ruby to fast JS (or preferably asm.js). Idea is that if Ruby module have `# "use asm"` directive and if that module uses only stdlib functions which are compatible with asm.js (such as Math) then compile it to this effective asm.js and then it would be possible to have really high-performance things written in nice Ruby and executing way faster in JS than with MRI.

Also it looks like in this specific test asm.js doesn't really give much improvement in speed thus just pure JS would be fine too, but I think in some cases it might give better improvement and that's why should better go for asm.js.

**Comment by eregon** [comment]
@meh, @vendethiel For the record, YARV treats some math operators like + specially by just checking a flag if the `Fixnum#+` method was not redefined and then performs the computation in place, avoiding call overhead. A good JIT can assume `Fixnum#+` is not redefined in compiled code and deopt if it is, leading to close to 0 overhead.

**Comment by vendethiel** [comment]
Thanks @eregon. I think there was a bit about this in "ruby under a microscope" as well – interesting stuff :).
