### ISSUE TITLE
Alternative `fails` modes for MSpec filters

### ISSUE THREAD

**Issue by mieko** [opal/opal#532]
I'm attempting to spruce up the MSpec filters since the rubyspec/rubysl update, and I have a feeling we have a decent amount of `fails` filters that aren't actually exercised anymore.  I've caught a few by sight, but a mechanized way to access these would be awesome.

MSpec and its filtering mechanism, beyond the obvious, are a bit opaque to me, but I think something like the following would help us keep up to date with rubyspec updates.  (This could possibly be turned on with an ENV var or whatever.)

1. Change the behavior of `fails`.  Tests matching the description *will be ran*, and we can keep track of which were set to `fails`, but were never ran.  This will catch rubyspec renamings and deletions.  At the end of a run, we'd get something like:

    ```
    "Something#method kicks kittens when provided a dollar" was expected to fail, but was not encountered.
```
    or
    ```
    "Something#method kicks kittens when provided a dollar" was expected to fail, but passed.
```
    This would subtly change the meaning of `fails` from "It's OK if this fails" to "I fully expect this to fail".

2. Add another filter method, `skip` or `hard_fail`, that acts as `fails` does currently.  This will allow tests which actually hang Opal (like the Array recursive handling) to be bypassed entirely, as they are now.

I'm not sure how hard it'd be to coax this behavior on top of MSpec.  I have a naive implementation in `OSpecRunner` that's not really robust.  Any thoughts from anyone that hacks on mspec would be appreciated.

**Comment by elia** [comment]
Fixed by `INVERT_RUNNING_MODE=true` thanks to @iliabylich. 

    $ env INVERT_RUNNING_MODE=true RUBYSPECS=true PATTERN="spec/ruby/core/string/*_spec.rb" rake mspec_ruby_nodejs


_See [HACKING.md](https://github.com/opal/opal/blob/master/HACKING.md) for more details._
