### ISSUE TITLE
Time.zone with russian date produces TypeError: Cannot read property 'join' of null

### ISSUE THREAD

**Issue by Mogztter** [opal/opal#539]
In JavaScript (russian locale) `new Date();` returns:

``` javascript
new Date();
// Wed May 07 2014 11:59:05 GMT+0300 (Финляндия (лето))
```

https://github.com/opal/opal/blob/master/opal/corelib/time.rb#L235

``` javascript
result = string.match(/\([^)]+\)/)[0].match(/[A-Z]/g).join('');
```

The second `match` returns `null` and end up with `TypeError: Cannot read property 'join' of null`.

 Réf: https://github.com/asciidoctor/asciidoctor-chrome-extension/issues/32

**Comment by kongou-ae** [comment]
I have encountered same problem.

`new Date().toString()` in Japanese local returns as below.  So occur `TypeError: Cannot read property 'join' of null`

```
Tue Jan 03 2017 12:05:55 GMT+0000 (協定世界時)
``

**Comment by stayfool** [comment]
same problem
```
new Date
Fri Feb 10 2017 15:33:05 GMT+0800 (中国标准时间)
```
windows 10
chrome 56
asciidoctorjs 1.5.5.100

**Comment by Mogztter** [comment]
I fixed this issue with a work around:

```javascript
var timezoneRegexp = /[A-Z]/g;
var insideParentheses = string.match(/\([^)]+\)/)[0];
var timezone = insideParentheses.match(timezoneRegexp);
if (!timezoneRegexp.test(insideParentheses)) {
  // Timezone is unknown... fallback to GMT
  result = 'GMT';
} else {
  result = timezone.join('');
}
```

I don't think we can use a Regexp with UTF-8 in JavaScript.
So until we switch to `xregexp.js` I think it's fine to fallback to GMT ? Wdyt ?

**Comment by pnowy** [comment]
The same for (Polish browser settings): 

```javascript
new Date();
Mon Apr 03 2017 21:32:12 GMT+0200 (Środkowoeuropejski czas letni)
```

**Comment by elia** [comment]
If someone can suggest a way to run nodejs or phantomjs with a local setting that would be a great addition to the test suite (e.g. [here nodejs is run with a different time zone](https://github.com/opal/opal/blob/08a5ac3db7a5e85f52e6097a7d7133c3d19b8465/.travis.yml#L29))

**Comment by gastaldi** [comment]
Can someone push a fix to this?

**Comment by gastaldi** [comment]
Running `export TZ=GMT` seems to work for me

**Comment by iliabylich** [comment]
@elia @meh @Mogztter Why can't we use `self.toString().match(/\((.*)\)/)[1]` as a full implementation of `Time#zone`?

Both MRI and Node respect a `TZ` environment variable (thanks to @gastaldi ). Node.js can't switch a timezone on the fly, that's a known issue, so here's the script that spawns a new node process every time:
``` ruby
# test.rb
require 'tzinfo'

TZInfo::Timezone.all_country_zone_identifiers.each do |tz|
  ENV['TZ'] = tz
  mri_result = Time.now.zone

  node_result = `TZ=#{tz} node test.js`.strip

  if mri_result != node_result
    p [tz, mri_result, node_result]
  end
end
```
``` js
// test.js
console.log(
  new Date().toString().match(/\((.*)\)/)[1]
);
```
By running it locally I get an empty output (the script prints something only the output differs). Could someone verify it locally? Uncommenting an `if` makes the code to print all outputs that it compares.

**Comment by iliabylich** [comment]
ahh, different JS engines. This code works only on V8. In FF I have a different format - `Thu Jun 15 2017 19:40:05 GMT+0300`. And I suppose old/new IE may have a 3rd format.

**Comment by meh** [comment]
@iliabylich yes, isn't that lovely?

**Comment by Mogztter** [comment]
I wonder how Moment.js is handling timezone https://momentjs.com/timezone/ ?
https://github.com/moment/moment-timezone/blob/develop/moment-timezone.js#L203-L225

**Comment by elia** [comment]
fixed by b7701da and caaa3a2 (also backported to 0.10 for a minor release)

@iliabylich it's still hackish since it still relies on parsing `Date.prototype.toString()` but at least the error is gone. Anyway I think I set the basis for a cozy way of testing the suff relying on `.toString()` [here](https://github.com/opal/opal/blob/caaa3a2645f4a0f4fb48d7caa4dcf5f7a2666d0d/spec/opal/core/time_spec.rb#L39-L61).

**Comment by iliabylich** [comment]
@elia MRI doesn't return [such](https://github.com/opal/opal/blob/caaa3a2645f4a0f4fb48d7caa4dcf5f7a2666d0d/spec/opal/core/time_spec.rb#L58) values from `Time#zone` 😄

**Comment by iliabylich** [comment]
@Mogztter https://momentjs.com/timezone/docs/#/using-timezones/guessing-user-timezone/ - that's where I've stolen an idea to use `Intl.DateTimeFormat().resolvedOptions().timeZone` 😄  (see my comment above) - [here's](https://github.com/moment/moment-timezone/blob/2b8da8f103f019949d45dc86fd6763960c8474d8/moment-timezone.js#L326) the way `moment-timezone` uses it to get a timezone

**Comment by elia** [comment]
@Mogztter @stayfool https://rubygems.org/gems/opal/versions/0.10.5

**Comment by elia** [comment]
I'll close this, I'll reopen upon request if it's still not fixed

**Comment by stayfool** [comment]
@elia thanks
