### ISSUE TITLE
kDO_BLOCK inside ->{} produces SyntaxError

### ISSUE THREAD

**Issue by elia** [opal/opal#544]
```ruby
a -> { b do |c|
end }
```

```
/Users/elia/Code/opal/lib/opal/parser.rb:81:in `on_error': An error occurred while compiling: -e (RuntimeError)

parse error on value "do" (kDO_BLOCK) :-e:1
Source: -e:1:11
a -> { b do |c|
~~~~~~~~~~^
	from /Users/elia/.rvm/gems/ruby-2.2.3/gems/racc-1.4.12/lib/racc/parser.rb:271:in `_racc_do_parse_c'
	from /Users/elia/.rvm/gems/ruby-2.2.3/gems/racc-1.4.12/lib/racc/parser.rb:271:in `do_parse'
	from /Users/elia/Code/opal/lib/opal/parser.rb:53:in `parse_to_sexp'
	from /Users/elia/Code/opal/lib/opal/parser.rb:38:in `parse'
	from /Users/elia/Code/opal/lib/opal/compiler.rb:149:in `compile'
	from /Users/elia/Code/opal/lib/opal/builder_processors.rb:91:in `compiled'
	from /Users/elia/Code/opal/lib/opal/builder_processors.rb:101:in `requires'
	from /Users/elia/Code/opal/lib/opal/builder.rb:41:in `build_str'
	from /Users/elia/Code/opal/lib/opal/cli.rb:110:in `block in build'
	from /Users/elia/Code/opal/lib/opal/cli.rb:154:in `evals_or_file'
	from /Users/elia/Code/opal/lib/opal/cli.rb:109:in `build'
	from /Users/elia/Code/opal/lib/opal/cli.rb:119:in `compiled_source'
	from /Users/elia/Code/opal/lib/opal/cli.rb:85:in `run_code'
	from /Users/elia/Code/opal/lib/opal/cli.rb:69:in `run'
	from bin/opal:22:in `<main>'
```

**update** updated the error output using master

**Comment by elia** [comment]
cc @alexdowad

**Comment by alexdowad** [comment]
Let me have a look at this. As before, the first step is to run Opal's parser in debug mode and see what the debug output is.

**Comment by alexdowad** [comment]
The lexer is returning `tIDENTIFIER tLAMBDA tLAMBEG tIDENTIFIER tDO_BLOCK`. As soon as hits `tDO_BLOCK`, it gets stuck. It does reduce the first `tIDENTIFIER` to `operation`.

**Comment by alexdowad** [comment]
It also produces an `f_larglist` node as soon as it sees `tLAMBEG` (before shifting `tLAMBEG`).

`tLAMBDA` can only be reduced via `primary : tLAMBDA lambda`. The only way to get `lambda` is via `lambda : f_larglist lambda_body`. For `lambda_body`, we can only follow `lambda_body : tLAMBEG compstmt tRCURLY`. So when it shifts `tIDENTIFIER`, the parser is expecting to reduce it to `compstmt` somehow.

**Comment by alexdowad** [comment]
Interestingly, `a -> { b 1 do |c| end }` works. This is because `tDO_BLOCK` can only be handled by reducing it to `do_block` and then going via `block_call : command do_block`. There are a few ways to get `command`, but the one we care about here is `command : operation command_args`. Unfortunately, `command_args` can't be empty.

**Comment by alexdowad** [comment]
I've noticed that in other cases where Opal's parser handles "do", like `a do 1 end`, it lexes it as `tDO`. I tried `a -> { b do |c| end }` with `parser`, which has a grammar somewhat similar to Opal (both were derived from Ruby's yacc grammar), and it also lexes it as `tDO` in this situation.

**Comment by alexdowad** [comment]
Opal's lexer returns `kDO_BLOCK` (I mistakenly called it `tDO_BLOCK`) in 2 places. In this case, it is coming from `lexer.rb:597`.

**Comment by alexdowad** [comment]
Aha. When Opal's parser sees the very first `tIDENTIFIER` followed by `tLAMBDA`, it's expecting to reduce it via `command : operation command_args`. That's why it converts the `tIDENTIFIER` to `operation`. Then it starts following the rule for `command_args`:

```ruby
    command_args:   {
                      lexer.cmdarg_push 1
                    }
                    open_args
                    {
                      lexer.cmdarg_pop
                      result = val[1]
                    }
```

That `lexer.cmdarg_push 1` puts the lexer in a state where it will emit `kDO_BLOCK` rather than `kDO`.

**Comment by alexdowad** [comment]
I've noticed that `parser` clears the lexer's `cmdarg` state before parsing the body, and restores it afterward. Opal doesn't.

**Comment by alexdowad** [comment]
OK, I have a fix. Need to add a new unit test, though. I'll use @elia's sample code.

**Comment by alexdowad** [comment]
Just opened a PR with a fix.

Thanks for an interesting challenge, I enjoyed it.

**Comment by elia** [comment]
read the updates live… awesome :D

As an aside, in the past we've talked a couple of times about switching to `parser` with Adam, the roadmap was more or less to move to a the same AST structure with the current parser and the do the switch and implement all the missing pieces in the compiler.

**Comment by alexdowad** [comment]
> in the past we've talked a couple of times about switching to parser with Adam

You would save a lot of maintenance that way. `parser` is very solid. On the other hand, I am also happy to see multiple working implementations of a Ruby parser out there. It's interesting to compare and see how things can be done in different ways.

**Comment by elia** [comment]
> You would save a lot of maintenance that way.

Yeah, that's really appealing, for Opal the only requirement is that the parser needs to be compiled to JS too (so the usual Opal gotchas apply: immutable strings, String == Symbol, etc).
