### ISSUE TITLE
Improve error output for compiler errors

### ISSUE THREAD

**Issue by elia** [opal/opal#562]
from #559

> > However, since the parser gives no line number, one has to "dichotomically" comment-out the code to find which line makes the parser choke...
> 
> @kubicle I add some harness to get better output for parsing errors if either `$DEBUG` or `$VERBOSE` are true and hopefully I'll add similar stuff to the compiler so that catching these errors should become less painful in the future. :smiley_cat:

**Comment by iliabylich** [comment]
Can we close it? It was fixed after switching to parser:
``` sh
$ cat -n test.rb
     1	
     2	
     3	m(a^^^b)
     4

$ opal -c --no-opal test.rb
test:3:5: error: unexpected token tCARET
test:3: m(a^^^b)
test:3:     ^
.. backtrace ...
```

**Comment by olombart** [comment]
Nice one, thanks!

**Comment by elia** [comment]
Sure!
