### ISSUE TITLE
round() bahaves different in Opal than in MRI

### ISSUE THREAD

**Issue by bwl21** [opal/opal#572]
```ruby
a=1.2345
puts a.class, a.round(2)
````
yields in http://opalrb.org/try/#

```
Numeric
1
```

while in MRI 1.9.3

```
Float
1.23
```

**Comment by catmando** [comment]
Just a note that giuan's patch is not quite right:

    if (decimal_digits >= 0) return self.toFixed(decimal_digits);

needs to be

    if (decimal_digits >= 0) return 1.0 * self.toFixed(decimal_digits);

otherwise you get a string back.

**Comment by vais** [comment]
@catmando I am new to this, please pardon my ignorance, but then why does this seem to be working correctly [in the following opalrb.org/try](http://opalrb.org/try/?code:a%3D1.2345%0Aputs%20a.class%2C%20a.round(2).class%0A%20%20):
```
a=1.2345
puts a.class, a.round(2).class
```
Output:
```
Numeric
Numeric
```
