### ISSUE TITLE
Incorrect handling of begin/end while

### ISSUE THREAD

**Issue by wmnnd** [opal/opal#575]
Opal seems to evaluate the condition in a begin/end while loop before executing the scope while MRI runs it once before checking the condition.

The following code will print "konichiwa" in MRI but not in Opal.:

```rb
begin
  puts "konichiwa"
end while false

#Prints "konichiwa" in MRI, but not in Opal
```

Regular while loops work fine and have their condition checked both in MRI and Opal:

```rb
while false
    puts "hello"
end

#Will never print anything
```

**Comment by elia** [comment]
Will keep this open and will find out who will come first, if the MRI that will remove this _feature_ eventually or us implementing it 😄 

---
_Here's the response from matz, just for reference_
_http://blade.nagaokaut.ac.jp/cgi-bin/scat.rb/ruby/ruby-core/6741_

```
Subject: Re: semenatics of if/unless/while statement modifiers
From: Yukihiro Matsumoto <matz ruby-lang.org>
Date: Wed, 23 Nov 2005 10:54:34 +0900
In-reply-to: 6719
Hi,

In message "Re: semenatics of if/unless/while statement modifiers"
    on Wed, 23 Nov 2005 01:11:39 +0900, ts <decoux / moulon.inra.fr> writes:

| What is a post-test loop ? This
|
|moulon% ruby -e 'i = 0; begin puts i; end while i > 0'
|0

Don't use it please.  I'm regretting this feature, and I'd like to
remove it in the future if it's possible.

							matz.
```
