### ISSUE TITLE
Source maps don't show correct position when using blocks

### ISSUE THREAD

**Issue by wmnnd** [opal/opal#582]
As mentioned earlier on IRC, source maps (in 0.6) don't show the correct position of exceptions when using blocks. They will always show the first line of the block as source of the exception which is especially problematic when using opal-jquery because then all exceptions will be displayed in the line where `Document.ready?` is used.
Interestingly, the `Document.ready?` line is still displayed as source of the exception even if it occurred outside of that block.

![without-jquery](https://cloud.githubusercontent.com/assets/7488303/4167510/07952b9a-3514-11e4-993d-0047c96580ef.png)
![with_jquery](https://cloud.githubusercontent.com/assets/7488303/4167511/0949b320-3514-11e4-95b5-080f2d6afcaf.png)

**Comment by elia** [comment]
Probably closed by #773, feel free to reopen (ping me) if it's still valid
