### ISSUE TITLE
Infinite loop when yielding inside Kernel#loop

### ISSUE THREAD

**Issue by epidemian** [opal/opal#592]
A script that should print all numbers from 0 to 10:

```ruby
def each_int
  n = 0
  loop do
    yield n
    n += 1
  end
end

each_int do |n|
  puts n
  break if n == 10
end
```

Produces [an infinite loop](http://opalrb.org/try/#code:def%20each_int%0A%20%20n%20%3D%200%0A%20%20loop%20do%0A%20%20%20%20yield%20n%0A%20%20%20%20n%20%2B%3D%201%0A%20%20end%0Aend%0A%0Aeach_int%20do%20|n|%0A%20%20puts%20n%0A%20%20break%20if%20n%20%3D%3D%2010%0Aend) on Opal 0.6.2.

The code terminates as expected if a [`while true` is used](http://opalrb.org/try/#code:def%20each_int%0A%20%20n%20%3D%200%0A%20%20while%20true%0A%20%20%20%20yield%20n%0A%20%20%20%20n%20%2B%3D%201%0A%20%20end%0Aend%0A%0Aeach_int%20do%20|n|%0A%20%20puts%20n%0A%20%20break%20if%20n%20%3D%3D%2010%0Aend), or [even `(0..Float::INFINITY).each`](http://opalrb.org/try/#code:def%20each_int%28%26block%29%0A%20%20%280..Float%3A%3AINFINITY%29.each%28%26block%29%0Aend%0A%0Aeach_int%20do%20|n|%0A%20%20puts%20n%0A%20%20break%20if%20n%20%3D%3D%2010%0Aend), so i'd guess this is a `Kernel#loop` specific thing.

I couldn't find any previous report for this issue; sorry if it's a duplicate! :sweat_smile:

**Comment by elia** [comment]
Fixed on _master_

```rb
def each_int
  n = 0
  loop do
    yield n
    n += 1
  end
end

each_int do |n|
  puts n
  break if n == 10
end
```


```
opal:master ⤑ pbpaste | ruby                                                                                                                                              ~/C/opal
0
1
2
3
4
5
6
7
8
9
10
opal:master ⤑ pbpaste | opal                                                                                                                                              ~/C/opal
0
1
2
3
4
5
6
7
8
9
10
```
