### ISSUE TITLE
 within a class, eval works differently than it does in MRI

### ISSUE THREAD

**Issue by jjgh** [opal/opal#622]
```rb
class Klass

  value = "nice value"

  eval "puts value"
  # => NoMethodError: undefined method `value' for main

  puts self  
  # => Klass

  eval "puts self"   
  # => main
  # while in ruby it would have returned:
  # => Klass

end
```

Is this a bug or it's the way Opal is supposed to work?

**Comment by elia** [comment]
The situation has improved, now the following works:

```rb
class Klass
  eval "puts self" # => Klass
end
```

but there's still an issue with making local variables available to eval'd code

**Comment by elia** [comment]
I don't think there's any short-term plan to support local vars in eval, I'll close this and defer to Ruby Spec to track this missing feature.
