### ISSUE TITLE
Get feedback on beta releases

### ISSUE THREAD

**Issue by elia** [opal/opal#624]
- [x] opal-browser / @meh 
- [x] volt / @ryanstout 
- [x] yeah / @skofo 
- [x] opal-active-* / @boberetezeke

did I miss something?

**EDIT:** btw 0.7.0.beta1 is out :smile:

**Comment by elia** [comment]
@boberetezeke @ryanstout I marked both opal-acriverecord and volt as checked against master

Let us know if you incur into any other issue.

**Comment by ryanstout** [comment]
@elia I need to spend a little more time with it.  The specs pass, but I need to try it with a few of the other volt components.  I'll let you know.

**Comment by boberetezeke** [comment]
I have merged your pull request after doing some checks. It seems good 
to go. I updated opal-actionpack as well to the latest opal and opal-rspec.

Thanks for the good work!

Steve

"You must be the change you want to see in the world." Mahatma Gandhi

blog: http://steve.stewdle.com/blog
twitter: @boberetezeke

**Comment by boberetezeke** [comment]
So, I have updated my gems to the latest opal, but my project depends on 
other opal gems like opal-sprockets which still requires opal ~ 0.5.0. 
Does this work with 0.7.0? Can I just forked and modify the gemspec or 
is someone going to update the main repository? I am kind of stuck in 
the middle now.

Steve

"You must be the change you want to see in the world." Mahatma Gandhi

blog: http://steve.stewdle.com/blog
twitter: @boberetezeke

**Comment by boberetezeke** [comment]
I tried forking opal-sprockets and just updating the gemspec and it fails when I try to run with the following error:

/Users/stevetuckner/Projects/Opal/opal-sprockets/lib/opal/sprockets/server.rb:13:in `initialize': wrong number of arguments (2 for 1) (ArgumentError)
	from /Users/stevetuckner/.rvm/gems/ruby-2.0.0-p481@golf/bundler/gems/opal-rails-127377f63269/lib/opal/rails/engine.rb:40:in `new'
	from /Users/stevetuckner/.rvm/gems/ruby-2.0.0-p481@golf/bundler/gems/opal-rails-127377f63269/lib/opal/rails/engine.rb:40:in `block (2 levels) in <class:Engine>'
	from /Users/stevetuckner/.rvm/gems/ruby-2.0.0-p481@golf/gems/actionpack-4.0.0/lib/action_dispatch/routing/route_set.rb:316:in `instance_exec'
	from /Users/stevetuckner/.rvm/gems/ruby-2.0.0-p481@golf/gems/actionpack-4.0.0/lib/action_dispatch/routing/route_set.rb:316:in `eval_block'
	from /Users/stevetuckner/.rvm/gems/ruby-2.0.0-p481@golf/gems/actionpack-4.0.0/lib/action_dispatch/rou
......

**Comment by adambeynon** [comment]
Hi @boberetezeke - You don't need opal-sprockets anymore, it's all built into the Opal gem.
