### ISSUE TITLE
Regexp::last_match missing

### ISSUE THREAD

**Issue by wmnnd** [opal/opal#641]
`Regexp::last_match` and the related `$~`, `$&` and `$[1…99]` global variables are not set when using Regexps in a case/when statement. In fact, `Regexp::last_match` is not defined at all.

```ruby
case "abc"
when /abc/
  puts Regexp.last_match
end
````

```ruby
case "abc"
when /abc/
  puts $~, $&
end
````

**Comment by elia** [comment]
closed via #822
