### ISSUE TITLE
`ERB` builder should support javascript and ruby contents

### ISSUE THREAD

**Issue by adambeynon** [opal/opal#645]
Currently, any `.erb` source required using the new builder system is assumed to be a javascript file, so once passed through ERB, its content is passed off just like a javascript file. We should really check to see if there is a nested extension, and pass the compiled source to that builder.

`foo.rb.erb` => ERB => Ruby => out
`foo.erb` => ERB => out

**Comment by elia** [comment]
Closing this as sprockets kinda dropped support for extension chains and `Builder` is meant to be a simpler solution.
