### ISSUE TITLE
Is there a way to sleep?

### ISSUE THREAD

**Issue by georgeu2000** [opal/opal#660]
`sleep 1` raises `NoMethodError: undefined method 'sleep'`

Is there another way to do it?

**Comment by zetachang** [comment]
Is it possible to implement this as `setTimeout` and put all the expressions below into the callback?

**Comment by adambeynon** [comment]
The problem in that case is that it would only apply to things within that method, and not higher in the stack. The method would "return", and the outside code would carry on running, and not wait for the timeout to expire. E.g.

```ruby
def do_something
  sleep 10
  puts "inside"
end

puts "foo"
do_something
puts "bar"

# => "foo"
# => "bar"
# => "inside"
```

**Comment by Ajedi32** [comment]
Possible duplicate of [What do I do if I want a JavaScript version of sleep()?](http://stackoverflow.com/questions/951021/what-do-i-do-if-i-want-a-javascript-version-of-sleep). :stuck_out_tongue_winking_eye:

**Comment by zetachang** [comment]
I just found a js library [Streamline](https://github.com/Sage/streamlinejs) which aim to do the same stuff through marking an async call with `_` variable. 

With Streamline, you can write as if the function call is sync by marking up **all** the function call with `_` parameter. 

I've tried this with following opal code:

```ruby
def do_stuff
  `setTimeout(_, 2000)`
  puts "inside"
end

do_stuff
puts "outside"
```
got it compiled and add `_` variable as below.

```js
/* Generated by Opal 0.7.0 */
(function(Opal, _) {
  Opal.dynamic_require_severity = "error";
  var self = Opal.top, $scope = Opal, nil = Opal.nil, $breaker = Opal.breaker, $slice = Opal.slice;

  Opal.add_stubs(['$puts', '$do_stuff']);
  Opal.Object.$$proto.$do_stuff = function(_) {
    var self = this;

    setTimeout(_, 2000);
    return self.$puts("inside");
  };
  self.$do_stuff(_);
  return self.$puts("outside");
})(Opal, _);
```

Feed that to streamline compiler and it works fine by outputting

```js
# wait 2 secs
inside
outside
```

So maybe we can integrate that to Opal by making all the function call from top to bottom all appended with `_` (`apply` replaced by `apply_` according to [doc](https://github.com/Sage/streamlinejs/blob/master/FAQ.md#can-a-streamline-function-take-optional-parameters) , etc) which will by default make all the method call execute in serial as MRI did. And providing API to allow async method call.

**Comment by Ajedi32** [comment]
Still having a bit of a hard time wrapping my head around that library, but it seems to be that for your code to work, all function calls have to be asynchronous?

**Comment by Ajedi32** [comment]
Exercise below is mostly for my own benefit, to make sure I understand how this works. Let me know if I get anything wrong here.

----

* Streamline assumes all callbacks are of the form:

```javascript
function callback(err, result) { do_stuff_here }
```

* When Streamline sees `_` in a function definition, it interprets that as "this function takes a callback as the argument in this position".

* Streamline rewrites returns in functions which take callbacks as "call the callback with `(nil, <return value>)`".

* Streamline rewrites thrown exceptions in functions which take callbacks as "call the callback with `(<error>)`".

* When you call a function with `_`, streamline takes all the code following that function call and places it into a callback which is passed to the function you're calling as an argument in the same position that `_` was in the original code. If you use the return value of the function you called with `_` in your code, the usage of that value is rewritten to instead use an argument to the callback. E.g. `var x = some_func(_); <more code>` becomes `some_func(function(error, x) { <more_code> })`, and `some_func(_).other_call()` becomes `some_func(function(error, temp_var) { temp_var.other_call() })`.

So in our case, streamline rewrites:

```javascript
/* Generated by Opal 0.7.0 */
(function(Opal, _) {
  Opal.dynamic_require_severity = "error";
  var self = Opal.top, $scope = Opal, nil = Opal.nil, $breaker = Opal.breaker, $slice = Opal.slice;

  Opal.add_stubs(['$puts', '$do_stuff']);
  Opal.Object.$$proto.$do_stuff = function(_) {
    var self = this;

    setTimeout(_, 2000);
    return self.$puts("inside");
  };
  self.$do_stuff(_);
  return self.$puts("outside");
})(Opal, _);
```

as something along the lines of:

```javascript
/* Generated by Opal 0.7.0 */
(function(Opal, outer_function_callback) {
  Opal.dynamic_require_severity = "error";
  var self = Opal.top, $scope = Opal, nil = Opal.nil, $breaker = Opal.breaker, $slice = Opal.slice;

  Opal.add_stubs(['$puts', '$do_stuff']);
  Opal.Object.$$proto.$do_stuff = function(do_stuff_callback) {
    var self = this;

    setTimeout(function(err, calling_set_timeout_callback) {
      do_stuff_callback(null, self.$puts("inside"));
    }, 2000);
  };
  self.$do_stuff(function(err, calling_do_stuff_callback) {
    outer_function_callback(null, self.$puts("outside"));
  });
})(Opal, function(err, calling_outer_function_callback) { /* Noop*/ });
```
