### ISSUE TITLE
"TypeError: undefined is not a function" with Native.convert on an array with native objects

### ISSUE THREAD

**Issue by ippeiukai** [opal/opal#661]
``` ruby
Native.convert(`[{foo: 'bar'}]`)
```

`TypeError: undefined is not a function`

The error is raised from here:
https://github.com/opal/opal/blob/v0.6.3/stdlib/native.rb#L426

This is especially true when converting back and forth with `Kernel#Native`:

``` ruby
def js_in_js_out(js_obj)
 obj = Native(js_obj)
 #manipulation
 Native.convert(obj)
end
js_in_js_out(`{foo: 'bar'}`) # okay
js_in_js_out(`[{foo: 'bar'}]`) # not okay
```

I'm at v0.6.3. But also reproduced with online Try which is at 0.7.0.beta2:
https://opalrb.com/try/#code:Native.convert(%60%5B%7Bfoo%3A%20'bar'%7D%5D%60)

Expected: no error, returns the array

**Comment by elia** [comment]
Fixed at least since v0.11

```
⤑ opal -v -rnative -e "%x{console.log(#{Native.convert(`[{foo: 'bar'}]`)})}"   ~
Opal v0.11.3
[ { foo: 'bar' } ]
```
