### ISSUE TITLE
Static Function does not works with Native

### ISSUE THREAD

**Issue by ndrluis** [opal/opal#662]
When I call a Static Function with Native this methods doesn't works
Source Code: https://github.com/andreanastacio/kolorblocks-opal
Static Function: https://github.com/andreanastacio/kolorblocks-opal/blob/master/lib/pixi-wrapper/pixi.rb#L27

With Shawn Anderson wrapper works
Source Code: https://github.com/andreanastacio/kolorblocks-opal/tree/shawn-wrapper
Static Function: https://github.com/andreanastacio/kolorblocks-opal/blob/shawn-wrapper/lib/pixi-wrapper/pixi.rb#L41

PIXI.js Static Function Doc:
http://www.goodboydigital.com/pixijs/docs/files/src_pixi_textures_Texture.js.html#l227

**Comment by elia** [comment]
Appears to be fixed on master for <code>Native([\`{}\`, 123])</code>:

```
opal:master ⤑ pbpaste | be bin/opal -rnative                           
[#<Native:[object Object]>, 123]
```
