### ISSUE TITLE
Start splat

### ISSUE THREAD

**Issue by ryanstout** [opal/opal#663]
The following runs in mri 2.1, but doesn't compile in opal 0.7beta4.

```ruby
*a, b = [1,2,3]
```

Thanks!

**Comment by bbatsov** [comment]
I think the title should say "splat". :-)

**Comment by ryanstout** [comment]
@bbatsov thanks, typo

**Comment by elia** [comment]
_(afk)_

@ryanstout can you check if this is solved on master?

@alexdowad if you already know it's solved close right away :)

**Comment by alexdowad** [comment]
This is fixed on HEAD.

**Comment by elia** [comment]
:+1: :rocket:
