### ISSUE TITLE
Latest opal beta: problem with source maps and sprockets

### ISSUE THREAD

**Issue by jaredcwhite** [opal/opal#670]
I getting this error when the browser is requesting source maps:

    TypeError (no implicit conversion of nil into String):
       json (1.8.1) lib/json/common.rb:155:in `initialize'
       json (1.8.1) lib/json/common.rb:155:in `new'
       json (1.8.1) lib/json/common.rb:155:in `parse'
       opal (0.7.0.beta3) lib/opal/sprockets/server.rb:39:in `call'
       ...

Anyone else run into this? I'm using the latest 0.7.0 beta versions of opal and opal-rails. (However, my app is still on Rails 4.0, not 4.1...maybe that's part of the problem)

**Comment by cantonic** [comment]
This solved it for me:

`app/assets/javascripts/application.js` has to be renamed to `application.js.rb`. 

The opal-rails documentation shows require statements like
```javascript
//= require opal
//= require opal_ujs
//= require foobar
```
but the file extension is `.rb`. so we have to require using Ruby like
```ruby
require `opal`
require `opal_ujs`
require `foobar`
```

**Comment by jaredcwhite** [comment]
@cantonic Thanks for sharing, but that technique did not work for me. I got nothing but errors (on the JS side). Granted, I couldn't actually rename application.js and change the format because I include a ton of other legit JS stuff. I tried a separate file (aka setup_opal.js.rb) and didn't have any success.

**Comment by jaredcwhite** [comment]
I can definitely confirm this is a bug with the latest opal beta. I fired up an old project that had been using opal 0.6.2, introduced a line of code that would error, and was able to verify the source mapping works fine. Then I updated to opal 0.7.0.beta3, loaded it up again, and I'm getting the same nil error I described above. @elia Did you say you might have a fix for this? I'm happy to help troubleshoot in any way possible. I want my source maps back! =)

**Comment by elia** [comment]
@jaredcwhite the "fix" is already in place iirc, I'd need to dig deeper bug but I'm not sure if I'll get the time in the next weeks

**Comment by ryanstout** [comment]
@elia let me know if I can help on the source maps stuff.  I think I've hit the same issues.

**Comment by elia** [comment]
@ryanstout what we need imo is some low level fine grained test, and cases could be more or less:

- simple files (1 row per file)
- with or without a CR at EOF

the test should go through generating the sourcemap and using the sourcemap lib to reparse it and check if js points in the right places.

the most difficult thing is not producing the files to test or fixing stuff, rather it setting up the test so that test cases can be added and we can start checking source maps decently.

Feel free to start a branch or a PR, even a trivial setup is valuable :)

**Comment by ryanstout** [comment]
@elia Cool, I should have some time this weekend to get something like that out the door.  I've been a little side tracked on my opal0.7 branch :-)

**Comment by elia** [comment]
great!

**Comment by catmando** [comment]
I just switched from 0.6.x to 0.7 and the source maps are all screwed up.

I am on Rails 3.2

First thing was it reported not being able to find the .map file...

After I touched one of the source files, that went away and now it try's to fetch the .rb files and they are not there.   

For example: I have a file at assets/doodle/pricing.rb.js

The browser tries to fetch assets/doodle/pricing.rb

I am wondering if there is some cache or something I have to clear after the upgrade?  The reason I think that is because it does seem to behave a little differently as I touch files.

**Comment by adambeynon** [comment]
@catmando Every so often I have to delete the compiled files from the cache:

```
rm -rf tmp/cache/assets
```

I do this every time I update the opal gem, especially on big changes like 0.6 -> 0.7. Restarting your server might also help as sprockets can keep some assets in memory, as well as in that dir.

**Comment by catmando** [comment]
@adambeynon thanks, but I had tried that and it doesn't work.

**Comment by deric** [comment]
Is there any equivalent of `require_tree .` which could be used in `application.js.rb`?

**Comment by cantonic** [comment]
@deric yes, `require_tree` is available in Opal: https://github.com/opal/opal/blob/0cd41883d9ac1a8c1d08cd70aa7be2d934898e09/opal/corelib/kernel.rb#L549

**Comment by catmando** [comment]
Still struggling with this source map problem...

What I am seeing now is that the browser is requesting files like this:

/assets/spec/models/test_spec.rb
or
/assets/libs/test.rb

these files don't exist but

the files named test.js.rb DO exist and are the compiled js files.


the end of the opal.map file looks like this:

"sources":["/assets/corelib/runtime.js","/assets/corelib/helpers.rb","/assets/corelib/module.rb","/assets/corelib/class.rb","/assets/corelib/basic_object.rb","/assets/corelib/kernel.rb","/assets/corelib/nil_class.rb","/assets/corelib/boolean.rb","/assets/corelib/error.rb","/assets/corelib/regexp.rb","/assets/corelib/comparable.rb","/assets/corelib/enumerable.rb","/assets/corelib/enumerator.rb","/assets/corelib/array.rb","/assets/corelib/array/inheritance.rb","/assets/corelib/hash.rb","/assets/corelib/string.rb","/assets/corelib/string/inheritance.rb","/assets/corelib/match_data.rb","/assets/corelib/numeric.rb","/assets/corelib/complex.rb","/assets/corelib/rational.rb","/assets/corelib/proc.rb","/assets/corelib/method.rb","/assets/corelib/range.rb","/assets/corelib/time.rb","/assets/corelib/struct.rb","/assets/corelib/io.rb","/assets/corelib/main.rb","/assets/corelib/variables.rb","/assets/corelib/dir.rb","/assets/corelib/file.rb","/assets/opal.rb"],"names":[]}

on the rails side: the backtrace looks like this:

Sprockets::FileNotFound (couldn't find file 'spec/models/test_spec.rb'):
  sprockets (2.2.3) lib/sprockets/trail.rb:81:in `resolve'
...

any help appreciated!

**Comment by cantonic** [comment]
PR dealing with this: #722

**Comment by elia** [comment]
#773 should have fixed this, feel free to reopen or ping me otherwise
