### ISSUE TITLE
obj.methods(false) returns [] even when there are methods

### ISSUE THREAD

**Issue by fkchang** [opal/opal#675]
``` ruby
class Foo
  def bar
    :bar
  end
end

f = Foo.new
f.methods(false) # returns []
```

Live code against 0.7.0.beta3 

http://fkchang.github.io/opal-irb/index-embeddable.html#code:class%20Foo%0A%20%20def%20bar%0A%20%20%20%20%3Abar%0A%20%20end%0Aend%0A%0Af%20%3D%20Foo.new%0Af.methods(false)

**Comment by cj** [comment]
@meh @elia  I just ran into this.  `public_methods(false)` doesn't exist in Opal. 0.8.0.rc1

**Comment by cj** [comment]
without it existing, how would you do something like this?  https://github.com/solnic/virtus/blob/2572ebe4c8346b51b372e1bf813940047db3f648/lib/virtus/instance_methods.rb#L207

**Comment by elia** [comment]
"public_methods" should be added as an alias of "methods"

@cj can you do a PR for this?
