### ISSUE TITLE
class_variable_set support.

### ISSUE THREAD

**Issue by ryanstout** [opal/opal#677]
In MRI you can do:

```
String.class_variable_set(:@@a, 5)
```

Doesn't seem to be a method in Opal.

Thanks!

**Comment by elia** [comment]
Added the methods (get/set) 

**WARNING** I must warn you though that the current cvar implementation makes them just another set of global variables (they're actually in `Opal.cvars`). They should be instead scoped by class and available to all descendants.

**Comment by elia** [comment]
fixed on master:

https://github.com/opal/opal/blob/acba5f18fb45e1c226c015abbe2cb99a26121bf6/opal/corelib/module.rb#L205-L212
