### ISSUE TITLE
for...in iterating over _klass and other Opal attributes

### ISSUE THREAD

**Issue by gabrielrios** [opal/opal#680]
So, I'm working on a wrapper for a javascript library and just stumbled into this problem.

    for (var key in frames)   {
       console.log(key)
    }

**Comment by adambeynon** [comment]
Not a lot we can do about that unfortunately. You could use `hasOwnProperty` to access just instance variables:

```javascript
for (var key in frames) {
  if (frames.hasOwnProperty(key)) {
    // ok
  }
}
```

Bare in mind though, that might also include any singleton methods defined on the object.

**Comment by gabrielrios** [comment]
Ok, thank you @adambeynon you were faster than my update (I had submitted it by mistake)

**Comment by adambeynon** [comment]
No problem. I think some browsers do skip those inherited keys, but `hasOwnProperty` is the safe way to go :+1:
