### ISSUE TITLE
Opal does not catch Object exceptions from Javascript

### ISSUE THREAD

**Issue by bwl21** [opal/opal#681]
Running the following code in http://opalrb.org/try/# indicates that Opal does not catch exceptions from Javascript which are objects. 

It ends in

```
called foo
unhandled exception
the end
```

It works with String exceptions. (remove the comment on 

```// throw "exception from foo"```

This ends in 

```
called foo
caught exception: exception from foo
the end
```

This is the code to play with

```ruby
def foo(m, at)
  puts "called foo"
  %x[
      //throw "exception from foo";
      throw {message: m, pos: at}
   ]
  nil
end

begin
foo("calling foo at", 10)
rescue Object => e
  puts "caught exception: #{Native(e)}"
rescue 
  puts "unhandled exception"
end

puts "the end"
```

**Comment by Ajedi32** [comment]
Is a Ruby `Object` really the same thing as a JavaScript `Object`? I presume it's not, which is why your code isn't working.

**Comment by bwl21** [comment]
I don't think this is the reason. Eventually everything a ruby object, even a Hash? Amazingly, the code also works if I throw an Array. I assume that Opal's exception handling has a missing link here. When I debug it on the Javascript level, I can even see that in between the $err variable is actually an $object, but not processed properly on the ruby side.

**Comment by adambeynon** [comment]
Opal error handling relies on the thrown object being a ruby class or object, so it checks for the `.$$klass` property. Of course, arrays would have this present. Non ruby objects being thrown simply pass through this check. Javascript errors are caught as we bridge between `Error` in js, to the base `Exception` class. Whether or not we should be catching regular js objects - Im not sure. Is there a good reason to throw them instead of `Error`, or a custom subclass?

**Comment by bwl21** [comment]
Not sure if there is a "good "reason for that. But it might happen in external libraries. I went into the issue with https://github.com/douglascrockford/JSON-js/blob/master/json_parse.js which contains

```javascript
        error = function (m) {

// Call error when something is wrong.

            throw {
                name:    'SyntaxError',
                message: m,
                at:      at,
                text:    text
            };
        },
```

I wanted to use this since I should have the position of error in user entered JSON. Standard lib JSON does not report this (neither in ruby nor in Opal)
