### ISSUE TITLE
opal-unity

### ISSUE THREAD

**Issue by ylluminate** [opal/opal#684]
Hey guys, can you chime in on something that has been rolling around our minds for > several months?

It seems that UnityScript is *mostly* a superset of JavaScript.  I was hoping to get some more authoritative input from [my question here](http://stackoverflow.com/questions/27809074/can-javascript-be-expressly-used-to-develop-unity-games), but there wasn't a lot of enlightenment so far since I was already familiar with the link he shared.  I had *hoped* that there was something I'm missing since I have heard people speak very firmly about using JS in Unity.  Oh well...

But, from reviewing [that link](http://wiki.unity3d.com/index.php?title=UnityScript_versus_JavaScript) and thinking about it a bit, it doesn't seem like a far stretch to make an `opal-unity`.  Granted, it would not be a standard wrapper since it would have to modify the output from JS to US, but it seems quite doable.

Any thoughts on what we'd need to work through and where to start in order to *properly* make an extension to `opal` to go down this path?  I don't want to outright fork the project since I think it should rather extend opal vs trying to maintain two codebases.

**Comment by vendethiel** [comment]
The hard part is getting types correctly / emulating their classes

**Comment by ylluminate** [comment]
Right @vendethiel it would appear, then, we would need to really compare Ruby classes with UnityScript classes and then see where we need to go with regards modifying the way Opal handles the class translation to JS vs what would be needed for US.  Hmm.

**Comment by ixixix** [comment]
I would like to opal treejs or(and) phaser JS in 2D

**Comment by ylluminate** [comment]
@ixixix https://github.com/orbitalimpact/opal-phaser

**Comment by elia** [comment]
Closing this, as it's outside the scope of the project. Anyone willing to try implementing it is welcome and will receive all the support we can give :space_invader:
