### ISSUE TITLE
Space regex

### ISSUE THREAD

**Issue by ryanstout** [opal/opal#685]
Not sure if this is something opal can handle (seems like it could), but the following returns true in mri, but false in opal:

```ruby
'  ' =~ /\s/
```

Thanks!

**Comment by adambeynon** [comment]
We do support this: http://opalrb.org/try/#code:p(%22%20%20%22%20%3D~%20%2F%5Cs%2F) 

What version of Opal are you running this against?

**Comment by ryanstout** [comment]
@adambeynon sorry, my bad, I'm still on 0.6.  I tried on opalrb.com, but I realized I messed up and was expecting something different.
