### ISSUE TITLE
Uncaught NoMethodError: undefined method `Native' for main

### ISSUE THREAD

**Issue by YuaShizuki** [opal/opal#689]
app.rb file

```rb
require 'native'
require 'opal'
$window = Native('window')
$window.alert("hello world")
```

this ruby scripts gives the following error in jsconsole 

    Uncaught NoMethodError: undefined method `Native' for main

also I have included these in my html head tag

```
script src="http://cdn.opalrb.org/opal/current/opal.min.js"
script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
script src="app.js"
```

**Comment by elia** [comment]
this should work:

script tags:

```
script src="http://cdn.opalrb.org/opal/current/opal.min.js"
script src="http://cdn.opalrb.org/opal/current/native.min.js"
script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
script src="app.js"
```

app.rb

```rb
require 'opal'
require 'native'
$window = Native(`window`)
$window.alert("hello world")
```

**Comment by YuaShizuki** [comment]
Yeah thanks it helped

**Comment by ashes999** [comment]
Can this be documented somewhere? There's no link to `native.min.js` on the main website, or on GitHub either. I ran into this today and only found this by searching GitHub.

**Comment by vais** [comment]
@ashes999 could you help by sending a PR please?

**Comment by ashes999** [comment]
@vais opened a PR [here](https://github.com/opal/opalrb.org/pull/29)

**Comment by vais** [comment]
Thanks @ashes999 :+1: 
@elia this one's for you to merge :stuck_out_tongue_winking_eye:
