### ISSUE TITLE
should HTTP payload be converted (optionally) to rails style params

### ISSUE THREAD

**Issue by catmando** [opal/opal#695]
Note: I could be missing something but...

For example lets say you have 
````
     my_params = {job: {copies: 10, width: 720, height: 1044}, customer_id: 9956}
````
if we send this up to a rails server this needs to get converted to
````
     job[copies]=10
     job[width]=720
     ....
     customer_id=9956
````
right now its sending it up as a json hash.

work around is to do this:  
````
     `jQuery.param(#{my_params}.to_n})`
````
I feel like this should be automatic perhaps  we could have a param_format option, where the default is `:json` but allow `:rails` etc.

Be happy to do a fork of this, if agreed.

**Comment by jaredcwhite** [comment]
I ran into this issue, and agree with you there should be an option for the param format. However, Rails (recent version anyway) can accept JSON payloads -- you just need to put `wrap_parameters false` at the top of your controller (or base/parent controller), which is what I did and that works out just fine.

**Comment by elia** [comment]
I'm not completely sure about the topic of this issue, but seems more related to opal-rails and/or opal-jquery than opal itself.

Gonna close it, please let me know if it should be reopened in one of those repos.
