### ISSUE TITLE
Array#product

### ISSUE THREAD

**Issue by JikkuJose** [opal/opal#699]
The `method` `Array#product` seem to be failing.

**Comment by vais** [comment]
@JikkuJose I don't think this method has been implemented yet. There is a [spec for it](https://github.com/opal/rubyspec/blob/master/core/array/product_spec.rb) but it is also listed in [spec/filters/bugs/array.rb](https://github.com/opal/opal/blob/master/spec/filters/bugs/array.rb#L84), which means that this is something that needs to be worked on? @elia is everything in https://github.com/opal/opal/tree/master/spec/filters/bugs basically a "to do" item for Opal?

**Comment by adambeynon** [comment]
@JikkuJose yeap, that's

**Comment by adambeynon** [comment]
Sorry. Closed by mistake. Yes, that's a method yet to be implemented.

**Comment by JikkuJose** [comment]
I just implemented `product` in a module and extended an already available class with it. Just wanted to know whether its recommended, I seem to feel the code seems be pretty slow. Its likely that I am making some stupid mistake, but felt like asking if there is anything recommended to use/not in Opal from Ruby?

**Comment by vais** [comment]
@JikkuJose are you implementing it in Ruby or JS? I imagine something like `Array#product` is best implemented in JS for performance reasons.

**Comment by JikkuJose** [comment]
@vais I implemented an algorithm for Conway Game of Life, but to my disappointment it ran less performant than what I expected. Its possible my implementation is pretty sloppy. Its done in Ruby. You can take a look at the [implementation](https://github.com/JikkuJose/Conway-Game-of-Life/blob/master/app/conway/algorithm.rb).
