### ISSUE TITLE
Native wrapper could shadow javascript-land objects

### ISSUE THREAD

**Issue by andrewhr** [opal/opal#704]
Experimenting with a simple bridge for native javascritpt objects, I wrote this simple code:

```ruby
require 'native'
document = Native(`document`)
```

This example is pretty naive, but my expectation was than `document` from Opal-land is a different scope of the Javascript `document` - to interop with JS have to create Opal wrapper objects after all. But looking on the generated code, a `var document = nil` is put in the beginning of the method, shadowing the browser's global `document`.

As a reference, the generated code (by Opal 0.7):

```javascript
/* Generated by Opal 0.7.0 */
(function(Opal) {
  Opal.dynamic_require_severity = "error";
  var self = Opal.top, $scope = Opal, nil = Opal.nil, $breaker = Opal.breaker, $slice = Opal.slice, document = nil;

  Opal.add_stubs(['$require', '$Native', '$puts']);
  self.$require("native");
  document = self.$Native(document);
  return self.$puts(document);
})(Opal);
```

**Comment by meh** [comment]
This is expected, note that you can still access `document` as `window.document`.
