### ISSUE TITLE
List of open issues that have already been resolved and should be closed

### ISSUE THREAD

**Issue by vais** [opal/opal#707]
I reviewed the 89 currently open issues, mostly to learn and to see what I can help with, but also because I noticed that sometimes issues do not get closed after they are resolved. I was hoping to find a treasure trove of issues that can be closed to reduce the signal to noise ratio, but unfortunately found just a few that I could test and say with confidence can be closed now.

Without further ado, the following issues currently remain open even though they have already been resolved:

@adambeynon 
* [bug: foo = ''; foo['bar'] ? true : false | is returning true. #700](https://github.com/opal/opal/issues/700)
* [Opal reports incorrect version numbers #698](https://github.com/opal/opal/issues/698)
* [Populate MatchData in String#sub (which will apply to String#gsub as well) #277](https://github.com/opal/opal/issues/277)

@meh, @adambeynon, @elia 
* [round() bahaves different in Opal than in MRI #572](https://github.com/opal/opal/issues/572)

@elia 
* [[edge-case] constant lookup diverge from MRI #548](https://github.com/opal/opal/issues/548)

@meh
* [const_missing does not work for inline constants #484](https://github.com/opal/opal/issues/484)

At anyone with the ability to close issues:
* ['Pipe equal' on array #665](https://github.com/opal/opal/issues/665)
* [False returned from && #664](https://github.com/opal/opal/issues/664)

**Comment by meh** [comment]
Verified and closed, except the edge-case which hasn't been fixed or decided upon. Thanks.

Also if you don't know there's an IRC channel on freenode, we're always there.

**Comment by vais** [comment]
Thank you, @meh! Yes, I misunderstood the edge-case issue, it's over my head :)
