### ISSUE TITLE
cant get source maps to work with 0.7 and clean rails 

### ISSUE THREAD

**Issue by catmando** [opal/opal#720]
been struggling with this for a while, so I created a brand new install with rails 4x and lo and behold I still can't get source maps to work.  For example 

/assets/spec/models/opal_spec.rb has an internal server error:

````
Started GET "/assets/spec/models/opal_spec.rb" for 67.240.177.41 at 2015-03-04 01:10:58 +0000

Sprockets::FileNotFound (couldn't find file 'spec/models/opal_spec.rb'):
  sprockets (2.12.3) lib/sprockets/base.rb:153:in `resolve'
  opal (0.7.0) lib/opal/sprockets/server.rb:48:in `call'
  rack (1.5.2) lib/rack/cascade.rb:33:in `block in call'
  rack (1.5.2) lib/rack/cascade.rb:24:in `each'
  rack (1.5.2) lib/rack/cascade.rb:24:in `call'
````
Here is my gem file list, I assume somehow I have an incompatibility.  I can also store this off to a repository if that would help.
````
Using rake 10.4.2
Using i18n 0.7.0
Using minitest 4.7.5
Using multi_json 1.10.1
Using thread_safe 0.3.4
Using tzinfo 0.3.43
Using activesupport 4.0.2
Using builder 3.1.4
Using erubis 2.7.0
Using rack 1.5.2
Using rack-test 0.6.3
Using actionpack 4.0.2
Using mime-types 1.25.1
Using polyglot 0.3.5
Using treetop 1.4.15
Using mail 2.5.4
Using actionmailer 4.0.2
Using activemodel 4.0.2
Using activerecord-deprecated_finders 1.0.3
Using arel 4.0.2
Using activerecord 4.0.2
Using bundler 1.8.3
Using coffee-script-source 1.9.1
Using execjs 2.3.0
Using coffee-script 2.3.0
Using thor 0.19.1
Using railties 4.0.2
Using coffee-rails 4.0.1
Using hike 1.2.3
Using jbuilder 1.5.3
Using jquery-rails 3.1.2
Using json 1.8.2
Using sourcemap 0.1.1
Using tilt 1.4.1
Using sprockets 2.12.3
Using opal 0.7.0
Using opal-activesupport 0.1.0
Using opal-jquery 0.3.0
Using opal-rspec 0.4.1
Using sprockets-rails 2.0.1
Using rails 4.0.2
Using opal-rails 0.7.0
Using rdoc 4.2.0
Using sass 3.2.19
Using sass-rails 4.0.5
Using sdoc 0.4.1
Using sqlite3 1.3.10
Using turbolinks 2.5.3
Using uglifier 2.7.1
````

**Comment by elia** [comment]
Source maps are quite broken in 0.7. 

Specifically the broken cog is the concatenation system, and probably the server. 

I'm willing to fix them as soon but I don't have much time these days as my newborn daughter takes most of the time and even if I often brag about how good I am at programming one handed I'm not *that* good. :)

**Comment by catmando** [comment]
hey congrats on the new born!  Suggestions?  I went to 0.7 because I could not get specs to work in 0.6.  I am happy to also work on this if I could get some hints on what we need to do to fix.   

Or is there a suggested good configuration that will work?  I have this chain of problems... first we cannot have $ used in our code base, so I need the newer version of opal-jquery (the old one had explicit references to $.)   The new one however I think forces me to upgrade to 0.7 as there seems to be something when you run specs that results in Element not be able to be extended.  If this is news I can recreate that as well :-)

**Comment by catmando** [comment]
Okay, so I think I have a fix for this, will try to add some tests, and do a pull request shortly.

**Comment by elia** [comment]
looking forward to it, I have some fixes ready too

**Comment by catmando** [comment]
okay, so I am noticing one thing in the tests which I want to clarify.

The tests for the source mapping do NOT have any files ending with .js.rb or .js.opal

I did some experiments in rails with ending files in .rb and while the code loads and executes and the map is correct, what happens is that the request for the foo.rb file never hits the source map server.  However the rails server just returns the same .js file content it already sent to the browser (which makes sense.)

So that is probably why the tests were passing regardless of the bug I found in the source map server.

So my question is do you want me to see if I can clean those tests up (i.e. change .rb file names to .js.rb) or simply add some new new tests for the .js.rb and .js.opal cases.

**Comment by elia** [comment]
@catmando pushing my WIP to a branch so you can cherry-pick or whatever

**Comment by elia** [comment]
@catmando https://github.com/opal/opal/pull/722

**Comment by catmando** [comment]
hmmm... I was running into other problems earlier this morning so i started with the 0.7.1 tag...

looks like you will get to cherry pick I am afraid :-)

**Comment by focused** [comment]
I hope you'll fix it soon, is there a way to turn off warnings about absent source maps in rails logs?

**Comment by cantonic** [comment]
@focused it is fixed already so far, but the pull request is not merged yet. see #722 
If you are using opal-rails, there is a pull request, too: https://github.com/opal/opal-rails/pull/40

**Comment by elia** [comment]
#773 should have fixed this, feel free to reopen/ping me otherwise
