### ISSUE TITLE
master branch is breaking rspec

### ISSUE THREAD

**Issue by catmando** [opal/opal#724]
running rspec in rails (i.e. /opal_spec seems broken in latest opal master branch)

Not sure if its an rspec problem or opal.

The rspec test is just the simple example shown in the readme.

The error seems to be in stub_chain (js line 5) which is doing an alias_method.  Opal is saying $$super does not exist on ancestor in Opal.alias

**Comment by elia** [comment]
@meh I think we should double check the recent cleanups for this

**Comment by meh** [comment]
@elia I'm pretty sure that stuff hasn't been touched by my changes, I'll need a reproducible example tho. Also weird it wasn't caught by the specs.

**Comment by elia** [comment]
Too bad, if it was there ig would have been easier to catch

**Comment by meh** [comment]
I mean, it does access `$$super`, but it shouldn't have touched super itself.

**Comment by meh** [comment]
Yeah it was the code, that error comes from when a method is missing in a `class << self; alias ...; end`, but the alias code was too closely tight with the runtime changes in my branch, so I reverted them.
