### ISSUE TITLE
object_id meaningless for strings, numbers, and booleans

### ISSUE THREAD

**Issue by vais** [opal/opal#729]
This is best explained with an example ([try opal](http://opalrb.org/try/?code:s%20%3D%20%22hello%22%0Ap%20s.object_id%0Ap%20s.object_id%0Ap%20s.object_id%0A%0Ai%20%3D%20420%0Ap%20i.object_id%0Ap%20i.object_id%0Ap%20i.object_id)):
```ruby
s = "hello"
p s.object_id
p s.object_id
p s.object_id

i = 420
p i.object_id
p i.object_id
p i.object_id

# => 6931
# => 6932
# => 6933
# => 6934
# => 6935
# => 6936
```

**Comment by Ajedi32** [comment]
FYI, in MRI I think certain objects have well-defined ids. For example, in all instances of Ruby:

```ruby
false.object_id
#=> 0
true.object_id
#=> 2
nil.object_id
#=> 4
0.object_id
#=> 1
1.object_id
#=> 3
2.object_id
#=> 5
-1.object_id
#=> -1
```

**Comment by Ajedi32** [comment]
For Strings and Numbers, could a consistent ID by implemented by utilizing the [Distinction between string primitives and String objects](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String#Distinction_between_string_primitives_and_String_objects) in JavaScript? E.g. We could somehow ensure that we're using String objects instead of raw strings. Or would that be a performance issue, even for the native JavaScript String class?

**Comment by vais** [comment]
@Ajedi32 I believe in MRI for objects that live on the heap the actual memory pointer to the object figures into the object_id somehow. There's no way to do that in JS.

As for String objects vs primitive strings, I feel there is a consensus that this would not be good for performance. And this is also why, as far as I understand, Opal does not support Ruby's mutable strings.

Perhaps others, who, unlike me, actually know what they are talking about, can comment on that here :)

**Comment by elia** [comment]
The problem is that those values are being promoted to objects each time a method is called on them. A possible fix would be to `new String('foo')` when instantiating string but I agree it could harm performance.

About #731 I don't like changing the type returned by object_id, I know we're already doing that for `#hash` but I'd avoid it too if possible.

**Comment by adambeynon** [comment]
I might be completely wrong here, but I always thought that string (or number) literals were converted to objects every time you call a method on them.

So, assuming most strings have a method called on them at some point, converting them to objects once at creation could actually save some overhead (but assuming could be a bad idea).

**Comment by elia** [comment]
I agree that's unlikely that doesn't get any method call (or property lookup). The only other thing that I'd consider is that generated code will be more noisy. Not saying it's not worth it tho.

**Comment by meh** [comment]
@elia @adambeynon we'd end up with the same problems with strings returned by native APIs, so I'd say no to that.

**Comment by Ajedi32** [comment]
@vais

> I believe in MRI for objects that live on the heap the actual memory pointer to the object figures into the object_id somehow. There's no way to do that in JS.

Well, for those particular objects I mentioned the id doesn't seem to have anything to do with the position in the heap. `false` will always have an id of 0, `true` will always have an id of 2, `nil` will always have an id of `4`, and positive integers (or, more precisely, `Fixnum`s) will always have an id of (<number>*2-1). (And because of that property of integers, all other objects will always have an even `object_id`. E.g. `10_000_000.times { puts "Odd object id!" if Object.new.object_id.odd? }` prints nothing.)

**Comment by Ajedi32** [comment]
I wonder if there's some way we could use the compiler to determine whether a given primitive ever has a method called on it, and then wrap it if it does. Maybe something similar to the current implementation of `method_missing`? (Which, if I understand correctly, implements `method_missing` stubs that way?) I really have no idea...

**Comment by meh** [comment]
@Ajedi32 we'd still have problems with native APIs.

**Comment by meh** [comment]
Also sincerely I don't know how valuable it is to have consistent `#object_id`, and I'm usually all for maintaining semantics.

**Comment by Ajedi32** [comment]
By consistent, I meant: `ob1.object_id == obj1.object_id`.

If you were referring to the way MRI object ids are determined for integers, `true`, `false`, and `nil`, really the only advantage there is that `1.object_id == 1.object_id #=>`, unlike JavaScript's `new Number(1) === new Number(1) //=> false`.

**Comment by Ajedi32** [comment]
Also, I'd like to prove opal/rubyspec#2 wrong if possible.

**Comment by vais** [comment]
Thanks @Ajedi32, [here is a PR](https://github.com/opal/opal/pull/733) that implements your suggestions regarding how `object_id` works in MRI.

@meh what do you mean by this:
> Also sincerely I don't know how valuable it is to have consistent #object_id, and I'm usually all for maintaining semantics.

I.e. would you be ok with `object_id` returning a string from `String#object_id` and numbers for everything else?

@elia you expressed that you don't like `object_id` returning strings. What do you think of https://github.com/opal/opal/pull/733 - now it's mostly numbers per @Ajedi32's suggestion, but I see no way of getting around returning a string from `String#object_id`.

**Comment by elia** [comment]
I like #733 very much, considering all strings as defined with .freeze could justify (in my mind) to have the same object id for the same contents. Just loud thinking :)

**Comment by vais** [comment]
@elia yep, I like how it works out too. Thanks to @Ajedi32 for proposing this approach!

**Comment by meh** [comment]
Sounds good enough for me.

**Comment by vais** [comment]
@meh, excellent, we are getting there!

So, I feel this thing needs tests, since it's not covered by rubyspec. What would be the best place to add such tests?

**Comment by elia** [comment]
I think it depends on what you wanna test. If it's something specific of the Opal implementation it should go in spec/opal:

https://github.com/opal/opal/tree/master/spec/opal

**Comment by vais** [comment]
Thanks, @elia. I added another commit to https://github.com/opal/opal/pull/733, and the tests are here: 
https://github.com/vais/opal/blob/object_id2/spec/opal/core/object_id_spec.rb

I debated with myself whether all the tests should be in a single file called `object_id_spec.rb` or have each test go into the appropriate file per class. I decided that keeping the `object_id` logic in a single file is a clearer approach as opposed to spreading it all over the spec suite. I am open to suggestions though.

**Comment by vais** [comment]
Thanks, @meh!
