### ISSUE TITLE
Guarding against performance regressions in Opal

### ISSUE THREAD

**Issue by vais** [opal/opal#736]
Rubyspec does an excellent job guarding against regressions when new code is added or existing code is modified. It makes it possible for new people like me to jump in and help out, and as long as the spec suite passes, everyone else on the project can be comfortable in the knowledge that the new guy didn't break anything :-) I am using "the new guy" for dramatic effect, but the same certainly applies to everyone who touches the code in any way.

What Rubyspec unfortunately *does not* do for us is provide any assurance that while the code is correct, it did not inadvertently degrade (or utterly kill) the performance of Opal in some indirect way, like changing a method in one class that another seemingly unrelated class in corelib happens to call a lot.

I would love to have some sort of a safety net in place for this. I am thinking about a separate performance analysis tool that works by hooking into mspec so that each spec is run as a benchmark multiple times against Opal and then the same number of times against MRI. Then maybe play with some average stats for MRI baseline and see where Opal deviates abnormally.

Anyway, before jumping into the deep end, I thought it would be a good idea to ask you guys if there is already something that does this for us that I am simply not aware of, or if you have any ideas about how to put such a safety net in place, so when people contribute code to the corelib you can easily see what impact the new code has on Opal. I think having something like that would help both the maintainers and the contributors to Opal.

**Comment by ryanstout** [comment]
@vais this sounds like an interesting idea. I was thinking about building out a simple benchmarking suite for volt. Maybe integrating capybara so we can test the browsers would be really useful.

**Comment by elia** [comment]
Sounds great!

Maybe it's worth checking CRuby and the other implementations too see if they already have something like that in place and if it's something that can become like the standard test bench for many rubies.

**Comment by elia** [comment]
Btw there's nothing like that that I'm aware of.

**Comment by elia** [comment]
Could be a starting point: 

http://programmingzen.com/2007/12/03/the-great-ruby-shootout/

https://github.com/acangiano/ruby-benchmark-suite

Then we'll ask @acangiano to write a new shootout across al js implementations :P

**Comment by vais** [comment]
@elia thanks for suggesting https://github.com/acangiano/ruby-benchmark-suite, that's a good starting place. It's not quite what I had in mind, but having some kind of benchmarking option is better than having none at all. I will look into what it would take to get it to run against Opal.

**Comment by vais** [comment]
@ryanstout please report any performance bottlenecks you find in Volt back to Opal as issues. Focusing on a real world app performance issues beats working with any artificial benchmark.

**Comment by KillaPL** [comment]
Check out this: https://rubybench.org. It has quite some benchmarks, with source code available.

**Comment by vais** [comment]
@KillaPL thanks!

**Comment by Ajedi32** [comment]
Hmm, this is a really interesting idea. I'm envisioning something like [SimpleCov](https://github.com/colszowka/simplecov), but for performance instead of coverage. It would track the run time of all the regular tests, and possibly also allow special "performance unit tests" that it would also keep track of the runtime of.

**Comment by KillaPL** [comment]
Maybe something like opalbench.org, which would run the whole suite for opal and keep truck of the results? But I suppose that would take quite some time of work. And would depend on opal environment.

**Comment by vais** [comment]
@Ajedi32 that's a nice way to look at it, yes, something like test coverage. Benchmark coverage? :)

**Comment by wied03** [comment]
@vais - can this be closed due to recent conversations?

**Comment by vais** [comment]
@wied03 done :sparkles:
