### ISSUE TITLE
First problem trying to run rubyspec on IE

### ISSUE THREAD

**Issue by vais** [opal/opal#740]
I am doing `rackup`, then visit `http://localhost:9292/` in IE 8. I do not have access to IE 6, but I figured getting rubyspec to run on IE 8 is a good enough first step to verifying IE 6 compatibility. I anticipate plenty of issues on IE 8 anyway :) So, here comes the first show-stopper.

This line `self.new = self.$new;` in the code below causes IE 8 to fail with the dreaded "Expected identifier" error. The reason for this is [explained very well here](http://tiffanybbrown.com/2013/09/10/expected-identifier-bug-in-internet-explorer-8/). This is an issue for all IEs prior to IE 9. The problem is using reserved words as identifiers, in this case `new`.

Interestingly, this is not an issue when running in production, as in Try Opal, because the minification process fixes the problem. Minification turns this: `self.new = self.$new` into this: `e["new"]=e.$new`, which is harmless.

Is there a way to make the compiler output `self["new"] = self.$new` instead of `self.new = self.$new`?

Am I taking crazy pills trying to get rubyspec to run on IE? Let me know :)

```javascript
  (function($base, $super) {
    function $Class(){};
    var self = $Class = $klass($base, $super, 'Class', $Class);

    var def = self.$$proto, $scope = self.$$scope;

    def.$native_alias = function(new_jsid, existing_mid) {var $arity = arguments.length;if ($arity !== 2) { Opal.ac($arity, 2, this, "native_alias"); }
      var self = this;

      
      var aliased = self.$$proto['$' + existing_mid];
      if (!aliased) {
        self.$raise($scope.get('NameError'), "undefined method `" + (existing_mid) + "' for class `" + (self.$inspect()) + "'");
      }
      self.$$proto[new_jsid] = aliased;
    ;
    };

    return (def.$native_class = function() {var $arity = arguments.length;if ($arity !== 0) { Opal.ac($arity, 0, this, "native_class"); }
      var self = this;

      self.$native_module();
      self.new = self.$new;
    }, nil) && 'native_class';
  })(self, null);
  return $gvars.$ = $gvars.global = self.$Native(Opal.global);
};
```

**Comment by elia** [comment]
good catch!

**Comment by meh** [comment]
From what I recall the problem with running rubyspec on IE was that it would time out and die.

**Comment by vais** [comment]
@meh as it stands, I would consider it great success to even get to that point. Any idea how I can work around this compiler issue?
cc @adambeynon

**Comment by adambeynon** [comment]
For IE (And other browsers that timeout), we could run some spec groups through `setTimeout` or similar, and run each group async. This should solve long running process of running all specs at the same time. Not ideal for testing performance (how long groups take to run), but at least we can run all specs on all browsers. It could even be an option on the runner.

**Comment by adambeynon** [comment]
@vais It looks like the bad code is from some inline js (using x-strings), see:

https://github.com/opal/opal/blob/fece6f3e12a82a320b16d2c5ca223246166e4044/stdlib/native.rb#L553

**Comment by elia** [comment]
shame on me 😞

**Comment by vais** [comment]
@adambeynon thanks! @elia shame on me for not seeing it when I grepped for it :) I am spinning up a Windows VM right now to test it out, will send a PR if it works out.

**Comment by vais** [comment]
@adambeynon @elia I've made some progress replacing `.new` with `["new"]` (turns out it's just two occurrences, really), but now I'm stuck on IE choking on Ruby's regexp flags (`x`, `u`, `n`, etc). This is not an IE-only issue, just try this out in your browser of choice (I'm getting basically the same result on Chrome, Safari, Firefox): http://opalrb.org/try/?code:re%20%3D%20%2Fhello%2Fx

Any suggestions for what to do with Ruby's regexp flags that are invalid in JS? Strip them out at compile time? Let the user get an error at runtime, but mark all the specs that use them as `not_supported_on :opal` to be able to run rubyspec? I feel like I'm in over my head. And more importantly I do not understand why this is not an issue when running rubyspec normally, considering that:
```
$ opal -e "re = /hello/x"

[stdin]:11475
  return re = /hello/x
  ^
SyntaxError: Invalid flags supplied to RegExp constructor 'x'
    at new RegExp (<anonymous>)
    at [stdin]:11475:3
    at [stdin]:11476:3
    at Object.<anonymous> ([stdin]-wrapper:6:22)
    at Module._compile (module.js:456:26)
    at evalScript (node.js:559:25)
    at Socket.<anonymous> (node.js:154:11)
    at Socket.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:442:13)
```
WTF?

**Comment by Ajedi32** [comment]
> Any suggestions for what to do with Ruby's regexp flags that are invalid in JS?

I'd say throw an error and refuse to compile (or throw an error at runtime, in the case where the flags are set dynamically). Failing fast is probably a good idea. The faster the feedback to the developer, the less time it will take them to correct the problem.

**Comment by vais** [comment]
Update: I think I get it now. It's not a syntax error until the code gets executed (which is crazy, but it is what it is).

So, the following is "no problem":
```
$ opal -e "a = lambda{re = /hello/x}"
```
But the following throws an error:
```
$ opal -e "a = lambda{re = /hello/x}; a.call"

[stdin]:11477
  return re = /hello/x}, TMP_1._s = self, TMP_1), $a).call($b);
  ^
SyntaxError: Invalid flags supplied to RegExp constructor 'x'
    at new RegExp (<anonymous>)
    at $a._p.TMP_1 ([stdin]:11477:3)
    at Function.def.$call.TMP_2 ([stdin]:10148:23)
    at [stdin]:11478:12
    at [stdin]:11479:3
    at Object.<anonymous> ([stdin]-wrapper:6:22)
    at Module._compile (module.js:456:26)
    at evalScript (node.js:559:25)
    at Socket.<anonymous> (node.js:154:11)
    at Socket.emit (events.js:117:20)
```
Same thing in Chrome console:
```
> a = function(){re = /hello/x;}
< function (){re = /hello/x;}
> a()
Uncaught SyntaxError: Invalid flags supplied to RegExp constructor 'x'
```
But in Firefox (and IE does a similar thing) a syntax error happens immediately:
```
> a = function(){re = /hello/x;}
x SyntaxError: invalid regular expression flag x
```
So, as long as a spec that contains invalid regular expressions does not get executed, all is fine everywhere except Firefox and IE.

Question: when you mark a spec as `fail`, does it mean that it **still gets included into the complied JS** and simply does not get executed? Is there a way to exclude it entirely?

**Comment by adambeynon** [comment]
@vais When we use `fail` to mark a spec, it still gets compiled. The runner (at runtime) basically checks each spec at runtime to see if it has been marked as a `fail`, and if so, just skips it. We can't stop specs running at compile time on a per spec basis, we can only do this on a per file basis (our ruby spec file has a long list of globs matching files and directories we wish to run).

**Comment by adambeynon** [comment]
For reference: https://github.com/opal/opal/blob/master/spec/rubyspecs

**Comment by vais** [comment]
@adambeynon got it, that's what I thought. So, even wrapping the assertions containing "invalid" regexps in `not_supported_on :opal` will not make a difference on Firefox and IE - you will still get a syntax error. That pretty much makes it impossible to run rubyspec in those browsers as far as I can tell.

**Comment by adambeynon** [comment]
@vais As the `x` flag is unsupported, we can either make it raise a runtime or compile time error. A compile time error doesn't help in this case, as it would prevent us running ruby spec anywhere. Instead, for unsupported regexp flags, the compiler can just generate a self raising error, instead of a knowingly bad regexp flag. That way, we can wrap it in `not_supported_on :opal`, and atleast it will not generate a syntax error.

**Comment by vais** [comment]
@adambeynon that would be great - it means I get to continue to play around with IE, awesome! :)
I assume you are aware that `x` is not the only Ruby flag that is invalid in JS though, there's also `u`, `n`, and others that I can't remember off the top of my head. Please let me know if you'd like me to do the legwork on this, anything I can do to help make this happen.

**Comment by elia** [comment]
Actually some calls are skipped at compiler level:

https://github.com/opal/opal/blob/master/lib/mspec/opal/special_calls.rb

**Comment by elia** [comment]
But agree on raising on unsupported regexps

**Comment by vais** [comment]
@elia wow, thanks for pointing that out, I had no idea! In that case I think the only thing that needs to be done is wrap those assertions in `not_supported_on :opal`. I'll try that.

**Comment by vais** [comment]
After wrapping the assertions that contain invalid regexp flags in `not_supported_on :opal`, Firefox is not throwing syntax errors anymore. Have not tested on IE yet, but that's as good a sign as any that this is no longer an issue!

Here is what running on different browsers on my Mac looks like now:

* Firefox: `3829 examples, 0 failures (time taken: 14.990000009536743)`
* Safari: `3829 examples, 0 failures (time taken: 16.342999935150146)`
* Chrome: `3829 examples, 1 failures (time taken: 11.952999830245972)` (Failure not related to regexp, in `Math#exp`, `Expected 11226018484.0012 to be within +/- 0.00003 of 11226018484.001236`)

@elia, there is only one file changed in the rubyspec fork, and I know how to send a PR for that. But there is also a single `not_supported_on :opal` that needs to be added to`opal/spec/stdlib/rubysl-strscan/spec/scan_spec.rb`, which is a submodule pointed to the original repo, not a fork we control as far as I understand. What should I do?

**Comment by vais** [comment]
@elia, btw, the change that needs to be made to `opal/spec/stdlib/rubysl-strscan/spec/scan_spec.rb` is just this:
```diff
-    it "returns the matched string for a multi byte string with unicode regexp" do
-      $KCODE = 'NONE'
-      m = StringScanner.new("Привет!")
-      m.scan(/[А-Яа-я]+/u).should == "Привет"
-      m.rest.should == "!"
+    not_supported_on :opal do
+      it "returns the matched string for a multi byte string with unicode regexp" do
+        $KCODE = 'NONE'
+        m = StringScanner.new("Привет!")
+        m.scan(/[А-Яа-я]+/u).should == "Привет"
+        m.rest.should == "!"
+      end
     end
```

**Comment by elia** [comment]
At this point I think it's better to check the status of stdlib in ruby/rubyspec first. Long term goal is still to share the same repo.

**Comment by elia** [comment]
After a quick check seems they have stdlib back into the main repo

https://github.com/ruby/rubyspec/tree/master/library/stringscanner

**Comment by adambeynon** [comment]
@elia Awesome. I really didn't like all the `ruby-sl` gems. I guess we should be looking to forking `ruby/rubyspec` instead?

**Comment by elia** [comment]
@adambeynon yep, I checked on a real keyboard too and apparently they just skipped the ruby-sl thing, there's also a ton of new stuff, but hopefully they'll merge in our stuff without much fuss

**Comment by vais** [comment]
@elia that's good news indeed! I lack the requisite git-fu to pull off this feat though, definitely need your help on this one.

**Comment by elia** [comment]
@vais #755

**Comment by elia** [comment]
@vais should be fine now, right?

**Comment by vais** [comment]
@elia, we are running a lot more rubyspecs now, and some of them come with more invalid regexp flags. So, running rubyspecs in the browser will be an on-going struggle. In the meantime, I think it's ok to close *this* issue.
