### ISSUE TITLE
Current state of trying to run rubyspec in different web browsers

### ISSUE THREAD

**Issue by vais** [opal/opal#741]
Doing `rackup`, then `http://localhost:9292`:

* __IE 8__: Does not run. Chokes on `self.new = self.$new;` with `Expected identifier` error due to `new` being a reserved keyword. See https://github.com/opal/opal/issues/740
* __Chrome__: fails `Math#exp is accessible as a private instance method`, `Expected 11226018484.0012 to be within +/- 0.00003 of 11226018484.001236` Any suggestions on how to squelch this failure? Set the `TOLERANCE` constant to be `0.00004` prior to running the spec in the browser?
* __Safari__: `3810 examples, 0 failures`. Yey! (But see *WTF regarding the `x` regexp flag* below)
* __Firefox__: Does not run. `SyntaxError: invalid regular expression flag x`

*WTF regarding the `x` regexp flag*: Firefox is the only one complaining about the invalid `x` flag on regular expressions. However, trying to use this flag on a regexp literal within developer tools console in Chrome and Safari also throws a syntax error, as does nodejs:
```
> /123/x
SyntaxError: Invalid flags supplied to RegExp constructor 'x'
    at new RegExp (<anonymous>)
    at repl:1:1
    at REPLServer.self.eval (repl.js:110:21)
    at Interface.<anonymous> (repl.js:239:12)
    at Interface.emit (events.js:95:17)
    at Interface._onLine (readline.js:202:10)
    at Interface._line (readline.js:531:8)
    at Interface._ttyWrite (readline.js:760:14)
    at ReadStream.onkeypress (readline.js:99:10)
    at ReadStream.emit (events.js:98:17)
```
Why does this happen in developer tools but not when running rubyspec?

**Comment by elia** [comment]
About the regexp issue I think that maybe on rubyspec it's initialized with `new`. That could explain Firefox complaining about the flag and not the syntax

**Comment by elia** [comment]
Ok forget the last sentence:)

**Comment by vais** [comment]
Closed because the real discussion is happening in https://github.com/opal/opal/issues/740
