### ISSUE TITLE
mspec's bignum_value helper

### ISSUE THREAD

**Issue by vais** [opal/opal#746]
Mspec defines `bignum_value` helper [as follows](https://github.com/rubyspec/mspec/blob/master/lib/mspec/helpers/numeric.rb#L10):
```ruby
  def bignum_value(plus=0)
    0x8000_0000_0000_0000 + plus
  end
```
This number is too big for javascript:
```
ruby -Ilib bin\opal -e "puts 0x8000_0000_0000_0000"
9223372036854776000

ruby -Ilib bin\opal -e "puts 0x8000_0000_0000_0000 + 1"
9223372036854776000
```
There are many specs using this helper. Any ideas on how to proceed? `not_supported_on :opal`?

**Comment by Ajedi32** [comment]
Fyi, on MRI:

```ruby
(0x3FFF_FFFF).class #=> Fixnum
(0x3FFF_FFFF+1).class #=> Bignum
```

So Ruby solves this problem by using an entirely separate class for large numbers. Not sure whether that's feasible to do with Opal. In order to support huge numbers though, I think at some point a Bignum class will be required, even if it's not integrated with the language as well as it is with MRI.

**Comment by vais** [comment]
From now on, any spec failure that involves bignums will be placed under `spec/filters/unsupported` if the entire example fails, or wrapped in `not_supported_on :opal` if only a sub-set of assertions within an example fails. @elia, @meh, @adambeynon, do you guys agree?

**Comment by elia** [comment]
Fine by me

**Comment by eregon** [comment]
One alternative could be to make `bignum_value` to be `INT_MAX` as many JS implems use `int` internally when it fits and goes to a "larger" (so double would be the "Bignum") type if not.

Or the maximum value which can be represented exactly as a `double` (around `2**52`) could also make sense as Fixnum are essentially immediate exact integral values, which `double` can provide in the approximate range `-2**52` to `2**52`.

**Comment by vais** [comment]
@eregon you mean make this change in MSpec? In the end Opal still cannot pass specs that involve bignums though. I'm confused.

**Comment by eregon** [comment]
@vais It's my mistake, I thought `bignum_value` was defined in terms of `fixnum_max` but it is arbitrarily `2**63 + x`. In any case, I think it would first be more useful to know whether Opal wants arbitrary-precision integers or not.
