### ISSUE TITLE
Integer division

### ISSUE THREAD

**Issue by vais** [opal/opal#748]
Currently all numbers are parsed as `Numeric`. I.e.:

``` ruby
p 1.class   #=> Numeric
p 1.0.class #=> Numeric
p 1.1.class #=> Numeric
```

Would it be possible to parse integers as `Integer` and floats as `Float`? This way appropriate logic could be implemented for the division `/` method.

As it stands now, in MRI:

``` ruby
1/3 #=> 0
```

In Opal:

``` ruby
1/3 #=> 0.3333333333333
```

Or is what I'm asking even possible? (I have a feeling it's not :) but I'd like to understand why).

**Comment by elia** [comment]
Of course the problems lies in mapping both Fixnum and Float to js Number. The only thing I can do is to point you to PR #481 by @meh which doesn't solve the problem but it's related anyway.

**Comment by meh** [comment]
Sadly it's not possible, keep in mind we also have numbers coming from native APIs, and those would still be Numeric.

The plan with that PR was to at least make `Numeric` inheritance proper, so have `Numeric` and `Number`.

But that PR is blocked by the implementation of proper bridging which is kind of hard to do.

**Comment by vais** [comment]
Thanks @elia and @meh, I see the problem.

So, then it would be correct to say that `[0, 1, 2, 3, 4, 5].partition { |i| i / 3 == 0 } == [[0, 1, 2], [3, 4, 5]]` cannot, and will **never** be supported on Opal? Because for this code to work, `1 / 3` and `2 / 3` would have to produce a `0` result, which is not possible with javascript numbers that are always floats.

If that's the case, I will send a PR to mark this assertion as `not_supported_on :opal` so we can pass all of the `Array#partition` specs. As it stands we are passing all assertions in "Array#partition returns in the left array values for which the block evaluates to true", except the one that uses integer division to partition the array.

**Comment by elia** [comment]
Relevant: http://fantom.org/forum/topic/878

Might be worth exploring. It could work if we assume all native stuff returning floats. 
What I imagin is some Opal.int helper that wraps a number in a Fixnum class. Still need to check how it plays with js weird casting, not sure if js would call valueOf before trying to do the op.

**Comment by vais** [comment]
Thanks @elia

**Comment by meh** [comment]
@elia I think it would slow down number stuff even further.

**Comment by meh** [comment]
Also I tested, it would be feasible to do with `valueOf` involved, but then any function testing with a `typeof(..) == "number"` would explode in a million pieces.

**Comment by elia** [comment]
I'll close this, nothing we can do for now.
