### ISSUE TITLE
Provide a simpler way to create hash

### ISSUE THREAD

**Issue by Mogztter** [opal/opal#758]
AFAIK the only way is to use the `Opal.hash2` method with an array of keys and an object with keys and values:

```javascript
Opal.hash2(["type", "target"], {"type": "link", "target": link})
```

To avoid the duplication, I created a simple JavaScript function:
```javascript
Opal.to_hash = function (data) {
  var keys = [];
  for (var key in data) {
    if (data.hasOwnProperty(key)) {
      keys.push(key);
    }
  }
  return Opal.hash2(keys, data);
};
```

I can now write the following:
```javascript
Opal.to_hash({"type": "link", "target": link})
```

I think it would be great to add this function in Opal. Another idea is to decorate the JavaScript object with a to_h or $to_h method so it could be written as:

```javascript
{type: "link", target: link}.$to_h()
```

What do you think ?

**Comment by elia** [comment]
Have you tried `Opal.hash`?

That should work, even if I may just have spotted a bug.

**Comment by Mogztter** [comment]
Can't believe this is as simple as that... Make me wonder why are we using `Opal.hash2`. Maybe @mojavelinux can give us some insight ?

**Comment by elia** [comment]
btw `Opal.hash2` is a more performant version with already digested keys

**Comment by mojavelinux** [comment]
Perhaps this comes down to a simple documentation issue.

I saw `hash2` used internally by Opal and assumed that it was the correct name to use. I never really gave much thought to why `hash` wasn't used instead.

Obviously, in code that Opal generates, it needs to use `hash2` (perhaps better named `fash_hash`) to take advantage of the digested keys so as to achieve better performance. For external APIs and examples, we should definitely use the simpler `hash` for usability reasons.

So perhaps the Opal documentation can make it clear why there are two methods and which one should be used in which case?

See http://opalrb.org/docs/compiled_ruby/#hash

**Comment by elia** [comment]
Closing, will promptly accept any PR for https://github.com/opal/opalrb.org/blob/master/source/docs/compiled_ruby.html.md#hash :stuck_out_tongue_winking_eye:
