### ISSUE TITLE
parameters method (on a proc) not implemented.

### ISSUE THREAD

**Issue by catmando** [opal/opal#762]
I am getting:   NoMethodError:  undefined method `parameters' for #Proc:0x377

understandably this is pretty obscure.  Is there a work around?  I need to get a hold of the block parameter names.

**Comment by catmando** [comment]
In case anybody else needs it, here is a 50% fix (gives parameter names, but not optional/req/rest 

````
  class Proc
    
    def parameters
      /.*function[^(]*\(([^)]*)\)/.match(`#{self}.toString()`)[1].split(",").collect { |param| [:req, param.strip.to_sym]}
    end
    
  end
````

If somebody wants to give me a hint about how to add this info to the block class during compilation, I would be happy to get it working... I looked at the compilers iter class, and am guessing that I can do something like `self.$$params = [....]` to save these away.  

Am I close?

**Comment by focused** [comment]
I need this method too, and i need curry method. I tried to override `Proc.new` without success. How we can implement these methods?

**Comment by adambeynon** [comment]
We won't be able to support it fully, but the suggestion by @catmando gets us half way there for given parameter names - we just won't be able to distinguish between args, optional args and rest args.

**Comment by misleb** [comment]
For what it's worth, this appears to to work with methods, but only if you convert them to proc first.

```
proc = obj.method(:blah).to_proc
```

I am using this for dependency injection. So I then have to apply the proc with resolved dependencies to the instance using instance_exec

```
obj.instance_exec(*resolved_params, &proc)
```

I'm actually impressed so far that so much of this low level stuff works. I was really not expecting a whole lot when I started playing with Opal.
