### ISSUE TITLE
Uncaught NameError: uninitialized constant ...

### ISSUE THREAD

**Issue by krainboltgreene** [opal/opal#764]
For some reason opal refuses to see constants I've defined.

See repository: https://github.com/krainboltgreene/hackerlife.opal
Setup: `bundle install && bundle exec rake build && open build/index.html`

**Comment by adambeynon** [comment]
The missing constant I get is for `Hacklife::Terminal`, but it gets defined as `Hackerlife::Terminal` in https://github.com/krainboltgreene/hackerlife.opal/blob/master/lib/hacklife/terminal.rb#L1-L12.

**Comment by krainboltgreene** [comment]
I have been sitting on this for like a month. I am also an idiot. Sorry to waste your time!

**Comment by adambeynon** [comment]
No problem! :smile: I did have a look at this for you before, but I also missed it.
