### ISSUE TITLE
can't create local variables in a block declaration

### ISSUE THREAD

**Issue by catmando** [opal/opal#765]
{ | ; c | }

Does not work...

**Comment by meh** [comment]
Never seen that syntax, are there any specs for it?

**Comment by catmando** [comment]
Could not find any thing "official"

However if you search for "ruby 1.9 block-local scope" you will see lots of references.

**Comment by Ajedi32** [comment]
Huh, that's weird. I'd never seen that syntax before now either, but apparently it *is* an actual thing. TIL...

**Comment by vais** [comment]
@Ajedi32 source?

**Comment by Ajedi32** [comment]
@vais As @catmando said, you can just Google "ruby 1.9 block-local scope" and you'll see a lot of references. Besides that though, it works in MRI:

```ruby
y = 10
1.times do |x; y|
  y = 100000
end  
y #=> 10
```

**Comment by vais** [comment]
@meh source: https://github.com/ruby/rubyspec/blob/master/language/block_spec.rb#L614

**Comment by elia** [comment]
Fixed on master, :beers: to @iliabylich who did it in https://github.com/opal/opal/pull/1387 !
