### ISSUE TITLE
self.class returns incorrect result for String and Array subclasses

### ISSUE THREAD

**Issue by vais** [opal/opal#771]
Here is how `self.class` works in MRI:
```
$ pry
[1] pry(main)> class String
[1] pry(main)*   def class_according_to_base_class
[1] pry(main)*     self.class
[1] pry(main)*   end  
[1] pry(main)* end  
=> :class_according_to_base_class
[2] pry(main)> class MyString < String
[2] pry(main)*   def class_according_to_sub_class
[2] pry(main)*     self.class
[2] pry(main)*   end  
[2] pry(main)* end  
=> :class_according_to_sub_class
[3] pry(main)> s = MyString.new
=> ""
[4] pry(main)> s.class
=> MyString
[5] pry(main)> s.class_according_to_sub_class
=> MyString
[6] pry(main)> s.class_according_to_base_class
=> MyString
```
Note that the result is always `MyString`.

But here is how it works in Opal ([Try Opal link](http://opalrb.org/try/?code:class%20String%0A%20%20def%20class_according_to_base_class%0A%20%20%20%20self.class%0A%20%20end%20%20%0Aend%20%20%0Aclass%20MyString%20%3C%20String%0A%20%20def%20class_according_to_sub_class%0A%20%20%20%20self.class%0A%20%20end%20%20%0Aend%20%20%0As%20%3D%20MyString.new%0Ap%20s.class%0Ap%20s.class_according_to_sub_class%0Ap%20s.class_according_to_base_class)):
```ruby
class String
  def class_according_to_base_class
    self.class
  end  
end  
class MyString < String
  def class_according_to_sub_class
    self.class
  end  
end  
s = MyString.new
s.class #=> MyString
s.class_according_to_sub_class #=> MyString
s.class_according_to_base_class #=> String <----- WTF?
```
I stared into the abyss trying to figure out how to fix this, but the abyss just stared back at me. I need you guys to point the way.

**Comment by elia** [comment]
And that happens for String only or for other classes too?, eg for bridged classes

**Comment by vais** [comment]
@elia interesting, it *does not* happen for a regular user-defined class:
```ruby
class Person
  def class_according_to_base_class
    self.class
  end  
end  
class Dude < Person
  def class_according_to_sub_class
    self.class
  end  
end  
s = Dude.new
p s.class #=> Dude
p s.class_according_to_sub_class #=> Dude
p s.class_according_to_base_class #=> Dude
```
[Try Opal link](http://opalrb.org/try/?code:class%20Person%0A%20%20def%20class_according_to_base_class%0A%20%20%20%20self.class%0A%20%20end%20%20%0Aend%20%20%0Aclass%20Dude%20%3C%20Person%0A%20%20def%20class_according_to_sub_class%0A%20%20%20%20self.class%0A%20%20end%20%20%0Aend%20%20%0As%20%3D%20Dude.new%0Ap%20s.class%0Ap%20s.class_according_to_sub_class%0Ap%20s.class_according_to_base_class)

So, it must be something specifically with `String` then?

**Comment by vais** [comment]
@elia `Array` suffers from the same problem.

**Comment by elia** [comment]
Then it's probably something to do with the wrappers that make inheritance possibile 

https://github.com/opal/opal/tree/master/opal/corelib/array
https://github.com/opal/opal/tree/master/opal/corelib/string

Had a quick look and didn't find anything evidently wrong but could easily be something subtle. Also the problem can reside in the interaction of them with the runtime.

**Comment by vais** [comment]
@elia yes, it does. Wrappers use `method_missing` to forward method calls to the underlying `@literal`. When the wrapped literal receives the message, `self` is the literal, not the wrapper. Hmm... so... do you see any obvious way to fix this?

**Comment by elia** [comment]
Real inheritance would be the definitive solution of course, redefining #class in the wrapper could work but can mess up redefinig methods on Array. 

@meh, any other ideas?

**Comment by meh** [comment]
I was going to work on that in the `proper-bridging` branch, but I got stuck and I'm scared to look back at it.

When I get the guts to get back into it that will be the direction.

I don't think there's a temporary workaround given the hacky state of bridged class inheritance.

**Comment by vais** [comment]
Thank you @elia and @meh, I will leave this issue open until there's some news.

**Comment by vais** [comment]
@elia, @meh, I'm closing this issue because I think I found a work-around that's basically good enough - here's an example of making `String#split` and `String#each_line` return instances of subclasses of `String` when called on an instance of a subclass of `String`:

```ruby
class String::Wrapper
  ...
  def split(pattern = undefined, limit = undefined)
    @literal.split(pattern, limit).map{|str| self.class.allocate(str)}
  end

  def each_line(separator = $/)
    return enum_for :each_line, separator unless block_given?
    @literal.each_line(separator){|str| yield self.class.allocate(str)}
  end
  ...
end
```
What I like about this approach is that there is no overhead at all associated with it when you are calling these methods on instances of `String` class. What I don't like about this approach is that you have to duplicate a bit of the logic in `String::Wrapper` in some cases. Overall I feel this is a reasonable compromise. Issue closed.
