### ISSUE TITLE
String#each_byte and Encoding

### ISSUE THREAD

**Issue by vais** [opal/opal#772]
stdlib/encoding.rb monkey-patches `String#each_byte` like this:

``` ruby
class String
  `def.encoding = #{Encoding::UTF_16LE}`
  def each_byte(&block)
    return enum_for :each_byte unless block_given?
    @encoding.each_byte(self, &block)
    self
  end
  #more stuff...
end
```

I cannot make rubyspec pass `String#each_byte` with this monkey-patch in place. I assume there is a reason the `Encoding` class is implemented, I'm just not sure what that reason is, considering all `String` specs that use encoding end up in the `unsupported` bucket.

Can anyone please comment on this situation?

**Comment by elia** [comment]
Digging in git history I can confirm that encoding.rb is there just to make libs and gems work

https://github.com/opal/opal/commits/69c96e1a7ce4e6a6a81701f5e67ef6ef2cedc4bf/corelib/encoding.rb
