### ISSUE TITLE
TypeError: Cannot read property '$nil?' of undefined

### ISSUE THREAD

**Issue by tioteath** [opal/opal#777]
It seems that  \`statement\`  constructions behaves inadequately in Opal:
http://opalrb.org/try/?code:puts%20%60undefined%60.nil%3F

It is impossible to call any method for \`statement\` construction if it returns \`undefined\`. 

Using opal 0.7.1.

**Comment by adambeynon** [comment]
This is the desired behaviour. Undefined and null are considered invalid ruby objects, and cannot respond to method calls.

**Comment by tioteath** [comment]
How it supposed to check if anything was returned in this kind of constructions:
```
`document.getElementById('some_id')`
```

**Comment by adambeynon** [comment]
It depends really on what you are doing. I personally don't mix javascript and ruby much, and any javascript I have to do I constrain it inside a method, e.g.:

```ruby
def do_something
  %x{
    var elem = document.getElementById('some_id');
    elem.foo();
    elem.bar();
  }
end
```

I know then that all my javascript is contained inside that one method, and I can invoke that method from my regular ruby code.

Another approach is using `Native`, in the sodlib, which can wrap javascript objects so you can interact with native api. Accessing `undefined` or `null` will be bridged as `nil`, so a regular `.nil?` check works.

Third approach is using `opal-jquery` or `opal-browser` for specialised DOM stuff.

It all comes down to exactly what you are trying to do, how much you need to interact with the code from ruby, and whether an abstraction through `Native` or `opal-jquery`/`opal-browser` would better serve your needs.
