### ISSUE TITLE
if RUBY_ENGINE == 'ruby' not working as expected

### ISSUE THREAD

**Issue by cj** [opal/opal#784]
If you check out http://goo.gl/8NI1e4 it will fail, but if you change it to `unless RUBY_ENGINE == 'opal'` it passes.  Shouldn't they both pass?

**Comment by elia** [comment]
Only checks against the "opal" are skipped at compiler level, it's intended to be really specific. 

Any reason

**Comment by elia** [comment]
Urrrrghhg …iOS decided it was time to submit :(

Any reason you see to be less specific?

**Comment by cj** [comment]
What would be the reason to allow `if RUBY_ENGINE == 'ruby'` to be compiled with `opal` only code?

I would think that people would get confused and use `if RUBY_ENGINE == 'ruby'` expecting it to be the opposite of `if RUBY_ENGINE == 'opal'`

**Comment by elia** [comment]
_the issue wa s closed by iOS, sorry_

**Comment by Ajedi32** [comment]
Well, it *is* kind of a hack to be turning off compilation this way. It's a necessary hack though; unless of course we can get the compiler to just ignore syntax that Opal doesn't support...

**Comment by elia** [comment]
Let's stick with current behavior for now
