### ISSUE TITLE
Please extend docu with one .cgi example (or a similar example)

### ISSUE THREAD

**Issue by shevegen** [opal/opal#788]
Heya,

I tried to ask this on IRC but folks seemed to be idling.

So here again, this time perhaps in an extended way.

The documentation of opal can be found here:

http://opalrb.org/docs/

So far so good but I am wondering how to actually use
opal myself.

Perhaps an entry at FAQ
http://opalrb.org/docs/faq/
could happen? Such as "how to setup opal"
or how to make it work in the browser.

I have a local webserver, and can serve my
ruby .cgi scripts but I am unsure how to get
opal support.

Perhaps a minimal "hello world" in a ruby
.cgi script could be shown or added, so that people
like me can understand the big picture?

Thanks for reading, thanks for considering, best
luck to you guys - being able to use ruby rather than
javascript would be SO AWESOME. I could literally
use all my ruby scripts and make them available
in the browser, at a minimal "cost".

**Comment by elia** [comment]
I have no experience with ruby and CGI. Could you please send a simple CGI example so that I can try to integrate Opal in it?

**Comment by elia** [comment]
Closing, but feel free to send me the example of how you currently use CGI, I'll be happy to reopen and prepare the Opal version.
