### ISSUE TITLE
Hash with boolean keys

### ISSUE THREAD

**Issue by ryanstout** [opal/opal#801]
Using boolean values in hash keys doesn't track the value correctly:

```ruby
a = {}
a[true] = 'one'
puts a.inspect
```

Thanks!  Keep up the good work.

**Comment by vais** [comment]
```
$ bundle exec opal -v -e "a = {}; a[true] = 'one'; puts a.inspect; p a[true]"
Opal v0.8.0.dev
{true=>"one"}
"one"
```
```
$ bundle exec opal -v -e "a = {}; a[false] = 'one'; puts a.inspect; p a[false]"
Opal v0.8.0.dev
{false=>"one"}
"one"
```
:beers:

**Comment by ryanstout** [comment]
@vais Thanks, How are you testing with 0.8.0?

**Comment by ryanstout** [comment]
@vais Are you just running in the checked out github project?

**Comment by vais** [comment]
@ryanstout Yep: https://github.com/opal/opal/blob/master/CONTRIBUTING.md#quick-start

**Comment by ryanstout** [comment]
@vais cool, I'll check next time before submitting :-)

**Comment by vais** [comment]
@ryanstout no problem, keep 'em coming!

**Comment by elia** [comment]
Also a `rake install` From the checked out project will install the gem on your current ruby

**Comment by vais** [comment]
@elia sorry, possibly a n00b question, but could you please elaborate a little on what exactly `rake install` does?

**Comment by elia** [comment]
`rake install` builds and installs opal locally from the checked out code, it's part of the standard bundler tasks for gem development

**Comment by vais** [comment]
@elia Just to clarify: so, `rake install` creates a kind of "alternative universe" in which the development version of Opal that lives in the repo you have checked out (the same repo where you execute this `rake install` command) acts as if it has already been released as the official Opal gem out on RubyGems, and as if you are installing that gem with the regular `gem install` command? Whoa... mind -> blown.

**Comment by elia** [comment]
Rubygems is capable of installing local gems in the form of files with `.gem` extension. So when you have a `mygem.gemspec` you can `gem build mygem.gemspec` and you'll get `mygem.gem`.

Bundler has a set of rake task to help gem development and the release cycle, you can build the skeleton for new gem with [`bundle gem MYGEM`](http://bundler.io/v1.9/bundle_gem.html). Among other things they'll add a Rakefile with the following tasks: https://github.com/bundler/bundler/blob/master/lib/bundler/gem_helper.rb#L42-L45.

**Comment by vais** [comment]
Thank you @elia - even though I am pretty familiar with both gems and bundler, doing `bundle exec rake install` in the context of Opal really made the whole thing click for me.

Now, I have:
```
$ gem list opal

*** LOCAL GEMS ***

opal (0.8.0.dev, 0.7.0.rc1, 0.6.3)
...<snip>...
```
But still:
```
$ opal -v
Opal v0.6.3
```
So, my default Opal is still the old version. I guess that's because of the `.dev` suffix on the latest, so rubygems refuses to use it by default?

**Comment by elia** [comment]
Oh, err, have no idea! 😳

**Comment by vais** [comment]
@elia I think what's hapening is `gem` considers any version of a given gem that contains letters to be a prerelease version, so it will not pick it by default and instead choose by default the latest version of that gem available on your system that does not include letters in the version. http://guides.rubygems.org/patterns/#prerelease-gems
