### ISSUE TITLE
Likely scope leakage without interpolation?

### ISSUE THREAD

**Issue by bglusman** [opal/opal#803]
in Opal v 0.7.1, just noticed this in some code working on ThirdRail, the code was this:
```ruby
    def content_for(tag = :layout)
      the_rails_content = page._rails_content
      tag = "#rails_content_#{tag}"
      raw `$(tag, the_rails_content)`.html
    end
```
and believe that should error or at least not work correctly when rendered on the client, but the variables are visible without interpolating inside the back ticks...  behaves identically to below code, which I think Mitch intended, but I think it shouldn't
```ruby
    def content_for(tag = :layout)
      the_rails_content = page._rails_content
      tag = "#rails_content_#{tag}"
      raw `$(#{tag}, #{the_rails_content})`.html
    end
```

**Comment by meh** [comment]
It's working as intended.

**Comment by bglusman** [comment]
OK, thanks...  can see it would be hard to isolate the scopes, just was curious if it was intentional and documented.  Thanks @meh !

**Comment by meh** [comment]
@bglusman just a note, most of the time it would actually be better to use interpolation, because some special variable names are mangled, like a lot of those JavaScript keywords that actually do nothing but some engines trip on.
