### ISSUE TITLE
Issue defining class method with the name 'name'

### ISSUE THREAD

**Issue by robfors** [opal/opal#816]
The following code was run at opalrb.org/try  
```ruby
class User
  @name = 'rob'
  
  def self.name
    @name
  end

end

user = User.new
puts user.class #prints 'rob' but I was expecting 'User'
```
Using Opal: 0.7.0
It appears to be an issue with defining a class method with the name 'name'.

**Comment by vais** [comment]
Good catch @robfors!

This can be [simplified further](http://opalrb.org/try/?code:class%20User%0A%20%20def%20self.name%0A%20%20%20%20%22hello%22%0A%20%20end%0Aend%0Aputs%20User.new.class). I.e. the class instance variable `@name` does not seem to have anything to do with the problem:
```ruby
class User
  def self.name
    "hello"
  end
end
puts User.new.class
```
outputs:
```
hello
```

**Comment by vais** [comment]
The closest I came in trying to figure this out is https://github.com/opal/opal/blob/master/opal/corelib/module.rb#L538
```ruby
  def to_s
    name || "#<#{`self.$$is_mod ? 'Module' : 'Class'`}:0x#{__id__.to_s(16)}>"
  end
```
@adambeynon could you please weigh in on this?

**Comment by Ajedi32** [comment]
Well, you could store the class name in some kind of hidden variable instead of depending on what the `name` method returns. That seems to be what MRI does, given that it can still get the correct name of the class even when the class's `name` method has been overridden.

**Comment by elia** [comment]
@Ajedi32 there's the `.$$name` property defined on modules and classes that probably is the right thing to use in `Module#to_s`

**Comment by vais** [comment]
@elia @Ajedi32 that works. @Ajedi32 wanna do a PR?

**Comment by vais** [comment]
https://github.com/opal/opal/blob/master/opal/corelib/module.rb#L538
```ruby
  def to_s
    `self.$$name` || "#<#{`self.$$is_mod ? 'Module' : 'Class'`}:0x#{__id__.to_s(16)}>"
  end
```

**Comment by Ajedi32** [comment]
I haven't made any significant changes to Opal so I'm not really set up for it, but this is a really small change so I wouldn't mind giving it a shot.

**Comment by vais** [comment]
@Ajedi32 every journey starts with a single step :wink: If you have questions about getting started, take a look at https://github.com/opal/opal/blob/master/CONTRIBUTING.md and/or feel free to ask me any questions here or on https://gitter.im/opal/opal

**Comment by Ajedi32** [comment]
Okay. I'm going to be pretty busy this week until Saturday, but I'll look into it then. I want to be able to at least run the specs myself before making changes to Opal, even a change as small as that.

**Comment by vais** [comment]
@Ajedi32 sounds good

**Comment by vais** [comment]
Closed by https://github.com/opal/opal/commit/9933c666c7dd276fd7d5ee601f828adb37468672

**Comment by Ajedi32** [comment]
Whoops, I guess I forgot about this. :grimacing: Thanks for taking care of that for me. :+1:

**Comment by vais** [comment]
No problem, @Ajedi32 :smile:

**Comment by vais** [comment]
Re-opened by https://github.com/opal/opal/commit/3e0b1b305ca625c21dcf293dd38578fd17da6a74
