### ISSUE TITLE
Compiled files via Sprockets + Rails not working in latest master

### ISSUE THREAD

**Issue by jaredcwhite** [opal/opal#817]
OK, I've been having issues with master lately, so just to better test stuff I created a brand new project (using Rails 4.2.1) and added these lines to Gemfile:

```
gem 'opal', :github => 'opal/opal'
gem 'opal-rails', :github => 'opal/opal-rails'
gem 'opal-jquery', :github => 'opal/opal-jquery'
gem 'opal-rspec', :github => 'opal/opal-rspec'
```

And added some simple test code to a file, like this: `app/assets/opal_application.rb`

```
require 'opal'
require 'opal_ujs'
require 'opal-jquery'

class Fooo
  def bar
    alert "Hello from jquery + opal"
  end
end
```

When I bring up a simple page via the Rails server, there's no `Opal.Fooo` in the JS console. There's no `Opal.Element` and other classes that are supposed to be from opal-jquery. I can verify there are JS files being loaded in the browser, for example the above is compiling down to this:

```
/* Generated by Opal 0.8.0.dev */
Opal.modules["opal_application"] = function(Opal) {
  Opal.dynamic_require_severity = "ignore";
  var self = Opal.top, $scope = Opal, nil = Opal.nil, $breaker = Opal.breaker, $slice = Opal.slice, $klass = Opal.klass;

  Opal.add_stubs(['$require', '$alert']);
  self.$require("opal");
  self.$require("opal_ujs");
  self.$require("opal-jquery");
  return (function($base, $super) {
    function $Fooo(){};
    var self = $Fooo = $klass($base, $super, 'Fooo', $Fooo);

    var def = self.$$proto, $scope = self.$$scope;

    return (def.$bar = function() {
      var self = this;

      return self.$alert("Hello from jquery + opal");
    }, nil) && 'bar'
  })(self, null);
};
```

Also, as an aside, source maps are broken again...they'd worked pretty recently again (w00t!) but now, not.

**Comment by elia** [comment]
That's weird, can you paste the source of the simple page? (looks like it's missing the bootstrapping code for some reason)

**Comment by jaredcwhite** [comment]
Basically just some dummy text and this code:

```
<%= opal_tag do %>
Document.ready? do
  fooo = Fooo.new
  fooo.bar
end
<% end %>
```

I have reason to believe it's not due to using opal_tag per se, but I could be wrong...

**Comment by elia** [comment]
It's opal_tag, as it's missing the boot code:

https://github.com/opal/opal-rails/blob/master/app/helpers/opal_helper.rb#L4
vs.
https://github.com/opal/opal-rails/blob/master/app/helpers/opal_helper.rb#L15

**Comment by elia** [comment]
@jaredcwhite moved to https://github.com/opal/opal-rails/issues/49
