### ISSUE TITLE
Non-obvious interpolation "problem"

### ISSUE THREAD

**Issue by krainboltgreene** [opal/opal#835]
So first I just want to state I realize this might not be "solvable", but should be listed somewhere. I had an error pop up in javascript due to Opal producing bad syntax. This ultimately was because I didn't understand how string interpolation would output. Here's what I wrote:

``` ruby
`alert("#{"greeting"}");`
```

I assumed it would come out as:

``` javascript
alert("greeting");
```

But instead it comes out as:

``` javascript
return alert(""greeting"");;
```

**Comment by vendethiel** [comment]
I think it should be seen as "code" (textified ast?) interpolation instead of text

**Comment by krainboltgreene** [comment]
The hard part is really that I get a unhelpful syntax error on a single line. If you're not in the opal mindset it can be hard to figure out what you did wrong.

**Comment by elia** [comment]
What you put into `#{}` will be compiled and inserted as is in the surrounding JS. 
To have better error messages we should parse JS too, which is unlikely. The only thing I can say is that it is a kind of advanced feature and once you know the rules it's super powerful.

Closing, but looking forward for any advice on how to make easier to understand (e.g. via docs etc.).

**Comment by krainboltgreene** [comment]
I'll see if I can't write something up about ` in the documentation in a
PR. Or at least a blog post.

**Comment by elia** [comment]
That would be great! (any of the above)
