### ISSUE TITLE
define_singleton_method with Proc/lambda argument instead of block does not work

### ISSUE THREAD

**Issue by Sketch** [opal/opal#838]
Using git version of Opal (currently v0.8.0.beta1). Also tested on Opal 0.7.2.
define_singleton_method is implemented, but only the one-argument symbol-and-block form, not two-argument symbol-and-method form. ( http://ruby-doc.org/core-1.9.3/Object.html#method-i-define_singleton_method )
Attempting to use define_singleton_method in the two-argument form produces the JavaScript console error: "ArgumentError: tried to create Proc object without a block".

```ruby
class DecoObject
  def this_works
    self.define_singleton_method(:cool!) do
      puts "Behold!"
    end
  end
  def this_does_not(lam)
    self.define_singleton_method(:and_that_is_bad, lam)
  end
  def neither_does_this(lam)
    self.send :define_singleton_method, :also_bad, lam
  end
end

deco = DecoObject.new()
deco.this_works
deco.cool!
l = lambda {puts "Cool! It works!"}
puts "Here we go..."
deco.this_does_not(l)
deco.and_that_is_bad
deco.neither_does_this(l)
deco.also_bad
```

**Comment by vais** [comment]
@Sketch thanks for spotting this. There may be more issues in this category. I'm a little strapped for time - if you find more, please submit issues or PRs using [this solution](https://github.com/opal/opal/pull/846) as an example of how to fix. Thanks again! :clap:
