### ISSUE TITLE
0.8 source maps

### ISSUE THREAD

**Issue by fazibear** [opal/opal#839]
Hi, I'm trying to get a source maps works. Using opal 0.8 with sprockets 3.0.
Every console `puts` points to last line.

This is example code:

```ruby
# use sprockets directive to include jquery
require 'opal'
require 'jquery'
require 'opal-jquery'

Document.ready? do
  # checkout browser console
  puts "Message from opal"

  # add some text to h2
  Element.find('#element').text = "Setting header with Opal"

  # onclick event
  Element.find('#button').on :click do
    Element.find('#element').text = "Button Clicked!"
  end
end

puts 'test 1'
puts 'test 2'
puts 'test 3'
``` 
and console output:
![screen shot 2015-05-08 at 18 27 04](https://cloud.githubusercontent.com/assets/687/7552197/b96253de-f6a7-11e4-9d41-3850aecdcba4.png)

Working version is here: `fazibear/opal-slim-sass-sprockets-example.git` in `opal-edge` branch.

**Comment by elia** [comment]
https://github.com/fazibear/opal-slim-sass-sprockets-example/blob/opal-edge/views/index.slim#L6

To get working source maps you need to link js files separately like rails does in development, an example can be found here: 

https://github.com/opal/opal/blob/e388357710a13db12a5995338c07a3db261f1736/lib/opal/sprockets/server.rb#L124-L142

not sure how it fits in with slim tho, closing but feel free to reopen if it doesn't work out :)

**Comment by ll14m4n** [comment]
working example `fazibear/opal-slim-sass-sprockets-example.git` is no longer working after bundle update.
I get `404` on  `"GET /__OPAL_SOURCE_MAPS__/app.map HTTP/1.1"`
```
I use :
  * opal (0.8.0) (was 0.8.0.beta1)
  * sprockets (3.4.0) (was 3.0.3)
```

**Comment by elia** [comment]
Actually seems it was 0.7, not 0.8 beta1 https://github.com/fazibear/opal-slim-sass-sprockets-example/blob/master/Gemfile.lock#L7

@ll14m4n a lot of stuff regarding source maps changed between 0.7 and 0.8, best thing is to keep the examples dir as a reference or alternatively the engine file in opal-rails.

Have a look at the changelog, and if you have more questions on how to handle the updated ask on gitter or IRC (see the README), someone (e.g. me) will be there to help. :smile:

**Comment by ll14m4n** [comment]
working example was 0.8.beta1 https://github.com/fazibear/opal-slim-sass-sprockets-example/blob/opal-edge/Gemfile.lock
