### ISSUE TITLE
Possible issue with tabs?

### ISSUE THREAD

**Issue by RickCarlino** [opal/opal#849]
I have a class level instance variable (It's an abstract class and I don't want to share the var with descendants):

```ruby

class Duck
  @quack = 'Quack!'

  def self.quack
	@quack
  end

  def quack
    self.class.quack
  end
end

puts Duck.new.quack
```

[Run with standard Ruby using repl.it](http://repl.it/neJ) (OK)
[Run with Opal](http://opalrb.org/try/?code:class%20Duck%0A%20%20%40quack%20%3D%20%27Quack!%27%0A%0A%20%20def%20self.quack%0A%09%40quack%0A%20%20end%0A%0A%20%20def%20quack%0A%20%20%20%20self.class.quack%0A%20%20end%0Aend%0A%0Aputs%20Duck.new.quack%0A) (ERROR)

```
SyntaxError: An error occurred while compiling: (file)

unexpected '"kEND"'
Source: (file):2:5
  @quack = 'Quack!'
~~~~^
SyntaxError: An error occurred while compiling: (file)

unexpected '"kEND"'
Source: (file):2:5
  @quack = 'Quack!'
~~~~^
    at t.$new (http://opalrb.org/javascripts/try.js:5:30463)
    at a.<anonymous> (http://opalrb.org/javascripts/try.js:5:26369)
    at a.d.$compile (http://opalrb.org/javascripts/try.js:19:4138)
    at e.$compile (http://opalrb.org/javascripts/try.js:19:2017)
    at $TryOpal.def.$run_code (http://opalrb.org/javascripts/try.js:20:27039)
    at HTMLDocument.$a.$$p.TMP_3 (http://opalrb.org/javascripts/try.js:20:28057)
    at f (http://opalrb.org/javascripts/application.js:2:16766)
    at Object.p.fireWith [as resolveWith] (http://opalrb.org/javascripts/application.js:2:17547)
    at Function.K.extend.ready (http://opalrb.org/javascripts/application.js:2:12308)
    at HTMLDocument.pt (http://opalrb.org/javascripts/application.js:2:9736)
```

**Comment by jaredcwhite** [comment]
There might be a stray odd character in there or something. I retyped the example and it runs without error: http://opalrb.org/try/?code:class%20Duck%0A%20%20%40quack%20%3D%20'Quack!'%0A%20%20%0A%20%20def%20self.quack%0A%20%20%20%20%40quack%0A%20%20end%0A%20%20%0A%20%20def%20quack%0A%20%20%20%20self.class.quack%0A%20%20end%0Aend%0A%0Aputs%20Duck.new.quack

**Comment by RickCarlino** [comment]
Oh that's strange. Good stuff. Thanks.

**Comment by Ajedi32** [comment]
That's totally weird. It looks like the only difference is whitespace. Here's the diff:

```text
$ diff file1 file2 -C 4
*** file1	2015-05-13 08:16:12.405565200 -0500
--- file2	2015-05-13 08:16:22.813565570 -0500
***************
*** 1,11 ****
  class Duck
    @quack = 'Quack!'
!   
    def self.quack
!     @quack
    end
!   
    def quack
      self.class.quack
    end
  end
--- 1,11 ----
  class Duck
    @quack = 'Quack!'
! 
    def self.quack
!   @quack
    end
! 
    def quack
      self.class.quack
    end
  end
```

After a little poking around, it seems that the `@quack` line in `self.quack` was indented with a tab instead of a space. Removing the tab fixes the problem.

This still seems like a bug to me. MRI handles tabs just fine, so I don't get why Opal is choking on them.

**Comment by alexdowad** [comment]
I cut-and-pasted the failing code from the browser into a local file. With `bundle exec bin/opal test.rb`, it runs fine... and even quacks!

If this is still a problem, can someone send me an `.rb` file which demonstrates the failure when run using `HEAD`? If not, maybe it should be closed.

**Comment by elia** [comment]
@alexdowad yes, looks like it's fixed on master. 

(Need to release 0.9 soon and update opalrb.org)
