### ISSUE TITLE
Array Coercion Not Working for Enumerables/Other Objects

### ISSUE THREAD

**Issue by wied03** [opal/opal#858]
I believe this is a compiler issue so a pull request may/may not be possible.

*When this issue is fixed, workaround code in opal/corelib/regexp.rb in #union needs to be removed*

It appears to work properly when the object is already an array but not for these other 2 cases.

Code:
```
class Tester
  include Enumerable
  
  def initialize
    @stuff = [:foobar, :bah]
  end
  
  def each(&block)
    @stuff.each &block
  end
end

an_enum = Tester.new

result = *an_enum
# Should be an array
puts "result type is #{result.class} is #{result}"

existing_array=3
result = *existing_array
puts "result type is #{result.class} is #{result}"

existing_array = [1,2,3]
result = *existing_array
puts "result type is #{result.class} is #{result}"
```
Output with Ruby 2.2 MRI:
```
result type is Array is [:foobar, :bah]
result type is Array is [3]
result type is Array is [1, 2, 3]
```
Output with Opal master:
```
result type is Tester is #<Tester:0x90>
result type is Numeric is 3
result type is Array is 1,2,3
```
The 2nd and 3rd responses seem to be wrong (should both be Array). They should both be arrays. I noticed this problem when trying to get RSpec 3.1 up and running with Opal.

**Comment by wied03** [comment]
Just digging into the nodes infrastructure a bit and realizing there are several places this would need to be fixed in:

1. When calling methods, arglist.rb (circa lines 20 and 32)
1. Assignments (as noted in example above)
1. Return statements
1. Other cases

I'm mainly being hit by 1 right now. There is a compilation issue with the test though (spec/corelib/language/send_spec.rb). :(

**Comment by wied03** [comment]
As an aside, this sort of falls into the "known bugs" category since several of the specs that expose this are commented out in the bugs filters (or rubyspecs file). Do folks prefer github issues not be created for these or is it helpful to track these by having issues open?

**Comment by wied03** [comment]
This appears to be fixed with ff297f5aeddec8f44281dd7c039d2404bf29516a and https://github.com/opal/opal/commit/121eff369b4de925e8a86f50927dd1635ca33b4b. Used the more accurate example below:

Test code:
```Ruby
require 'set'

def stuff(*notifications)
  puts "notifications is #{notifications} of type #{notifications.class}"
  puts "first element is #{notifications[0]}"
  # This is the way in opal-rspec that I mitigate this
  #notifications = notifications[0].to_a unless notifications[0].is_a? Array  
end

input = Set.new(Set.new([:foo, :bar]))
stuff *input
```

MRI 2.2.2:
```
notifications is [:foo, :bar] of type Array
first element is foo
```

Opal 0.8:
```
notifications is #<Set:0x94> of type Array
first element is #<Set:0x94>
```

Opal 0.9/master (d9dee023a057de5b4289825826dad8037ca08508)
```
notifications is foo,bar of type Array
first element is foo
```

**Comment by meh** [comment]
@wied03 can you elaborate on `3.` and `4.`?

Small testcase would help.

**Comment by meh** [comment]
For the record

```ruby
class Foo
	def to_a
		[1, 2, 3]
	end
end

def foo
	return *Foo.new
end

puts foo.inspect
```

Is working properly, so I think that rules out `3.` as fixed as well, `4.` remains.
