### ISSUE TITLE
break does not stop looping in  String#each_char

### ISSUE THREAD

**Issue by fkchang** [opal/opal#866]
The below code in Opal 0.7.* and 0.8.0 beta prints out all 6 letters, in MRI, it prints a and b only.  The break isn't working.  I recall a similar 'break doesn't break out of loop' issue
```ruby
"abcdef".each_char {|c|
  if c == "c"
    break
  end
  puts c
  }
    
```

**Comment by vais** [comment]
Right, here's the compiled code:
```javascript
    def.$each_char = TMP_2 = function() {
      var $a, self = this, $iter = TMP_2.$$p, block = $iter || nil;

      TMP_2.$$p = null;
      if ((block !== nil)) {
        } else {
        return self.$enum_for("each_char")
      };
      
      for (var i = 0, length = self.length; i < length; i++) {
        ((($a = Opal.yield1(block, self.charAt(i))) === $breaker) ? $breaker.$v : $a);
      }
    
      return self;
    };
```
Note this part:
```javascript
...
      for (var i = 0, length = self.length; i < length; i++) {
        ((($a = Opal.yield1(block, self.charAt(i))) === $breaker) ? $breaker.$v : $a);
      }
    
      return self;
    };
```
Inside the loop, it compares the return of `Opal.yield1` with the value of `$breaker`, but then it does not do anything with that even though the block that's passed to it does `if (c['$==']("c")) {return ($breaker.$v = nil, $breaker)}`, it simply continues the loop, and returns self.

Re-writing the loop like this has the desired effect:
```js
      for (var i = 0, length = self.length; i < length; i++) {
        if (Opal.yield1(block, self.charAt(i)) === $breaker) { return $breaker.$v };
      }
```
The problem with me trying to change the compiler (based on a couple of past experiences) is that fixing this one issue will break a dozen other cases, so I dare not tread there, cause "there be dragons". We would need @adambeynon the dragon slayer to take a look.

**Comment by meh** [comment]
Fixed on master.
