### ISSUE TITLE
Can't call native methods on strings using Native

### ISSUE THREAD

**Issue by jeremyevans** [opal/opal#870]
Looks like `Native(str)` just returns `str`, so it's not possible to use `Native` to call native methods on strings.  Example:

```
puts Native('a').replace(/[^0-9.]/g, '')
# raises NoMethodError: undefined method `replace' for "a"
```

**Comment by meh** [comment]
That's working as expected, `String` is already an Opal object.

**Comment by jeremyevans** [comment]
So how do you call native javascript methods on a string?  I sort of understand why it doesn't work, but not sure what the workaround is, without using backticks.

**Comment by meh** [comment]
There's no other way.

**Comment by elia** [comment]
I'm In favor of having a way to force Native, not particularly for strings but in general for all bridged classes. On clear use case it arrays which are not "native" but can contain native objects thus needing native wrapping when their elements are accessed. 

I know there's Native::Array and that's as easy as creating a class with proper method_missing but that use case can be optimized a bit.

**Comment by meh** [comment]
We could have `Native!()`.

**Comment by vais** [comment]
@jeremyevans what's the problem with using backticks?

**Comment by jeremyevans** [comment]
@vais It's not a deal breaker, but it would be nice to not have to drop down to raw javascript so often.

Personally, I think it would be nice to have a syntax-level support for calling javascript methods, what are your thoughts on that?

**Comment by vais** [comment]
@jeremyevans I commented here before I read your comment in another thread, https://github.com/opal/opal/pull/867#issuecomment-102815948, so now I see what you mean.

I'm new to the project, so I believe @meh when he says (https://github.com/opal/opal/pull/867#issuecomment-102818134) that didn't work out well.

I think handling JS with "rubber gloves" by explicitly wrapping it in a Ruby API is the right approach. Mixing JS and Ruby code is appealing, but if you think about it, the right thing to do is to isolate it, much like that's the right thing to do when dealing with any external API, be it interfacing with native C libs or even interfacing with 3rd-party REST APIs - you make your own wrapper, then talk to that wrapper.

**Comment by jeremyevans** [comment]
@vais I don't have a problem with the wrapping approach, though I think it should be done implicitly instead of explicitly if that is the approach used.

Note that this issue is regarding a problem that occurs when trying to use the explicit wrapping approach.

**Comment by vais** [comment]
@jeremyevans I think I'm missing the bigger picture here. Perhaps a larger example of the issue (more context) would help.

**Comment by jeremyevans** [comment]
@vais Let's say you are converting some javascript to opal, and it uses javascript string methods such as replace, indexOf, search, slice, localeCompare, etc.  There's not really a way to use those methods in opal without dropping down to raw javascript via backticks.  In a lot of cases, there are ruby equivalent methods you can use (such as sub/gsub instead of replace), but it does make such a conversion more difficult.

**Comment by adambeynon** [comment]
Back in the day, we could call native methods due to the way we compiled method calls, but it generated VERY ugly code, and was quite a lot slower on every method dispatch.

For String, Array, Number etc, one solution is that we COULD implement `method_missing` on them to dispatch methods to the javascript functions. It would only apply to a handful, but might make porting code a little easier.

**Comment by meh** [comment]
@adambeynon I wouldn't be against an optin for that in `stdlib/native/classes` or something.

**Comment by jeremyevans** [comment]
With the recently merged support for `recv.JS.meth` and `recv.JS[:prop]`, I think we now have adequate workarounds for this.  I'll leave the issue open in case you still think something should be done about it, but I'm fine with closing it.

**Comment by vais** [comment]
This issue is closed via https://github.com/opal/opal/pull/879
Thank you, Jeremy! :clap:
