### ISSUE TITLE
Kernel#caller returning empty array

### ISSUE THREAD

**Issue by robfors** [opal/opal#894]
The following code was run at opalrb.org/try
```ruby
class User
  def remote
    caller
  end

  def name
    remote
  end
end

puts User.new.name #returns an empty array, but I was expecting it to have some elements
```
Using Opal: 0.8.0.beta1

I am interested in getting the name of the closest calling method, in this case 'name'.

**Comment by adambeynon** [comment]
`#caller` is something we can't really support in opal, so an empty array is just a placeholder to try and stop things breaking.

**Comment by Ajedi32** [comment]
Does returning an empty array really stop things from breaking? I guess that would depend on the code, but I can imagine that `caller` returning an empty array might cause things to break anyway in some cases.

I wonder if throwing an error, or perhaps printing a warning might be a good idea.

Also, I'm not entirely convinced that this is impossible to support in Opal (try `new Error().stack` in your browser console). It would definitely be a pain to implement though.

**Comment by adambeynon** [comment]
Cross browser support is the tricky thing with this as well.

**Comment by ylluminate** [comment]
Interesting.  I wonder if there would be a way to hack this together.  There are some facilities that could perhaps be used to (mostly) support what would be needed to bring this to a (near) one-to-one parity, but I think you're right in that it would be tricky on the cross-browser front.  Hmm.

**Comment by elia** [comment]
There's an implementation for nodejs in the stdlib
https://github.com/opal/opal/blob/master/stdlib/nodejs/kernel.rb#L6-L17

Maybe if someone comes up with implementations for different browsers they can be added too (either in the stdlib or in opal-browser).

**Comment by robfors** [comment]
There's a js library that parses error stacks.
It would be a good place to start. But it sounds like IE9 and younger stacks won't give us enough information.
Ill see what I can do with it.
https://github.com/stacktracejs/error-stack-parser

**Comment by robfors** [comment]
I have made some progress on this but I'm wondering what it should return for the code file and row. I can return the url of compiled javascript file and row but im not sure if that would be beneficial information. I could use a source map to get the original file and row but I would imagine that would be very difficult to do. Would it be acceptable to return a placeholder instead?

It would return something like this:
```ruby
["unavailable:0:in `remote'", "unavailable:0:in `name'"]
```

**Comment by Ajedi32** [comment]
I imagine that `Kernel#caller` is typically used for debugging, right? If so, then getting the original line file and line number via source maps would probably be best.
