### ISSUE TITLE
Problems with the Ruby Time class and making other classes of the same name

### ISSUE THREAD

**Issue by ylluminarious** [opal/opal#898]
I ran into a problem with an Opal wrapper I've been working on by making a class called `Time`. Basically, I had a method that used `alias_native` to return the class, like so: https://gist.github.com/ylluminarious/90557cff002d1d090627
However, it appears that it is instead accessing the core Ruby / Opal `Time` class instead of the class of the same name that I created. Here is another example, with simplified code to recreate the problem: https://gist.github.com/dd6304b95db6bd034b38

**Comment by gabrielrios** [comment]
Just to add to what @ylluminarious said, on that gist, we have a Module scoped Time class
https://github.com/orbitalimpact/opal-phaser/blob/master/lib/opal/phaser/time/time.rb

but when we `alias_native` here: https://github.com/orbitalimpact/opal-phaser/blob/master/lib/opal/phaser/core/game.rb#L51

It gives the error on that gist, which feels like its calling the Ruby Time class and passing the `Phaser.Time` object

**Comment by ylluminarious** [comment]
@gabrielrios Yes, thanks for the elaboration.

**Comment by meh** [comment]
This is a definition order issue, the `Time` in the `alias_native` call is not lazily loaded, at that time (pun) the local `Time` is not defined yet, so it accesses the global one.
