### ISSUE TITLE
proc is empty when it shouldn't be

### ISSUE THREAD

**Issue by cj** [opal/opal#932]
The proc is empty when it shouldn't be.  http://goo.gl/1FA7Q7

It seems to be something to do with `#deep_dup`

**Comment by vais** [comment]
@cj I look for small, isolated, minimum viably reproducible examples :stuck_out_tongue_winking_eye:

**Comment by cj** [comment]
@vais this is a minimum as I could get it :smile: , it only happens with `#deep_dup`.

**Comment by cj** [comment]
@vais if you remove all the comments, it's only 30 lines... not including all the simple 5 liners like:

```
class Object
  def duplicable?
    true
  end
end
```

**Comment by cj** [comment]
@vais here's it without the comments:  http://goo.gl/sw1umi it looks like the cause is line 68.  If you change it from `hash[key.deep_dup] = value.deep_dup` to `hash[key.deep_dup] = value.dup` it works, but then obviously it's not going to fully deep dup.

**Comment by cj** [comment]
@vais so it's duping a proc which is the cause, http://goo.gl/iYJWE0.  Is that example short enough for you? :smile:

**Comment by elia** [comment]
here's an even reduced version: `-> {}.dup.call` returns `undefined`

**Comment by vais** [comment]
@cj the ability to `dup` a `Proc` object is simply not implemented right now: https://github.com/opal/opal/blob/master/opal/corelib/proc.rb

@elia I'm having a hard time wrapping my head around how the `Proc` class works at all. There are no instance variables, no initialization. To support `dup`, is it just a matter then of storing the block in an instance variable? It's a very confusing class, looks like maybe the real work happens in the compiler.

**Comment by elia** [comment]
@vais Proc is one of the core classes that are bridged directly from JavaScript, in this case [it's mapped from `Function`](https://github.com/opal/opal/blob/master/opal/corelib/runtime.js#L1446). Not sure what clone can mean in this context, but being functions immutable (I think) we can use prototypal inheritance, or a wrapping function as this SO answer suggests: http://stackoverflow.com/a/1833851

**Comment by vais** [comment]
Oh, I see... Thank you, @elia!
