### ISSUE TITLE
🍬🍭🍫

### ISSUE THREAD

**Issue by ernie** [opal/opal#943]
I heard that this issue tracker was the place where we should discuss candy. I prefer chocolate to hard candy, though a nice peppermint is fine from time to time.

I read the guidelines for contributing, and they did not say I could not discuss candy here, so hopefully this is helpful.

**Comment by cha0s** [comment]
Air Heads and Dum Dums vs. Nerds and Laffy Taffy

**Comment by bf4** [comment]
I like the thought, but not sure I want to get involved. Oops. ( I like chocolate like I like my coffee: dark and bitter )

**Comment by binarycleric** [comment]
I'm a pretty huge fan of junior mints and dark chocolate peanut M&M. Cadbury dark chocolate will always have a special place in my heart.

**Comment by ngauthier** [comment]
I haven't tried Opal candy before, has anyone else?

![http://assets.coolhunting.com/coolhunting/mt_asset_cache/2011/04/11/opalcandy1.jpg](http://assets.coolhunting.com/coolhunting/mt_asset_cache/2011/04/11/opalcandy1.jpg)

**Comment by ernie** [comment]
@ngauthier I am pretty sure it can't have taste, because it can't exist, because something something reasons

**Comment by adambeynon** [comment]
Rowntree's Fruit Gums are also quite epic.
