### ISSUE TITLE
Blacklist Specific Users from Project for Repeated Frivolous Complains

### ISSUE THREAD

**Issue by onmran** [opal/opal#954]
On Github Issues page, user CoralineAda requested removal of a contributor for expressing a particular viewpoint on a particular political issue on a discussion outside of Github. This was a frivolous, disrespectful, and deeply offensive complaint within Github that made the contributor feel unwelcome. I request that Opal blacklist the user.

CoralineAda accused the contributor of "transphobia" on Opal's Github page; this is extremely offensive to the contributor. She also frivolously suggested Opal is unwelcoming towards people of certain gender identities. Opal welcomes towards people of all gender identities, and CoralineAda's frivolous and offensive accusations on Opal's Github site runs contrary to Opal's goals. She offended both a contributor, tarnished Opal's reputation, and brought sensitive political issues into Opal's Github page, making Opal less welcoming towards people of certain gender identities and political persuasions.

The new code of conduct bans:

(a) being disrespectful towards other Opal contributors within the project, particularly based on gender identity and race
(b) making other Opal contributors feel unwelcome via unprofessional conduct within the project
(c) unprofessional conduct (offensive, frivolous and time-consuming complaints would be included in this) within the project

These are common sense rules and CarolineAda has violated all of them. Therefore I request that CarolineAda should be blacklisted from the project.

In addition, CarolineAda has done the following frivolous and offensive activity on the Github Issues page:

(a) injected politics into the discussion by linking to a political blog within the Github Issues page
(b) disrespectfully suggested contributor meh has a “deep ignorance” due to his clear decision on the matter

In addition to CoralineAda, the following users ought to be blacklisted, for similar reasons:

strand - Frivolous, disrespectful and deeply offensive complaint on the Github Issues page claiming that the contributor's activity in an external political discussion (unrelated to the project) makes users feel “unsafe” and “unwelcome” within the project.

aredridel - Frivolous, disrespectful and deeply offensive complaint on the Github Issues page that the contributor's activity in an external political discussion (unrelated to the project) makes one feel that one would need to “not […] come near” the project. Frivolous complaint that the contributor’s activity in an external political discussion causes other contributors to be “second class” and not “respected.”

tobascodagama - Frivolous, disrespectful and deeply offensive complaint on the Github Issues page that the contributor's activity in an external political discussion (unrelated to the project) means the contributor would not treat other contributors “with respect.”

sellout - Frivolous, disrespectful and deeply offensive complaint on the Github Issues page that the contributor's activity in an external political discussion (unrelated to the project) “dissaudes [others] from participating [in the project].”

fivetanley - Frivolous, disrespectful and deeply offensive complaint on the Github Issues page calling meh’s clear decision on the matter “dismissive” and “dehumanizing.”

bhaibel - Frivolous, disrespectful and deeply offensive complaint on the Github Issues page that the contributor's activity in an external political discussion (unrelated to the project) makes her feel “[not] welcomed” and not treated “fairly.” Also, frivolous injection of her own personal gender identity and sexual orientation into the discussion as a political tactic. Opal strives to be welcoming to all gender identities, so injecting one's gender identity into the project as a political tactic is contrary to Opal's goals.

erisdev - Frivolous, disrespectful and deeply offensive complaint on the Github Issues page that the contributor's activity in an external political discussion (unrelated to the project) causes “hostility towards people like me” within the project. This is deeply offensive towards the contributor.

jdax - Frivolous, disrespectful and deeply offensive complaint on the Github Issues page claiming the contributor's activity in an external political discussion (unrelated to the project) brings “dehumanizing” political views into the Github project and makes other people “not feel safe” within the project.

hnrysmth - Frivolous, disrespectful and deeply offensive complaint on the Github Issues page about the contributor's activity in an external political discussion (unrelated to the project) implying that the Opal project “systematically protects abusers and excludes LGBT developers.” This is very disrespectful and deeply offensive as it suggests that the contributor is an 'abuser' and 'excludes LGBT developers' because of the contributor's activity in an external political discussion unrelated to the project. This also creates an unwelcoming environment for LGBT developers because it suggests that the project excludes LGBT developers. hnrysmth’s activity on the Github page was discriminatory and damaging to LGBT developers.

juanplopes - Amplification of hnrysmth’s frivolous, disrespectful and deeply offensive complaint on the Github Issues page.

nslater - Frivolous, disrespectful and deeply offensive complaint on the Github Issues page suggesting that the contributor's activity in an external political discussion (unrelated to the project) means he does not “care about people.” Also nslater created an unwelcoming environment for people of different skin colors and genders by suggesting on the Github Issues page that Opal is excluding people that are not “aggressive young white men.” Since Opal strives for a welcoming environment for contributors of all skin colors and genders, nslater’s activity on the Github Issues page was damaging to the goals of Opal’s project. nslater’s activity on the Github Issues page was also frivolous because it offensively suggests the contributor is an “aggressive young white man,” presumably because of his activity in an external political discussion. Also, nslater created an unwelcoming environment for andrewmcwatters by bringing the user's “privilege” into the picture. This is offensive and contrary to Opal’s goals because Opal strives to have a welcoming environment for all contributors regardless of privilege.

frank - Amplification of hnrysmth’s frivolous, disrespectful and deeply offensive complaint on the Github Issues page.

lutoma - Frivolous, disrespectful and deeply offensive comment on the Github Issues page trying to accuse Opal contributors of being a certain race, sexual orientation and gender based on their behavior on Opal's Github site. This is unwelcoming to people of certain races and gender identities and contrary to Opal’s goals because Opal strives to have a welcoming environment for all contributors regardless of race and gender identity.

copumpkin - Suggestion on the Github Issues page that a contributor's activity in an external political discussion (unrelated to the project) is comparable to “child molestation.” This is frivolous, offensive to the contributor and generally an offensive thing to say.

juanplopes - Frivolous, disrespectful and deeply offensive comment on the Github Issues page suggesting that Opal only welcomes “straight white dudes.” This is offensive and contrary to Opal’s goals because Opal strives to have a welcoming environment for all contributors regardless of race and gender. 

abritinthebay - Frivolous, disrespectful and deeply offensive comment on the Github Issues page suggesting that a contributor's activity in an external political discussion (unrelated to the project) caused “exclusionary behavior” within the project because the contributor was not purged from the project.

I request you take action on these users for their frivolous, disrespectful and deeply offensive complaints. I would like Opal to not discriminate against people based on:

(a) political opinions expressed in political discussions outside of Opal,
(b) gender identity, and
(c) race.

These users were making Opal unwelcoming for others and insulting specific contributors on its Github page in a disrespectful and unprofessional way, and the quantity and severity of the unprofessional behavior by these users was extreme. I request that action be taken against these users so that Opal affirms that it is welcoming to people of all political persuasions, gender identity and races, and so that Opal affirms that deeply disrespectful and offensive behavior on its Github Issues page is not tolerated.

**Comment by adambeynon** [comment]
Thank you for your concern about Opal. While this has all been handled badly, by all sides, the outcome is that we now have a Code of Conduct that will hopefully illustrate the general feelings about how contributors and users of Opal should behave and act. I don't think banning users is a very productive step to take.

However, if there are concerns about existing contributors or their behaviour in chat, gitter, irc, github, etc, etc, then please, raise concerns and it shall be dealt as best as possible.

**Comment by Lisias** [comment]
@adambeynon , the guy can have a good point.

It's god damned too easy to anyone out there come here and play havoc with the maintainers and contributors without the slightest fear of consequences.

You must stand for your guys/gals/whatever, even (and to tell you the true, mainly) if in the process you end up making someone unpleased.
