### ISSUE TITLE
Investigate using WebAssembly as a compiler target

### ISSUE THREAD

**Issue by Ajedi32** [opal/opal#956]
WebAssembly is a sort of bytecode intended to be used as a compiler target for languages that run in web browsers. It's an open standard being developed by Google, Microsoft, Mozilla, and others. (See [Google, Microsoft, Mozilla And Others Team Up To Launch WebAssembly, A New Binary Format For The Web](http://techcrunch.com/2015/06/17/google-microsoft-mozilla-and-others-team-up-to-launch-webassembly-a-new-binary-format-for-the-web/))

Okay, maybe it's a bit early to be thinking about this given that WebAssembly hasn't even been standardized yet, but it definitely seems like something to keep an eye on. See https://github.com/WebAssembly/design for details.

**Comment by adambeynon** [comment]
This would be a fun experiment. I did work on a ruby -> swift compiler before, using the opal lexer and parser. It didn't get very far, but it was surprisingly easy to reuse most of the compiler and just having optional code generation parts.

**Comment by ylluminate** [comment]
That's really interesting to hear @adambeynon.  I'm kind of curious, even having not gotten very far, would you mind throwing what you did onto `github`?  I've personally contemplated using `opal` as the base for a couple of other transpiler ideas, including `swift`, and I think just seeing your commits and the thought process would be useful.

**Comment by Ajedi32** [comment]
Yeah, it seems WebAssembly is a pretty low-level language, so maybe there wouldn't be much benefit to compiling Ruby down to it, but I'm not really sure. Definitely worth looking into though.

**Comment by bbatsov** [comment]
Seems to me this will be a worth-while endeavour down the road, when WebAssembly is better established. Right now we should probably be focused on compiling to JS only.

**Comment by zetachang** [comment]
[WebAssembly has reached the Browser Preview milestone](http://webassembly.org/roadmap/)

Some works has been done by @xxuejie, [webruby](https://github.com/xxuejie/webruby) compiles mruby vm to asm.js. And the good news is the toolchain which compile C/C++ to asm.js (emscripten) also got WebAssembly as compiling target support now.

**Comment by Ajedi32** [comment]
FYI, [WASM is now considered stable](https://lists.w3.org/Archives/Public/public-webassembly/2017Feb/0002.html).

[Still no garbage collection though](https://github.com/WebAssembly/design/blob/master/GC.md). I imagine that'd be a rather important feature for Opal, since you probably don't want to have to implement your own GC.

**Comment by elia** [comment]
Not familiar enough but would be great if we could give alternative more performat implementations of subsets of the code, that would also allow for a gradual transition I think.

**Comment by ylluminate** [comment]
Was probing a bit here, might give a touch of insight: https://github.com/graalvm/truffleruby/issues/82

**Comment by elia** [comment]
I'll close this issue for now. We'll surely reconsider wasm if something viable comes down the pike.

_See also #1715_

**Comment by erlend-sh** [comment]
Maybe it's time to revisit WASM?

http://www.blacktm.com/blog/ruby-on-webassembly

**Comment by elia** [comment]
@erlend-sh yes, the best route would be to start with replacing some performance-critical small parts with WASM implementations, and then gradually migrate the whole codebase. If anything like this comes up (a PR would be great but an example is good too) then we can start considering WASM in a more practical way. 

Last time I checked anything that wasn't already going through LLVM for the compilation was basically unsupported, also I think mixing WASM with regular JS wasn't possible (but I might be wrong on this last one).

**Comment by iliabylich** [comment]
From what I understand LLVM IR is statically typed, which means that we need to have a VM to handle complex stuff. We can't do a simple source-to-source compilation.

MRuby can handle some simple things, but it's not a full replacement of MRI (for example, MRuby doesn't support kwargs, it handles differently post-args, and that's only what I've got from the quick 1 min check). It was initially designed as an "embedded ruby", so I guess it's wrong to require MRuby to do such things.

I think it's easier to partially compile MRI as it has VM, GC and other cool stuff that is required. Please, correct me if I'm wrong, I'm open for this discussion, but I don't see what we can do here.

**Comment by ylluminate** [comment]
Hmm, I think the MRuby approach may be the most sane entry point as per @blacktm's article from above regarding MRuby. His [repo](https://github.com/blacktm/ruby-wasm) is interesting. As per his article, the size he notes for just shipping MRI is indeed size prohibitive (I don't think we want to ship a 20-40 MB runtime over the web)...

We might be better off trying to figure out and push efforts forward in MRuby that are missing from MRI that we want / need such as kwargs.

Is there another vector of approach? I suppose so, but we might end up with something more akin to an even more Ruby-like Crystal in the end vs true MRI Ruby.  Is that a bad thing?  Maybe not... maybe so...

Definitely needing some more input all the way around here so we don't shoot ourselves in the foot with a lot of wasted effort and time in a poor or less optimal solution.

**Comment by blacktm** [comment]
Hey all. I wrote that post @erlend-sh linked to. It's worth noting that WebAssembly is, like, really simple. They refer to it as a "virtual machine," but it's not a VM as we think of it. Rather, it's just a slight hardware abstraction — instructions, types, linear memory, that's about it ([details here](https://webassembly.org/docs/semantics/)). The reason MRuby works on WebAssembly, as described in [my post](http://www.blacktm.com/blog/ruby-on-webassembly), is because they've implemented a [VM](https://github.com/mruby/mruby/blob/master/src/vm.c), [GC](https://github.com/mruby/mruby/blob/master/src/gc.c), and everything else you'd expect a stand-alone Ruby implementation to have. To my knowledge, Opal relies on JavaScript for all that. This is one of the reasons JavaScript is most likely never going away — browsers already ship with a mature and performant (and large) VM, _scriptable_ with JavaScript. Therefore, there's really no reason to "compile" JS to WebAssembly, since you would have to ship an _additional_ complete VM with your app code. (See this robust discussion in the WebAssembly/design repo about whether there will be a [JS to WASM compiler](https://github.com/WebAssembly/design/issues/219).) For clarity, we could describe Opal as a "Ruby implementation built on the JavaScript VM." With all that said — and sorry to be blunt — I don't think WebAssembly will be relevant to Opal.

**Comment by ylluminate** [comment]
Hmmmm. That's a very interesting remark with wide reaching ramifications.  I guess this, by extension, begs the question: Is WASM relevant to Ruby generally?

I appreciate the frankness and clarity of the thought process @blacktm.

I suppose it makes sense for a language like Crystal where it's based on LLVM and there seems to be a clear path, but given that there is already a very robust VM in place (JavaScript) and WASM doesn't facilitate that which is needed (yet), then the idea of Ruby atop WASM may be relegated to simply an interesting topic and something to think about until WASM is more mature and essentially facilitates what JavaScript VMs already provide... and even when that happens, how much longer past that point will it finally become feasible given adoption / uptake of web browsers capable of running it.  In all reality we may be looking at 5+ years unless things drastically change.

Perhaps it would be worthwhile "playing" in this area and seeing where things go, especially with the MRuby path, but Opal does seem to perhaps be ideally situated for at least the time being. 

So a big "hmmmmmm" and I think we're all definitely interested in seeing some other perspectives percolate up here...

**Comment by pannous** [comment]
FYI: I uploaded and hosted the mruby to wasm experiment by blacktm[0] :
https://github.com/pannous/wruby 

Thanks to emscripten mruby really works out of the box in wasm, but can be optimized (loading mrbc bytecode, replacing window.prompt in irb etc)

[0] https://github.com/mruby/mruby/issues/3709

**Comment by elia** [comment]
> Maybe wasm will become relevant for opal again once the JS VM can be accessed directly from wasm (planned in the next release of webassembly).

yes, that would open a bunch of possibilities 🤩

**Comment by go2null** [comment]
There is also [run.rb](https://github.com/jasoncharnes/run.rb) as per the [Awesome WebAssembly Languages](https://github.com/appcypher/awesome-wasm-langs#ruby) list.

It would be great if there was more cooperation to reduce effort duplication in this space.

**Comment by ylluminate** [comment]
@go2null it is interesting, but I don't think they're entirely compatible. It appears that all that `run.rb` is doing is to compile the MRI to run in browser. Right now they don't have the stdlib and who knows how much size that's going to add to the payload... I mean, I don't want to deploy Ruby web apps that are enormous download sizes... 

Kind of a crazy thought, but I wonder if it would be possible to rework the stdlib so that it's highly modular and only what's needed would be pulled in as it's needed... I'd think that would be an ENORMOUS job.

**Comment by eregon** [comment]
> Kind of a crazy thought, but I wonder if it would be possible to rework the stdlib so that it's highly modular and only what's needed would be pulled in as it's needed... I'd think that would be an ENORMOUS job.

Looks like you are describing MRuby to me :wink:

**Comment by ylluminate** [comment]
LOL, yes, this is true @eregon - and this is something I've seen thrown around in terms of MRuby being the next Ruby to run via WASM. I guess I've not spent enough time in it yet to understand just how compliant it is to MRI. From what I'm hearing with the last drop, it seems as though there is some serious effort involved to give it feature parity with MRI... and if that's the case, then MRuby could simply become the next mainstream Ruby (aside from Truffle) to really take the language forward to all platforms (including WASM). Are you seeing anything in the MRuby space that flows along these lines?

**Comment by eregon** [comment]
Final size and modularity of the stdlib is what MRuby shines at. See https://github.com/mruby/mruby/blob/master/mrbgems/default.gembox for instance about how each part (including IO, the parser & compiler, etc) can be included or excluded.
MRuby is "embedded Ruby" and given the current constraints of WebAssembly (notably, no direct access to the DOM/JS) I think they make a lot of sense together.

In terms of compatibility, I think it's good for most core classes which do not depend on low-level OS facilities (Process, Socket, etc), but it's a bit different to traditional Ruby, e.g., `require`/`require_relative` are not there by default, but then again in an embedded scenario you might not want to have a filesystem, parse and compile code at runtime, but instead compile everything to MRuby bytecode on the host system, and only ship the MRuby bytecode interpreter + the bytecode.

**Comment by go2null** [comment]
Two interesting links:
- https://github.com/artichoke/artichoke
- https://github.com/ruby-llvm/ruby-llvm

Artichoke already compiles to WebAssembly - https://artichoke.run/
