### ISSUE TITLE
Ruby Time "is a" JS Date vs "has a" JS Date

### ISSUE THREAD

**Issue by vais** [opal/opal#957]
Currently Ruby `Time` is bridged to JS `Date`. This makes implementing support for a `Time` instance having an arbitrary time zone difficult (impossible?). In JS, `Date` can be UTC or *local*, whereas in Ruby, a `Time` object can carry with it its own arbitrary time zone that is independent of *local* time on the machine.

Making the relationship between Ruby `Time` and JS `Date` a *"has a"* relationship instead of an *"is a"* relationship could solve this problem. But what other problems would it create? What was the original reason for bridging `Time` to `Date`?

@adambeynon, @meh, @elia, any ideas?

**Comment by meh** [comment]
I'm ok with that, we can always implement `#to_n` and add a note to the documentation.

I think the original reason was because it seemed to make sense at the time, but since we have `Hash` that isn't some kind of automatical `Object`, I'm fine with `Date` and `Time` being like that.

**Comment by vais** [comment]
@meh right, I was thinking of the `Hash` example as well when debating this issue with myself :)

**Comment by elia** [comment]
I'm ok too with reimplementing from scratch, It's also notable that JSON too avoids supporting the Date type.

**Comment by adambeynon** [comment]
@vais `Time` does need to become a wrapper, just never had time to work on it. It is a complex beast, so any help is more than welcome. Some work might need to be done on `Date` as well, as that uses some ruby time methods that it assumes exists on the raw javascript object.

**Comment by vais** [comment]
@adambeynon @elia thanks for the feedback guys. I'm slowly working through the `Time` bugs now as time permits (pun intended, not a lot of free time lately). The various methods are so interdependent, I have not been able to push anything that I would consider an atomic commit yet.

**Comment by elia** [comment]
@vais I remember the rubinius implementation to be great as a reference (and already in ruby!)

**Comment by vais** [comment]
The reason I originally proposed this change was to be able to support "time zone travel" for `Time` objects, but at this point I still don't see a clear way to accomplish that with or without wrapping, so I'm closing this issue.

In https://github.com/opal/opal/pull/967 I left `Time` as is, bridged to JS `Date`, and `unsupported` all the specs that call for ability to explicitly manipulate a `Time` object's time zone offset. Also anything that requires sub-millisecond resolution, which is not possible in JS, or the use of Rationals which are not supported in Opal at this time.

**Comment by ylluminate** [comment]
You're probably aware @vais: http://stackoverflow.com/a/21120901/320681

**Comment by vais** [comment]
@ylluminate yep, just not sure how to integrate that with how the rest of it works. Maybe later.
