### ISSUE TITLE
`Date.parse()` sometimes produces wrong date

### ISSUE THREAD

**Issue by adambeynon** [opal/opal#958]
Looks like `Date.parse()` uses `parseInt` without a second param, which in some browsers (older safari versions from my tests) can parse months or days with leading zeros as octal, instead of base10, which gives the wrong result.

**Comment by adambeynon** [comment]
Should have checked master before submitting this - Im using old version, and this issue has been fixed.

**Comment by vais** [comment]
Yep, all hail the great JSHint! :smile:
