### ISSUE TITLE
.hash on Time

### ISSUE THREAD

**Issue by ryanstout** [opal/opal#963]
In MRI et al, the Time class's hash method is based on the value, not the object.

In MRI the following returns true:

```ruby
Time.new(500).hash == Time.new(500).hash
```

Tested in 0.8.0.beta1

Keep up the great work!

**Comment by vais** [comment]
https://github.com/opal/opal/blob/master/opal/corelib/time.rb#L211:
```ruby
  def hash
    `self.getTime()`
  end
```
It's a bit of a hack.

**Comment by ryanstout** [comment]
@vais Yea, I did this as a hack: 

```
    def hash
      "Time:#{to_i}"
    end
```

It sort of follows the opal .hash convention.

**Comment by vais** [comment]
Good point. I guess I got a little greedy, because this way we also pass the spec that calls for the hash to be a fixnum ;) We can change that to be consistent, but not sure if that's a problem. @opal/core feedback welcome...

**Comment by ryanstout** [comment]
@vais yea, my main issue right now is that storing Time instances with the same time as hash keys (or part of hash keys) doesn't return because the hash is different.

**Comment by elia** [comment]
Our hash table implementation is the js object which has string keys, for that reason the result of `#hash` in opal is generally a string, but actually I never benchmarked to check if there was a difference.

I  also have the suspect that we're missing some `#eql?` checks inside `Hash` that would allow I think for collisions in the hash keys. Would need to dig deeper to see how exactly MRI handles such cases. 

Right now opal doesn't allow collusions (except maybe in case of strings vs other objects).

@vais maybe it's a good idea to keep all `#hash` implementation in sync by returning a string at the cost of some failed specs (or by updating them to avoid the type check), wdyt?

**Comment by vais** [comment]
@elia I agree, keeping `#hash` implementations consistently returning a String across the board is more valuable than passing one extra Time spec :)

**Comment by vais** [comment]
@ryanstout now Opal does the same thing as your current monkeypatch, so once you update Volt to latest Opal, you'll be able to just remove the monkeypatch.

**Comment by vais** [comment]
@ryanstout actually, you may or may not want to call `Time#to_i` in your implementation of `Time#hash` there. Opal's implementation of `Time#hash` will use the maximum available time resolution, which is *milliseconds*. Using `TIme#to_i` means that all `Time` objects created within the same *second* will have the same `#hash` value in Volt. Just a heads up.
