### ISSUE TITLE
!= method not implemented on BasicObject

### ISSUE THREAD

**Issue by mojavelinux** [opal/opal#970]
The `!=` method is not implemented on BasicObject. While the `!=` expression can be used in the normal way, it cannot be sent to an object using the `send` method.

Example:

```
$ opal-repl
>> s = ''
>> s == ''
>> true
>> s.send :==, ''
>> true
>> s != ''
>> false
>> s.send :!=, ''
undefined method `!=' for ""
```

I expect the last example to return false.

**Comment by mojavelinux** [comment]
It's important to note that the `!=` is also missing for Numeric objects, so this is not limited to String objects.

**Comment by mojavelinux** [comment]
I tested with the latest master.

**Comment by vais** [comment]
@mojavelinux lol there's no spec for this in RubySpec :smirk: @eregon please correct me if I'm wrong, this is all we got: https://github.com/ruby/rubyspec/blob/master/core/basicobject/not_equal_spec.rb, and it does not currently test for `send`-ing a `:!=` method.

**Comment by elia** [comment]
In fact the current implementation translates it to `!(a == b)`… TMYK

**Comment by vais** [comment]
This spec should do it: https://github.com/ruby/rubyspec/blob/master/core/basicobject/not_equal_spec.rb#L4 It was getting filtered out as unsupported. PR is on the way.

**Comment by eregon** [comment]
@elia Yeah, it would be good to add a version with `send(:!=)` which would make sure such a method exists and works.

**Comment by mojavelinux** [comment]
Fantastic!

**Comment by vais** [comment]
@eregon something like this? https://github.com/ruby/rubyspec/pull/91

**Comment by eregon** [comment]
@vais exactly :)
