### ISSUE TITLE
to_i/to_f/to_s not behaving correctly

### ISSUE THREAD

**Issue by cj** [opal/opal#982]
Using this code in ruby http://goo.gl/gN56K0 it will be a `Float` in opal it return a 'String'.

**Comment by vais** [comment]
```
$ ruby -v
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]
$ pry
[1] pry(main)> val = '55.00' 
=> "55.00"
[2] pry(main)> 
[3] pry(main)> if val.to_s == val.to_s.to_i.to_s
[3] pry(main)*   val.to_s.to_i  
[3] pry(main)* elsif val.to_s == val.to_s.to_f.to_s  
[3] pry(main)*   val.to_s.to_f  
[3] pry(main)* else  
[3] pry(main)*   val  
[3] pry(main)* end  
=> "55.00"
[4] pry(main)> 
[5] pry(main)> puts val.class
String
=> nil
```
:confused:

**Comment by cj** [comment]
@vais yee, I think the issue is the way the data is getting converted to client side from the server and not opal.  I'll look into it tomorrow and re-open if need be, when I've had more than 4 hours sleep :smile:

**Comment by vais** [comment]
@cj no problem. Please note that in the example you provided, val can only ever be a string because that variable is assigned to exactly once, and it is assigned a string.

**Comment by Ajedi32** [comment]
@cj Also, `'55.00'.to_f.to_s` is `"55"` so even if you added a `val =` before that if statement your code still wouldn't work correctly. You might want to look into using [`Kernel#Float`](http://ruby-doc.org/core/Kernel.html#method-i-Float) and [`Kernel#Integer`](http://ruby-doc.org/core/Kernel.html#method-i-Integer) instead.

**Comment by vais** [comment]
```
$ ruby -ve "p '55.00'.to_f.to_s"
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]
"55.0"
```
```
$ bundle exec opal -ve "p '55.00'.to_f.to_s"
Opal v0.8.0.rc1
"55"
```
:-(

**Comment by vais** [comment]
`String#to_f` is the problem:
```
$ bundle exec opal -ve "p '55.00'.to_f"
Opal v0.8.0.rc1
55
```
```
$ ruby -ve "p '55.00'.to_f"
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]
55.0
```

**Comment by vais** [comment]
`String#to_f` is fine, actually, it's `Float#to_s` that's not conforming to RubySpec - this is a "known issue", the following specs are filtered out in spec/filters/bugs:
```
...
float.rb|89| fails "Float#to_s emits '-' for -0.0"
float.rb|90| fails "Float#to_s emits a trailing '.0' for a whole number"
float.rb|91| fails "Float#to_s emits a trailing '.0' for the mantissa in e format"
float.rb|92| fails "Float#to_s returns '0.0' for 0.0"
...
```

**Comment by vais** [comment]
@cj how critical is this for you?

**Comment by vais** [comment]
Hmm... since all numbers are floats in JS, I'm not sure there's anything we can do about this one, and those failures in filters/bugs I referenced above should probably find their final resting place in filters/unsupported. @meh, I believe we discussed this before - even if a distinction was made between integer and float literals at the parser/compiler level (i.e. dot blah blah becomes an instance of `Float` class), we'd still have a problem when it comes to JS native APIs (if I recall correctly).

**Comment by meh** [comment]
@vais yeah, there's nothing we can do, in my `numeric` rework branch there was just a type `Number` that encompassed both.

**Comment by vais** [comment]
Closed via https://github.com/opal/opal/pull/983

@cj if you need trailing '.0' support, try using `Kernel#format` a.k.a. `String#%` which give you complete control over Float to String conversion.

**Comment by cj** [comment]
@vais so I wasn't crazy! :)  Thank you for looking into this.  Will do.
