### ISSUE TITLE
Hash#slice

### ISSUE THREAD

**Issue by ryanstout** [opal/opal#985]
Not a big deal, but at some point ruby added Hash#slice to select keys.  Doesn't look like its in opal.  Thanks!

**Comment by Ajedi32** [comment]
Are you sure you're not thinking of Rails?

```text
$ irb
2.2.2 :001 > {key: 'value'}.slice(:key)
NoMethodError: undefined method `slice' for {:key=>"value"}:Hash
	from (irb):1
	from /home/meyerat/.rvm/rubies/ruby-2.2.2/bin/irb:11:in `<main>'
```

**Comment by ryanstout** [comment]
@Ajedi32 weird, I tried it in a project of mine, must have been added by a dependency (but nothing's depending on active support).  Sorry for wasting time :-)

**Comment by Ajedi32** [comment]
No problem. Actually, there has been some discussion regarding an equivalent to `Hash#slice` in the Ruby core, but so far it doesn't look like anyone's been able to come to a consensus on what to name the method: https://bugs.ruby-lang.org/issues/9108
