### ISSUE TITLE
Duplicated method definition in NodeJSFormatter

### ISSUE THREAD

**Issue by bbatsov** [opal/opal#991]
https://github.com/opal/opal/blob/432552860fa41f83ea0a16b3dbea59cf50401c2b/lib/mspec/opal/runner.rb#L174

Not sure which one should I remove.

**Comment by elia** [comment]
The last one was the one actually used, thus the right one

**Comment by Ajedi32** [comment]
Well, in Ruby the last method definition would be the one that is actually used, so you should be able to remove the first one without changing any behavior.

No idea whether "not changing the behavior" is the correct thing to do or not in this case though, as it's certainly possible this could be a bug.
