### ISSUE TITLE
<<self bug

### ISSUE THREAD

**Issue by dancinglightning** [opal/opal#992]
Moi,
found a strange bug when some code i try to use is trying to meta-program.

    class <<self ; self ; end

fails, while 

    class << self ; self ; end

works fine. You really have to read that twice to catch it: it is the space after <<
Without it boom, with it, fine.
beats me, but there it is.

**Comment by dancinglightning** [comment]
Just stumbled across another one, you choose if it is related. I put it here as it has the << in it too, though maybe it's more the |= , but anyway parsing.

    val |= (12 << 16)

breaks, while the version where one spells it out works

    val = val | (12 << 16)

**Comment by vais** [comment]
@dancinglightning what error are you getting? I have this:
```
$ bundle exec opal -v
Opal v0.8.0.rc1
$ bundle exec opal-repl
>> val |= (12 << 16)
=> true
```

**Comment by dancinglightning** [comment]
I assigned the val to 1 before
But more importantly i am on 0.7.2 , sorry i didn't mention that.
but i tried with the release candidate and still get 

parse error on value "(" (tLPAREN2) :main:10
Source: main:10:12
    val |= (12 << 16)

**Comment by vais** [comment]
@dancinglightning I see now... It parses without a problem as long as that statement is parsed alone, as is the case in opal-repl, or simply putting it by itself in a file and running that. As soon as there's more ruby around it, it fails. Bizarro. If you don't mind, please submit this as a separate issue with minimal sample code to repo the error.

**Comment by dancinglightning** [comment]
ok, #995
