### ISSUE TITLE
parser bug

### ISSUE THREAD

**Issue by dancinglightning** [opal/opal#995]
require "opal"
    class Game
      def initialize
        val = 1
        val |= (12 << 16)
      end
    end

parse error on value "(" (tLPAREN2) :main:5
Source: main:5:12
    val |= (12 << 16)

opal 0.7.2   ( but tried also 0.8.0pre1)  ruby 2.1.5 , chrome 43 on mac (latest)

**Comment by alexdowad** [comment]
I've done some investigation. This looks very much like a bug in Racc.

**Comment by alexdowad** [comment]
I thought this might be a bug in Racc, because both when parsing `val |= (1)` and `val = 1; val |= (1)`, the parser reaches state 198. However, when parsing `val |= (1)`, it shifts the left paren token; whereas when parsing `val = 1; val |= (1)`, it chokes on it and errors out.

How can the same parser accept a left paren from state 198, but then reject a left paren, *also* from state 198?

I should have looked at the trace more carefully. In one case, the token is `tLPAREN_ARG`, but in the other, it's `tLPAREN2`. Completely different token. No wonder it doesn't work!

Looks like we need to fix the lexer up again.

**Comment by alexdowad** [comment]
The difference is whether the lexer is in `expr_arg` or `expr_cmdarg` state. In those 2 states, the lexer emits `tLPAREN_ARG`. In `expr_beg` state, it emits `tLPAREN`. Otherwise, it emits `tLPAREN2`.

**Comment by alexdowad** [comment]
The design of the Ruby lexer/parser is a very, very goofy thing. I'm not blaming the Opal guys here; you inherited the design from MRI. Couldn't they just use a single "left parenthesis" token and sort out any dependencies on context with appropriate parser rules?

**Comment by alexdowad** [comment]
In the "good" example, the parser state is `expr_arg` when it emits the lparen. In the "bad" example, it's `expr_end`.

**Comment by alexdowad** [comment]
Added a couple debug print statements in `Lexer#next_token` to print `@lex_state` before and after lexing each token. I can see that in the "good" example, lexing `tIDENTIFIER` from "val" is putting the lexer in `expr_arg` state; in the "bad" example, it's putting it into `expr_end` state.

**Comment by alexdowad** [comment]
A couple of debug statements later, I find that `lexer.rb:633` is where it is going into `expr_end` state. But why?

**Comment by alexdowad** [comment]
The difference, interestingly enough, is whether a local variable has already been seen with the same name. If so, the lexer goes into `expr_end` state after lexing the variable name.

**Comment by alexdowad** [comment]
Aha. I've noticed something from comparing `parser` and `opal`.

`parser` ALWAYS puts the lexer into `expr_beg` state after lexing an operator-assign like `+=`, `-=`, `*=` and so on. `opal` almost always does the same... *except* when the operator-assign is `|=` or `<<=`.

That's the problem. I'm sure of it.

**Comment by alexdowad** [comment]
Sure enough, the parser chokes on `val = 1; val >>= (1)`.

**Comment by dancinglightning** [comment]
good work alex. Hope this gets some attention from the core then.

**Comment by vais** [comment]
@dancinglightning Alex has been on a roll fixing these bugs over the past few days, it's like christmas came early this year :smile:
