### ISSUE TITLE
StringScanner exist? is missing

### ISSUE THREAD

**Issue by dancinglightning** [opal/opal#996]
I tried a simple

    def exist?(reg)
      nil != check(reg)
    end

but that didn't seem to do the trick.

**Comment by vais** [comment]
Yep, https://github.com/opal/opal/blob/master/spec/filters/bugs/strscan.rb#L22-L24

**Comment by dancinglightning** [comment]
hmm, maybe a miscommunication: This bug stops me from running my app.

It wasn't a point about opal not being compliant, just stops mew working.

**Comment by vais** [comment]
Sorry @dancinglightning, that method is not implemented. I was simply pointing out the failing spec. See https://github.com/opal/opal/blob/master/CONTRIBUTING.md :wink:
