### ISSUE TITLE
source map documentation issue

### ISSUE THREAD

**Issue by rubydesign** [opal/opal#997]
Just learning about source maps and read this : http://opalrb.org/docs/source_maps/

which maybe should point to the rack example as it is the simplest way to get up (or both)

And in the rack example (and above docs) it should mention the debug and sourcemap flags, which seem a much simpler way to achieve the result than in the sinatra example.

```
s.source_map = true
s.debug = true
```

And i am not sure if this is an issue, but i read elia saying on SO that the javascript_include_tag should be used, as is in the rack example, but not in the sinatra example.

**Comment by bbatsov** [comment]
I think you should just fire up a PR to the documentation. Your suggestion seems super reasonable to me, as I've wondered myself what's the simple way to experiment with source maps.

**Comment by dancinglightning** [comment]
Well @bbatsov that is a fair point. I'm sure though someone with commit rights could fix both.
I was talking about the actual rack example in this repo.

Which btw has no readme

**Comment by elia** [comment]
Now the examples/ dir features the new sourcemaps with inlined sources which work great 👍
